// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.controllers.attack - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::controllers::attack {

class AggroInfo;
class AggroList;
enum class AggroTarget : std::uint8_t;
class AttackResult;
enum class AttackStatus : std::uint8_t;
class AttackUtil;
template <class T> class DamageInfo;
class DamageList;
class KillCounter;
class PlayerAggroList;
class TeamDamageList;

} // namespace aion::gameserver::controllers::attack
