// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.skillengine.task - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::skillengine::task {

class AbstractCraftTask;
class AbstractInteractionTask;
class CraftingTask;
class GatheringTask;

// Nested types (declared inside their outer class, include its header):
//   AbstractCraftTask::CraftType

} // namespace aion::gameserver::skillengine::task
