#pragma once

// Prelude of the AI handlers (data/handlers/ai, also ai/instance/<map>/...).
// A prelude holds the core names of its category as using-declarations in the category namespace, e.g. `using gameserver::ai::NpcAI;`
// (handlers-and-porting-plan.md §1.2). It is identical for every file of the category, so unity batches may include it any number of times,
// and it is the category's precompiled header. Handler files include it first; it also provides the registration markers and
// AION_UNPORTED. The handler file rules apply (aion_gs_regscan): declarations only inside the namespace of this directory, no namespace-scope
// `static`, no other namespaces.
// Using-declarations (S0b): every core type that the Java files of the category import, when a forward header declares it, its simple
// name comes from one package only and no Java type of the category has that name (nested types are spelled Outer::Inner or
// Outer_Inner). The prelude includes the full headers of the category's handler base classes, the generated headers of the
// re-exported enums, the full hub headers the category's handlers use most (Player, Npc, PacketSendUtility, ...; spine freeze) and the forward
// headers of the rest.

#include "aion/gameserver/runtime/base/Unported.h"
#include "aion/gameserver/ai/AIState.h"
#include "aion/gameserver/ai/AISubState.h"
#include "aion/gameserver/ai/AttackIntention.h"
#include "aion/gameserver/ai/NpcAI.h"
#include "aion/gameserver/ai/event/AIEventType.h"
#include "aion/gameserver/ai/event/fwd.h"
#include "aion/gameserver/ai/fwd.h"
#include "aion/gameserver/ai/handler/fwd.h"
#include "aion/gameserver/ai/manager/fwd.h"
#include "aion/gameserver/ai/poll/AIQuestion.h"
#include "aion/gameserver/ai/poll/fwd.h"
#include "aion/gameserver/configs/main/fwd.h"
#include "aion/gameserver/controllers/attack/AggroTarget.h"
#include "aion/gameserver/controllers/attack/fwd.h"
#include "aion/gameserver/controllers/effect/fwd.h"
#include "aion/gameserver/controllers/fwd.h"
#include "aion/gameserver/controllers/observer/ObserverType.h"
#include "aion/gameserver/controllers/observer/fwd.h"
#include "aion/gameserver/custom/instance/CustomInstanceRankEnum.h"
#include "aion/gameserver/custom/instance/fwd.h"
#include "aion/gameserver/custom/instance/neuralnetwork/fwd.h"
#include "aion/gameserver/custom/pvpmap/fwd.h"
#include "aion/gameserver/dao/fwd.h"
#include "aion/gameserver/dataholders/fwd.h"
#include "aion/gameserver/dataholders/loadingutils/adapters/fwd.h"
#include "aion/gameserver/geoEngine/math/fwd.h"
#include "aion/gameserver/handlers/HandlerRegistry.h"
#include "aion/gameserver/instance/handlers/fwd.h"
#include "aion/gameserver/model/ChatType.h"
#include "aion/gameserver/model/CreatureType.h"
#include "aion/gameserver/model/DialogPage.h"
#include "aion/gameserver/model/EmotionType.h"
#include "aion/gameserver/model/PlayerClass.h"
#include "aion/gameserver/model/Race.h"
#include "aion/gameserver/model/SkillElement.h"
#include "aion/gameserver/model/TaskId.h"
#include "aion/gameserver/model/TribeClass.h"
#include "aion/gameserver/model/actions/PlayerMode.h"
#include "aion/gameserver/model/actions/fwd.h"
#include "aion/gameserver/model/animations/ActionAnimation.h"
#include "aion/gameserver/model/animations/AttackHandAnimation.h"
#include "aion/gameserver/model/animations/AttackTypeAnimation.h"
#include "aion/gameserver/model/animations/TeleportAnimation.h"
#include "aion/gameserver/model/animations/fwd.h"
#include "aion/gameserver/model/autogroup/AutoGroupType.h"
#include "aion/gameserver/model/autogroup/fwd.h"
#include "aion/gameserver/model/base/BaseOccupier.h"
#include "aion/gameserver/model/base/fwd.h"
#include "aion/gameserver/model/drop/fwd.h"
#include "aion/gameserver/model/fwd.h"
#include "aion/gameserver/model/gameobjects/Creature.h"
#include "aion/gameserver/model/gameobjects/LetterType.h"
#include "aion/gameserver/model/gameobjects/Npc.h"
#include "aion/gameserver/model/gameobjects/NpcObjectType.h"
#include "aion/gameserver/model/gameobjects/fwd.h"
#include "aion/gameserver/model/gameobjects/player/Player.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/model/gameobjects/siege/fwd.h"
#include "aion/gameserver/model/gameobjects/state/CreatureSeeState.h"
#include "aion/gameserver/model/gameobjects/state/CreatureState.h"
#include "aion/gameserver/model/gameobjects/state/CreatureVisualState.h"
#include "aion/gameserver/model/gameobjects/state/fwd.h"
#include "aion/gameserver/model/geometry/fwd.h"
#include "aion/gameserver/model/house/fwd.h"
#include "aion/gameserver/model/instance/InstanceProgressionType.h"
#include "aion/gameserver/model/instance/StageList.h"
#include "aion/gameserver/model/instance/StageType.h"
#include "aion/gameserver/model/instance/fwd.h"
#include "aion/gameserver/model/instance/instancescore/fwd.h"
#include "aion/gameserver/model/instance/playerreward/fwd.h"
#include "aion/gameserver/model/items/fwd.h"
#include "aion/gameserver/model/legionDominion/fwd.h"
#include "aion/gameserver/model/siege/ArtifactStatus.h"
#include "aion/gameserver/model/siege/SiegeModType.h"
#include "aion/gameserver/model/siege/SiegeRace.h"
#include "aion/gameserver/model/siege/fwd.h"
#include "aion/gameserver/model/skill/fwd.h"
#include "aion/gameserver/model/stats/calc/functions/fwd.h"
#include "aion/gameserver/model/stats/calc/fwd.h"
#include "aion/gameserver/model/stats/container/StatEnum.h"
#include "aion/gameserver/model/stats/container/fwd.h"
#include "aion/gameserver/model/summons/SummonMode.h"
#include "aion/gameserver/model/summons/fwd.h"
#include "aion/gameserver/model/team/fwd.h"
#include "aion/gameserver/model/team/legion/LegionPermissionsMask.h"
#include "aion/gameserver/model/team/legion/fwd.h"
#include "aion/gameserver/model/templates/ai/fwd.h"
#include "aion/gameserver/model/templates/chest/fwd.h"
#include "aion/gameserver/model/templates/flypath/fwd.h"
#include "aion/gameserver/model/templates/fwd.h"
#include "aion/gameserver/model/templates/item/ItemAttackType.h"
#include "aion/gameserver/model/templates/item/actions/fwd.h"
#include "aion/gameserver/model/templates/item/enums/EquipType.h"
#include "aion/gameserver/model/templates/item/enums/ItemSubType.h"
#include "aion/gameserver/model/templates/item/enums/fwd.h"
#include "aion/gameserver/model/templates/item/fwd.h"
#include "aion/gameserver/model/templates/npc/NpcRating.h"
#include "aion/gameserver/model/templates/npc/NpcTemplateType.h"
#include "aion/gameserver/model/templates/npc/SubDialogType.h"
#include "aion/gameserver/model/templates/npc/fwd.h"
#include "aion/gameserver/model/templates/npcshout/ShoutEventType.h"
#include "aion/gameserver/model/templates/npcshout/fwd.h"
#include "aion/gameserver/model/templates/npcskill/NpcSkillTargetAttribute.h"
#include "aion/gameserver/model/templates/npcskill/fwd.h"
#include "aion/gameserver/model/templates/portal/fwd.h"
#include "aion/gameserver/model/templates/siegelocation/fwd.h"
#include "aion/gameserver/model/templates/spawns/basespawns/fwd.h"
#include "aion/gameserver/model/templates/spawns/fwd.h"
#include "aion/gameserver/model/templates/spawns/panesterra/fwd.h"
#include "aion/gameserver/model/templates/spawns/siegespawns/fwd.h"
#include "aion/gameserver/model/templates/teleport/fwd.h"
#include "aion/gameserver/model/templates/walker/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"
#include "aion/gameserver/questEngine/fwd.h"
#include "aion/gameserver/questEngine/model/QuestActionType.h"
#include "aion/gameserver/questEngine/model/QuestStatus.h"
#include "aion/gameserver/questEngine/model/fwd.h"
#include "aion/gameserver/services/drop/fwd.h"
#include "aion/gameserver/services/event/fwd.h"
#include "aion/gameserver/services/findgroup/fwd.h"
#include "aion/gameserver/services/fwd.h"
#include "aion/gameserver/services/instance/fwd.h"
#include "aion/gameserver/services/item/fwd.h"
#include "aion/gameserver/services/mail/fwd.h"
#include "aion/gameserver/services/panesterra/ahserion/PanesterraFaction.h"
#include "aion/gameserver/services/panesterra/ahserion/fwd.h"
#include "aion/gameserver/services/panesterra/fwd.h"
#include "aion/gameserver/services/player/fwd.h"
#include "aion/gameserver/services/siege/fwd.h"
#include "aion/gameserver/services/summons/fwd.h"
#include "aion/gameserver/services/teleport/fwd.h"
#include "aion/gameserver/services/trade/fwd.h"
#include "aion/gameserver/skillengine/SkillEngine.h"
#include "aion/gameserver/skillengine/condition/fwd.h"
#include "aion/gameserver/skillengine/effect/AbnormalState.h"
#include "aion/gameserver/skillengine/effect/fwd.h"
#include "aion/gameserver/skillengine/fwd.h"
#include "aion/gameserver/skillengine/model/SkillTargetSlot.h"
#include "aion/gameserver/skillengine/model/SkillType.h"
#include "aion/gameserver/skillengine/model/TransformType.h"
#include "aion/gameserver/skillengine/model/fwd.h"
#include "aion/gameserver/skillengine/properties/TargetSpeciesAttribute.h"
#include "aion/gameserver/skillengine/properties/fwd.h"
#include "aion/gameserver/spawnengine/SpawnHandlerType.h"
#include "aion/gameserver/spawnengine/fwd.h"
#include "aion/gameserver/utils/PacketSendUtility.h"
#include "aion/gameserver/utils/ThreadPoolManager.h"
#include "aion/gameserver/utils/audit/fwd.h"
#include "aion/gameserver/utils/fwd.h"
#include "aion/gameserver/utils/stats/AbyssRankEnum.h"
#include "aion/gameserver/utils/stats/CalculationType.h"
#include "aion/gameserver/utils/stats/fwd.h"
#include "aion/gameserver/utils/time/fwd.h"
#include "aion/gameserver/world/WorldMapType.h"
#include "aion/gameserver/world/WorldType.h"
#include "aion/gameserver/world/fwd.h"
#include "aion/gameserver/world/geo/fwd.h"
#include "aion/gameserver/world/knownlist/fwd.h"
#include "aion/gameserver/world/zone/fwd.h"

namespace aion::gameserver::handlers::ai {

using ::aion::gameserver::ai::AIActions;
using ::aion::gameserver::ai::AILogger;
using ::aion::gameserver::ai::AIRequest;
using ::aion::gameserver::ai::AIState;
using ::aion::gameserver::ai::AISubState;
using ::aion::gameserver::ai::AITemplate;
using ::aion::gameserver::ai::AttackIntention;
using ::aion::gameserver::ai::HpPhases;
using ::aion::gameserver::ai::NpcAI;
using ::aion::gameserver::ai::event::AIEventType;
using ::aion::gameserver::ai::handler::AggroEventHandler;
using ::aion::gameserver::ai::handler::AttackEventHandler;
using ::aion::gameserver::ai::handler::CreatureEventHandler;
using ::aion::gameserver::ai::handler::FollowEventHandler;
using ::aion::gameserver::ai::handler::MoveEventHandler;
using ::aion::gameserver::ai::handler::ReturningEventHandler;
using ::aion::gameserver::ai::handler::TalkEventHandler;
using ::aion::gameserver::ai::handler::TargetEventHandler;
using ::aion::gameserver::ai::handler::ThinkEventHandler;
using ::aion::gameserver::ai::manager::EmoteManager;
using ::aion::gameserver::ai::manager::SkillAttackManager;
using ::aion::gameserver::ai::manager::WalkManager;
using ::aion::gameserver::ai::poll::AIQuestion;
using ::aion::gameserver::configs::main::CustomConfig;
using ::aion::gameserver::configs::main::DropConfig;
using ::aion::gameserver::configs::main::GroupConfig;
using ::aion::gameserver::configs::main::LegionConfig;
using ::aion::gameserver::configs::main::LoggingConfig;
using ::aion::gameserver::configs::main::SiegeConfig;
using ::aion::gameserver::controllers::NpcController;
using ::aion::gameserver::controllers::SiegeWeaponController;
using ::aion::gameserver::controllers::attack::AggroInfo;
using ::aion::gameserver::controllers::attack::AggroTarget;
using ::aion::gameserver::controllers::attack::DamageInfo;
using ::aion::gameserver::controllers::effect::EffectController;
using ::aion::gameserver::controllers::observer::ActionObserver;
using ::aion::gameserver::controllers::observer::DeathObserver;
using ::aion::gameserver::controllers::observer::ItemUseObserver;
using ::aion::gameserver::controllers::observer::ObserverType;
using ::aion::gameserver::custom::instance::CustomInstanceRankEnum;
using ::aion::gameserver::custom::instance::CustomInstanceService;
using ::aion::gameserver::custom::instance::RoahCustomInstanceHandler;
using ::aion::gameserver::custom::instance::neuralnetwork::PlayerModel;
using ::aion::gameserver::custom::instance::neuralnetwork::PlayerModelController;
using ::aion::gameserver::custom::instance::neuralnetwork::PlayerModelEntry;
using ::aion::gameserver::custom::pvpmap::PvpMapService;
using ::aion::gameserver::dao::PlayerBindPointDAO;
using ::aion::gameserver::dataholders::DataManager;
using ::aion::gameserver::dataholders::loadingutils::adapters::NpcEquipmentList;
using ::aion::gameserver::geoEngine::math::Vector3f;
using ::aion::gameserver::instance::handlers::InstanceHandler;
using ::aion::gameserver::model::ChatType;
using ::aion::gameserver::model::CreatureType;
using ::aion::gameserver::model::DialogPage;
using ::aion::gameserver::model::EmotionType;
using ::aion::gameserver::model::PlayerClass;
using ::aion::gameserver::model::Race;
using ::aion::gameserver::model::SkillElement;
using ::aion::gameserver::model::TaskId;
using ::aion::gameserver::model::TribeClass;
using ::aion::gameserver::model::actions::PlayerMode;
using ::aion::gameserver::model::animations::ActionAnimation;
using ::aion::gameserver::model::animations::AttackHandAnimation;
using ::aion::gameserver::model::animations::AttackTypeAnimation;
using ::aion::gameserver::model::animations::TeleportAnimation;
using ::aion::gameserver::model::autogroup::AutoGroupType;
using ::aion::gameserver::model::base::Base;
using ::aion::gameserver::model::base::BaseOccupier;
using ::aion::gameserver::model::drop::DropItem;
using ::aion::gameserver::model::gameobjects::AionObject;
using ::aion::gameserver::model::gameobjects::Creature;
using ::aion::gameserver::model::gameobjects::DropNpc;
using ::aion::gameserver::model::gameobjects::Item;
using ::aion::gameserver::model::gameobjects::Kisk;
using ::aion::gameserver::model::gameobjects::LetterType;
using ::aion::gameserver::model::gameobjects::Npc;
using ::aion::gameserver::model::gameobjects::NpcObjectType;
using ::aion::gameserver::model::gameobjects::Servant;
using ::aion::gameserver::model::gameobjects::Summon;
using ::aion::gameserver::model::gameobjects::SummonedHouseNpc;
using ::aion::gameserver::model::gameobjects::VisibleObject;
using ::aion::gameserver::model::gameobjects::player::BindPointPosition;
using ::aion::gameserver::model::gameobjects::player::Player;
using ::aion::gameserver::model::gameobjects::player::RequestResponseHandler;
using ::aion::gameserver::model::gameobjects::siege::SiegeNpc;
using ::aion::gameserver::model::gameobjects::state::CreatureSeeState;
using ::aion::gameserver::model::gameobjects::state::CreatureState;
using ::aion::gameserver::model::gameobjects::state::CreatureVisualState;
using ::aion::gameserver::model::geometry::Point3D;
using ::aion::gameserver::model::house::House;
using ::aion::gameserver::model::instance::InstanceProgressionType;
using ::aion::gameserver::model::instance::StageList;
using ::aion::gameserver::model::instance::StageType;
using ::aion::gameserver::model::instance::instancescore::HarmonyArenaScore;
using ::aion::gameserver::model::instance::instancescore::InstanceScore;
using ::aion::gameserver::model::instance::instancescore::PvPArenaScore;
using ::aion::gameserver::model::instance::playerreward::CruciblePlayerReward;
using ::aion::gameserver::model::items::ItemCooldown;
using ::aion::gameserver::model::legionDominion::LegionDominionLocation;
using ::aion::gameserver::model::siege::ArtifactLocation;
using ::aion::gameserver::model::siege::ArtifactStatus;
using ::aion::gameserver::model::siege::FortressLocation;
using ::aion::gameserver::model::siege::SiegeLocation;
using ::aion::gameserver::model::siege::SiegeModType;
using ::aion::gameserver::model::siege::SiegeRace;
using ::aion::gameserver::model::skill::NpcSkillEntry;
using ::aion::gameserver::model::skill::NpcSkillList;
using ::aion::gameserver::model::skill::PlayerSkillEntry;
using ::aion::gameserver::model::stats::calc::Stat2;
using ::aion::gameserver::model::stats::calc::functions::StatSetFunction;
using ::aion::gameserver::model::stats::container::PlayerGameStats;
using ::aion::gameserver::model::stats::container::StatEnum;
using ::aion::gameserver::model::summons::SummonMode;
using ::aion::gameserver::model::team::TemporaryPlayerTeam;
using ::aion::gameserver::model::team::legion::LegionPermissionsMask;
using ::aion::gameserver::model::templates::BindPointTemplate;
using ::aion::gameserver::model::templates::LegionDominionInvasionRift;
using ::aion::gameserver::model::templates::ai::BombTemplate;
using ::aion::gameserver::model::templates::ai::Percentage;
using ::aion::gameserver::model::templates::ai::SummonGroup;
using ::aion::gameserver::model::templates::chest::ChestTemplate;
using ::aion::gameserver::model::templates::chest::KeyItem;
using ::aion::gameserver::model::templates::flypath::FlyPathEntry;
using ::aion::gameserver::model::templates::item::ItemAttackType;
using ::aion::gameserver::model::templates::item::ItemTemplate;
using ::aion::gameserver::model::templates::item::ItemUseLimits;
using ::aion::gameserver::model::templates::item::actions::SkillUseAction;
using ::aion::gameserver::model::templates::item::enums::EquipType;
using ::aion::gameserver::model::templates::item::enums::ItemSubType;
using ::aion::gameserver::model::templates::npc::NpcRating;
using ::aion::gameserver::model::templates::npc::NpcTemplate;
using ::aion::gameserver::model::templates::npc::NpcTemplateType;
using ::aion::gameserver::model::templates::npc::SubDialogType;
using ::aion::gameserver::model::templates::npc::TalkInfo;
using ::aion::gameserver::model::templates::npcshout::NpcShout;
using ::aion::gameserver::model::templates::npcshout::ShoutEventType;
using ::aion::gameserver::model::templates::npcskill::NpcSkillConditionTemplate;
using ::aion::gameserver::model::templates::npcskill::NpcSkillTargetAttribute;
using ::aion::gameserver::model::templates::npcskill::NpcSkillTemplate;
using ::aion::gameserver::model::templates::npcskill::NpcSkillTemplates;
using ::aion::gameserver::model::templates::portal::PortalPath;
using ::aion::gameserver::model::templates::siegelocation::ArtifactActivation;
using ::aion::gameserver::model::templates::siegelocation::DoorRepairData;
using ::aion::gameserver::model::templates::siegelocation::DoorRepairStone;
using ::aion::gameserver::model::templates::spawns::SpawnGroup;
using ::aion::gameserver::model::templates::spawns::SpawnTemplate;
using ::aion::gameserver::model::templates::spawns::basespawns::BaseSpawnTemplate;
using ::aion::gameserver::model::templates::spawns::panesterra::AhserionsFlightSpawnTemplate;
using ::aion::gameserver::model::templates::spawns::siegespawns::SiegeSpawnTemplate;
using ::aion::gameserver::model::templates::teleport::TelelocationTemplate;
using ::aion::gameserver::model::templates::teleport::TeleportLocation;
using ::aion::gameserver::model::templates::teleport::TeleporterTemplate;
using ::aion::gameserver::model::templates::walker::RouteStep;
using ::aion::gameserver::model::templates::walker::WalkerTemplate;
using ::aion::gameserver::network::aion::serverpackets::SM_ACTION_ANIMATION;
using ::aion::gameserver::network::aion::serverpackets::SM_ATTACK_STATUS;
using ::aion::gameserver::network::aion::serverpackets::SM_AUTO_GROUP;
using ::aion::gameserver::network::aion::serverpackets::SM_CUSTOM_SETTINGS;
using ::aion::gameserver::network::aion::serverpackets::SM_DIALOG_WINDOW;
using ::aion::gameserver::network::aion::serverpackets::SM_EMOTION;
using ::aion::gameserver::network::aion::serverpackets::SM_FORCED_MOVE;
using ::aion::gameserver::network::aion::serverpackets::SM_FORTRESS_INFO;
using ::aion::gameserver::network::aion::serverpackets::SM_FRIEND_LIST;
using ::aion::gameserver::network::aion::serverpackets::SM_HEADING_UPDATE;
using ::aion::gameserver::network::aion::serverpackets::SM_HOUSE_TELEPORT;
using ::aion::gameserver::network::aion::serverpackets::SM_MESSAGE;
using ::aion::gameserver::network::aion::serverpackets::SM_PLAYER_STATE;
using ::aion::gameserver::network::aion::serverpackets::SM_PLAY_MOVIE;
using ::aion::gameserver::network::aion::serverpackets::SM_POSITION;
using ::aion::gameserver::network::aion::serverpackets::SM_QUESTION_WINDOW;
using ::aion::gameserver::network::aion::serverpackets::SM_QUEST_ACTION;
using ::aion::gameserver::network::aion::serverpackets::SM_SHIELD_EFFECT;
using ::aion::gameserver::network::aion::serverpackets::SM_SYSTEM_MESSAGE;
using ::aion::gameserver::network::aion::serverpackets::SM_TRANSFORM_IN_SUMMON;
using ::aion::gameserver::network::aion::serverpackets::SM_USE_OBJECT;
using ::aion::gameserver::questEngine::QuestEngine;
using ::aion::gameserver::questEngine::model::QuestActionType;
using ::aion::gameserver::questEngine::model::QuestEnv;
using ::aion::gameserver::questEngine::model::QuestState;
using ::aion::gameserver::questEngine::model::QuestStatus;
using ::aion::gameserver::services::BaseService;
using ::aion::gameserver::services::DialogService;
using ::aion::gameserver::services::HousingService;
using ::aion::gameserver::services::KiskService;
using ::aion::gameserver::services::LegionDominionService;
using ::aion::gameserver::services::NpcShoutsService;
using ::aion::gameserver::services::QuestService;
using ::aion::gameserver::services::RespawnService;
using ::aion::gameserver::services::RiftService;
using ::aion::gameserver::services::SiegeService;
using ::aion::gameserver::services::drop::DropRegistrationService;
using ::aion::gameserver::services::drop::DropService;
using ::aion::gameserver::services::event::EventService;
using ::aion::gameserver::services::findgroup::FindGroupService;
using ::aion::gameserver::services::instance::InstanceService;
using ::aion::gameserver::services::item::ItemService;
using ::aion::gameserver::services::mail::SystemMailService;
using ::aion::gameserver::services::panesterra::PanesterraService;
using ::aion::gameserver::services::panesterra::ahserion::AhserionRaid;
using ::aion::gameserver::services::panesterra::ahserion::PanesterraFaction;
using ::aion::gameserver::services::panesterra::ahserion::PanesterraTeam;
using ::aion::gameserver::services::player::PlayerMailboxState;
using ::aion::gameserver::services::siege::AgentSiege;
using ::aion::gameserver::services::siege::BalaurAssaultService;
using ::aion::gameserver::services::siege::FortressAssault;
using ::aion::gameserver::services::siege::FortressSiege;
using ::aion::gameserver::services::siege::MercenaryLocation;
using ::aion::gameserver::services::siege::Siege;
using ::aion::gameserver::services::siege::SiegeException;
using ::aion::gameserver::services::summons::SummonsService;
using ::aion::gameserver::services::teleport::PortalService;
using ::aion::gameserver::services::teleport::TeleportService;
using ::aion::gameserver::services::trade::PricesService;
using ::aion::gameserver::skillengine::SkillEngine;
using ::aion::gameserver::skillengine::condition::Condition;
using ::aion::gameserver::skillengine::condition::DpCondition;
using ::aion::gameserver::skillengine::effect::AbnormalState;
using ::aion::gameserver::skillengine::model::Effect;
using ::aion::gameserver::skillengine::model::Skill;
using ::aion::gameserver::skillengine::model::SkillTargetSlot;
using ::aion::gameserver::skillengine::model::SkillTemplate;
using ::aion::gameserver::skillengine::model::SkillType;
using ::aion::gameserver::skillengine::model::TransformType;
using ::aion::gameserver::skillengine::properties::TargetSpeciesAttribute;
using ::aion::gameserver::spawnengine::SpawnEngine;
using ::aion::gameserver::spawnengine::SpawnHandlerType;
using ::aion::gameserver::spawnengine::VisibleObjectSpawner;
using ::aion::gameserver::utils::ChatUtil;
using ::aion::gameserver::utils::PacketSendUtility;
using ::aion::gameserver::utils::PositionUtil;
using ::aion::gameserver::utils::ThreadPoolManager;
using ::aion::gameserver::utils::audit::AuditLogger;
using ::aion::gameserver::utils::stats::AbyssRankEnum;
using ::aion::gameserver::utils::stats::CalculationType;
using ::aion::gameserver::utils::time::ServerTime;
using ::aion::gameserver::world::World;
using ::aion::gameserver::world::WorldMapInstance;
using ::aion::gameserver::world::WorldMapType;
using ::aion::gameserver::world::WorldPosition;
using ::aion::gameserver::world::WorldType;
using ::aion::gameserver::world::geo::GeoService;
using ::aion::gameserver::world::knownlist::NpcKnownList;
using ::aion::gameserver::world::zone::ZoneInstance;
using ::aion::gameserver::world::zone::ZoneName;

} // namespace aion::gameserver::handlers::ai
