// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.questEngine.model - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::questEngine::model {

enum class ConditionOperation : std::uint8_t;
enum class ConditionUnionType : std::uint8_t;
enum class QuestActionType : std::uint8_t;
class QuestEnv;
class QuestState;
enum class QuestStatus : std::uint8_t;
class QuestVars;

} // namespace aion::gameserver::questEngine::model
