#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/model/gameobjects/Persistable.h"
#include "aion/gameserver/model/gameobjects/Persistable_PersistentState.h"
#include "aion/gameserver/model/items/ItemStone_ItemStoneType.h"
#include "aion/gameserver/model/items/fwd.h"
#include "aion/gameserver/model/stats/calc/StatOwner.h"
#include "aion/gameserver/model/templates/L10n.h"
#include "aion/gameserver/model/templates/item/fwd.h"

namespace aion::gameserver::model::items {

/**
 * S0c declaration header (docs/design/hub-headers.md §3.5). Java's ItemStone is the base of GodStone and ManaStone (RefCounted, held by Ref in
 * Item) and of IdianStone (a part of Item, cycles review). One C++ object cannot be both, so ItemStone has no runtime base (fieldmap says
 * RefCounted): it is an abstract base with data members, and each subclass picks its runtime base and forwards the retain()/release() of the
 * retainable interface StatOwner (§9.2), so `Ref<ItemStone>`/`Ptr<ItemStone>` work through the interface. The constructor checks the item
 * template (Java DataManager.ITEM_DATA, through model/items/detail/StaticDataLookups.h).
 *
 * @author ATracer, Wakizashi
 */
class ItemStone : public stats::calc::StatOwner, public gameobjects::Persistable, public templates::L10n {
public:
	using ItemStoneType = ItemStone_ItemStoneType; // generated by xmlgen

private:
	const int32_t itemObjId;
	const int32_t itemId;
	runtime::Field<int32_t> slot;
	runtime::Field<PersistentState> persistentState;

protected:
	ItemStone(int32_t itemObjId, int32_t itemId, int32_t slot, PersistentState persistentState);

public:
	~ItemStone() override;

	int32_t getItemObjId() const { return itemObjId; }

	int32_t getItemId() const { return itemId; }

	const templates::item::ItemTemplate* getItemTemplate() const;

	int32_t getSlot() const { return slot.get(); }

	void setSlot(int32_t slot);

	PersistentState getPersistentState() override { return persistentState.get(); }

	void setPersistentState(PersistentState persistentState) override;

	int32_t getL10nId() const override;
};

} // namespace aion::gameserver::model::items
