# Chunk manifest of the game server port (docs/design/handlers-and-porting-plan.md §2.2, §2.4-§2.10 and amendments §8-§12).
#
# One aion_gs_chunk() call per chunk part: a chunk is the unit of ownership of one porting agent, a TARGET is the static library its files are
# compiled into. A chunk may have several parts with different targets (P4-02a, P5-05, P5-14), and several chunks may share a target (P4-07a/b,
# C1/C2). The syntax, the glob language and the checks are documented in cmake/AionChunks.cmake; tools/porting/chunks.py reads this file directly
# (owner, files, java, check, check-ownership).
#
# Owned by the integrator: nobody else edits this file (§2.2). Keep it to aion_gs_chunks_settings() and aion_gs_chunk() calls and comments, so
# chunks.py can parse it without CMake.
#
# Every .cpp/.h/.ipp/.inc below src/, handlers/ and generated/ must match exactly one chunk part, and every Java file below game-server/src and
# game-server/data/handlers must be claimed by exactly one part's JAVA globs (configure fails otherwise, listing the files). Globs are relative
# to the part's ROOT(s) (C++: src, handlers, generated) or to the Java game-server directory (JAVA). Directories hold their fwd.h (generated by
# tools/gen/skeleton.py --fwd): where a package directory is split by file globs, the part that owns "the rest" of the directory owns it.
# Every .cpp/.h/.ipp/.inc below tests/ must lie in one chunk's test directory: TESTS (default: the target name without aion_gs_, plus /<chunk>
# when several chunks share the target, e.g. tests/templates/P4-07a) or TEST_SUPPORT. A chunk's unit test executable is built only from those
# directories, and chunks.py check-ownership allows exactly them.

aion_gs_chunks_settings(
	EXTENSIONS cpp h ipp inc
	ROOTS src handlers generated
	JAVA_ROOTS "src/**/*.java" "data/handlers/**/*.java"
)

# ---------------------------------------------------------------------------------------------------------------------------------------------
# Wave 1 (§2.4, built): leaf libraries. A part with DEPENDS is a leaf: it links only its dependencies (commons, runtime) and its unit tests link
# only the part's library. Every other core part links the shared core dependencies and its tests link aion_gs_core plus empty registries.
# ---------------------------------------------------------------------------------------------------------------------------------------------

# P4-01: the 33 config classes, game-server property transformers (CronExpression lives in P4-02b's services/cron)
aion_gs_chunk(P4-01 TARGET aion_gs_configs PHASE 4
	GLOBS "aion/gameserver/configs/**"
	EXCLUDE "aion/gameserver/configs/ingameshop/**" "aion/gameserver/configs/schedule/**"
	JAVA "src/com/aionemu/gameserver/configs/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/configs/ingameshop/**" "src/com/aionemu/gameserver/configs/schedule/**"
	DEPENDS aion_gs_runtime aion_commons_configuration
	TESTS configs)

# P4-02a (runtime lifetime lane): kernel libraries without Java counterparts, bottom-up (see the dependency comment in CMakeLists.txt). It owns
# the shared kernel test support (tests/runtime/support) and the stress harness (tests/runtime/stress, built by CMakeLists.txt); P4-02b leases
# both.
aion_gs_chunk(P4-02a TARGET aion_gs_runtime_base PHASE 4
	GLOBS "aion/gameserver/runtime/base/**"
	DEPENDS aion_commons_core
	TESTS runtime/base TEST_INCLUDES runtime TEST_SUPPORT runtime/support runtime/stress)
aion_gs_chunk(P4-02a TARGET aion_gs_runtime_sync PHASE 4
	GLOBS "aion/gameserver/runtime/sync/**"
	DEPENDS aion_gs_runtime_base
	TESTS runtime/sync TEST_INCLUDES runtime)
aion_gs_chunk(P4-02a TARGET aion_gs_runtime_lifetime PHASE 4
	GLOBS "aion/gameserver/runtime/lifetime/**"
	DEPENDS aion_gs_runtime_sync
	TESTS runtime/lifetime TEST_INCLUDES runtime)
aion_gs_chunk(P4-02a TARGET aion_gs_runtime_fields PHASE 4
	GLOBS "aion/gameserver/runtime/fields/**"
	DEPENDS aion_gs_runtime_lifetime
	TESTS runtime/fields TEST_INCLUDES runtime)
aion_gs_chunk(P4-02a TARGET aion_gs_runtime_collections PHASE 4
	GLOBS "aion/gameserver/runtime/collections/**"
	DEPENDS aion_gs_runtime_lifetime
	TESTS runtime/collections TEST_INCLUDES runtime)

# P4-02b (runtime scheduling lane): scheduler, ThreadPoolManager, cron, IDFactory, services, the handler registry. The Java class listeners and
# loaders of the scripting engine are replaced by HandlerRegistry.h and aion_gs_regscan (§1.1), so this chunk claims them.
aion_gs_chunk(P4-02b TARGET aion_gs_runtime_sched PHASE 4
	GLOBS "aion/gameserver/runtime/sched/**" "aion/gameserver/utils/ThreadPoolManager.*"
	JAVA "src/com/aionemu/gameserver/utils/ThreadPoolManager.java"
	DEPENDS aion_gs_runtime_lifetime
	TESTS runtime/sched TEST_INCLUDES runtime)
aion_gs_chunk(P4-02b TARGET aion_gs_runtime_services PHASE 4
	GLOBS "aion/gameserver/runtime/services/**" "aion/gameserver/services/cron/**" "aion/gameserver/utils/cron/**" "aion/gameserver/utils/idfactory/**"
	JAVA "src/com/aionemu/gameserver/services/cron/**" "src/com/aionemu/gameserver/utils/cron/**" "src/com/aionemu/gameserver/utils/idfactory/**"
	DEPENDS aion_gs_runtime_sched aion_gs_runtime_collections aion_gs_runtime_fields aion_commons_configuration
	TESTS runtime/services TEST_INCLUDES runtime)
aion_gs_chunk(P4-02b TARGET aion_gs_handler_registry PHASE 4
	GLOBS "aion/gameserver/handlers/**"
	JAVA "src/com/aionemu/gameserver/ai/AIHandlerClassListener.java" "src/com/aionemu/gameserver/instance/InstanceHandlerClassListener.java"
		"src/com/aionemu/gameserver/questEngine/handlers/QuestHandlerLoader.java" "src/com/aionemu/gameserver/utils/chathandlers/ChatCommandsLoader.java"
		"src/com/aionemu/gameserver/world/zone/handler/ZoneHandlerClassListener.java"
	DEPENDS aion_gs_runtime
	TESTS handler_registry)
aion_gs_chunk(P4-02b LEASE PHASE 4
	TEST_SUPPORT runtime/support runtime/stress)

# P4-03: the used jMonkeyEngine math subset
aion_gs_chunk(P4-03 TARGET aion_gs_geomath PHASE 4
	GLOBS "aion/gameserver/geoEngine/math/**"
	JAVA "src/com/aionemu/gameserver/geoEngine/math/**"
	DEPENDS aion_commons_core
	TESTS geomath)

# P4-15a: game client encryption
aion_gs_chunk(P4-15a TARGET aion_gs_network_crypt PHASE 4
	GLOBS "aion/gameserver/network/Crypt.*" "aion/gameserver/network/EncryptionKeyPair.*"
	JAVA "src/com/aionemu/gameserver/network/Crypt.java" "src/com/aionemu/gameserver/network/EncryptionKeyPair.java"
	DEPENDS aion_commons_core
	TESTS network_crypt)

# T2: XML binder runtime and import resolver (static-data.md), the port of dataholders.loadingutils
aion_gs_chunk(T2 TARGET aion_gs_xml PHASE 4
	GLOBS "aion/gameserver/dataholders/loadingutils/**"
	JAVA "src/com/aionemu/gameserver/dataholders/loadingutils/**"
	DEPENDS aion_gs_runtime pugixml::pugixml
	TESTS xml)

# T2-gen: everything tools/xmlgen generates into generated/ (enums, data structs, member blocks, binders). Tool output: only regeneration
# changes it (the integrator lane). The binders reference the hooks of the hand-written shells in src/, so the library links only as part of
# aion_gs_core. Its Java classes are claimed by the chunks that own the hand-written side.
aion_gs_chunk(T2-gen TARGET aion_gs_staticdata PHASE 4 ROOT generated
	GLOBS "aion/gameserver/**")

# ---------------------------------------------------------------------------------------------------------------------------------------------
# Phase 4 (§2.6)
# ---------------------------------------------------------------------------------------------------------------------------------------------

# P4-04: geoEngine. Not a leaf, unlike §2.2's list: the Java loader and models use DataManager, WorldMapTemplate, ZoneService, GeoDataConfig,
# RegionUtil, WorldMapType, HouseDoorState and SiegeService (49 edges into other chunks), so its tests link aion_gs_core. The chunk may make
# itself a leaf (DEPENDS aion_gs_geomath aion_gs_configs aion_gs_runtime ...) once those uses are callbacks.
aion_gs_chunk(P4-04 TARGET aion_gs_geo PHASE 4
	GLOBS "aion/gameserver/geoEngine/**"
	EXCLUDE "aion/gameserver/geoEngine/math/**"
	JAVA "src/com/aionemu/gameserver/geoEngine/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/geoEngine/math/**")

# P4-05: utils (except stats, chathandlers and the runtime's ThreadPoolManager/cron/idfactory), the direct model classes and enums (including the
# generated DialogAction), model.geometry, audit, cache
aion_gs_chunk(P4-05 TARGET aion_gs_base PHASE 4
	GLOBS "aion/gameserver/utils/**" "aion/gameserver/model/*" "aion/gameserver/model/{actions,animations,geometry}/**" "aion/gameserver/cache/**"
	EXCLUDE "aion/gameserver/utils/ThreadPoolManager.*" "aion/gameserver/utils/{stats,chathandlers,cron,idfactory}/**"
	JAVA "src/com/aionemu/gameserver/utils/**" "src/com/aionemu/gameserver/model/*" "src/com/aionemu/gameserver/model/{actions,animations,geometry}/**"
		"src/com/aionemu/gameserver/cache/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/utils/ThreadPoolManager.java" "src/com/aionemu/gameserver/utils/{stats,chathandlers,cron,idfactory}/**")

# P4-06: the generated SM_SYSTEM_MESSAGE factories plus the hand-written packet. The generated definitions need the hand-written header (S0b),
# so they are compiled only once it exists.
aion_gs_chunk(P4-06 TARGET aion_gs_sysmsg PHASE 4
	GLOBS "aion/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.*"
	JAVA "src/com/aionemu/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.java"
	COMPILE_WHEN_EXISTS "aion/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.h")

# P4-07a/b: model.templates (data part; item actions are behaviour, P5-07), split by subpackage
aion_gs_chunk(P4-07a TARGET aion_gs_templates PHASE 4
	GLOBS "aion/gameserver/model/templates/{item,npc,spawns,world,zone,stats,pet}/**"
	EXCLUDE "aion/gameserver/model/templates/item/actions/**"
	JAVA "src/com/aionemu/gameserver/model/templates/{item,npc,spawns,world,zone,stats,pet}/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/model/templates/item/actions/**")
aion_gs_chunk(P4-07b TARGET aion_gs_templates PHASE 4
	GLOBS "aion/gameserver/model/templates/**"
	EXCLUDE "aion/gameserver/model/templates/{item,npc,spawns,world,zone,stats,pet}/**"
	JAVA "src/com/aionemu/gameserver/model/templates/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/model/templates/{item,npc,spawns,world,zone,stats,pet}/**")

# P4-08: the xmlgen shells of skillengine and questEngine (generated blocks + afterUnmarshal hooks). LEASE: the files belong to P5-02/03/04/06
# (their targets compile them, `chunks.py owner` names those chunks); the lease only lets P4-08 change them during phase 4. Ownership passes to
# the P5 chunks at the end of phase 4 by removing this call. XMLGEN_SHELLS restricts the globs to behaviour class shells: X.h/X.cpp whose
# generated/<same path>/X.xml.inc exists.
aion_gs_chunk(P4-08 LEASE PHASE 4 XMLGEN_SHELLS
	GLOBS "aion/gameserver/skillengine/**" "aion/gameserver/questEngine/**")
# The shell tests link the libraries the shells compile into, so they live in the test directories of P5-02 (tests/skills) and P5-06
# (tests/quest); P4-08 leases both during phase 4 (header request shells-5).
aion_gs_chunk(P4-08 LEASE PHASE 4
	TEST_SUPPORT skills quest)

# P4-09: the 97 holders, StaticData, DataManager, and the JAXB roots of config/ingameshop and config/schedule (they need the static data runtime)
aion_gs_chunk(P4-09 TARGET aion_gs_dataholders PHASE 4
	GLOBS "aion/gameserver/dataholders/**" "aion/gameserver/configs/{ingameshop,schedule}/**"
	EXCLUDE "aion/gameserver/dataholders/loadingutils/**"
	JAVA "src/com/aionemu/gameserver/dataholders/**" "src/com/aionemu/gameserver/configs/{ingameshop,schedule}/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/dataholders/loadingutils/**")

# P4-10: world, zones, knownlist, spawnengine, GeoService facade, Respawn/Weather/GameTime services, movement task managers and their bases
aion_gs_chunk(P4-10 TARGET aion_gs_world PHASE 4
	GLOBS "aion/gameserver/world/**" "aion/gameserver/spawnengine/**" "aion/gameserver/model/flypath/**"
		"aion/gameserver/services/{GameTimeService,RespawnService,WeatherService}.*"
		"aion/gameserver/taskmanager/{AbstractPeriodicTaskManager,AbstractFIFOPeriodicTaskManager}.*"
		"aion/gameserver/taskmanager/tasks/{MoveTaskManager,PlayerMoveTaskManager,MovementNotifyTask}.*"
	JAVA "src/com/aionemu/gameserver/world/**" "src/com/aionemu/gameserver/spawnengine/**" "src/com/aionemu/gameserver/model/flypath/**"
		"src/com/aionemu/gameserver/services/{GameTimeService,RespawnService,WeatherService}.java"
		"src/com/aionemu/gameserver/taskmanager/{AbstractPeriodicTaskManager,AbstractFIFOPeriodicTaskManager}.java"
		"src/com/aionemu/gameserver/taskmanager/tasks/{MoveTaskManager,PlayerMoveTaskManager,MovementNotifyTask}.java"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/world/zone/handler/ZoneHandlerClassListener.java")

# P4-11a: model.gameobjects except player (create<T>/postConstruct) and the visible objects of flyring, road and assemblednpc
aion_gs_chunk(P4-11a TARGET aion_gs_objects PHASE 4
	GLOBS "aion/gameserver/model/gameobjects/**" "aion/gameserver/model/{assemblednpc,flyring,road}/**"
	EXCLUDE "aion/gameserver/model/gameobjects/player/**"
	JAVA "src/com/aionemu/gameserver/model/gameobjects/**" "src/com/aionemu/gameserver/model/{assemblednpc,flyring,road}/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/model/gameobjects/player/**")

# P4-11b: controllers direct, movement, observer
aion_gs_chunk(P4-11b TARGET aion_gs_controllers PHASE 4
	GLOBS "aion/gameserver/controllers/*" "aion/gameserver/controllers/{movement,observer}/**"
	JAVA "src/com/aionemu/gameserver/controllers/*" "src/com/aionemu/gameserver/controllers/{movement,observer}/**")

# P4-12: model.gameobjects.player and model.account
aion_gs_chunk(P4-12 TARGET aion_gs_player PHASE 4
	GLOBS "aion/gameserver/model/gameobjects/player/**" "aion/gameserver/model/account/**"
	JAVA "src/com/aionemu/gameserver/model/gameobjects/player/**" "src/com/aionemu/gameserver/model/account/**")

# P4-13: model.items (storage), trade, broker, drop, enchants
aion_gs_chunk(P4-13 TARGET aion_gs_items PHASE 4
	GLOBS "aion/gameserver/model/{items,trade,broker,drop,enchants}/**"
	JAVA "src/com/aionemu/gameserver/model/{items,trade,broker,drop,enchants}/**")

aion_gs_chunk(P4-14 TARGET aion_gs_dao PHASE 4
	GLOBS "aion/gameserver/dao/**"
	JAVA "src/com/aionemu/gameserver/dao/**")

# P4-15: AionConnection, packet bases, client factory and opcode tables (the generated ServerPacketsOpcodes.gen.h and ClientPacketInfo.gen.inc),
# iteminfo/instanceinfo/skillinfo, flood filter, LS/CS links; tests/support holds the shared network test support (FakeGameClient,
# NetworkTestSupport; handlers-and-porting-plan.md §3.1 item 4), included by name through TEST_INCLUDES (header request network-4)
aion_gs_chunk(P4-15 TARGET aion_gs_network PHASE 4
	GLOBS "aion/gameserver/network/**"
	EXCLUDE "aion/gameserver/network/{Crypt,EncryptionKeyPair}.*" "aion/gameserver/network/aion/{serverpackets,clientpackets}/**"
	JAVA "src/com/aionemu/gameserver/network/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/network/{Crypt,EncryptionKeyPair}.java" "src/com/aionemu/gameserver/network/aion/{serverpackets,clientpackets}/**"
	TEST_INCLUDES support TEST_SUPPORT support)

# P4-16/17: server packets A-K / L-Z plus the Abstract* bases and the directory's fwd.h
aion_gs_chunk(P4-16 TARGET aion_gs_sm_ak PHASE 4
	GLOBS "aion/gameserver/network/aion/serverpackets/SM_[A-K]*"
	JAVA "src/com/aionemu/gameserver/network/aion/serverpackets/SM_[A-K]*.java")
aion_gs_chunk(P4-17 TARGET aion_gs_sm_lz PHASE 4
	GLOBS "aion/gameserver/network/aion/serverpackets/**"
	EXCLUDE "aion/gameserver/network/aion/serverpackets/SM_[A-K]*" "aion/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.*"
	JAVA "src/com/aionemu/gameserver/network/aion/serverpackets/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/network/aion/serverpackets/SM_[A-K]*.java"
		"src/com/aionemu/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.java")

# ---------------------------------------------------------------------------------------------------------------------------------------------
# Phase 5 (§2.8)
# ---------------------------------------------------------------------------------------------------------------------------------------------

# P5-00: vertical login slice (file-level globs). The listed client packets and AbstractCharacterEditPacket are excluded from P5-15/16.
aion_gs_chunk(P5-00 TARGET aion_gs_login_slice PHASE 5
	GLOBS "aion/gameserver/services/AccountService.*"
		"aion/gameserver/services/player/{PlayerService,PlayerEnterWorldService,PlayerLeaveWorldService}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_VERSION_CHECK,CM_L2AUTH_LOGIN_CHECK,CM_MAC_ADDRESS,CM_CHARACTER_LIST,CM_CREATE_CHARACTER}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_DELETE_CHARACTER,CM_RESTORE_CHARACTER,CM_CHECK_NICKNAME,CM_CHARACTER_PASSKEY}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_MAY_LOGIN_INTO_GAME,CM_ENTER_WORLD,CM_LEVEL_READY,CM_TIME_CHECK,CM_PING,CM_MOVE,CM_QUIT}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_DISCONNECT,CM_UI_SETTINGS,CM_GAMEGUARD,CM_SECURITY_TOKEN,CM_RECONNECT_AUTH}.*"
		"aion/gameserver/network/aion/clientpackets/AbstractCharacterEditPacket.*"
	JAVA "src/com/aionemu/gameserver/services/AccountService.java"
		"src/com/aionemu/gameserver/services/player/{PlayerService,PlayerEnterWorldService,PlayerLeaveWorldService}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_VERSION_CHECK,CM_L2AUTH_LOGIN_CHECK,CM_MAC_ADDRESS,CM_CHARACTER_LIST,CM_CREATE_CHARACTER}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_DELETE_CHARACTER,CM_RESTORE_CHARACTER,CM_CHECK_NICKNAME,CM_CHARACTER_PASSKEY}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_MAY_LOGIN_INTO_GAME,CM_ENTER_WORLD,CM_LEVEL_READY,CM_TIME_CHECK,CM_PING,CM_MOVE,CM_QUIT}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_DISCONNECT,CM_UI_SETTINGS,CM_GAMEGUARD,CM_SECURITY_TOKEN,CM_RECONNECT_AUTH}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/AbstractCharacterEditPacket.java")

# P5-01: model.stats, utils.stats (StatFunctions), controllers.attack
aion_gs_chunk(P5-01 TARGET aion_gs_stats PHASE 5
	GLOBS "aion/gameserver/model/stats/**" "aion/gameserver/utils/stats/**" "aion/gameserver/controllers/attack/**"
	JAVA "src/com/aionemu/gameserver/model/stats/**" "src/com/aionemu/gameserver/utils/stats/**" "src/com/aionemu/gameserver/controllers/attack/**")

# P5-02a / P5-02b: skillengine except the effect classes (effect/modifier stays here), model.skill, controllers.effect - two parts of one target,
# split along the Skill | Effect seam for M5b-2 (m5b2-plan.md D1, accepted 2026-09-23). P5-02 held 262 of the three skill chunks' 436 unported
# sites and 9,505 of their 17,835 Java lines in ONE chunk, and a chunk is the unit of ownership, so the core of the abilities milestone would have
# been a single lane for the whole of it. The seam is also the review seam: P5-02a is the cast state machine (Skill, the engine, its conditions,
# actions, changes, periodic actions and tasks), P5-02b is the application and lifetime of what a cast produces (Effect, the effect modifiers, the
# effect controller and the player's skill list). Two parts of one target is the pattern P4-07a/P4-07b already use for aion_gs_templates.
aion_gs_chunk(P5-02a TARGET aion_gs_skills PHASE 5
	GLOBS "aion/gameserver/skillengine/*" "aion/gameserver/skillengine/{action,change,condition,periodicaction,properties,task}/**"
		"aion/gameserver/skillengine/model/*"
	EXCLUDE "aion/gameserver/skillengine/model/Effect*"
	JAVA "src/com/aionemu/gameserver/skillengine/*" "src/com/aionemu/gameserver/skillengine/{action,change,condition,periodicaction,properties,task}/**"
		"src/com/aionemu/gameserver/skillengine/model/*"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/skillengine/model/Effect*")
# The tests follow the seam into tests/skills/P5-02a and tests/skills/P5-02b, which is what the manifest derives for a target of several chunks
# (the same shape as tests/templates/P4-07a and P4-07b). The cast state machine, the engine's critical proc, the interaction tasks and the xmlgen
# shells went to P5-02a; the npc skill list and the player's skills and effects to P5-02b.
aion_gs_chunk(P5-02b TARGET aion_gs_skills PHASE 5
	GLOBS "aion/gameserver/skillengine/model/Effect*" "aion/gameserver/skillengine/effect/modifier/**"
		"aion/gameserver/model/skill/**" "aion/gameserver/controllers/effect/**"
	JAVA "src/com/aionemu/gameserver/skillengine/model/Effect*" "src/com/aionemu/gameserver/skillengine/effect/modifier/**"
		"src/com/aionemu/gameserver/model/skill/**" "src/com/aionemu/gameserver/controllers/effect/**")

# P5-03/04: behaviour of the effect classes A-L / M-Z (shells from P4-08); P5-04 also owns the directory's fwd.h
aion_gs_chunk(P5-03 TARGET aion_gs_effects_al PHASE 5
	GLOBS "aion/gameserver/skillengine/effect/[A-L]*"
	JAVA "src/com/aionemu/gameserver/skillengine/effect/[A-L]*.java")
aion_gs_chunk(P5-04 TARGET aion_gs_effects_mz PHASE 5
	GLOBS "aion/gameserver/skillengine/effect/*"
	EXCLUDE "aion/gameserver/skillengine/effect/[A-L]*"
	JAVA "src/com/aionemu/gameserver/skillengine/effect/*"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/skillengine/effect/[A-L]*.java")

# P5-05: the src/ai framework and the 43 root AI handlers (the AI prelude is shared by A1 and I1-I6)
aion_gs_chunk(P5-05 TARGET aion_gs_ai PHASE 5
	GLOBS "aion/gameserver/ai/**"
	JAVA "src/com/aionemu/gameserver/ai/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/ai/AIHandlerClassListener.java")
aion_gs_chunk(P5-05 TARGET aion_gs_handlers_ai_core PHASE 5 ROOT handlers
	GLOBS "aion/gameserver/handlers/ai/*"
	JAVA "data/handlers/ai/*"
	PCH "aion/gameserver/handlers/ai/AiPrelude.h")

# P5-06: questEngine, QuestService, QuestSpawnAnalyzer
aion_gs_chunk(P5-06 TARGET aion_gs_quest PHASE 5
	GLOBS "aion/gameserver/questEngine/**" "aion/gameserver/services/QuestService.*"
	JAVA "src/com/aionemu/gameserver/questEngine/**" "src/com/aionemu/gameserver/services/QuestService.java"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/questEngine/handlers/QuestHandlerLoader.java")

# P5-07: services.item, item actions, Enchant/Armsfusion/Stigma/Warehouse/CubeExpand/Repurchase/LimitedItemTrade/UpgradeArcade
aion_gs_chunk(P5-07 TARGET aion_gs_itemsvc PHASE 5
	GLOBS "aion/gameserver/services/item/**" "aion/gameserver/model/templates/item/actions/**" "aion/gameserver/model/limiteditems/**"
		"aion/gameserver/services/{EnchantService,ArmsfusionService,StigmaService,WarehouseService,CubeExpandService,RepurchaseService}.*"
		"aion/gameserver/services/{LimitedItemTradeService,UpgradeArcadeService}.*" "aion/gameserver/taskmanager/tasks/TemporaryTradeTimeTask.*"
	JAVA "src/com/aionemu/gameserver/services/item/**" "src/com/aionemu/gameserver/model/templates/item/actions/**"
		"src/com/aionemu/gameserver/model/limiteditems/**"
		"src/com/aionemu/gameserver/services/{EnchantService,ArmsfusionService,StigmaService,WarehouseService,CubeExpandService,RepurchaseService}.java"
		"src/com/aionemu/gameserver/services/{LimitedItemTradeService,UpgradeArcadeService}.java"
		"src/com/aionemu/gameserver/taskmanager/tasks/TemporaryTradeTimeTask.java")

# P5-08: services.player (rest), teleport, revive, recall, kisk, duel, pvp, skill learn, class change, dialog, social, summons, abyss, toypet,
# life stats restore, punishment, ban
aion_gs_chunk(P5-08 TARGET aion_gs_playersvc PHASE 5
	GLOBS "aion/gameserver/services/{player,teleport,summons,abyss,toypet,ban}/**" "aion/gameserver/model/summons/**"
		"aion/gameserver/services/{ClassChangeService,DialogService,DuelService,KiskService,LifeStatsRestoreService,PunishmentService}.*"
		"aion/gameserver/services/{PvpService,RecallService,SkillLearnService,SocialService}.*"
	EXCLUDE "aion/gameserver/services/player/{PlayerService,PlayerEnterWorldService,PlayerLeaveWorldService}.*"
	JAVA "src/com/aionemu/gameserver/services/{player,teleport,summons,abyss,toypet,ban}/**" "src/com/aionemu/gameserver/model/summons/**"
		"src/com/aionemu/gameserver/services/{ClassChangeService,DialogService,DuelService,KiskService,LifeStatsRestoreService,PunishmentService}.java"
		"src/com/aionemu/gameserver/services/{PvpService,RecallService,SkillLearnService,SocialService}.java"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/services/player/{PlayerService,PlayerEnterWorldService,PlayerLeaveWorldService}.java")

# P5-09: drop, mail, craft, reward, trade/exchange/private store, broker, recipe, passport, bonus/faction packs
aion_gs_chunk(P5-09 TARGET aion_gs_economy PHASE 5
	GLOBS "aion/gameserver/services/{drop,mail,craft,reward,trade}/**" "aion/gameserver/model/{craft,guide}/**"
		"aion/gameserver/services/{AtreianPassportService,BonusPackService,BrokerService,ExchangeService,FactionPackService}.*"
		"aion/gameserver/services/{PrivateStoreService,RecipeService,TradeService}.*"
	JAVA "src/com/aionemu/gameserver/services/{drop,mail,craft,reward,trade}/**" "src/com/aionemu/gameserver/model/{craft,guide}/**"
		"src/com/aionemu/gameserver/services/{AtreianPassportService,BonusPackService,BrokerService,ExchangeService,FactionPackService}.java"
		"src/com/aionemu/gameserver/services/{PrivateStoreService,RecipeService,TradeService}.java")

# P5-10: model.team, autogroup, findgroup, challenge tasks, team task updaters
aion_gs_chunk(P5-10 TARGET aion_gs_team PHASE 5
	GLOBS "aion/gameserver/model/{team,autogroup,challenge}/**" "aion/gameserver/services/{autogroup,findgroup}/**"
		"aion/gameserver/services/{AutoGroupService,ChallengeTaskService}.*" "aion/gameserver/taskmanager/tasks/{TeamMoveUpdater,TeamStatUpdater}.*"
	JAVA "src/com/aionemu/gameserver/model/{team,autogroup,challenge}/**" "src/com/aionemu/gameserver/services/{autogroup,findgroup}/**"
		"src/com/aionemu/gameserver/services/{AutoGroupService,ChallengeTaskService}.java"
		"src/com/aionemu/gameserver/taskmanager/tasks/{TeamMoveUpdater,TeamStatUpdater}.java")

# P5-11: LegionService, Housing(+Bid), Town, LegionDominion, model.house/town/legionDominion, housing tasks
aion_gs_chunk(P5-11 TARGET aion_gs_legionhouse PHASE 5
	GLOBS "aion/gameserver/services/{LegionService,HousingService,HousingBidService,TownService,LegionDominionService}.*"
		"aion/gameserver/model/{house,town,legionDominion}/**" "aion/gameserver/taskmanager/tasks/housing/**"
		"aion/gameserver/taskmanager/tasks/LegionDominionIntruderUpdateTask.*"
	JAVA "src/com/aionemu/gameserver/services/{LegionService,HousingService,HousingBidService,TownService,LegionDominionService}.java"
		"src/com/aionemu/gameserver/model/{house,town,legionDominion}/**" "src/com/aionemu/gameserver/taskmanager/tasks/housing/**"
		"src/com/aionemu/gameserver/taskmanager/tasks/LegionDominionIntruderUpdateTask.java")

# P5-12a: siege + SiegeService + model.siege (+ ShieldService)
aion_gs_chunk(P5-12a TARGET aion_gs_siege PHASE 5
	GLOBS "aion/gameserver/services/siege/**" "aion/gameserver/services/{SiegeService,ShieldService}.*" "aion/gameserver/model/siege/**"
	JAVA "src/com/aionemu/gameserver/services/siege/**" "src/com/aionemu/gameserver/services/{SiegeService,ShieldService}.java"
		"src/com/aionemu/gameserver/model/siege/**")

# P5-12b: base, rift, vortex, world raid, panesterra, conqueror/protector, events
aion_gs_chunk(P5-12b TARGET aion_gs_worldevents PHASE 5
	GLOBS "aion/gameserver/services/{rift,vortex,worldraid,panesterra,event,conquerorAndProtectorSystem}/**"
		"aion/gameserver/services/{BaseService,RiftService,VortexService,WorldRaidService}.*" "aion/gameserver/model/{base,rift,vortex,event}/**"
	JAVA "src/com/aionemu/gameserver/services/{rift,vortex,worldraid,panesterra,event,conquerorAndProtectorSystem}/**"
		"src/com/aionemu/gameserver/services/{BaseService,RiftService,VortexService,WorldRaidService}.java"
		"src/com/aionemu/gameserver/model/{base,rift,vortex,event}/**")

# P5-13: instance engine and handler core, services.instance, custom (PvpMap, Roah), transfers, model.instance, restrictions
aion_gs_chunk(P5-13 TARGET aion_gs_instance PHASE 5
	GLOBS "aion/gameserver/{instance,custom,restrictions}/**" "aion/gameserver/services/{instance,transfers}/**" "aion/gameserver/model/instance/**"
	JAVA "src/com/aionemu/gameserver/{instance,custom,restrictions}/**" "src/com/aionemu/gameserver/services/{instance,transfers}/**"
		"src/com/aionemu/gameserver/model/instance/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/instance/InstanceHandlerClassListener.java")

# P5-14: remaining services, taskmanager, chathandlers framework (ChatProcessor, ChatUtil), CommandsAccessService, AdminService; aion_gs_app:
# GameServer (main complete), ShutdownHook coordinator, and the executable's main.cpp (MAIN: compiled into aion_game_server, not the library);
# tests/m4: the database helper of CTest gs.m4.check_static_data (aion_gs_m4_database; M4 gate); OTHER_FILES: the server process tests
# (cmake/AppTests.cmake, included by CMakeLists.txt: aion_gs_m4_database, gs.smoke.startup, gs.m4.check_static_data) and their scripts
# (m5a-plan.md I-01: game-server/cmake -> P5-14; the other scripts of cmake/ stay with the integrator)
aion_gs_chunk(P5-14 TARGET aion_gs_misc PHASE 5
	GLOBS "aion/gameserver/services/fwd.h"
		"aion/gameserver/services/{AdminService,AnnouncementService,CommandsAccessService,CronJobService,CuringZoneService}.*"
		"aion/gameserver/services/{DatabaseCleaningService,DebugService,FlyRingService,HTMLService,NameRestrictionService}.*"
		"aion/gameserver/services/{NpcShoutsService,PeriodicSaveService,RoadService,StaticDoorService,SurveyService}.*"
		"aion/gameserver/services/TribeRelationService.*"
		"aion/gameserver/services/antihack/**" "aion/gameserver/taskmanager/**" "aion/gameserver/utils/chathandlers/**"
		"aion/gameserver/model/curingzone/**"
	EXCLUDE "aion/gameserver/taskmanager/{AbstractPeriodicTaskManager,AbstractFIFOPeriodicTaskManager}.*"
		"aion/gameserver/taskmanager/tasks/{MoveTaskManager,PlayerMoveTaskManager,MovementNotifyTask,TemporaryTradeTimeTask,TeamMoveUpdater}.*"
		"aion/gameserver/taskmanager/tasks/{TeamStatUpdater,LegionDominionIntruderUpdateTask}.*" "aion/gameserver/taskmanager/tasks/housing/**"
	JAVA "src/com/aionemu/gameserver/services/{AdminService,AnnouncementService,CommandsAccessService,CronJobService,CuringZoneService}.java"
		"src/com/aionemu/gameserver/services/{DatabaseCleaningService,DebugService,FlyRingService,HTMLService,NameRestrictionService}.java"
		"src/com/aionemu/gameserver/services/{NpcShoutsService,PeriodicSaveService,RoadService,StaticDoorService,SurveyService}.java"
		"src/com/aionemu/gameserver/services/TribeRelationService.java"
		"src/com/aionemu/gameserver/services/antihack/**" "src/com/aionemu/gameserver/taskmanager/**" "src/com/aionemu/gameserver/utils/chathandlers/**"
		"src/com/aionemu/gameserver/model/curingzone/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/utils/chathandlers/ChatCommandsLoader.java"
		"src/com/aionemu/gameserver/taskmanager/{AbstractPeriodicTaskManager,AbstractFIFOPeriodicTaskManager}.java"
		"src/com/aionemu/gameserver/taskmanager/tasks/{MoveTaskManager,PlayerMoveTaskManager,MovementNotifyTask,TemporaryTradeTimeTask,TeamMoveUpdater}.java"
		"src/com/aionemu/gameserver/taskmanager/tasks/{TeamStatUpdater,LegionDominionIntruderUpdateTask}.java"
		"src/com/aionemu/gameserver/taskmanager/tasks/housing/**")
aion_gs_chunk(P5-14 TARGET aion_gs_app PHASE 5
	GLOBS "aion/gameserver/*"
	MAIN "main.cpp"
	JAVA "src/com/aionemu/gameserver/*"
	TEST_SUPPORT m4
	OTHER_FILES "cmake/{AppTests,RunStartupSmoke,RunM4Check}.cmake")

# P5-SC: the M5a scenario harness and gate (m5a-plan.md §5, F-04/F-06/F-08, G-01): tests/scenario builds aion_gs_scenario_tests, which starts
# aion_login_server and aion_game_server as child processes. A test-only chunk: its library aion_gs_scenario has no sources (GLOBS names a
# directory that must stay empty; the placeholder translation unit keeps the target valid). The executable links aion_gs_core (like other core
# chunk tests), aion_loginserver_crypto and the include directory login-server/tests/support (AionLoginClientCrypto.h); CMakeLists.txt adds
# them, the build dependencies on both servers and the executable paths, and includes tests/scenario/ScenarioTests.cmake (owned by P5-SC through
# its test directory) for the CTest registrations. TEST_INCLUDES support: FakeGameClient.h of P4-15.
aion_gs_chunk(P5-SC TARGET aion_gs_scenario PHASE 5
	GLOBS "aion/gameserver/scenario/**"
	TESTS scenario TEST_INCLUDES support)

# P5-15/16: client packets A-K / L-Z minus the login slice files (Abstract* bases go with A-K, the directory's fwd.h with L-Z)
aion_gs_chunk(P5-15 TARGET aion_gs_cm_ak PHASE 5
	GLOBS "aion/gameserver/network/aion/clientpackets/{CM_[A-K],Abstract}*"
	EXCLUDE "aion/gameserver/network/aion/clientpackets/{CM_CHARACTER_LIST,CM_CREATE_CHARACTER,CM_DELETE_CHARACTER,CM_CHECK_NICKNAME}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_CHARACTER_PASSKEY,CM_ENTER_WORLD,CM_DISCONNECT,CM_GAMEGUARD}.*"
		"aion/gameserver/network/aion/clientpackets/AbstractCharacterEditPacket.*"
	JAVA "src/com/aionemu/gameserver/network/aion/clientpackets/{CM_[A-K],Abstract}*.java"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/network/aion/clientpackets/{CM_CHARACTER_LIST,CM_CREATE_CHARACTER,CM_DELETE_CHARACTER,CM_CHECK_NICKNAME}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_CHARACTER_PASSKEY,CM_ENTER_WORLD,CM_DISCONNECT,CM_GAMEGUARD}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/AbstractCharacterEditPacket.java")
aion_gs_chunk(P5-16 TARGET aion_gs_cm_lz PHASE 5
	GLOBS "aion/gameserver/network/aion/clientpackets/**"
	EXCLUDE "aion/gameserver/network/aion/clientpackets/{CM_[A-K],Abstract}*"
		"aion/gameserver/network/aion/clientpackets/{CM_VERSION_CHECK,CM_L2AUTH_LOGIN_CHECK,CM_MAC_ADDRESS,CM_RESTORE_CHARACTER}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_MAY_LOGIN_INTO_GAME,CM_LEVEL_READY,CM_TIME_CHECK,CM_PING,CM_MOVE,CM_QUIT}.*"
		"aion/gameserver/network/aion/clientpackets/{CM_UI_SETTINGS,CM_SECURITY_TOKEN,CM_RECONNECT_AUTH}.*"
	JAVA "src/com/aionemu/gameserver/network/aion/clientpackets/**"
	JAVA_EXCLUDE "src/com/aionemu/gameserver/network/aion/clientpackets/{CM_[A-K],Abstract}*.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_VERSION_CHECK,CM_L2AUTH_LOGIN_CHECK,CM_MAC_ADDRESS,CM_RESTORE_CHARACTER}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_MAY_LOGIN_INTO_GAME,CM_LEVEL_READY,CM_TIME_CHECK,CM_PING,CM_MOVE,CM_QUIT}.java"
		"src/com/aionemu/gameserver/network/aion/clientpackets/{CM_UI_SETTINGS,CM_SECURITY_TOKEN,CM_RECONNECT_AUTH}.java")

# Wave 5a stage 2 leases (m5a-plan.md D7, C-01, lane packets-dao): the seven in-world client packets that need no service, with their byte-vector
# tests. P4-16 (server packets A-K) leases the three P5-15 classes and tests/cm_ak, P4-17 (L-Z) the four P5-16 classes and tests/cm_lz.
# Released (these calls removed) when stage 2 is merged.
aion_gs_chunk(P4-16 LEASE PHASE 5
	GLOBS "aion/gameserver/network/aion/clientpackets/{CM_CHECK_MAIL_UNK,CM_CUSTOM_SETTINGS,CM_CHAT_AUTH}.*"
	TEST_SUPPORT cm_ak)
aion_gs_chunk(P4-17 LEASE PHASE 5
	GLOBS "aion/gameserver/network/aion/clientpackets/{CM_MAY_QUIT,CM_PING_REQUEST,CM_SHOW_FRIENDLIST,CM_SUBZONE_CHANGE}.*"
	TEST_SUPPORT cm_lz)

# ---------------------------------------------------------------------------------------------------------------------------------------------
# Phase 6 (§2.10): handler libraries (ROOT handlers). Category preludes are the PCH; a prelude shared by several chunks is owned by one of them.
# ---------------------------------------------------------------------------------------------------------------------------------------------

aion_gs_chunk(Q01 TARGET aion_gs_handlers_quest_reshanta PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/reshanta/**" "aion/gameserver/handlers/quest/QuestPrelude.h"
	JAVA "data/handlers/quest/reshanta/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q02 TARGET aion_gs_handlers_quest_q02 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/inggison/**"
	JAVA "data/handlers/quest/inggison/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q03 TARGET aion_gs_handlers_quest_q03 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{heiron,verteron}/**"
	JAVA "data/handlers/quest/{heiron,verteron}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q04 TARGET aion_gs_handlers_quest_q04 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{beluslan,brusthonin}/**"
	JAVA "data/handlers/quest/{beluslan,brusthonin}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q05 TARGET aion_gs_handlers_quest_q05 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{eltnen,poeta,oriel}/**"
	JAVA "data/handlers/quest/{eltnen,poeta,oriel}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q06 TARGET aion_gs_handlers_quest_q06 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{crafting,ascension}/**"
	JAVA "data/handlers/quest/{crafting,ascension}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q07 TARGET aion_gs_handlers_quest_q07 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{beshmundir,abyss_entry,silentera_canyon}/**"
	JAVA "data/handlers/quest/{beshmundir,abyss_entry,silentera_canyon}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q08 TARGET aion_gs_handlers_quest_q08 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{gelkmaros,enshar}/**"
	JAVA "data/handlers/quest/{gelkmaros,enshar}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q09 TARGET aion_gs_handlers_quest_q09 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{morheim,ishalgen,pernon}/**"
	JAVA "data/handlers/quest/{morheim,ishalgen,pernon}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q10 TARGET aion_gs_handlers_quest_q10 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{pandaemonium,altgard}/**"
	JAVA "data/handlers/quest/{pandaemonium,altgard}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q11 TARGET aion_gs_handlers_quest_q11 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{daevanion,sanctum}/**"
	JAVA "data/handlers/quest/{daevanion,sanctum}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q12 TARGET aion_gs_handlers_quest_q12 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{theobomos,event_quests,cygnea}/**"
	JAVA "data/handlers/quest/{theobomos,event_quests,cygnea}/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
# Q13/Q14: the remaining small directories, split alphabetically (about 7.8k Java lines each). A new quest directory fails the ownership check
# until it is added here.
aion_gs_chunk(Q13 TARGET aion_gs_handlers_quest_q13 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{abyssal_splinter,alabaster_order,aturam_sky_fortress,bare_truth,black_cloud_traders,blood_crusade}/**"
		"aion/gameserver/handlers/quest/{chantra_dredgion,charlirunerks_daemons,clash_of_destiny,danuar_sanctuary,empyrean_crucible,esoterrace}/**"
		"aion/gameserver/handlers/quest/{fatebound_abbey,fenris_fang,field_wardens,fortuneers,greater_stigma,haramel,iron_wall_warfront}/**"
		"aion/gameserver/handlers/quest/kaisinel_academy/**"
	JAVA "data/handlers/quest/{abyssal_splinter,alabaster_order,aturam_sky_fortress,bare_truth,black_cloud_traders,blood_crusade}/**"
		"data/handlers/quest/{chantra_dredgion,charlirunerks_daemons,clash_of_destiny,danuar_sanctuary,empyrean_crucible,esoterrace}/**"
		"data/handlers/quest/{fatebound_abbey,fenris_fang,field_wardens,fortuneers,greater_stigma,haramel,iron_wall_warfront}/**"
		"data/handlers/quest/kaisinel_academy/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")
aion_gs_chunk(Q14 TARGET aion_gs_handlers_quest_q14 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/quest/{kaldor,kromedes_trial,levinshor,linkgate_foundry,marchutan_priory,miragent_holy_templar}/**"
		"aion/gameserver/handlers/quest/{nightmare_circus,orichalcum_key,pangaea,radiant_ops,rentus_base,sauro_supply_base,shugo_imperial_tomb}/**"
		"aion/gameserver/handlers/quest/{steel_rake,talocs_hollow,terath_dredgion,the_circle,the_eternal_bastion,tiamat_stronghold,udas_temple}/**"
		"aion/gameserver/handlers/quest/wisplight_abbey/**"
	JAVA "data/handlers/quest/{kaldor,kromedes_trial,levinshor,linkgate_foundry,marchutan_priory,miragent_holy_templar}/**"
		"data/handlers/quest/{nightmare_circus,orichalcum_key,pangaea,radiant_ops,rentus_base,sauro_supply_base,shugo_imperial_tomb}/**"
		"data/handlers/quest/{steel_rake,talocs_hollow,terath_dredgion,the_circle,the_eternal_bastion,tiamat_stronghold,udas_temple}/**"
		"data/handlers/quest/wisplight_abbey/**"
	PCH "aion/gameserver/handlers/quest/QuestPrelude.h")

# A1: world AIs (worlds, siege, portals, events, quests, classNpc, walkers)
aion_gs_chunk(A1 TARGET aion_gs_handlers_ai_world PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/ai/{worlds,siege,portals,events,quests,classNpc,walkers}/**"
	JAVA "data/handlers/ai/{worlds,siege,portals,events,quests,classNpc,walkers}/**"
	PCH "aion/gameserver/handlers/ai/AiPrelude.h")

# I1-I6: vertical instance slices, each @InstanceID handler with its ai/instance directory (bin-packed to about 6-8k Java lines; handlers without
# an AI directory go to I1). I1 owns the instance prelude.
aion_gs_chunk(I1 TARGET aion_gs_handlers_inst_1 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/instance/{abyss,dredgion}/**"
		"aion/gameserver/handlers/ai/instance/{abyss,abyssal_splinter,esoterrace,theHexway,unstableSplinterpath,custom,dredgion,azoturanFortress}/**"
		"aion/gameserver/handlers/instance/{AdmaStrongholdInstance,DraupnirCaveInstance,FireTempleInstance,HaramelInstance,LowerUdasTempleInstance}.*"
	JAVA "data/handlers/instance/{abyss,dredgion}/**"
		"data/handlers/ai/instance/{abyss,abyssal_splinter,esoterrace,theHexway,unstableSplinterpath,custom,dredgion,azoturanFortress}/**"
		"data/handlers/instance/{AdmaStrongholdInstance,DraupnirCaveInstance,FireTempleInstance,HaramelInstance,LowerUdasTempleInstance}.java"
	PCH "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/ai/AiPrelude.h")
aion_gs_chunk(I2 TARGET aion_gs_handlers_inst_2 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/instance/crucible/**"
		"aion/gameserver/handlers/ai/instance/{empyreanCrucible,crucibleChallenge,illuminaryObelisk,stonespearReach,darkPoeta,padmarashkasCave}/**"
		"aion/gameserver/handlers/ai/instance/danuarSanctuary/**"
		"aion/gameserver/handlers/instance/{IlluminaryObeliskInstance,InfernalIlluminaryObelisk,StonespearReachInstance,DarkPoetaInstance}.*"
		"aion/gameserver/handlers/instance/{PadmarashkasCaveInstance,DanuarSanctuaryInstance,SeizedDanuarSanctuaryInstance}.*"
	JAVA "data/handlers/instance/crucible/**"
		"data/handlers/ai/instance/{empyreanCrucible,crucibleChallenge,illuminaryObelisk,stonespearReach,darkPoeta,padmarashkasCave}/**"
		"data/handlers/ai/instance/danuarSanctuary/**"
		"data/handlers/instance/{IlluminaryObeliskInstance,InfernalIlluminaryObelisk,StonespearReachInstance,DarkPoetaInstance}.java"
		"data/handlers/instance/{PadmarashkasCaveInstance,DanuarSanctuaryInstance,SeizedDanuarSanctuaryInstance}.java"
	PCH "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/ai/AiPrelude.h")
aion_gs_chunk(I3 TARGET aion_gs_handlers_inst_3 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/instance/{pvp,pvparenas}/**"
		"aion/gameserver/handlers/ai/instance/{engulfedOphidianBridgeInstance,ophidianBridge,idgelDome,kamarBf,pvpArenas,eternalBastion}/**"
		"aion/gameserver/handlers/ai/instance/{kromedesTrial,linkgateFoundry}/**"
		"aion/gameserver/handlers/instance/{OphidanBridgeInstance,OphidanBridgeInstance_L,EternalBastionInstance,KromedesTrialInstance}.*"
		"aion/gameserver/handlers/instance/LinkgateFoundryInstance.*"
	JAVA "data/handlers/instance/{pvp,pvparenas}/**"
		"data/handlers/ai/instance/{engulfedOphidianBridgeInstance,ophidianBridge,idgelDome,kamarBf,pvpArenas,eternalBastion}/**"
		"data/handlers/ai/instance/{kromedesTrial,linkgateFoundry}/**"
		"data/handlers/instance/{OphidanBridgeInstance,OphidanBridgeInstance_L,EternalBastionInstance,KromedesTrialInstance}.java"
		"data/handlers/instance/LinkgateFoundryInstance.java"
	PCH "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/ai/AiPrelude.h")
aion_gs_chunk(I4 TARGET aion_gs_handlers_inst_4 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/ai/instance/{dragonLordsRefuge,drakenspire,beshmundirTemple,aturamSkyFortress}/**"
		"aion/gameserver/handlers/instance/{DragonLordsRefugeInstance,AnguishedDragonLordsRefugeInstance,DrakenspireDepthsInstance}.*"
		"aion/gameserver/handlers/instance/{BeshmundirInstance,AturamSkyFortressInstance}.*"
	JAVA "data/handlers/ai/instance/{dragonLordsRefuge,drakenspire,beshmundirTemple,aturamSkyFortress}/**"
		"data/handlers/instance/{DragonLordsRefugeInstance,AnguishedDragonLordsRefugeInstance,DrakenspireDepthsInstance}.java"
		"data/handlers/instance/{BeshmundirInstance,AturamSkyFortressInstance}.java"
	PCH "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/ai/AiPrelude.h")
aion_gs_chunk(I5 TARGET aion_gs_handlers_inst_5 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/ai/instance/{danuarReliquary,nightmareCircus,raksang,rentusBase,sauroBase,tallocsHollow}/**"
		"aion/gameserver/handlers/instance/{DanuarReliquaryInstance,DanuarReliquaryInstance_L,InfernalDanuarReliquaryInstance}.*"
		"aion/gameserver/handlers/instance/{DanuarMysticariumInstance,NightmareCircus,RaksangRuinsInstance,RentusBaseInstance}.*"
		"aion/gameserver/handlers/instance/{OccupiedRentusBaseInstance,SauroSupplyBaseInstance,TalocsHollowInstance}.*"
	JAVA "data/handlers/ai/instance/{danuarReliquary,nightmareCircus,raksang,rentusBase,sauroBase,tallocsHollow}/**"
		"data/handlers/instance/{DanuarReliquaryInstance,DanuarReliquaryInstance_L,InfernalDanuarReliquaryInstance}.java"
		"data/handlers/instance/{DanuarMysticariumInstance,NightmareCircus,RaksangRuinsInstance,RentusBaseInstance}.java"
		"data/handlers/instance/{OccupiedRentusBaseInstance,SauroSupplyBaseInstance,TalocsHollowInstance}.java"
	PCH "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/ai/AiPrelude.h")
aion_gs_chunk(I6 TARGET aion_gs_handlers_inst_6 PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/instance/rakes/**"
		"aion/gameserver/handlers/ai/instance/{tiamatStrongHold,shugoImperialTomb,theShugoEmperorsVault,rakes,infinityShard,theobomosLab}/**"
		"aion/gameserver/handlers/instance/{TiamatStrongHoldInstance,ShugoImperialTombInstance,TheShugoEmperorsVault,InfinityShardInstance}.*"
		"aion/gameserver/handlers/instance/TheobomosLabInstance.*"
	JAVA "data/handlers/instance/rakes/**"
		"data/handlers/ai/instance/{tiamatStrongHold,shugoImperialTomb,theShugoEmperorsVault,rakes,infinityShard,theobomosLab}/**"
		"data/handlers/instance/{TiamatStrongHoldInstance,ShugoImperialTombInstance,TheShugoEmperorsVault,InfinityShardInstance}.java"
		"data/handlers/instance/TheobomosLabInstance.java"
	PCH "aion/gameserver/handlers/instance/InstancePrelude.h" "aion/gameserver/handlers/ai/AiPrelude.h")

aion_gs_chunk(Z1 TARGET aion_gs_handlers_zone PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/zone/**"
	JAVA "data/handlers/zone/**"
	PCH "aion/gameserver/handlers/zone/ZonePrelude.h")

# C1/C2: one library. C1 = simple admin commands + player commands (+ CommandPrelude.h and the admin/player command preludes); C2 = system commands (reflection, JAXB, XML
# write-back, cross-references) + the console commands.
aion_gs_chunk(C1 TARGET aion_gs_handlers_commands PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/CommandPrelude.h" "aion/gameserver/handlers/admincommands/**" "aion/gameserver/handlers/playercommands/**"
	EXCLUDE "aion/gameserver/handlers/admincommands/{Configure,Ai,Debug,Dye,Reload,Send,FixPath,Stat,SpawnNpc,Delete,SpawnUpdate,GoTo,Quest}.*"
		"aion/gameserver/handlers/admincommands/{RemoveCd,Bookmark}.*"
	JAVA "data/handlers/admincommands/**" "data/handlers/playercommands/**"
	JAVA_EXCLUDE "data/handlers/admincommands/{Configure,Ai,Debug,Dye,Reload,Send,FixPath,Stat,SpawnNpc,Delete,SpawnUpdate,GoTo,Quest}.java"
		"data/handlers/admincommands/{RemoveCd,Bookmark}.java"
	PCH "aion/gameserver/handlers/CommandPrelude.h")
aion_gs_chunk(C2 TARGET aion_gs_handlers_commands PHASE 6 ROOT handlers
	GLOBS "aion/gameserver/handlers/admincommands/{Configure,Ai,Debug,Dye,Reload,Send,FixPath,Stat,SpawnNpc,Delete,SpawnUpdate,GoTo,Quest}.*"
		"aion/gameserver/handlers/admincommands/{RemoveCd,Bookmark}.*" "aion/gameserver/handlers/consolecommands/**"
	JAVA "data/handlers/admincommands/{Configure,Ai,Debug,Dye,Reload,Send,FixPath,Stat,SpawnNpc,Delete,SpawnUpdate,GoTo,Quest}.java"
		"data/handlers/admincommands/{RemoveCd,Bookmark}.java" "data/handlers/consolecommands/**"
	PCH "aion/gameserver/handlers/CommandPrelude.h")
