#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_14054KrallIngToKralltumagna.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Ritsu, Majka
 */
class _14054KrallIngToKralltumagna final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 20> indratu_runaway{235483, 235484, 235485, 235486, 235487, 235488, 235489, 235490, 235491, 235492, 235493, 235494, 235495, 235496, 235497, 235498, 235499, 235500, 235501, 235502};
	static constexpr int32_t baranath = 702040;
	static constexpr int32_t vitusa = 233861;

public:
	_14054KrallIngToKralltumagna() : AbstractQuestHandler(14054) {}

	void register_() override {
		std::array<int32_t, 3> npc_ids{204602, 800413, 802050};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLogOut(questId);
		qe.registerOnLevelChanged(questId);
		for (int32_t npc : npc_ids)
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		for (int32_t mob_id : indratu_runaway)
			qe.registerQuestNpc(mob_id)->addOnKillEvent(questId);
		qe.registerQuestNpc(baranath)->addOnKillEvent(questId);
		qe.registerQuestNpc(vitusa)->addOnKillEvent(questId);
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {14050, 14051, 14052, 14053});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {14050, 14051, 14052, 14053});
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t targetId = env.getTargetId();
		int32_t var = qs->getQuestVarById(0);
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 204602: // Atalante
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							break;
						case SETPRO1:
							return defaultCloseDialog(env, var, var + 1); // 1
					}
					break;
				case 800413: // Javlantia
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1)
								return sendQuestDialog(env, 1352);
							break;
						case SETPRO2:
							return defaultCloseDialog(env, var, var + 1); // 2
					}
					break;

				case 802050: // Bartyn
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 2)
								return sendQuestDialog(env, 2034);
							if (var == 4)
								return sendQuestDialog(env, 2716);
							break;
						case SETPRO4:
							return defaultCloseDialog(env, 2, 3); // 3
						case SETPRO6:
							qs->setRewardGroup(0); // both available groups are the same
							return defaultCloseDialog(env, 4, 5, true, false); // 3
					}
					break;
			}
		}
		if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 800413) { // Javlantia
				if (dialogActionId == USE_OBJECT)
					return sendQuestDialog(env, 3057);
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (qs->getQuestVarById(0) == 2) {
				return defaultOnKillEvent(env, indratu_runaway, 0, 6, 1) || defaultOnKillEvent(env, baranath, 0, 3, 2);
			}
			if (qs->getQuestVarById(0) == 3) {
				return defaultOnKillEvent(env, vitusa, 3, 4); // 4
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_14054KrallIngToKralltumagna, 14054);

} // namespace aion::gameserver::handlers::quest::heiron
