#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_1535TheColdColdGround.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Rolandas, Neon
 */
class _1535TheColdColdGround final : public AbstractQuestHandler {
public:
	_1535TheColdColdGround() : AbstractQuestHandler(1535) {}

	void register_() override {
		qe.registerQuestNpc(204580)->addOnQuestStart(questId);
		qe.registerQuestNpc(204580)->addOnTalkEvent(questId);
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (targetId != 204580)
			return false;

		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->isStartable()) {
			if (env.getDialogActionId() == QUEST_SELECT)
				return sendQuestDialog(env, 4762);
			else
				return sendQuestStartDialog(env);
		}

		if (qs->getStatus() == QuestStatus::START) {
			bool abexSkins = player->getInventory().getItemCountByItemId(182201818) > 4;
			bool worgSkins = player->getInventory().getItemCountByItemId(182201819) > 2;
			bool karnifSkins = player->getInventory().getItemCountByItemId(182201820) > 0;

			switch (env.getDialogActionId()) {
				case QUEST_SELECT:
					return sendQuestDialog(env, 1352);
				case SETPRO1:
					if (abexSkins && removeQuestItem(env, 182201818, 5)) {
						qs->setRewardGroup(0);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 5);
					}
					return sendQuestDialog(env, 1693);
				case SETPRO2:
					if (worgSkins && removeQuestItem(env, 182201819, 3)) {
						qs->setRewardGroup(1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 6);
					}
					return sendQuestDialog(env, 1693);
				case SETPRO3:
					if (karnifSkins && removeQuestItem(env, 182201820, 1)) {
						qs->setRewardGroup(2);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 7);
					}
					return sendQuestDialog(env, 1693);
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1535TheColdColdGround, 1535);

} // namespace aion::gameserver::handlers::quest::heiron
