#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_1540BaittheHooks.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Balthazar
 */
class _1540BaittheHooks final : public AbstractQuestHandler {
public:
	_1540BaittheHooks() : AbstractQuestHandler(1540) {}

	void register_() override {
		qe.registerQuestNpc(204588)->addOnQuestStart(questId);
		qe.registerQuestNpc(204588)->addOnTalkEvent(questId);
		qe.registerQuestNpc(730189)->addOnTalkEvent(questId);
		qe.registerQuestNpc(730190)->addOnTalkEvent(questId);
		qe.registerQuestNpc(730191)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204588) {
				switch (env.getDialogActionId()) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case QUEST_ACCEPT_1:
					case QUEST_ACCEPT_SIMPLE:
						return sendQuestStartDialog(env, 182201822, 1);
				}
			}
		}

		if (qs == nullptr)
			return false;

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 730189:
					switch (env.getDialogActionId()) {
						case USE_OBJECT:
							{
								if (player->getInventory().getItemCountByItemId(182201822) == 1) {
									return useQuestObject(env, 0, 1, false, 0); // 1
								}
							}
					}
					return false;
				case 730190:
					switch (env.getDialogActionId()) {
						case USE_OBJECT:
							{
								if (player->getInventory().getItemCountByItemId(182201822) == 1) {
									return useQuestObject(env, 1, 2, false, 0); // 2
								}
							}
					}
					return false;
				case 730191:
					switch (env.getDialogActionId()) {
						case USE_OBJECT:
							{
								if (qs->getQuestVarById(0) == 2 && player->getInventory().getItemCountByItemId(182201822) == 1) {
									qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
									qs->setStatus(QuestStatus::REWARD);
									updateQuestStatus(env);
									removeQuestItem(env, 182201822, 1);
									return true;
								}
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204588) {
				if (env.getDialogActionId() == SELECT_QUEST_REWARD)
					return sendQuestDialog(env, 5);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1540BaittheHooks, 1540);

} // namespace aion::gameserver::handlers::quest::heiron
