#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/item/ItemTemplate.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_1563TheLegendofVindachinerk.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Gigi, Shepper, Pad
 */
class _1563TheLegendofVindachinerk final : public AbstractQuestHandler {
public:
	_1563TheLegendofVindachinerk() : AbstractQuestHandler(1563) {}

	void register_() override {
		qe.registerQuestNpc(798096)->addOnQuestStart(questId); // Poporinerk
		qe.registerQuestNpc(798096)->addOnTalkEvent(questId); // Poporinerk
		qe.registerQuestNpc(279005)->addOnTalkEvent(questId); // Kohrunerk
		qe.registerQuestItem(182201729, questId); // Jaiorunerk's Diary
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798096) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START && var == 1) {
			switch (targetId) {
				case 798096: // Poporinerk
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1352);
						case SETPRO2:
							if (player->getInventory().getItemCountByItemId(182201729) < 1) {
								return sendQuestDialog(env, 1353);
							} else {
								player->getInventory().decreaseByItemId(182201729, 1);
								qs->setQuestVar(2);
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								return sendQuestDialog(env, 5);
							}
					}
					break;
				case 279005: // Kohrunerk
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1438);
						case SETPRO2:
							if (player->getInventory().getItemCountByItemId(182201729) < 1) {
								return sendQuestDialog(env, 1439);
							} else {
								player->getInventory().decreaseByItemId(182201729, 1);
								qs->setQuestVar(2);
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								return sendQuestDialog(env, 6);
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798096)
				qs->setRewardGroup(0);
			else if (targetId == 279005)
				qs->setRewardGroup(1);
			else
				return false;
			return sendQuestEndDialog(env);
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t id = item.getItemTemplate()->getTemplateId();

		if (id != 182201729)
			return HandlerResult::UNKNOWN;
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return HandlerResult::UNKNOWN;
		changeQuestStep(env, 0, 1);

		return HandlerResult::SUCCESS;
	}
};
AION_QUEST_HANDLER(_1563TheLegendofVindachinerk, 1563);

} // namespace aion::gameserver::handlers::quest::heiron
