#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_1614WheresBelbua.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * Go to the Mudthorn Experiment Lab and find Belbua (204645). When you're ready to leave, talk to Belbua. Escort Belbua outside the Mudthorn
 * Experiment Lab. Let Phuthollo (204519) know Belbua is free.
 *
 * @author Rhys2002, vlog
 */
class _1614WheresBelbua final : public AbstractQuestHandler {
public:
	_1614WheresBelbua() : AbstractQuestHandler(1614) {}

	void register_() override {
		qe.registerQuestNpc(204519)->addOnQuestStart(questId);
		qe.registerOnLogOut(questId);
		qe.registerQuestNpc(204519)->addOnTalkEvent(questId);
		qe.registerQuestNpc(204645)->addOnTalkEvent(questId);
		qe.registerAddOnReachTargetEvent(questId);
		qe.registerAddOnLostTargetEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204519) { // Phuthollo
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 204645: // Belbua
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (qs->getQuestVarById(0) == 0) {
								return sendQuestDialog(env, 1011);
							} else if (qs->getQuestVarById(0) == 1) {
								return sendQuestDialog(env, 1352);
							}
							return false;
						case SETPRO1:
							changeQuestStep(env, 0, 1);
							return sendQuestDialog(env, 1352);
						case SETPRO2:
							return defaultStartFollowEvent(env, *runtime::cast<Npc>(env.getVisibleObject()), 376.0f, 529.0f, 133.0f, 1, 2);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204519) { // Phuthollo
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 10002);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onLogOutEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (qs->getQuestVarById(0) == 2) {
				changeQuestStep(env, 2, 1);
			}
		}
		return false;
	}

	bool onNpcReachTargetEvent(QuestEnv& env) override {
		return defaultFollowEndEvent(env, 2, 2, true); // reward
	}

	bool onNpcLostTargetEvent(QuestEnv& env) override {
		return defaultFollowEndEvent(env, 2, 1, false); // 1
	}
};
AION_QUEST_HANDLER(_1614WheresBelbua, 1614);

} // namespace aion::gameserver::handlers::quest::heiron
