#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_1687TheTigrakiAgreement.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * Go to Draupnir Cave in Asmodae and get Blue Balaur Blood (186000035) (2) and Balaur Rainbow Scales (186000036) (5) for Brosia (204601). Go to
 * Brosia to choose your reward.
 *
 * @author Balthazar, vlog
 */
class _1687TheTigrakiAgreement final : public AbstractQuestHandler {
public:
	_1687TheTigrakiAgreement() : AbstractQuestHandler(1687) {}

	void register_() override {
		qe.registerQuestNpc(204601)->addOnQuestStart(questId);
		qe.registerQuestNpc(204601)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204601) { // Brosia
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 204601) { // Brosia
				switch (env.getDialogActionId()) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case CHECK_USER_HAS_QUEST_ITEM: {
						int64_t collect1 = player->getInventory().getItemCountByItemId(186000035);
						int64_t collect2 = player->getInventory().getItemCountByItemId(186000036);
						if (collect1 >= 2 && collect2 >= 5) {
							removeQuestItem(env, 186000035, 2);
							removeQuestItem(env, 186000036, 5);
							return sendQuestDialog(env, 1352); // choose your reward
						} else
							return sendQuestDialog(env, 1097);
					}
					case FINISH_DIALOG:
						return defaultCloseDialog(env, var, var);
					case SETPRO10:
						qs->setRewardGroup(0);
						return defaultCloseDialog(env, var, var, true, true); // reward 1
					case SETPRO20:
						qs->setRewardGroup(1);
						return defaultCloseDialog(env, var, var, true, true); // reward 2
					case SETPRO30:
						qs->setRewardGroup(2);
						return defaultCloseDialog(env, var, var, true, true); // reward 3
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204601) { // Brosia
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1687TheTigrakiAgreement, 1687);

} // namespace aion::gameserver::handlers::quest::heiron
