#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/controllers/effect/EffectController.h"
#include "aion/gameserver/controllers/effect/PlayerEffectController.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/instance/InstanceService.h"
#include "aion/gameserver/services/teleport/TeleportService.h"
#include "aion/gameserver/skillengine/SkillEngine.h"
#include "aion/gameserver/skillengine/model/Effect.h"
#include "aion/gameserver/world/WorldMapInstance.h"
#include "aion/gameserver/world/WorldMapTypeInfo.h"

namespace aion::gameserver::handlers::quest::heiron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/heiron/_18602NightmareinShiningArmor.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Gigi, Majka
 */
class _18602NightmareinShiningArmor final : public AbstractQuestHandler {
private:
	// Raninia 205229
	// Maga's Potions 730308
	// Robstin's Corpse 700939
	static constexpr std::array<int32_t, 3> npc_ids{205229, 730308, 700939};

public:
	_18602NightmareinShiningArmor() : AbstractQuestHandler(18602) {}

	void register_() override {
		qe.registerOnEnterWorld(questId);
		qe.registerOnDie(questId);
		for (int32_t npc_id : npc_ids)
			qe.registerQuestNpc(npc_id)->addOnTalkEvent(questId);
		qe.registerQuestNpc(205229)->addOnQuestStart(questId);
		qe.registerQuestNpc(217005)->addOnKillEvent(questId); // Shadow Judge Kaliga
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (player->getWorldId() != 300230000) {
				int32_t var = qs->getQuestVarById(0);
				if (var > 0) {
					changeQuestStep(env, var, 0);
					return true;
				}
			}
		}
		return false;
	}

	bool onDieEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (var > 0) {
				changeQuestStep(env, var, 0);
				return true;
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			return defaultOnKillEvent(env, 217005, 3, true); // Shadow Judge Kaliga
		}
		return false;
	}

	void onMovieEndEvent(QuestEnv& env, int32_t movieId) override {
		if (movieId == 454)
			changeQuestStep(env, 1, 2);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = env.getTargetId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 205229) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 205229) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else if (env.getDialogActionId() == SETPRO1) {
					runtime::Ptr<WorldMapInstance> newInstance = InstanceService::getNextAvailableInstance(::aion::gameserver::world::getId(WorldMapType::KROMEDES_TRIAL), *player);
					TeleportService::teleportTo(*player, *newInstance, 244.98566f, 244.14162f, 189.52058f, static_cast<int8_t>(30), TeleportAnimation::FADE_OUT_BEAM);
					changeQuestStep(env, 0, 1); // 1
					return closeDialogWindow(env);
				}
			} else if (targetId == 730308) {
				if (env.getDialogActionId() == USE_OBJECT) {
					if (var == 1) {
						return sendQuestDialog(env, 1352);
					}
				} else if (env.getDialogActionId() == SELECT2_1) {
					return sendQuestDialog(env, 1353);
				} else if (env.getDialogActionId() == SETPRO2) {
					// Check item
					if (var == 1) {
						if (checkItemExistence(env, 185000109, 1, true)) { // Hisen's key
							changeQuestStep(env, 1, 2); // 2
							TeleportService::teleportTo(*player, 300230000, 687.56116f, 681.68225f, 200.28648f, static_cast<int8_t>(30), TeleportAnimation::FADE_OUT_BEAM);
							return closeDialogWindow(env);
						} else {
							return sendQuestDialog(env, 10001);
						}
					} else {
						TeleportService::teleportTo(*player, 300230000, 687.56116f, 681.68225f, 200.28648f, static_cast<int8_t>(30), TeleportAnimation::FADE_OUT_BEAM);
						return closeDialogWindow(env);
					}
				}
			} else if (targetId == 700939) {
				if (env.getDialogActionId() == USE_OBJECT) {
					if (var == 2) {
						return sendQuestDialog(env, 1693);
					}
				} else if (env.getDialogActionId() == SETPRO3) {
					if (!player->getEffectController()->hasAbnormalEffect(19288)) {
						SkillEngine::getInstance().applyEffectDirectly(19288, *player, *player); // Rage of Kromede
					}
					return defaultCloseDialog(env, 2, 3);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 205229) {
				if (env.getDialogActionId() == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_18602NightmareinShiningArmor, 18602);

} // namespace aion::gameserver::handlers::quest::heiron
