#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::ishalgen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/ishalgen/_2005TeachingaLesson.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Mr. Poke, Majka
 */
class _2005TeachingaLesson final : public AbstractQuestHandler {
public:
	_2005TeachingaLesson() : AbstractQuestHandler(2005) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(203540)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 203540:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							else if (var == 1)
								return sendQuestDialog(env, 1352);
							break;
						case SELECT1_1:
							playQuestMovie(env, 54);
							break;
						case SETPRO1:
							if (var == 0) {
								qs->setQuestVarById(0, var + 1);
								updateQuestStatus(env);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
								return true;
							}
							break;
						case CHECK_USER_HAS_QUEST_ITEM:
							if (var == 1) {
								if (QuestService::collectItemCheck(env, true)) {
									qs->setStatus(QuestStatus::REWARD);
									updateQuestStatus(env);
									return sendQuestDialog(env, 5);
								} else
									return sendQuestDialog(env, 1693);
							}
							break;
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203540)
				return sendQuestEndDialog(env);
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {2100});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {2100});
	}
};
AION_QUEST_HANDLER(_2005TeachingaLesson, 2005);

} // namespace aion::gameserver::handlers::quest::ishalgen
