#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::ishalgen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/ishalgen/_2006HitThemWhereitHurts.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Mr. Poke, vlog, Majka
 */
class _2006HitThemWhereitHurts final : public AbstractQuestHandler {
public:
	_2006HitThemWhereitHurts() : AbstractQuestHandler(2006) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(203540)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700095)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203516)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;
		int32_t dialogActionId = env.getDialogActionId();
		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 203540: // Mijou
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 1011);
							} else if (var == 1) {
								return sendQuestDialog(env, 1352);
							}
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
						case CHECK_USER_HAS_QUEST_ITEM:
							return checkQuestItems(env, 1, 1, true, 1438, 1353); // reward
						case FINISH_DIALOG:
							return sendQuestSelectionDialog(env);
					}
					break;
				case 700095: // Mau Grain Sack
					if (var == 1) {
						return true; // give loot
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203516) { // Ulgorn
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 1693);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {2100});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {2100});
	}
};
AION_QUEST_HANDLER(_2006HitThemWhereitHurts, 2006);

} // namespace aion::gameserver::handlers::quest::ishalgen
