#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::ishalgen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/ishalgen/_2003TreasureOfTheDeceased.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Mr. Poke, Majka
 */
class _2003TreasureOfTheDeceased final : public AbstractQuestHandler {
public:
	_2003TreasureOfTheDeceased() : AbstractQuestHandler(2003) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(203539)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 203539) {
				switch (env.getDialogActionId()) {
					case QUEST_SELECT:
						if (var == 0)
							return sendQuestDialog(env, 1011);
						else if (var == 1)
							return sendQuestDialog(env, 1352);
						return false;
					case SELECT1_1:
						playQuestMovie(env, 53);
						break;
					case SETPRO1:
						if (var == 0) {
							qs->setQuestVarById(0, var + 1);
							updateQuestStatus(env);
							PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
							return true;
						}
						return false;
					case CHECK_USER_HAS_QUEST_ITEM:
						if (var == 1) {
							if (QuestService::collectItemCheck(env, true)) {
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								return sendQuestDialog(env, 5);
							} else
								return sendQuestDialog(env, 1693);
						}
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203539)
				return sendQuestEndDialog(env);
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {2100});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {2100});
	}
};
AION_QUEST_HANDLER(_2003TreasureOfTheDeceased, 2003);

} // namespace aion::gameserver::handlers::quest::ishalgen
