#pragma once

#include <cstdint>
#include <vector>

#include "aion/gameserver/runtime/collections/ConcurrentHashMap.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/runtime/lifetime/RefCounted.h"
#include "aion/gameserver/controllers/observer/fwd.h"
#include "aion/gameserver/model/gameobjects/fwd.h"
#include "aion/gameserver/model/siege/FortressLocation_SiegeBuffAction.h"
#include "aion/gameserver/model/siege/SiegeLocation.h"
#include "aion/gameserver/model/siege/fwd.h"
#include "aion/gameserver/model/templates/siegelocation/fwd.h"
#include "aion/gameserver/world/zone/fwd.h"

namespace aion::gameserver::model::siege {

/**
 * S0c declaration header (docs/design/hub-headers.md §3.5), written for the member-type guards waiting for it at the spine freeze.
 *
 * @author Source
 */
class FortressLocation : public SiegeLocation {
	AION_MAKE_REF_FRIEND
public:
	using SiegeBuffAction = ::aion::gameserver::model::siege::FortressLocation_SiegeBuffAction; // generated by xmlgen

private:
	// Java: = new ConcurrentHashMap<>()
	runtime::ConcurrentHashMap<int32_t, runtime::Ref<controllers::observer::ShieldObserver>> shieldObservers{
		AION_LOCK_CLASS(FortressLocation::shieldObservers#stripe)};

protected:
	explicit FortressLocation(const templates::siegelocation::SiegeLocationTemplate* template_);

public:
	static runtime::Ref<FortressLocation> create(const templates::siegelocation::SiegeLocationTemplate* value);

	std::vector<const templates::siegelocation::SiegeLegionReward*> getLegionRewards();

	std::vector<const templates::siegelocation::SiegeMercenaryZone*> getSiegeMercenaryZones();

	bool isEnemy(gameobjects::Creature& creature);

	void onEnterZone(gameobjects::Creature& creature, world::zone::ZoneInstance& zone) override;

	void onLeaveZone(gameobjects::Creature& creature, world::zone::ZoneInstance& zone) override;

	void checkForBalanceBuff(gameobjects::Creature& creature, FortressLocation::SiegeBuffAction siegeBuffAction);

	void clearLocation() override;

protected:
	~FortressLocation() override;
};

} // namespace aion::gameserver::model::siege
