#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::sauro_supply_base {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/sauro_supply_base/_18910TheSauroSupplyBase.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Tibald
 */
class _18910TheSauroSupplyBase final : public AbstractQuestHandler {
public:
	_18910TheSauroSupplyBase() : AbstractQuestHandler(18910) {}

	void register_() override {
		qe.registerQuestNpc(801944)->addOnQuestStart(questId); // Amalde.
		qe.registerQuestNpc(801945)->addOnTalkEvent(questId); // Kanix.
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();
		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 801944) { // Amalde.
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case QUEST_ACCEPT_1:
					case QUEST_ACCEPT_SIMPLE:
						return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 801945:
					{ // Kanix.
						switch (dialogActionId) {
							case QUEST_SELECT:
								return sendQuestDialog(env, 2375);
							case SELECT_QUEST_REWARD:
								changeQuestStep(env, 0, 0, true);
								return sendQuestEndDialog(env);
						}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 801945) { // Kanix.
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_18910TheSauroSupplyBase, 18910);

} // namespace aion::gameserver::handlers::quest::sauro_supply_base
