#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/runtime/lifetime/RefCounted.h"
#include "aion/gameserver/model/gameobjects/Persistable.h"
#include "aion/gameserver/model/gameobjects/Persistable_PersistentState.h"
#include "aion/gameserver/model/gameobjects/player/AbyssRank_AbyssRankUpdateType.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/utils/stats/fwd.h"

namespace aion::gameserver::model::gameobjects::player {

/**
 * S0c declaration header (docs/design/hub-headers.md §3.5). RefCounted (fieldmap K4, `Player.abyssRank`), created with create(). The constructor
 * resolves the rank through AbyssRankEnum and runs doUpdate() (server time, config), so it stays `AION_UNPORTED` after the member
 * initializers.
 *
 * @author ATracer, Divinity
 */
class AbyssRank : public runtime::RefCounted, public Persistable {
	AION_MAKE_REF_FRIEND
public:
	using AbyssRankUpdateType = AbyssRank_AbyssRankUpdateType; // generated by xmlgen

private:
	runtime::Field<int32_t> dailyAP{};
	runtime::Field<int32_t> weeklyAP{};
	runtime::Field<int32_t> currentAp{};
	runtime::Field<int32_t> lastAP{};
	runtime::Field<int32_t> dailyGP{};
	runtime::Field<int32_t> weeklyGP{};
	runtime::Field<int32_t> currentGp{};
	runtime::Field<int32_t> lastGP{};
	runtime::Field<utils::stats::AbyssRankEnum> rank{};
	runtime::Field<PersistentState> persistentState{};
	runtime::Field<int32_t> dailyKill{};
	runtime::Field<int32_t> weeklyKill{};
	runtime::Field<int32_t> allKill{};
	runtime::Field<int32_t> maxRank{};
	runtime::Field<int32_t> lastKill{};
	runtime::Field<int64_t> lastUpdate{};

protected:
	AbyssRank(int32_t dailyAP, int32_t weeklyAP, int32_t ap, int32_t rank, int32_t dailyKill, int32_t weeklyKill, int32_t allKill, int32_t maxRank,
		int32_t lastKill, int32_t lastAP, int64_t lastUpdate, int32_t daily_gp, int32_t weekly_gp, int32_t gp, int32_t last_gp);
	~AbyssRank() override;

public:
	/** Java: new AbyssRank(...) */
	static runtime::Ref<AbyssRank> create(int32_t dailyAP, int32_t weeklyAP, int32_t ap, int32_t rank, int32_t dailyKill, int32_t weeklyKill,
		int32_t allKill, int32_t maxRank, int32_t lastKill, int32_t lastAP, int64_t lastUpdate, int32_t daily_gp, int32_t weekly_gp, int32_t gp,
		int32_t last_gp);

	void addAp(int32_t additionalAp);

	void addGp(int32_t amount, bool addToStats);

	int32_t getDailyAP() const { return dailyAP.get(); }

	int32_t getWeeklyAP() const { return weeklyAP.get(); }

	int32_t getAp() const { return currentAp.get(); }

	utils::stats::AbyssRankEnum getRank() const { return rank.get(); }

	void setRank(utils::stats::AbyssRankEnum rank);

	int32_t getDailyKill() const { return dailyKill.get(); }

	int32_t getWeeklyKill() const { return weeklyKill.get(); }

	int32_t getAllKill() const { return allKill.get(); }

	void incrementAllKills();

	int32_t getMaxRank() const { return maxRank.get(); }

	int32_t getLastKill() const { return lastKill.get(); }

	int32_t getLastAP() const { return lastAP.get(); }

	PersistentState getPersistentState() override { return persistentState.get(); }

	void setPersistentState(PersistentState persistentState) override;

	int64_t getLastUpdate() const { return lastUpdate.get(); }

	void doUpdate();

	int32_t getDailyGP() const { return dailyGP.get(); }

	int32_t getWeeklyGP() const { return weeklyGP.get(); }

	int32_t getCurrentGP() const { return currentGp.get(); }

	int32_t getLastGP() const { return lastGP.get(); }
};

} // namespace aion::gameserver::model::gameobjects::player
