#pragma once

#include <cstdint>
#include <iterator>
#include <string_view>
#include <vector>

#include "aion/gameserver/runtime/collections/ConcurrentHashMap.h"
#include "aion/gameserver/runtime/collections/Iterators.h"
#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Parts.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/model/gameobjects/player/FriendList_Status.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"

namespace aion::gameserver::model::gameobjects::player {

/**
 * Represents a player's Friend list
 * <p>
 * S0c declaration header (docs/design/hub-headers.md §3.5). A part of Player (`PartSlot<FriendList>`, cycles review, created by the DAO and set
 * with setFriendList), bound to the player in the constructor. Java `Iterable<Friend>`: iterator()/begin()/end() iterate a snapshot of the
 * friends (§7.2).
 *
 * @author Ben
 */
class FriendList : public runtime::OwnedPart {
public:
	using Status = FriendList_Status; // generated by xmlgen

private:
	runtime::ConcurrentHashMap<int32_t, runtime::Ref<Friend>> friends{AION_LOCK_CLASS(FriendList::friends#stripe)};
	runtime::OwnerRef<Player> player;
	runtime::Field<Status> status{Status::OFFLINE};

public:
	/** Constructs a friend list for the given player, with the given friends */
	FriendList(Player& owner, const std::vector<runtime::Ptr<Friend>>& friends);

	~FriendList() override;

	/** Gets the friend with this objId, null if not in this list */
	runtime::Ptr<Friend> getFriend(int32_t objId);

	/** Returns number of friends in list */
	int32_t getSize();

	/** Adds the given friend to the list To add a friend and send the correct packets, use addFriend */
	void addFriend(Friend& friend_);

	/** Gets the Friend by this name, null if not in this list */
	runtime::Ptr<Friend> getFriend(std::string_view name);

	/** Deletes given friend from this friends list */
	void delFriend(int32_t friendOid);

	bool isFull();

	/** Gets players status */
	Status getStatus() const { return status.get(); }

	/** Sets the status of the player<br /> <ul><li>Note: Does not update friends</li></ul> */
	void setStatus(Status status, PlayerCommonData& pcd);

	/** Java: Iterator<Friend> iterator() over friends.values() (§7.2) */
	runtime::JavaIterator<runtime::Ptr<Friend>> iterator();

	/** C++ only: range-for over a snapshot of the friends (§7.2) */
	runtime::SnapshotIterator<runtime::Ptr<Friend>> begin();

	std::default_sentinel_t end() const noexcept { return {}; }
};

} // namespace aion::gameserver::model::gameobjects::player
