#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::chantra_dredgion {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/chantra_dredgion/_3725MyLuckyNumber.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author vlog
 */
class _3725MyLuckyNumber final : public AbstractQuestHandler {
public:
	_3725MyLuckyNumber() : AbstractQuestHandler(3725) {}

	void register_() override {
		qe.registerOnDredgionReward(questId);
		qe.registerQuestNpc(799069)->addOnQuestStart(questId);
		qe.registerQuestNpc(799069)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798928)->addOnTalkEvent(questId);
		qe.registerQuestNpc(281866)->addOnKillEvent(questId);
		qe.registerQuestNpc(216866)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799069) { // Yannis
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var1 = qs->getQuestVarById(1);
			int32_t var2 = qs->getQuestVarById(2);
			if (targetId == 798928) { // Yulia
				if (dialogActionId == QUEST_SELECT) {
					if (var1 == 6 && var2 == 15) {
						return sendQuestDialog(env, 10002);
					}
				} else if (dialogActionId == SELECT_QUEST_REWARD) {
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return sendQuestDialog(env, 5);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798928) { // Yulia
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		std::array<int32_t, 2> mobs{281866, 216866};
		return defaultOnKillEvent(env, mobs, 0, 15, 2); // 2: 0 - 15
	}

	bool onDredgionRewardEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var1 = qs->getQuestVarById(1);
			if (var1 < 6) {
				changeQuestStep(env, var1, var1 + 1, false, 1); // 1: 0 - 6
				return true;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_3725MyLuckyNumber, 3725);

} // namespace aion::gameserver::handlers::quest::chantra_dredgion
