#pragma once

// Q03's handler table (P6-Q slice 2, 2026-09-29): the AION_QUEST_HANDLER factories of the 74 handlers of chunk Q03 in the tree (72 generated by
// questgen, 2 hand ports), in the Java directories' file order, and the 4 Java handlers held back out of the tree (the review of 2026-09-29,
// docs/deviations/Q03.md "Held back": gs.scenario.travel's Elyos Daeva arrives in Verteron at level 10, where 14010 starts and 1131, 1146 and
// 1152 show their quest marker). Q03RegistrationTest.cpp and GeneratedHooksTest.cpp share it.

#include <cstdint>
#include <memory>
#include <string_view>
#include <vector>

#include "aion/gameserver/questEngine/handlers/AbstractQuestHandler.h"

// clang-format off
#define AION_Q03_HANDLERS(X) \
	X(verteron, _1141BelbuasTreasure, 1141, true) \
	X(verteron, _1149MissingPoppy, 1149, true) \
	X(verteron, _1156StolenVillageSeal, 1156, true) \
	X(verteron, _1157GaphyrksLove, 1157, true) \
	X(verteron, _1158VillageSealFound, 1158, true) \
	X(verteron, _1162AltenosWeddingRing, 1162, true) \
	X(verteron, _1163ArachnaAntidote, 1163, true) \
	X(verteron, _1169LightningfootTuka, 1169, true) \
	X(verteron, _1170HeadlessStoneStatue, 1170, true) \
	X(verteron, _1183SpiritOfNature, 1183, true) \
	X(verteron, _1192VerteronReinforcements, 1192, true) \
	X(verteron, _1194ReducingTursinStrength, 1194, true) \
	X(verteron, _1197KrallBook, 1197, true) \
	X(verteron, _1198TheWritingOnTheWall, 1198, true) \
	X(verteron, _1218NumonerksDemandNote, 1218, true) \
	X(verteron, _1220ASecretDelivery, 1220, true) \
	X(verteron, _14011FragmentsInTheSky, 14011, true) \
	X(verteron, _14012DukakiMischief, 14012, true) \
	X(verteron, _14013AFrillOfAFuss, 14013, true) \
	X(verteron, _14014TurningTheIde, 14014, true) \
	X(verteron, _14015NotBlindedByVengeance, 14015, true) \
	X(verteron, _14016AGateAgape, 14016, true) \
	X(heiron, _14050OrdersFromHeironFortress, 14050, true) \
	X(heiron, _14051RootOfTheProblem, 14051, true) \
	X(heiron, _14052RestlessSouls, 14052, true) \
	X(heiron, _14053DangerCubed, 14053, true) \
	X(heiron, _14054KrallIngToKralltumagna, 14054, true) \
	X(heiron, _1527RottenRotrons, 1527, true) \
	X(heiron, _1528StrangeLeather, 1528, true) \
	X(heiron, _1535TheColdColdGround, 1535, true) \
	X(heiron, _1537FishOnTheLine, 1537, true) \
	X(heiron, _1540BaittheHooks, 1540, true) \
	X(heiron, _1548KlawControl, 1548, true) \
	X(heiron, _1553MirrorMirror, 1553, true) \
	X(heiron, _1559WhatsintheBox, 1559, true) \
	X(heiron, _1560AJobForPobinerk, 1560, true) \
	X(heiron, _1561TheMisersMap, 1561, true) \
	X(heiron, _1562CrossedDestiny, 1562, true) \
	X(heiron, _1563TheLegendofVindachinerk, 1563, true) \
	X(heiron, _1573SomeTastyMushrooms, 1573, true) \
	X(heiron, _1574AFeatForAVillage, 1574, true) \
	X(heiron, _1578WhereDoRotronsComeFrom, 1578, true) \
	X(heiron, _1582ThePriestsNightmare, 1582, true) \
	X(heiron, _1604ToCatchASpy, 1604, true) \
	X(heiron, _1605TheLepharistSituation, 1605, true) \
	X(heiron, _1607MappingTheRevolutionaries, 1607, true) \
	X(heiron, _1609MessageToArbolusHaven, 1609, true) \
	X(heiron, _1612LepharistSecrets, 1612, true) \
	X(heiron, _1614WheresBelbua, 1614, true) \
	X(heiron, _1620StartSpreadingTheNews, 1620, true) \
	X(heiron, _1626LightThePath, 1626, true) \
	X(heiron, _1628MeteriasRegret, 1628, true) \
	X(heiron, _1634TheWreckOfTheArgos, 1634, true) \
	X(heiron, _1636AFluteForTheFixing, 1636, true) \
	X(heiron, _1640TeleporterRepairs, 1640, true) \
	X(heiron, _1643TheStarOfHeiron, 1643, false) \
	X(heiron, _1644AVeryOldLetter, 1644, true) \
	X(heiron, _1647DressingUpForBollvig, 1647, true) \
	X(heiron, _1648UndeadWarAlert, 1648, true) \
	X(heiron, _1661FindingTheForges, 1661, true) \
	X(heiron, _1670InvisibleBridges, 1670, true) \
	X(heiron, _1687TheTigrakiAgreement, 1687, true) \
	X(heiron, _1691TheLittleLeatherSlipper, 1691, true) \
	X(heiron, _1692ADayOlderAndDeeperInDebt, 1692, true) \
	X(heiron, _1693AreYouMyFather, 1693, true) \
	X(heiron, _18600ScoringSomeBadStigma, 18600, true) \
	X(heiron, _18601NightmareonMyStreets, 18601, true) \
	X(heiron, _18602NightmareinShiningArmor, 18602, true) \
	X(heiron, _3200PriceOfGoodwill, 3200, false) \
	X(heiron, _3502NereusNeedsYou, 3502, true) \
	X(heiron, _80217ToDarkPoeta, 80217, true) \
	X(heiron, _80218DarkPoetaEncore, 80218, true) \
	X(heiron, _80219DarkPoetaFinale, 80219, true) \
	X(heiron, _80220DarkPoetaFinale, 80220, true)
// clang-format on

#define AION_Q03_DECLARE_FACTORY(dir, Class, questId, generated)                                                                               \
	namespace aion::gameserver::handlers::quest::dir {                                                                                           \
	::std::unique_ptr<::aion::gameserver::questEngine::handlers::AbstractQuestHandler> Class##_questFactory();                                  \
	}
AION_Q03_HANDLERS(AION_Q03_DECLARE_FACTORY)
#undef AION_Q03_DECLARE_FACTORY

namespace aion::gameserver::questEngine::handlers::q03::test {

struct Q03Handler {
	std::string_view directory;
	std::string_view javaClass;
	int32_t questId;
	bool generated; // questgen's output (docs/deviations/Q03.md), else a hand port
	std::unique_ptr<AbstractQuestHandler> (*factory)();
};

inline const std::vector<Q03Handler>& q03Handlers() {
#define AION_Q03_ENTRY(dir, Class, questId, generated) \
	Q03Handler{#dir, #Class, questId, generated, &::aion::gameserver::handlers::quest::dir::Class##_questFactory},
	static const std::vector<Q03Handler> table{AION_Q03_HANDLERS(AION_Q03_ENTRY)};
#undef AION_Q03_ENTRY
	return table;
}

/** The Java handlers of the chunk held back out of the tree (directory/class) and their quest ids */
struct Q03HeldBack {
	std::string_view directory;
	std::string_view javaClass;
	int32_t questId;
};

inline constexpr Q03HeldBack Q03_HELD_BACK[] = {
	{"verteron", "_1131UndeliveredArmor", 1131},
	{"verteron", "_1146DelicateMandrake", 1146},
	{"verteron", "_1152OdellaRecipe", 1152},
	{"verteron", "_14010TerrainOfTheVerteronFortress", 14010},
};

} // namespace aion::gameserver::questEngine::handlers::q03::test
