#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::marchutan_priory {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/marchutan_priory/_48006TheMarchutanPrioryBeckons.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _48006TheMarchutanPrioryBeckons final : public AbstractQuestHandler {
public:
	_48006TheMarchutanPrioryBeckons() : AbstractQuestHandler(48006) {}

	void register_() override {
		qe.registerQuestNpc(204191)->addOnQuestStart(questId);
		qe.registerQuestNpc(799847)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204191) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 799847) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 2375);
				} else if (dialogActionId == SELECT_QUEST_REWARD) {
					return defaultCloseDialog(env, 0, 1, true, true);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799847) {
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_48006TheMarchutanPrioryBeckons, 48006);

} // namespace aion::gameserver::handlers::quest::marchutan_priory
