// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.item.bonuses - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::templates::item::bonuses {

struct RandomBonusSet;
enum class StatBonusType : std::uint8_t;

} // namespace aion::gameserver::model::templates::item::bonuses
