#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::daevanion {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/daevanion/_19636FinalStabilization.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Pad
 */
class _19636FinalStabilization final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 2> npcIds{205304, 798155}; // Ionse & Atropos
	static constexpr std::array<int32_t, 4> mobIds{214263, 214264, 214265, 214266};

public:
	_19636FinalStabilization() : AbstractQuestHandler(19636) {}

	void register_() override {
		qe.registerQuestNpc(npcIds[0])->addOnQuestStart(questId);
		for (int32_t npcId : npcIds) {
			qe.registerQuestNpc(npcId)->addOnTalkEvent(questId);
		}
		for (int32_t mobId : mobIds) {
			qe.registerQuestNpc(mobId)->addOnKillEvent(questId);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == npcIds[0]) { // Ionse
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == npcIds[1]) { // Atropos
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 5);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var1 = qs->getQuestVarById(1);
			int32_t targetId = env.getTargetId();
			for (int32_t mobId : mobIds) {
				if (targetId == mobId) {
					if (qs->getQuestVarById(0) == 0) {
						if (0 <= var1 && var1 < 9) {
							changeQuestStep(env, var1, var1 + 1, false, 1); // @1: 1 - 9
							return true;
						} else if (var1 == 9) {
							qs->setQuestVarById(0, 1); // 1
							qs->setStatus(QuestStatus::REWARD); // Reward
							updateQuestStatus(env);
							return true;
						}
					}
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_19636FinalStabilization, 19636);

} // namespace aion::gameserver::handlers::quest::daevanion
