#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_10035SoartotheCorridor.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @Author Majka
 */
class _10035SoartotheCorridor final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 3> mobs{220021, 220022, 216775};

public:
	_10035SoartotheCorridor() : AbstractQuestHandler(10035) {}

	void register_() override {
		// Yulia ID: 798928
		// Laokon ID: 799025
		// Veille ID: 798958
		// Laetia ID: 798996
		// Corridor Entry Controller ID: 702663
		// Outremus ID: 798926
		std::array<int32_t, 7> npcs{798928, 799025, 798958, 798996, 206363, 702663, 798926};
		qe.registerOnLevelChanged(questId);
		qe.registerOnQuestCompleted(questId);
		qe.registerOnEnterZone(ZoneName::get("ANGRIEF_GATE_210050000"), questId);
		for (int32_t mob : mobs) {
			qe.registerQuestNpc(mob)->addOnKillEvent(questId);
		}
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		if (qs == nullptr) {
			return false;
		}
		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 798928: // Yulia
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 1011);
							} else if (var == 7) {
								return sendQuestDialog(env, 3398);
							}
							break;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1);
						case SET_SUCCEED:
							qs->setQuestVar(8);
							qs->setStatus(QuestStatus::REWARD);
							updateQuestStatus(env);
							return closeDialogWindow(env);
					}
					break;
				case 799025: // Laokon
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1) {
								return sendQuestDialog(env, 1352);
							}
							break;
						case SETPRO2:
							return defaultCloseDialog(env, 1, 2);
					}
					break;
				case 798958: // Veille
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 2) {
								return sendQuestDialog(env, 1693);
							}
							break;
						case SETPRO3:
							return defaultCloseDialog(env, 2, 3);
					}
					break;
				case 798996: // Laetia
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 3) {
								return sendQuestDialog(env, 2034);
							}
							break;
						case SELECT4_1:
							playQuestMovie(env, 517);
							return sendQuestDialog(env, 2035);
						case SETPRO4:
							giveQuestItem(env, 182215629, 1);
							return defaultCloseDialog(env, 3, 4);
					}
					break;
				case 702663: // Corridor Entry Controller
					switch (dialogActionId) {
						case USE_OBJECT:
							if (var == 6) {
								removeQuestItem(env, 182215629, 1);
								// spawnForFiveMinutes(700641, player, 1377, 2297, 296, (byte) 90); ToDo: to check on retail what's
								// its function
								qs->setQuestVar(7);
								updateQuestStatus(env);
								return true;
							}
							break;
					}
					break;
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798926) { // Outremus
				if (env.getDialogActionId() == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (var == 5) {
				int32_t var1 = qs->getQuestVarById(1);
				if (var1 >= 0 && var1 < 9) {
					return defaultOnKillEvent(env, mobs, var1, var1 + 1, 1);
				} else if (var1 == 9) {
					qs->setQuestVar(6);
					updateQuestStatus(env);
					return true;
				}
			}
		}
		return false;
	}

	bool onEnterZoneEvent(QuestEnv& env, const ZoneName* zoneName) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (zoneName == ZoneName::get("ANGRIEF_GATE_210050000")) {
				if (var == 4) {
					changeQuestStep(env, 4, 5);
					return true;
				}
			}
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {10031, 10032, 10033, 10034});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {10031, 10032, 10033, 10034});
	}
};
AION_QUEST_HANDLER(_10035SoartotheCorridor, 10035);

} // namespace aion::gameserver::handlers::quest::inggison
