#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/instance/handlers/InstanceHandler.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/model/QuestVars.h"
#include "aion/gameserver/services/instance/InstanceService.h"
#include "aion/gameserver/services/teleport/TeleportService.h"
#include "aion/gameserver/world/WorldMapInstance.h"
#include "aion/gameserver/world/WorldMapTypeInfo.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_10034FoundUnderground.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Majka
 */
class _10034FoundUnderground final : public AbstractQuestHandler {
public:
	_10034FoundUnderground() : AbstractQuestHandler(10034) {}

	void register_() override {
		// Sueros ID: 799030
		// Honeus ID: 799029
		// Titus ID: 798990
		// Drakan Stone Statue ID: 730295
		// Hidden Switch ID: 700604
		// Traveler's bag ID: 730229
		std::array<int32_t, 6> npcs{799030, 799029, 798990, 730295, 700604, 730229};
		qe.addHandlerSideQuestDrop(questId, 730229, 182215628, 1, 100);
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
		qe.registerOnEnterWorld(questId);
		qe.registerQuestItem(182215628, questId);
		qe.registerQuestNpc(216531)->addOnKillEvent(questId);
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr) {
			return false;
		}
		int32_t dialogActionId = env.getDialogActionId();
		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 799030: // Sueros
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 1011);
							}
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1);
					}
					break;
				case 799029:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1) {
								return sendQuestDialog(env, 1352);
							}
							return false;
						case SETPRO2:
							return defaultCloseDialog(env, 1, 2);
					}
					break;
				case 798990:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 2) {
								return sendQuestDialog(env, 1693);
							}
							return false;
						case SELECT3_1_1:
							playQuestMovie(env, 504);
							return sendQuestDialog(env, 1695);
						case SETPRO3:
							return defaultCloseDialog(env, 2, 3);
					}
					break;
				case 730295:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 3) {
								return sendQuestDialog(env, 2034);
							}
							break;
						case SETPRO4:
							if (var == 3) {
								if (removeQuestItem(env, 182215627, 1)) {
									runtime::Ptr<WorldMapInstance> instance = InstanceService::getNextAvailableInstance(::aion::gameserver::world::getId(WorldMapType::UDAS_TEMPLE_LOWER), *player);
									TeleportService::teleportTo(*player, *instance, 795.28143f, 918.806f, 149.80243f, static_cast<int8_t>(73), TeleportAnimation::FADE_OUT_BEAM);
									return true;
								} else {
									return sendQuestDialog(env, 10001);
								}
							}
							break;
					}
					break;
				case 700604:
					if (var == 4 && dialogActionId == USE_OBJECT) {
						runtime::Ptr<InstanceHandler> instanceHandler = player->getWorldMapInstance()->getInstanceHandler();
						instanceHandler->handleUseItemFinish(player, *runtime::cast<Npc>(env.getVisibleObject()));
						return useQuestObject(env, 4, 5, false, 0);
					}
					break;
				case 730229:
					if (var == 6) {
						if (dialogActionId == QUEST_SELECT) {
							return sendQuestDialog(env, 3057);
						}

						if (dialogActionId == SETPRO7) {
							giveQuestItem(env, 182215628, 1);
							return defaultCloseDialog(env, 6, 7);
						}
					}
					break;
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799030) {
				if (env.getDialogActionId() == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVars()->getQuestVars();
			if (var == 3) {
				if (player->getWorldId() == 300160000) {
					qs->setQuestVar(4);
					updateQuestStatus(env);
					return true;
				}
			} else if (var >= 4 && var < 7) {
				if (player->getWorldId() != 300160000) {
					qs->setQuestVar(3);
					updateQuestStatus(env);
					return true;
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->getStatus() != QuestStatus::START) {
			return false;
		}
		int32_t var = qs->getQuestVarById(0);
		switch (env.getTargetId()) {
			case 216531:
				if (var == 5) {
					spawnForFiveMinutes(730229, *player->getWorldMapInstance(), 744, 885, 154, static_cast<int8_t>(90)); // Traveler's Bag
					spawnForFiveMinutes(804815, *player->getWorldMapInstance(), 776, 876, 151, static_cast<int8_t>(90));
					qs->setQuestVarById(0, var + 1);
					updateQuestStatus(env);
					return true;
				}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		if (item.getItemId() == 182215628) {
			runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
			if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
				qs->setQuestVar(8);
				qs->setStatus(QuestStatus::REWARD);
				updateQuestStatus(env);
			}
			return HandlerResult::SUCCESS;
		}
		return HandlerResult::FAILED;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {10031});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {10031});
	}
};
AION_QUEST_HANDLER(_10034FoundUnderground, 10034);

} // namespace aion::gameserver::handlers::quest::inggison
