#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_11012PracticalNursing.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author dta3000
 */
class _11012PracticalNursing final : public AbstractQuestHandler {
public:
	_11012PracticalNursing() : AbstractQuestHandler(11012) {}

	void register_() override {
		qe.registerQuestNpc(799071)->addOnQuestStart(questId);
		qe.registerQuestNpc(799071)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799072)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799073)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799074)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (targetId == 799071) {
			if (qs == nullptr) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else if (env.getDialogActionId() == QUEST_ACCEPT_1) {
					if (giveQuestItem(env, 182206715, 3))
						return sendQuestStartDialog(env);
					else
						return true;
				} else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 799072 && var == 0) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else if (env.getDialogActionId() == SETPRO1) {
					qs->setQuestVar(++var);
					updateQuestStatus(env);
					removeQuestItem(env, 182206715, 1);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				} else
					return sendQuestStartDialog(env);
			} else if (targetId == 799073 && var == 1) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1352);
				} else if (env.getDialogActionId() == SETPRO2) {
					qs->setQuestVar(++var);
					updateQuestStatus(env);
					removeQuestItem(env, 182206715, 1);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				} else
					return sendQuestStartDialog(env);
			} else if (targetId == 799074 && var == 2) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1693);
				} else if (env.getDialogActionId() == SETPRO3) {
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					removeQuestItem(env, 182206715, 1);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				} else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799071) {
				if (env.getDialogActionId() == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_11012PracticalNursing, 11012);

} // namespace aion::gameserver::handlers::quest::inggison
