#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_11005TheLimitsofGenius.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author dta
 */
class _11005TheLimitsofGenius final : public AbstractQuestHandler {
public:
	_11005TheLimitsofGenius() : AbstractQuestHandler(11005) {}

	void register_() override {
		qe.registerQuestNpc(798942)->addOnQuestStart(questId); // Harknes
		qe.registerQuestNpc(798942)->addOnTalkEvent(questId); // Harknes
		qe.registerQuestNpc(798950)->addOnTalkEvent(questId); // Veloso
		qe.registerQuestNpc(798951)->addOnTalkEvent(questId); // Ambred
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798942) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 798950:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							{
								return sendQuestDialog(env, 1352);
							}
						case SETPRO1:
							{
								qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
								updateQuestStatus(env);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
								return true;
							}
					}
					return false;
				case 798951:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							{
								return sendQuestDialog(env, 1693);
							}
						case SETPRO2:
							{
								qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
								updateQuestStatus(env);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
								return true;
							}
					}
					return false;
				case 798942:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							{
								return sendQuestDialog(env, 2375);
							}
						case SELECT_QUEST_REWARD:
							{
								qs->setQuestVar(4);
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								return sendQuestEndDialog(env);
							}
						default:
							return sendQuestEndDialog(env);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798942) {
				switch (env.getDialogActionId()) {
					case SELECT_QUEST_REWARD:
						return sendQuestDialog(env, 5);
					default:
						return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_11005TheLimitsofGenius, 11005);

} // namespace aion::gameserver::handlers::quest::inggison
