#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_11006TestingTheWaters.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _11006TestingTheWaters final : public AbstractQuestHandler {
public:
	_11006TestingTheWaters() : AbstractQuestHandler(11006) {}

	void register_() override {
		qe.registerQuestItem(182206704, questId);
		qe.registerQuestItem(182206705, questId);
		qe.registerQuestNpc(798940)->addOnQuestStart(questId);
		qe.registerQuestNpc(798940)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798940) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env, 182206704, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 798940) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 1)
						return sendQuestDialog(env, 1352);
				} else if (dialogActionId == SETPRO2) {
					giveQuestItem(env, 182206705, 1);
					removeQuestItem(env, 182206706, 1);
					return defaultCloseDialog(env, 1, 2);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798940) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				removeQuestItem(env, 182206707, 1);
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (item.getItemId() == 182206704) {
				return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 0, 1, false, 182206706, 1));
			} else if (item.getItemId() == 182206705) {
				return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 2, 2, true, 182206707, 1));
			}
		}
		return HandlerResult::FAILED;
	}
};
AION_QUEST_HANDLER(_11006TestingTheWaters, 11006);

} // namespace aion::gameserver::handlers::quest::inggison
