#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/controllers/NpcController.h"
#include "aion/gameserver/controllers/VisibleObjectController.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_11147CuteBeadyEyes.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _11147CuteBeadyEyes final : public AbstractQuestHandler {
public:
	_11147CuteBeadyEyes() : AbstractQuestHandler(11147) {}

	void register_() override {
		qe.registerQuestNpc(798997)->addOnQuestStart(questId);
		qe.registerQuestNpc(798997)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799079)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799081)->addOnTalkEvent(questId);
		qe.registerOnEnterZone(ZoneName::get("KLAWNICKTS_CAVE_210050000"), questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798997) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 798997) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0)
						return sendQuestDialog(env, 1011);
					else if (qs->getQuestVarById(0) == 1)
						return sendQuestDialog(env, 1352);
				} else if (dialogActionId == SETPRO1) {
					spawnForFiveMinutesInFrontOf(799079, *player, 1);
					spawnForFiveMinutesInFrontOf(799081, *player, -1);
					return defaultCloseDialog(env, 0, 1);
				} else if (dialogActionId == SETPRO2) {
					return defaultCloseDialog(env, 1, 2);
				}
			} else if (targetId == 799079) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1693);
				} else if (dialogActionId == SETPRO3) {
					runtime::Ptr<Npc> npc = runtime::cast<Npc>(env.getVisibleObject());
					npc->getController().delete_();
					return defaultCloseDialog(env, 2, 3);
				}
			} else if (targetId == 799081) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 2034);
				} else if (dialogActionId == SETPRO4) {
					runtime::Ptr<Npc> npc = runtime::cast<Npc>(env.getVisibleObject());
					npc->getController().delete_();
					return defaultCloseDialog(env, 3, 4);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798997) {
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 10002);
					default:
						{
							return sendQuestEndDialog(env);
						}
				}
			}
		}
		return false;
	}

	bool onEnterZoneEvent(QuestEnv& env, const ZoneName* zoneName) override {
		if (zoneName == ZoneName::get("KLAWNICKTS_CAVE_210050000")) {
			runtime::Ptr<Player> player = env.getPlayer();
			if (player == nullptr)
				return false;
			runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
			if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
				int32_t var = qs->getQuestVarById(0);
				if (var == 4) {
					changeQuestStep(env, 4, 4, true);
					return true;
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_11147CuteBeadyEyes, 11147);

} // namespace aion::gameserver::handlers::quest::inggison
