#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_11107ComfortisaBox.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Leunam
 */
class _11107ComfortisaBox final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 4> npc_ids{798963, 296489, 296490, 296491};

public:
	_11107ComfortisaBox() : AbstractQuestHandler(11107) {}

	void register_() override {
		qe.registerQuestNpc(798963)->addOnQuestStart(questId);
		for (int32_t npc_id : npc_ids)
			qe.registerQuestNpc(npc_id)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (targetId == 798963) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else if (env.getDialogActionId() == QUEST_ACCEPT_1) {
					if (giveQuestItem(env, 182206859, 3))
						return sendQuestStartDialog(env);
					else
						return true;
				} else
					return sendQuestStartDialog(env);
			}
		}
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798963) {
				if (env.getDialogActionId() == USE_OBJECT)
					return sendQuestDialog(env, 2375);
				else if (env.getDialogActionId() == SELECT_QUEST_REWARD)
					return sendQuestDialog(env, 5);
				else
					return sendQuestEndDialog(env);
			}
		} else if (qs->getStatus() != QuestStatus::START) {
			return false;
		}
		if (targetId == 296489) {
			switch (env.getDialogActionId()) {
				case QUEST_SELECT:
					if (var == 0)
						return sendQuestDialog(env, 1352);
					return false;
				case SETPRO1:
					if (var == 0) {
						removeQuestItem(env, 182206859, 1);
						qs->setQuestVarById(0, var + 1);
						updateQuestStatus(env);
						PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
						return true;
					}
					return false;
			}
		} else if (targetId == 296490) {
			switch (env.getDialogActionId()) {
				case QUEST_SELECT:
					if (var == 1)
						return sendQuestDialog(env, 1693);
					return false;
				case SETPRO2:
					if (var == 1) {
						removeQuestItem(env, 182206859, 1);
						qs->setQuestVarById(0, var + 1);
						updateQuestStatus(env);
						PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
						return true;
					}
					return false;
			}
		} else if (targetId == 296491) {
			switch (env.getDialogActionId()) {
				case QUEST_SELECT:
					if (var == 2)
						return sendQuestDialog(env, 2034);
					return false;
				case SETPRO3:
					if (var == 2) {
						removeQuestItem(env, 182206859, 1);
						qs->setQuestVarById(0, var + 1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
						return true;
					}
					return false;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_11107ComfortisaBox, 11107);

} // namespace aion::gameserver::handlers::quest::inggison
