#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::inggison {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/inggison/_11143BabyShulackJourney.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _11143BabyShulackJourney final : public AbstractQuestHandler {
public:
	_11143BabyShulackJourney() : AbstractQuestHandler(11143) {}

	void register_() override {
		qe.registerQuestItem(182206866, questId);
		qe.registerQuestNpc(700909)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798985)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798984)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798976)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798948)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 0) {
				if (dialogActionId == QUEST_ACCEPT_1) {
					QuestService::startQuest(env);
					return closeDialogWindow(env);
				}
			} else if (targetId == 700909) {
				return giveQuestItem(env, 182206866, 1);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 798985) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1352);
				} else if (dialogActionId == SETPRO1) {
					return defaultCloseDialog(env, 0, 1);
				}
			} else if (targetId == 798984) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1693);
				} else if (dialogActionId == SETPRO2) {
					return defaultCloseDialog(env, 1, 2);
				}
			} else if (targetId == 798976) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 2034);
				} else if (dialogActionId == SETPRO3) {
					qs->setQuestVar(3);
					return defaultCloseDialog(env, 3, 3, true, false);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798948) {
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 2375);
					default:
						{
							removeQuestItem(env, 182206866, 1);
							return sendQuestEndDialog(env);
						}
				}
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->isStartable()) {
			return ::aion::gameserver::questEngine::handlers::fromBoolean(sendQuestDialog(env, 4));
		}
		return HandlerResult::FAILED;
	}
};
AION_QUEST_HANDLER(_11143BabyShulackJourney, 11143);

} // namespace aion::gameserver::handlers::quest::inggison
