#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::fenris_fang {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/fenris_fang/_4941GroupPandaemoniumHonors.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Gigi
 */
class _4941GroupPandaemoniumHonors final : public AbstractQuestHandler {
public:
	_4941GroupPandaemoniumHonors() : AbstractQuestHandler(4941) {}

	void register_() override {
		qe.registerQuestNpc(204060)->addOnQuestStart(questId);
		qe.registerQuestNpc(204060)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204060) {
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 204060:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							else if (var == 1)
								return sendQuestDialog(env, 1352);
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
						case CHECK_USER_HAS_QUEST_ITEM: {
							int64_t itemCount1 = player->getInventory().getItemCountByItemId(182207121);
							if (itemCount1 >= 1) {
								removeQuestItem(env, 182207121, 1);
								changeQuestStep(env, 1, 1, true);
								return sendQuestDialog(env, 5);
							} else
								return sendQuestDialog(env, 10001);
						}
					}
					break;
				default:
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204060)
				return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_4941GroupPandaemoniumHonors, 4941);

} // namespace aion::gameserver::handlers::quest::fenris_fang
