// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.world - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::model::templates::world {

struct AiInfo;
class WeatherEntry;
class WeatherTable;
class WorldMapTemplate;

} // namespace aion::gameserver::model::templates::world
