#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::haramel {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/haramel/_18511OutOfThePast.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author vlog
 */
class _18511OutOfThePast final : public AbstractQuestHandler {
public:
	_18511OutOfThePast() : AbstractQuestHandler(18511) {}

	void register_() override {
		std::array<int32_t, 4> npcs{799522, 700954, 730359, 790000};
		qe.registerQuestNpc(799522)->addOnQuestStart(questId);
		qe.registerOnGetItem(182212011, questId);
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799522) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 700954:
					{ // Well-Dried Ginseng
						return true; // loot
					}
				case 730359: // Huge Cauldron
					switch (dialogActionId) {
						case USE_OBJECT:
							if (var == 0) {
								return sendQuestDialog(env, 1011);
							}
							return false;
						case CHECK_USER_HAS_QUEST_ITEM:
							return checkQuestItems(env, 0, 0, false, 1352, 10001);
						case SETPRO2:
							giveQuestItem(env, 182212011, 1);
							return closeDialogWindow(env);
						case FINISH_DIALOG:
							return closeDialogWindow(env);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 790000) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onGetItemEvent(QuestEnv& env) override {
		defaultOnGetItemEvent(env, 0, 1, false); // 1
		changeQuestStep(env, 1, 1, true); // reward
		return true;
	}
};
AION_QUEST_HANDLER(_18511OutOfThePast, 18511);

} // namespace aion::gameserver::handlers::quest::haramel
