#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/controllers/movement/PlayerMoveController.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::haramel {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/haramel/_28500OdellaOdellaWhereArtThou.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author zhkchi, Majka
 */
class _28500OdellaOdellaWhereArtThou final : public AbstractQuestHandler {
public:
	_28500OdellaOdellaWhereArtThou() : AbstractQuestHandler(28500) {}

	void register_() override {
		std::array<int32_t, 5> npcs{203560, 203649, 730306, 730307, 799522};
		qe.registerQuestNpc(203560)->addOnQuestStart(questId);
		qe.registerOnEnterZone(ZoneName::get("DF1A_SENSORYAREA_Q28500_206151_3_220030000"), questId);
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203560) { // Morn
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 203649: // Gulkalla
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 1011);
							}
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
					}
					break;
				case 730306: // Discarded Odium Piece
					switch (dialogActionId) {
						case USE_OBJECT:
							if (var == 1) {
								return sendQuestDialog(env, 1352);
							}
							return false;
						case SETPRO2:
							return defaultCloseDialog(env, 1, 2); // 2
					}
					break;
				case 730307: // Discarded Odium Pile
					switch (dialogActionId) {
						case USE_OBJECT:
							if (var == 2) {
								return sendQuestDialog(env, 1693);
							}
							return false;
						case SETPRO3:
							playQuestMovie(env, 217);
							return defaultCloseDialog(env, 2, 3); // 3
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799522) { // Moorilerk
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				} else if (dialogActionId == SELECT_QUEST_REWARD) {
					return sendQuestDialog(env, 5);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onEnterZoneEvent(QuestEnv& env, const ZoneName* zoneName) override { // Investigate the Abandoned Relic Site.
		if (zoneName == ZoneName::get("DF1A_SENSORYAREA_Q28500_206151_3_220030000")) {
			runtime::Ptr<Player> player = env.getPlayer();
			if (player == nullptr) {
				return false;
			}

			runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
			if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
				int32_t var = qs->getQuestVarById(0);

				if (var == 3) {
					playQuestMovie(env, 217);
					player->getMoveController()->abortMove();
				}
			}
			return true;
		}
		return false;
	}

	void onMovieEndEvent(QuestEnv& env, int32_t movieId) override {
		if (movieId == 217)
			changeQuestStep(env, 3, 3, true); // reward
	}
};
AION_QUEST_HANDLER(_28500OdellaOdellaWhereArtThou, 28500);

} // namespace aion::gameserver::handlers::quest::haramel
