#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::oriel {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/oriel/_50009TisTheSeason.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Bobobear
 */
class _50009TisTheSeason final : public AbstractQuestHandler {
public:
	_50009TisTheSeason() : AbstractQuestHandler(50009) {}

	void register_() override {
		qe.registerQuestNpc(831032)->addOnQuestStart(questId);
		qe.registerQuestNpc(831038)->addOnQuestStart(questId);
		qe.registerQuestNpc(831032)->addOnTalkEvent(questId);
		qe.registerQuestNpc(831038)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 831032 || targetId == 831038) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case QUEST_ACCEPT_1:
					case QUEST_ACCEPT_SIMPLE:
						return sendQuestStartDialog(env);
					case QUEST_REFUSE_1:
					case QUEST_REFUSE_SIMPLE:
						return sendQuestDialog(env, 1004);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 831032 || targetId == 831038) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 2375);
					case SELECT_QUEST_REWARD:
						changeQuestStep(env, 0, 0, true);
						return sendQuestEndDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 831032 || targetId == 831038)
				return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_50009TisTheSeason, 50009);

} // namespace aion::gameserver::handlers::quest::oriel
