// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.ai - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::ai {

class AI;
class AIActions;
class AIEngine;
class AIHandlerClassListener;
class AILogger;
class AIRequest;
enum class AIState : std::uint8_t;
enum class AISubState : std::uint8_t;
template <class T> class AITemplate;
class AbstractAI;
enum class AttackIntention : std::uint8_t;
class HpPhases;
class NpcAI;

// Nested types (declared inside their outer class, include its header):
//   AIEngine::DummyAI
//   AIEngine::SingletonHolder
//   HpPhases::PhaseHandler

// Java annotation types (no C++ type; markers and registries replace them):
//   @AIName

} // namespace aion::gameserver::ai
