#pragma once

#include <cstdint>
#include <optional>

#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/runtime/lifetime/RefCounted.h"
#include "aion/gameserver/utils/time/gametime/GameTime_Month.h"
#include "aion/gameserver/utils/time/gametime/fwd.h"

namespace aion::gameserver::utils::time::gametime {

/**
 * Represents the internal clock for the time in aion world
 * <p>
 * S0c declaration header (docs/design/hub-headers.md §3.5): RefCounted (fieldmap K4, GameTimeService). Java Cloneable: clone(), minus() and
 * plus() return new objects.
 *
 * @author Ben, vlog, Neon
 */
class GameTime : public runtime::RefCounted {
	AION_MAKE_REF_FRIEND
private:
	using Month = ::aion::gameserver::utils::time::gametime::GameTime_Month; // generated by xmlgen
	static constexpr int32_t MINUTES_IN_HOUR = 60;
	static constexpr int32_t MINUTES_IN_DAY = MINUTES_IN_HOUR * 24;
	/** Java: Month.getDaysOfYear() * MINUTES_IN_DAY; every one of the 12 months has 31 days */
	static constexpr int32_t MINUTES_IN_YEAR = 12 * 31 * MINUTES_IN_DAY;
	runtime::Field<int32_t> gameTime{};
	runtime::Field<DayTime> dayTime{};

protected:
	/** Constructs a GameTime with the given time in minutes since midnight 01.01.0000 */
	explicit GameTime(std::optional<int32_t> time);

public:
	static runtime::Ref<GameTime> create(std::optional<int32_t> time);

	int32_t getTime() const { return this->gameTime.get(); }

	/** Adds the given number of minutes to the GameTime */
	void addMinutes(int32_t minutes);

	DayTime getDayTime() const { return this->dayTime.get(); }

	bool setDayTime(DayTime dayTime);

	int32_t getYear();

	int32_t getMonth();

	int32_t getDay();

	int32_t getHour();

	int32_t getMinute();

private:
	void onHourChange(bool changedByClock);

	DayTime calculateDayTime();

public:
	/** @return a new GameTime */
	runtime::Ref<GameTime> minus(GameTime& gt);

	/** @return a new GameTime */
	runtime::Ref<GameTime> plus(GameTime& gt);

	bool isGreaterThan(GameTime& gt);

	bool isLessThan(GameTime& gt);

	int32_t hashCode() const;

	bool equals(const GameTime& obj) const;

	runtime::Ref<GameTime> clone();

protected:
	~GameTime() override;
};

} // namespace aion::gameserver::utils::time::gametime
