#include "aion/gameserver/handlers/quest/QuestPrelude.h"

namespace aion::gameserver::handlers::quest::steel_rake {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/steel_rake/_3220KeyItemHiddenQuest02.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author vlog TODO: implement
 */
class _3220KeyItemHiddenQuest02 final : public AbstractQuestHandler {
public:
	_3220KeyItemHiddenQuest02() : AbstractQuestHandler(3220) {}

	void register_() override {
		// TODO Auto-generated method stub
	}
};
AION_QUEST_HANDLER(_3220KeyItemHiddenQuest02, 3220);

} // namespace aion::gameserver::handlers::quest::steel_rake
