// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.rewards - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::templates::rewards {

class ArenaRewardItem;
enum class BonusType : std::uint8_t;
class CraftItem;
class CraftRecipe;
class CraftReward;
class FoodItem;
class FullRewardItem;
class IdLevelReward;
class MedicineItem;
class RewardEntryItem;
class RewardItem;

} // namespace aion::gameserver::model::templates::rewards
