#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::talocs_hollow {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/talocs_hollow/_21467SpawningTheSapSuckers.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _21467SpawningTheSapSuckers final : public AbstractQuestHandler {
public:
	_21467SpawningTheSapSuckers() : AbstractQuestHandler(21467) {}

	void register_() override {
		qe.registerOnDie(questId);
		qe.registerOnLogOut(questId);
		qe.registerOnQuestTimerEnd(questId);
		qe.registerQuestNpc(799527)->addOnQuestStart(questId);
		qe.registerQuestNpc(799503)->addOnTalkEvent(questId);
		qe.registerQuestNpc(215480)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799527) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else if (dialogActionId == QUEST_ACCEPT_1) {
					QuestService::questTimerStart(env, 480);
					return sendQuestStartDialog(env);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799503) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (env.getTargetId() == 215480) {
				int32_t var = qs->getQuestVarById(0);
				QuestService::questTimerEnd(env);
				qs->setRewardGroup(var); // reward group = count of timer resets (quest retries)
				changeQuestStep(env, var, var, true);
				return true;
			}
		}
		return false;
	}

	bool onQuestTimerEndEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (var == 0) {
				QuestService::questTimerStart(env, 240);
				changeQuestStep(env, var, 1);
			} else if (var == 1) {
				QuestService::questTimerStart(env, 240);
				changeQuestStep(env, var, 2);
			} else if (var == 2) {
				changeQuestStep(env, var, 3);
			}
			return true;
		}
		return false;
	}

	bool onDieEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			QuestService::abandonQuest(*player, questId);
			return true;
		}
		return false;
	}

	bool onLogOutEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			QuestService::abandonQuest(*player, questId);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_21467SpawningTheSapSuckers, 21467);

} // namespace aion::gameserver::handlers::quest::talocs_hollow
