#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/runtime/lifetime/RefCounted.h"
#include "aion/gameserver/model/account/CharacterPasskey_ConnectType.h"
#include "aion/gameserver/model/account/fwd.h"

namespace aion::gameserver::model::account {

/**
 * S0c declaration header (docs/design/hub-headers.md §3.5). RefCounted (fieldmap K4, `Account.characterPasskey`), created with create().
 *
 * @author cura
 */
class CharacterPasskey : public runtime::RefCounted {
	AION_MAKE_REF_FRIEND
public:
	using ConnectType = CharacterPasskey_ConnectType; // generated by xmlgen

private:
	runtime::Field<int32_t> objectId{};
	runtime::Field<int32_t> wrongCount{0};
	runtime::Field<bool> isPass_{false};
	runtime::Field<ConnectType> connectType{};

protected:
	CharacterPasskey();
	~CharacterPasskey() override;

public:
	/** Java: new CharacterPasskey() */
	static runtime::Ref<CharacterPasskey> create();

	/** @return the objectId */
	int32_t getObjectId() const { return objectId.get(); }

	/** @param value the objectId to set */
	void setObjectId(int32_t value) { objectId.set(value); }

	/** @return the wrongCount */
	int32_t getWrongCount() const { return wrongCount.get(); }

	/** @param value the wrongCount to set (Java: count) */
	void setWrongCount(int32_t value) { wrongCount.set(value); }

	/** @return the isPass */
	bool isPass() const { return isPass_.get(); }

	/** @param value the isPass to set */
	void setIsPass(bool value) { isPass_.set(value); }

	/** @return the connectType */
	ConnectType getConnectType() const { return connectType.get(); }

	/** @param value the connectType to set */
	void setConnectType(ConnectType value) { connectType.set(value); }
};

} // namespace aion::gameserver::model::account
