// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.teleport - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::templates::teleport {

class TeleLocIdData;
class TelelocationTemplate;
struct TeleportLocation;
enum class TeleportType : std::uint8_t;
class TeleporterTemplate;

} // namespace aion::gameserver::model::templates::teleport
