#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/runtime/lifetime/RefCounted.h"
#include "aion/gameserver/model/templates/flypath/FlightPath_Type.h"
#include "aion/gameserver/model/templates/flypath/fwd.h"

namespace aion::gameserver::model::templates::flypath {

/**
 * S0c declaration header (docs/design/hub-headers.md §3.5). Not a template despite its package: the player's current flight (fieldmap K4,
 * `Player.flightPath`), RefCounted, created with create().
 */
class FlightPath : public runtime::RefCounted {
	AION_MAKE_REF_FRIEND
public:
	using Type = FlightPath_Type; // generated by xmlgen

private:
	const Type type;
	const int32_t id;
	runtime::Field<int32_t> distance;

protected:
	FlightPath(Type type, int32_t id, int32_t distance);
	~FlightPath() override;

public:
	/** Java: new FlightPath(type, id, distance) */
	static runtime::Ref<FlightPath> create(Type type, int32_t id, int32_t distance);

	Type getType() const { return type; }

	int32_t getId() const { return id; }

	int32_t getDistance() const { return distance.get(); }

	void setDistance(int32_t value) { distance.set(value); }
};

} // namespace aion::gameserver::model::templates::flypath
