// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.flypath - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::model::templates::flypath {

class FlightPath;
class FlyPathEntry;

// Nested types (declared inside their outer class, include its header):
//   FlightPath::Type

} // namespace aion::gameserver::model::templates::flypath
