#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::kaldor {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/kaldor/_13817TheFuryWithin.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Ritsu
 */
class _13817TheFuryWithin final : public AbstractQuestHandler {
public:
	_13817TheFuryWithin() : AbstractQuestHandler(13817) {}

	void register_() override {
		qe.registerQuestNpc(804585)->addOnQuestStart(questId);
		qe.registerQuestNpc(804585)->addOnTalkEvent(questId);
		qe.registerQuestNpc(804595)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 804585) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 4762);
					case QUEST_ACCEPT_SIMPLE:
						return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 804595:
					switch (dialogActionId) {
						case QUEST_SELECT:
							{
								if (var == 0)
									return sendQuestDialog(env, 1011);
								return false;
							}
						case SET_SUCCEED:
							{
								return defaultCloseDialog(env, 0, 0, true, false);
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 804585)
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 10002);
					case SELECT_QUEST_REWARD:
						return sendQuestDialog(env, 5);
					default:
						return sendQuestEndDialog(env);
				}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_13817TheFuryWithin, 13817);

} // namespace aion::gameserver::handlers::quest::kaldor
