// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.stats.calc.functions - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::model::stats::calc::functions {

class AttackSpeedFunction;
class BlockFunction;
class BoostCastingTimeFunction;
class DuplicateStatFunction;
class EvasionFunction;
class IStatFunction;
class MagicalAttackFunction;
class MaxHpFunction;
class MaxMpFunction;
class PDefFunction;
class ParryFunction;
class PhysicalAccuracyFunction;
class PhysicalAttackFunction;
class PhysicalCriticalFunction;
class PlayerStatFunctions;
class PvEAttackRatioFunction;
class PvEDefendRatioFunction;
class PvPAttackRatioFunction;
class StatAbsFunction;
class StatAddFunction;
class StatArmorMasteryFunction;
class StatFunction;
class StatFunctionProxy;
class StatRateFunction;
class StatSetFunction;
class StatShieldMasteryFunction;
class StatSubFunction;
class StatWeaponMasteryFunction;

} // namespace aion::gameserver::model::stats::calc::functions
