#include "RegscanTestSupport.h"

#include <filesystem>
#include <fstream>
#include <sstream>

#include "Emitter.h"

using namespace aion::gameserver::tools::regscan;
using namespace aion::gameserver::tools::regscan::test;

namespace {

std::string fileContent(const std::vector<GeneratedFile>& files, std::string_view name) {
	for (const GeneratedFile& file : files) {
		if (file.name == name)
			return file.content;
	}
	throw std::logic_error("not generated: " + std::string(name));
}

RegistryModel smallModel() {
	ScanInput input;
	input.handlersGiven = true;
	input.handlerFiles = {
		source("aion/gameserver/handlers/ai/B.cpp", "namespace aion::gameserver::handlers::ai {\nclass B {};\nAION_AI(B, \"b\");\nint f() { return spawn(215074); }\n}\n"),
		source("aion/gameserver/handlers/ai/instance/x/A.cpp", "namespace aion::gameserver::handlers::ai::instance::x {\nclass A {};\nAION_AI(A, \"a\");\n}\n"),
		source("aion/gameserver/handlers/zone/Z.cpp", "namespace aion::gameserver::handlers::zone {\nclass Z {};\nAION_ZONE_HANDLER(Z, \"N1 N2\", 5);\n}\n"),
	};
	return buildRegistry(input);
}

} // namespace

TEST(EmitterTest, GeneratedTableGolden) {
	RegistryModel model = smallModel();
	ASSERT_NO_FATAL_FAILURE(EXPECT_NO_ERRORS(model.errors));
	std::vector<GeneratedFile> files = generateFiles(model);
	EXPECT_EQ(fileContent(files, "Registry.ai.gen.cpp"),
		R"cpp(// Registry.ai.gen.cpp - generated by aion_gs_regscan from 2 AION_AI markers in 2 files. Do not edit.
#include "aion/gameserver/handlers/HandlerRegistry.h"

namespace aion::gameserver::handlers::ai {
::aion::gameserver::handlers::AIFactory B_aiFactory;
} // namespace aion::gameserver::handlers::ai
namespace aion::gameserver::handlers::ai::instance::x {
::aion::gameserver::handlers::AIFactory A_aiFactory;
} // namespace aion::gameserver::handlers::ai::instance::x

namespace aion::gameserver::handlers {

namespace {

constinit const AIHandlerEntry AI_HANDLERS[] = {
	{"a", "ai.instance.x.A", &::aion::gameserver::handlers::ai::instance::x::A_aiFactory, "ai/instance/x/A.cpp:3"},
	{"b", "ai.B", &::aion::gameserver::handlers::ai::B_aiFactory, "ai/B.cpp:3"},
};

} // namespace

std::span<const AIHandlerEntry> aiHandlerEntries() noexcept {
	return AI_HANDLERS;
}

} // namespace aion::gameserver::handlers
)cpp");
	EXPECT_EQ(fileContent(files, "Registry.zone.gen.cpp").find("\t{\"N1 N2\", 5, \"zone.Z\", &::aion::gameserver::handlers::zone::Z_zoneFactory, \"zone/Z.cpp:3\"},\n") !=
			std::string::npos,
		true);
	EXPECT_EQ(fileContent(files, "Registry.instance.gen.cpp"),
		R"cpp(// Registry.instance.gen.cpp - generated by aion_gs_regscan from 0 AION_INSTANCE_HANDLER markers in 0 files. Do not edit.
#include "aion/gameserver/handlers/HandlerRegistry.h"

namespace aion::gameserver::handlers {

std::span<const InstanceHandlerEntry> instanceHandlerEntries() noexcept {
	return {};
}

} // namespace aion::gameserver::handlers
)cpp");
	EXPECT_EQ(fileContent(files, "Registry.npcids.gen.cpp"),
		R"cpp(// Registry.npcids.gen.cpp - generated by aion_gs_regscan from 1 npc ids in 2 files of ai, instance and quest (QuestSpawnAnalyzer pattern). Do not edit.
#include "aion/gameserver/handlers/HandlerRegistry.h"

namespace aion::gameserver::handlers {

namespace {

constinit const int32_t NPC_IDS[] = {
	215074,
};

} // namespace

std::span<const int32_t> npcIdsSpawnedByHandlers() noexcept {
	return NPC_IDS;
}

} // namespace aion::gameserver::handlers
)cpp");
	// the empty variants define the same accessors
	std::string emptyAi = fileContent(files, "Registry.ai.empty.gen.cpp");
	EXPECT_NE(emptyAi.find("std::span<const AIHandlerEntry> aiHandlerEntries() noexcept {\n\treturn {};\n}"), std::string::npos) << emptyAi;
	EXPECT_EQ(files.size(), 15u);
}

TEST(EmitterTest, OutputIsDeterministic) {
	std::vector<GeneratedFile> first = generateFiles(smallModel());
	std::vector<GeneratedFile> second = generateFiles(smallModel());
	ASSERT_EQ(first.size(), second.size());
	for (size_t i = 0; i < first.size(); i++) {
		EXPECT_EQ(first[i].name, second[i].name);
		EXPECT_EQ(first[i].content, second[i].content) << first[i].name;
	}
}

TEST(EmitterTest, ReportFormat) {
	RegistryModel model = smallModel();
	std::string report = generateReport(model);
	EXPECT_NE(report.find("files\tai=2\tzone=1\n"), std::string::npos) << report;
	EXPECT_NE(report.find("registry\tported\tjava\tmissing\tunknownToJava\nai\t2\t-\t-\t0\ninstance\t0\t-\t-\t0\nzone names\t2\t-\t-\t0\n"), std::string::npos)
		<< report;
	EXPECT_NE(report.find("npc ids spawned by handlers\t1\t-\t-\t0\n"), std::string::npos) << report;

	RegistryModel empty = buildRegistry(ScanInput{});
	EXPECT_NE(generateReport(empty).find("files\t(none)\n"), std::string::npos);
}

TEST(EmitterTest, StringLiteralsAreEscaped) {
	RegistryModel model;
	model.clientPackets.push_back(RegistryEntry{MarkerKind::CLIENT_PACKET, "CM_\"X\\", 0, "CM_X", "ns", "CM_X_clientPacketFactory", "a\tb"});
	std::string table = fileContent(generateFiles(model), "Registry.clientpackets.gen.cpp");
	EXPECT_NE(table.find(R"({"CM_\"X\\", &::ns::CM_X_clientPacketFactory, "a\x09""b"})"), std::string::npos) << table;
}

TEST(EmitterTest, WriteIfChanged) {
	namespace fs = std::filesystem;
	fs::path dir = fs::path(AION_REGSCAN_TEMP_DIR) / "EmitterTest";
	fs::remove_all(dir);
	fs::path file = dir / "sub" / "Registry.ai.gen.cpp";
	EXPECT_TRUE(writeIfChanged(file, "one\n"));
	auto firstTime = fs::last_write_time(file);
	EXPECT_FALSE(writeIfChanged(file, "one\n"));
	EXPECT_EQ(fs::last_write_time(file), firstTime);
	EXPECT_TRUE(writeIfChanged(file, "two\r\n"));
	std::ifstream in(file, std::ios::binary);
	std::ostringstream content;
	content << in.rdbuf();
	EXPECT_EQ(content.str(), "two\r\n"); // written byte for byte
	in.close();
	fs::remove_all(dir);
}
