#include "Emitter.h"

#include <fstream>
#include <map>
#include <sstream>
#include <stdexcept>

namespace aion::gameserver::tools::regscan {

namespace {

constexpr std::string_view HANDLER_REGISTRY_INCLUDE = "#include \"aion/gameserver/handlers/HandlerRegistry.h\"\n";
constexpr std::string_view REGISTRY_NAMESPACE = "aion::gameserver::handlers";

std::string literal(std::string_view text) {
	std::string result = "\"";
	for (char c : text) {
		unsigned char u = static_cast<unsigned char>(c);
		if (c == '"' || c == '\\') {
			result += '\\';
			result += c;
		} else if (u < 0x20 || u == 0x7F) {
			static constexpr char HEX[] = "0123456789ABCDEF";
			result += "\\x";
			result += HEX[u >> 4];
			result += HEX[u & 0xF];
			result += "\"\""; // ends the hex escape
		} else {
			result += c;
		}
	}
	return result + "\"";
}

std::string qualifiedFunction(const RegistryEntry& entry) {
	return "&::" + entry.ns + "::" + entry.function;
}

struct TableSpec {
	std::string name;         // registry name
	std::string entryType;    // e.g. "AIHandlerEntry"
	std::string factoryType;  // e.g. "AIFactory"
	std::string accessor;     // e.g. "aiHandlerEntries"
	std::string arrayName;    // e.g. "AI_HANDLERS"
	std::string description;  // for the header comment, e.g. "AION_AI markers"
	std::vector<std::string> categories; // handler directories whose files are counted in the header comment
};

std::string header(const std::string& fileName, const std::string& origin) {
	return "// " + fileName + " - generated by aion_gs_regscan from " + origin + ". Do not edit.\n" + std::string(HANDLER_REGISTRY_INCLUDE) + "\n";
}

size_t countFiles(const RegistryModel& model, const std::vector<std::string>& categories) {
	size_t count = 0;
	for (const std::string& category : categories) {
		if (auto it = model.filesPerCategory.find(category); it != model.filesPerCategory.end())
			count += it->second;
	}
	return count;
}

std::string table(const RegistryModel& model, const TableSpec& spec, const std::vector<RegistryEntry>& entries, bool empty,
	std::string (*row)(const RegistryEntry&)) {
	std::string fileName = "Registry." + spec.name + (empty ? ".empty" : "") + ".gen.cpp";
	std::string origin = empty ? "nothing (the empty variant for tests without handlers)"
	                           : std::to_string(entries.size()) + " " + spec.description + " in " + std::to_string(countFiles(model, spec.categories)) + " files";
	std::string out = header(fileName, origin);
	if (!empty && !entries.empty()) {
		// factory declarations, grouped by namespace (the function type comes from the registry, so a mismatch fails to link)
		std::map<std::string, std::vector<std::string>> byNamespace;
		for (const RegistryEntry& entry : entries)
			byNamespace[entry.ns].push_back(entry.function);
		for (const auto& [ns, functions] : byNamespace) {
			out += "namespace " + ns + " {\n";
			for (const std::string& function : functions)
				out += "::aion::gameserver::handlers::" + spec.factoryType + " " + function + ";\n";
			out += "} // namespace " + ns + "\n";
		}
		out += "\n";
	}
	out += "namespace " + std::string(REGISTRY_NAMESPACE) + " {\n\n";
	if (!empty && !entries.empty()) {
		out += "namespace {\n\nconstinit const " + spec.entryType + " " + spec.arrayName + "[] = {\n";
		for (const RegistryEntry& entry : entries)
			out += "\t" + row(entry) + ",\n";
		out += "};\n\n} // namespace\n\n";
		out += "std::span<const " + spec.entryType + "> " + spec.accessor + "() noexcept {\n\treturn " + spec.arrayName + ";\n}\n";
	} else {
		out += "std::span<const " + spec.entryType + "> " + spec.accessor + "() noexcept {\n\treturn {};\n}\n";
	}
	out += "\n} // namespace " + std::string(REGISTRY_NAMESPACE) + "\n";
	return out;
}

std::string aiRow(const RegistryEntry& e) {
	return "{" + literal(e.key) + ", " + literal(e.javaClass) + ", " + qualifiedFunction(e) + ", " + literal(e.source) + "}";
}

std::string instanceRow(const RegistryEntry& e) {
	return "{" + std::to_string(e.number) + ", " + literal(e.javaClass) + ", " + qualifiedFunction(e) + ", " + literal(e.source) + "}";
}

std::string zoneRow(const RegistryEntry& e) {
	return "{" + literal(e.key) + ", " + std::to_string(e.number) + ", " + literal(e.javaClass) + ", " + qualifiedFunction(e) + ", " + literal(e.source) + "}";
}

std::string questRow(const RegistryEntry& e) {
	return instanceRow(e);
}

std::string commandRow(const RegistryEntry& e) {
	std::string kind = e.kind == MarkerKind::ADMIN_COMMAND ? "ADMIN" : e.kind == MarkerKind::PLAYER_COMMAND ? "PLAYER" : "CONSOLE";
	return "{CommandKind::" + kind + ", " + literal(e.javaClass) + ", " + qualifiedFunction(e) + ", " + literal(e.source) + "}";
}

std::string clientPacketRow(const RegistryEntry& e) {
	return "{" + literal(e.key) + ", " + qualifiedFunction(e) + ", " + literal(e.source) + "}";
}

std::string npcIdsTable(const RegistryModel& model, bool empty) {
	std::string fileName = std::string("Registry.npcids") + (empty ? ".empty" : "") + ".gen.cpp";
	std::string origin = empty ? "nothing (the empty variant for tests without handlers)"
	                           : std::to_string(model.npcIds.size()) + " npc ids in " + std::to_string(countFiles(model, {"ai", "instance", "quest"})) +
			" files of ai, instance and quest (QuestSpawnAnalyzer pattern)";
	std::string out = header(fileName, origin);
	out += "namespace " + std::string(REGISTRY_NAMESPACE) + " {\n\n";
	if (!empty && !model.npcIds.empty()) {
		out += "namespace {\n\nconstinit const int32_t NPC_IDS[] = {\n";
		size_t column = 0;
		for (int32_t id : model.npcIds) {
			out += column == 0 ? "\t" : " ";
			out += std::to_string(id) + ",";
			if (++column == 12) {
				out += "\n";
				column = 0;
			}
		}
		if (column != 0)
			out += "\n";
		out += "};\n\n} // namespace\n\n";
		out += "std::span<const int32_t> npcIdsSpawnedByHandlers() noexcept {\n\treturn NPC_IDS;\n}\n";
	} else {
		out += "std::span<const int32_t> npcIdsSpawnedByHandlers() noexcept {\n\treturn {};\n}\n";
	}
	out += "\n} // namespace " + std::string(REGISTRY_NAMESPACE) + "\n";
	return out;
}

const TableSpec& spec(std::string_view name) {
	static const std::vector<TableSpec> SPECS{
		{"ai", "AIHandlerEntry", "AIFactory", "aiHandlerEntries", "AI_HANDLERS", "AION_AI markers", {"ai"}},
		{"instance", "InstanceHandlerEntry", "InstanceFactory", "instanceHandlerEntries", "INSTANCE_HANDLERS", "AION_INSTANCE_HANDLER markers", {"instance"}},
		{"zone", "ZoneHandlerEntry", "ZoneFactory", "zoneHandlerEntries", "ZONE_HANDLERS", "AION_ZONE_HANDLER markers", {"zone"}},
		{"quest", "QuestHandlerEntry", "QuestFactory", "questHandlerEntries", "QUEST_HANDLERS", "AION_QUEST_HANDLER markers", {"quest"}},
		{"commands", "CommandEntry", "CommandFactory", "commandEntries", "COMMANDS", "AION_*_COMMAND markers", {"admincommands", "playercommands", "consolecommands"}},
		{"clientpackets", "ClientPacketEntry", "ClientPacketFactory", "clientPacketEntries", "CLIENT_PACKETS", "AION_CLIENT_PACKET markers", {"clientpackets"}},
	};
	for (const TableSpec& s : SPECS) {
		if (s.name == name)
			return s;
	}
	throw std::logic_error("unknown registry " + std::string(name));
}

std::string countCell(const std::optional<size_t>& value) {
	return value ? std::to_string(*value) : "-";
}

} // namespace

const std::vector<std::string>& registryNames() {
	static const std::vector<std::string> NAMES{"ai", "instance", "zone", "quest", "commands", "clientpackets", "npcids"};
	return NAMES;
}

std::vector<GeneratedFile> generateFiles(const RegistryModel& model) {
	std::vector<GeneratedFile> files;
	for (bool empty : {false, true}) {
		std::string suffix = empty ? ".empty.gen.cpp" : ".gen.cpp";
		files.push_back({"Registry.ai" + suffix, table(model, spec("ai"), model.ai, empty, &aiRow)});
		files.push_back({"Registry.instance" + suffix, table(model, spec("instance"), model.instances, empty, &instanceRow)});
		files.push_back({"Registry.zone" + suffix, table(model, spec("zone"), model.zones, empty, &zoneRow)});
		files.push_back({"Registry.quest" + suffix, table(model, spec("quest"), model.quests, empty, &questRow)});
		files.push_back({"Registry.commands" + suffix, table(model, spec("commands"), model.commands, empty, &commandRow)});
		files.push_back({"Registry.clientpackets" + suffix, table(model, spec("clientpackets"), model.clientPackets, empty, &clientPacketRow)});
		files.push_back({"Registry.npcids" + suffix, npcIdsTable(model, empty)});
	}
	files.push_back({"registry_report.txt", generateReport(model)});
	return files;
}

std::string generateReport(const RegistryModel& model) {
	std::ostringstream out;
	out << "# aion_gs_regscan registry report (generated, do not edit)\n";
	out << "# ported: C++ registrations; java: registrations of the Java handlers (- without Java input); missing: Java keys without a C++ marker;\n";
	out << "# unknownToJava: C++ keys whose Java class does not exist at the mirrored path\n\n";
	out << "files";
	for (const auto& [category, count] : model.filesPerCategory)
		out << '\t' << category << '=' << count;
	if (model.filesPerCategory.empty())
		out << "\t(none)";
	out << "\n\n";
	out << "registry\tported\tjava\tmissing\tunknownToJava\n";
	for (const ReportSection& section : model.report) {
		out << section.title << '\t' << section.ported << '\t' << countCell(section.java) << '\t'
			<< (section.java ? std::to_string(section.missing.size()) : "-") << '\t' << section.unknownToJava.size() << '\n';
	}
	for (const ReportSection& section : model.report) {
		if (!section.missing.empty()) {
			out << "\n## " << section.title << ": missing (" << section.missing.size() << ")\n";
			for (const std::string& line : section.missing)
				out << line << '\n';
		}
		if (!section.unknownToJava.empty()) {
			out << "\n## " << section.title << ": unknown to Java (" << section.unknownToJava.size() << ")\n";
			for (const std::string& line : section.unknownToJava)
				out << line << '\n';
		}
	}
	return out.str();
}

std::string summaryLine(const RegistryModel& model) {
	std::string line;
	for (const ReportSection& section : model.report) {
		if (!line.empty())
			line += ", ";
		line += section.title + " " + std::to_string(section.ported) + "/" + countCell(section.java);
	}
	return line;
}

bool writeIfChanged(const std::filesystem::path& path, const std::string& content) {
	{
		std::ifstream in(path, std::ios::binary);
		if (in) {
			std::ostringstream existing;
			existing << in.rdbuf();
			if (existing.str() == content)
				return false;
		}
	}
	if (path.has_parent_path())
		std::filesystem::create_directories(path.parent_path());
	std::ofstream out(path, std::ios::binary | std::ios::trunc);
	if (!out)
		throw std::runtime_error("cannot write " + path.string());
	out << content;
	out.close();
	if (!out)
		throw std::runtime_error("cannot write " + path.string());
	return true;
}

} // namespace aion::gameserver::tools::regscan
