// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.services.conquerorAndProtectorSystem - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::services::conquerorAndProtectorSystem {

class CPBuff;
class CPInfo;
class ConquerorAndProtectorService;

// Nested types (declared inside their outer class, include its header):
//   ConquerorAndProtectorService::SingletonHolder

} // namespace aion::gameserver::services::conquerorAndProtectorSystem
