#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::abyssal_splinter {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/abyssal_splinter/_30255TheLastCrusade.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Rikka & vlog
 */
class _30255TheLastCrusade final : public AbstractQuestHandler {
public:
	_30255TheLastCrusade() : AbstractQuestHandler(30255) {}

	void register_() override {
		qe.registerQuestNpc(260264)->addOnQuestStart(questId);
		qe.registerQuestNpc(260264)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700857)->addOnTalkEvent(questId);
		qe.registerQuestNpc(278501)->addOnTalkEvent(questId);
		qe.registerQuestNpc(216952)->addOnKillEvent(questId);
		qe.registerQuestNpc(216960)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 260264) { // Aratus
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 700857) { // Artifact of Protection
				switch (dialogActionId) {
					case USE_OBJECT:
						if (var == 1) {
							return useQuestObject(env, 1, 1, true, false);
						}
						break;
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 278501) { // Michalis
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 10002);
					default:
						{
							return sendQuestEndDialog(env);
						}
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		std::array<int32_t, 2> mobs{216952, 216960};
		return defaultOnKillEvent(env, mobs, 0, 1); // 1
	}
};
AION_QUEST_HANDLER(_30255TheLastCrusade, 30255);

} // namespace aion::gameserver::handlers::quest::abyssal_splinter
