#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::abyssal_splinter {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/abyssal_splinter/_30264ANecklacewithHistory.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Rikka
 */
class _30264ANecklacewithHistory final : public AbstractQuestHandler {
public:
	_30264ANecklacewithHistory() : AbstractQuestHandler(30264) {}

	void register_() override {
		qe.registerQuestNpc(203706)->addOnTalkEvent(questId);
		qe.registerQuestItem(182209802, questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		if (qs == nullptr || qs->isStartable()) {
			return false;
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203706) { // Charna
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->isStartable()) {
			if (QuestService::startQuest(env)) {
				changeQuestStep(env, 0, 0, true); // reward
				return HandlerResult::SUCCESS;
			}
		}
		return HandlerResult::FAILED;
	}
};
AION_QUEST_HANDLER(_30264ANecklacewithHistory, 30264);

} // namespace aion::gameserver::handlers::quest::abyssal_splinter
