// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.dataholders.loadingutils.adapters - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::dataholders::loadingutils::adapters {

class LocalDateTimeAdapter;
struct NpcEquipmentList;
class NpcEquippedGearAdapter;
class SpaceSeparatedBytesAdapter;

} // namespace aion::gameserver::dataholders::loadingutils::adapters
