"""Writes PngFixtures.h for PngImageTest.cpp: small PNG files encoded here with Python's zlib (an independent deflate encoder, dynamic
Huffman blocks at level 9, stored blocks at level 0), every scanline filter type, Adam7 interlacing, a palette, a tRNS chunk and packed
4-bit samples, together with the raw samples Java's ImageIO would put into the image's DataBuffer.

	python make_png_fixtures.py > PngFixtures.h
"""

import struct
import zlib

ADAM7 = [(0, 0, 8, 8), (4, 0, 8, 8), (0, 4, 4, 8), (2, 0, 4, 4), (0, 2, 2, 4), (1, 0, 2, 2), (0, 1, 1, 2)]


def chunk(kind, body):
	return struct.pack(">I", len(body)) + kind + body + struct.pack(">I", zlib.crc32(kind + body) & 0xFFFFFFFF)


def paeth(a, b, c):
	p = a + b - c
	pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
	if pa <= pb and pa <= pc:
		return a
	return b if pb <= pc else c


def filter_rows(rows, bpp, first_filter):
	out = bytearray()
	previous = bytes(len(rows[0])) if rows else b""
	for index, row in enumerate(rows):
		kind = (first_filter + index) % 5
		line = bytearray()
		for i, value in enumerate(row):
			left = row[i - bpp] if i >= bpp else 0
			up = previous[i]
			up_left = previous[i - bpp] if i >= bpp else 0
			predictor = [0, left, up, (left + up) // 2, paeth(left, up, up_left)][kind]
			line.append((value - predictor) & 0xFF)
		out.append(kind)
		out += line
		previous = row
	return bytes(out)


def png(width, height, bit_depth, color_type, rows, level=9, interlace=False, extra=b"", first_filter=0, samples_per_pixel=1):
	bpp = max(1, samples_per_pixel * bit_depth // 8)
	if interlace:
		data = bytearray()
		pixel_bytes = samples_per_pixel * bit_depth // 8
		for start_x, start_y, step_x, step_y in ADAM7:
			sub_rows = []
			for y in range(start_y, height, step_y):
				row = bytearray()
				for x in range(start_x, width, step_x):
					row += rows[y][x * pixel_bytes:(x + 1) * pixel_bytes]
				if row:
					sub_rows.append(bytes(row))
			if sub_rows:
				data += filter_rows(sub_rows, bpp, first_filter)
		raw = bytes(data)
	else:
		raw = filter_rows(rows, bpp, first_filter)
	header = struct.pack(">IIBBBBB", width, height, bit_depth, color_type, 0, 0, 1 if interlace else 0)
	return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + extra + chunk(b"IDAT", zlib.compress(raw, level)) + chunk(b"IEND", b"")


def c_list(values):
	items = [str(v) for v in values]
	lines = [", ".join(items[i:i + 24]) for i in range(0, len(items), 24)]
	newline = chr(10)
	return newline + "\t" + ("," + newline + "\t").join(lines) + "," + newline


def emit(name, data, kind, values, width, height):
	print(f"inline const std::vector<uint8_t> {name}_PNG{{{c_list(data)}}};")
	element = "int16_t" if kind == "USHORT" else "int8_t"
	signed = [(v - 0x10000 if v >= 0x8000 else v) if kind == "USHORT" else (v - 0x100 if v >= 0x80 else v) for v in values]
	print(f"inline const std::vector<{element}> {name}_SAMPLES{{{c_list(signed)}}};")
	print(f"inline constexpr int32_t {name}_WIDTH = {width};")
	print(f"inline constexpr int32_t {name}_HEIGHT = {height};")
	print()


def main():
	print("#pragma once")
	print("// GENERATED by make_png_fixtures.py (Python zlib encodes the image data) - do not edit")
	print()
	print("#include <cstdint>")
	print("#include <vector>")
	print()
	print("namespace aion::gameserver::geoEngine::test::png {")
	print()

	# 16-bit grayscale 7x5, all filter types, level 9 (dynamic Huffman)
	width, height = 7, 5
	values = [(x * 9001 + y * 7919 + x * y * 131) % 65536 for y in range(height) for x in range(width)]
	values[3] = 0xFFFF
	rows = [b"".join(struct.pack(">H", values[y * width + x]) for x in range(width)) for y in range(height)]
	emit("GRAY16", png(width, height, 16, 0, rows), "USHORT", values, width, height)

	# 8-bit grayscale 64x40 with a long repeated run (length/distance codes), level 9
	width, height = 64, 40
	values = [((x // 8) * 17 + (y // 5) * 29) % 256 if y % 7 else (x * 37 + y) % 256 for y in range(height) for x in range(width)]
	rows = [bytes(values[y * width:(y + 1) * width]) for y in range(height)]
	emit("GRAY8", png(width, height, 8, 0, rows, first_filter=1), "BYTE", values, width, height)

	# 8-bit palette 5x3: the indices, not the palette colors
	width, height = 5, 3
	values = [(x + 2 * y) % 4 for y in range(height) for x in range(width)]
	rows = [bytes(values[y * width:(y + 1) * width]) for y in range(height)]
	palette = chunk(b"PLTE", bytes([255, 0, 0, 0, 255, 0, 0, 0, 255, 200, 200, 200]))
	emit("PALETTE8", png(width, height, 8, 3, rows, extra=palette, first_filter=2), "BYTE", values, width, height)

	# 8-bit grayscale 9x9, Adam7 interlaced, stored deflate blocks (level 0)
	width, height = 9, 9
	values = [(x * 23 + y * 41 + (x ^ y) * 7) % 256 for y in range(height) for x in range(width)]
	rows = [bytes(values[y * width:(y + 1) * width]) for y in range(height)]
	emit("ADAM7", png(width, height, 8, 0, rows, level=0, interlace=True, first_filter=3), "BYTE", values, width, height)

	# 8-bit RGB 3x2: three samples per pixel (PNG order)
	width, height = 3, 2
	values = [(i * 29 + 5) % 256 for i in range(width * height * 3)]
	rows = [bytes(values[y * width * 3:(y + 1) * width * 3]) for y in range(height)]
	emit("RGB8", png(width, height, 8, 2, rows, first_filter=4, samples_per_pixel=3), "BYTE", values, width, height)

	# 16-bit grayscale 4x2 with tRNS: an alpha sample is added (0 for the transparent gray value)
	width, height = 4, 2
	grays = [1000, 2000, 1000, 65535, 0, 1000, 5, 1000]
	rows = [b"".join(struct.pack(">H", grays[y * width + x]) for x in range(width)) for y in range(height)]
	trns = chunk(b"tRNS", struct.pack(">H", 1000))
	values = []
	for gray in grays:
		values += [gray, 0 if gray == 1000 else 0xFFFF]
	emit("GRAY16_TRNS", png(width, height, 16, 0, rows, extra=trns), "USHORT", values, width, height)

	# 4-bit grayscale 5x2: the packed rows (ImageIO's MultiPixelPackedSampleModel data)
	width, height = 5, 2
	packed_rows = [bytes([0x12, 0x34, 0x50]), bytes([0xFE, 0xDC, 0xB0])]
	emit("GRAY4", png(width, height, 4, 0, packed_rows, first_filter=1), "BYTE", list(packed_rows[0] + packed_rows[1]), width, height)

	print("} // namespace aion::gameserver::geoEngine::test::png")


if __name__ == "__main__":
	main()
