// The generated handlers of the rest of morheim and pernon that questgen transliterates (chunk Q09, phase 6 step 2, lane C) compiled into Q05's test executable by #include
// (GoldenHandlers.h says why); docs/deviations/Q09.md.

// clang-format off
#include "aion/gameserver/handlers/quest/morheim/_2303DaevaWheresMyHerb.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2307IrresistibleSoup.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2316VivisBook.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2321SpyTheSpiritsLetter.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2324TheSpiritsNotebook.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2332MeatyTreats.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2343AncientGinseng.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2345OrashunerkSpecialOrder.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2367APrizedPossession.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2392BeautifulFeather.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2393TheLoveOfAFather.cpp"
#include "aion/gameserver/handlers/quest/morheim/_24020AegirsOrders.cpp"
#include "aion/gameserver/handlers/quest/morheim/_24021GhostsintheDesert.cpp"
#include "aion/gameserver/handlers/quest/morheim/_24022SneakBehindtheIceClaw.cpp"
#include "aion/gameserver/handlers/quest/morheim/_24023ABlazingRescue.cpp"
#include "aion/gameserver/handlers/quest/morheim/_24024ANepraProtector.cpp"
#include "aion/gameserver/handlers/quest/morheim/_24025CrisisinMorheim.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2409Propaganda.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2411EarthSpiritWaterSpirit.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2421AsgeirrsRequest.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2422LiquorThatMakesYouVanish.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2423ThereAndBackAgain.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2428TheAbsolutelyEssentialBook.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2430SecretInformation.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2435TheBlueVineNecklace.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2436LookingForBuBuPat.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2443TaisanMessage.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2448ChaomirkSendsForHelp.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2449ExtricatingChaomirk.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2458RoastGadillForAFriend.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2477ADishForDukar.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2480ElimOfElysea.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2482CaryatidOfAbyss.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2484OurManInElysea.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2486AStrangeCreature.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2488PretorsInBeluslan.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2493BringingUpTayga.cpp"
#include "aion/gameserver/handlers/quest/morheim/_2498TheSoddenScroll.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28802BeItEverSoHumble.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28805SomethingOldSomethingNew.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28807BlessingsofaGreenThumb.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28808OpenSaysMe.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28809FirstClassorCoach.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28826FreetoaGoodHome.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28832TakingtheTour.cpp"
#include "aion/gameserver/handlers/quest/pernon/_28847AHomeThatsYourOwn.cpp"
#include "aion/gameserver/handlers/quest/pernon/_51009TheGiftOfCharity.cpp"
// clang-format on
