// The generated pandaemonium handlers (chunk Q10, P6-Q slice 2) compiled into Q05's test executable by #include (GoldenHandlers.h says why). Only
// the files the table names; the hand ports and held-back files of the directory are not generated (docs/deviations/Q10.md).

// clang-format off
#include "aion/gameserver/handlers/quest/pandaemonium/_29004VeldinaCall.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_29048SeriphimTeachings.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2911SongOfBlessing.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2912FollowtheRibbon.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2913AChainofDebt.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2914ATokenofLostLove.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2916ManInTheLongBlackRobe.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2917ArekedilsHeritage.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2918DeepMaternalLove.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2919BookOfOblivion.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2920ElementaryMyDearDaeva.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2921LoveAtFirstSight.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2922FascinatingGift.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2925AHeartfeltConfession.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2928PowerofLove.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2937UnexpectedReward.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2938SecretLibraryAccess.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2948HuronsLetter.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2952WinningVindachinerksFavor.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2953DeliveringSupplyRequest.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2954DeliveringOdellaJuice.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2957FlowersForTheBanquet.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2958LastMinuteWorries.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2962JafnharWhereabouts.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2963OnBehalfOfAFriend.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2965AncientWeapons.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_2985AnExpertsReward.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4210MissingHaorunerk.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4905InterviewingTheVeterans.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4906TalesOfHeroes.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4920MakingTheActivatedSurkana.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4966GrowthNinissFirstCharm.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4967GrowthNinissSecondCharm.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4968GrowthNinissThirdCharm.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4969GrowthNinissFourthCharm.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4970TheFashionistas.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4971ProjectRunway.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4972JudgeNot.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4973MarraWorry.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4974TheSecretOfHisSuccess.cpp"
#include "aion/gameserver/handlers/quest/pandaemonium/_4976ASettlerAmbition.cpp"
// clang-format on
