// The generated handlers of the rest of eltnen and oriel that questgen transliterates (chunk Q05, phase 6 step 2, lane C) compiled into Q05's test executable by #include
// (GoldenHandlers.h says why); docs/deviations/Q05.md.

// clang-format off
#include "aion/gameserver/handlers/quest/eltnen/_1311AGermOfHope.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1314Anelimoutofwater.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1319PrioritesMoney.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1322ALeafFromLodas.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1324ConfidentialOrders.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1336ScoutingForDemokritos.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1345BearerOfBadNews.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1351EarningMaranasRespect.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1361FindingDrinkingWater.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1363ThankingMabangtah.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1364JourneytoAgairon.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1371FlowersForIsson.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1373WaterTherapy.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1376AMountaineOfTrouble.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1385RescuingGriffo.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1393NewFlightPath.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1394ReportingtheNewFlightPath.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_14020OrdersFromEltnen.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_14021ToCureACurse.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_14022TheTestOfTheHeart.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_14023PlayingAroundAtTheTemple.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_14024AKrallIngSuspicion.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_14025CookingUpDisasters.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1414OperationWindmill.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1422ABetterSword.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1423ExpertAdvice.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1430ATeleportationExperiment.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1452DoubtfulCharacters.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1463MessageToASpy.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1464AGiftofLove.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1466RespectForDeltras.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1467TheFourLeaders.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1468HannetsLostLove.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1469FindingDenlavis.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1470HannetsVengeance.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1471FakeStigma.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1472GanimerksEspionage.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1479HelpingMemnes.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1482ATeleportationAdventure.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1483HarumonerksRequest.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_1484ChiyorinrinerksRequest.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_3319AnOrderforGojirunerk.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_3326TheShugoMenace.cpp"
#include "aion/gameserver/handlers/quest/eltnen/_3329DinnersonMe.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18802AndAHomeforEveryDaeva.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18805GoingThrifting.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18807BlessedBeThyHame.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18808FoolproofPackaging.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18809DaevaontheRide.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18826TodaysFind.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18832ImaginingAQuietLife.cpp"
#include "aion/gameserver/handlers/quest/oriel/_18847Housewarming.cpp"
#include "aion/gameserver/handlers/quest/oriel/_50009TisTheSeason.cpp"
// clang-format on
