#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::empyrean_crucible {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/empyrean_crucible/_18212FirstBlood.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _18212FirstBlood final : public AbstractQuestHandler {
public:
	_18212FirstBlood() : AbstractQuestHandler(18212) {}

	void register_() override {
		qe.registerQuestNpc(205985)->addOnQuestStart(questId);
		qe.registerQuestNpc(205985)->addOnTalkEvent(questId);
		qe.registerOnKillInWorld(300350000, questId);
		qe.registerOnKillInWorld(300360000, questId);
	}

	bool onKillInWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			giveQuestItem(env, 182212218, 1);
			return defaultOnKillRankedEvent(env, 0, 1, true);
		}
		return false;
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (env.getTargetId() == 205985) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			} else if (qs->getStatus() == QuestStatus::REWARD) {
				if (env.getDialogActionId() == USE_OBJECT)
					return sendQuestDialog(env, 10002);
				else {
					removeQuestItem(env, 182212218, 1);
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_18212FirstBlood, 18212);

} // namespace aion::gameserver::handlers::quest::empyrean_crucible
