#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::sanctum {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/sanctum/_1908UlaguruSpeaks.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _1908UlaguruSpeaks final : public AbstractQuestHandler {
public:
	_1908UlaguruSpeaks() : AbstractQuestHandler(1908) {}

	void register_() override {
		qe.registerQuestNpc(203864)->addOnQuestStart(questId);
		qe.registerQuestNpc(203864)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203890)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203864) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 203890) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0) {
						return sendQuestDialog(env, 1352);
					}
				} else if (dialogActionId == SETPRO1) {
					return defaultCloseDialog(env, 0, 1);
				}
			} else if (targetId == 203864) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 1) {
						return sendQuestDialog(env, 2375);
					}
				} else if (dialogActionId == SETPRO21) {
					qs->setQuestVar(21);
					qs->setRewardGroup(0);
					return sendQuestDialog(env, 2376);
				} else if (dialogActionId == SETPRO22) {
					qs->setQuestVar(22);
					qs->setRewardGroup(1);
					return sendQuestDialog(env, 2461);
				} else if (dialogActionId == SETPRO23) {
					qs->setQuestVar(23);
					qs->setRewardGroup(2);
					return sendQuestDialog(env, 2546);
				} else if (dialogActionId == SELECT_QUEST_REWARD) {
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return sendQuestEndDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203864) {
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1908UlaguruSpeaks, 1908);

} // namespace aion::gameserver::handlers::quest::sanctum
