#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::sanctum {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/sanctum/_1938BlackCloudFakery.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author zhkchi
 */
class _1938BlackCloudFakery final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 3> npcs{203703, 279001, 279008};

public:
	_1938BlackCloudFakery() : AbstractQuestHandler(1938) {}

	void register_() override {
		qe.registerQuestNpc(203703)->addOnQuestStart(questId);
		for (int32_t npc : npcs)
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (sendQuestNoneDialog(env, 203703))
			return true;

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 279001:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1352);
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1);
					}
					break;
				case 279008:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1)
								return sendQuestDialog(env, 1693);
							return false;
						case SETPRO2:
							qs->setQuestVar(2);
							qs->setStatus(QuestStatus::REWARD);
							updateQuestStatus(env);
							return closeDialogWindow(env);
					}
					break;
			}
		}
		return sendQuestRewardDialog(env, 203703, 2375);
	}
};
AION_QUEST_HANDLER(_1938BlackCloudFakery, 1938);

} // namespace aion::gameserver::handlers::quest::sanctum
