#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/model/QuestVars.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::sanctum {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/sanctum/_1947ALuckyDay.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Gigi, kale
 */
class _1947ALuckyDay final : public AbstractQuestHandler {
public:
	_1947ALuckyDay() : AbstractQuestHandler(1947) {}

	void register_() override {
		qe.registerQuestNpc(203795)->addOnQuestStart(questId);
		qe.registerQuestNpc(203795)->addOnTalkEvent(questId); // Demodocos
		qe.registerQuestNpc(798012)->addOnTalkEvent(questId); // Yiehmonerk
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr || qs->isStartable()) { // TODO: If cube size is bigger than 5
			switch (env.getDialogActionId()) {
				case QUEST_SELECT:
					return sendQuestDialog(env, 1011);
				case ASK_QUEST_ACCEPT:
					return sendQuestDialog(env, 4);
				case QUEST_ACCEPT_1:
					env.setQuestId(questId);
					QuestService::startQuest(env);
					return sendQuestDialog(env, 1003);
			}
		}

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVars()->getQuestVars();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 798012: // Yiehmonerk
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 2375);
							return false;
						case SELECT_QUEST_REWARD:
							if (var == 0) {
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								return sendQuestDialog(env, 5);
							}
					}
					break;
			}
		} else if (qs->getStatus() == QuestStatus::REWARD && targetId == 798012)
			return sendQuestEndDialog(env);
		return false;
	}
};
AION_QUEST_HANDLER(_1947ALuckyDay, 1947);

} // namespace aion::gameserver::handlers::quest::sanctum
