#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/world/WorldMapInstance.h"

namespace aion::gameserver::handlers::quest::sanctum {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/sanctum/_3908ToMastertheDragon.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author sky123
 */
class _3908ToMastertheDragon final : public AbstractQuestHandler {
public:
	_3908ToMastertheDragon() : AbstractQuestHandler(3908) {}

	void register_() override {
		qe.registerQuestNpc(798316)->addOnQuestStart(questId);
		qe.registerQuestNpc(798316)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700515)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798316) {
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env, 182206056, 1);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 700515) {
				switch (dialogActionId) {
					case USE_OBJECT:
						if (removeQuestItem(env, 182206056, 1))
							spawn(215384, *player->getWorldMapInstance(), static_cast<float>(493.9681), static_cast<float>(519.1524), static_cast<float>(968.9094), static_cast<int8_t>(0));
						return true;
				}
			} else if (targetId == 798316) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case CHECK_USER_HAS_QUEST_ITEM:
						if (player->getInventory().getItemCountByItemId(182206057) >= 1)
							return defaultCloseDialog(env, 0, 0, true, true, 0, 0, 182206057, 1);
						else
							return sendQuestDialog(env, 10001);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_3908ToMastertheDragon, 3908);

} // namespace aion::gameserver::handlers::quest::sanctum
