#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::sanctum {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/sanctum/_3964GrowthFlorasFourthCharm.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * Talk with Erdos (203740). Bring the Yellow Aether Powder (186000090) and Kinah (90000) to Flora (798384).
 *
 * @author undertrey, vlog
 */
class _3964GrowthFlorasFourthCharm final : public AbstractQuestHandler {
public:
	_3964GrowthFlorasFourthCharm() : AbstractQuestHandler(3964) {}

	void register_() override {
		qe.registerQuestNpc(798384)->addOnQuestStart(questId);
		qe.registerQuestNpc(798384)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203740)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798384) { // Flora
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env, 182206111, 1);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 203740: // Erdos
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1352);
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1, 0, 0, 182206111, 1); // 1
					}
					return false;
				case 798384: // Flora
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 1) {
								removeQuestItem(env, 182206111, 1);
								return sendQuestDialog(env, 2375);
							}
							return false;
						case CHECK_USER_HAS_QUEST_ITEM: {
							int64_t itemAmount = player->getInventory().getItemCountByItemId(186000090);
							if (var == 1 && itemAmount >= 1 && player->getInventory().tryDecreaseKinah(90000)) {
								// java-bug kept (U3, phase6-inventory.md §11): tryDecreaseKinah on the line above already took the kinah (Storage.java:82-88); this takes it a second time
								player->getInventory().decreaseKinah(90000);
								removeQuestItem(env, 186000090, 1);
								changeQuestStep(env, 1, 1, true); // reward
								return sendQuestDialog(env, 5);
							} else
								return sendQuestDialog(env, 2716);
						}
						case FINISH_DIALOG:
							return defaultCloseDialog(env, 1, 1);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798384) { // Flora
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_3964GrowthFlorasFourthCharm, 3964);

} // namespace aion::gameserver::handlers::quest::sanctum
