#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/item/ItemTemplate.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_ITEM_USAGE_ANIMATION.h"
#include "aion/gameserver/utils/ThreadPoolManager.h"

namespace aion::gameserver::handlers::quest::gelkmaros {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/gelkmaros/_20033DranaSolution.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @Author Majka
 */
class _20033DranaSolution final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 4> mobs{216444, 216445, 216446, 216447};

public:
	_20033DranaSolution() : AbstractQuestHandler(20033) {}

	void register_() override {
		// Nunglark Drana Growing Device ID: 700701
		// Skira ID: 799270
		std::array<int32_t, 2> npcs{700701, 799270};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
		for (int32_t mob : mobs) {
			qe.registerQuestNpc(mob)->addOnKillEvent(questId);
		}
		qe.registerQuestItem(182215614, questId);
		qe.registerQuestItem(182215594, questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr) {
			return false;
		}

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 799270) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0) {
							return sendQuestDialog(env, 1011);
						}
						return false;
					case SETPRO1:
						giveQuestItem(env, 182215614, 1);
						giveQuestItem(env, 182215594, 1);
						return defaultCloseDialog(env, 0, 1); // 1
				}
			} else if (targetId == 700701) {
				switch (dialogActionId) {
					case USE_OBJECT:
						return useQuestObject(env, 2, 3, false, 0, 0, 0, 182215614, 1); // 3
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799270) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (var == 1) {
				int32_t var1 = qs->getQuestVarById(1);
				if (var1 >= 0 && var1 < 4) {
					return defaultOnKillEvent(env, mobs, var1, var1 + 1, 1);
				} else if (var1 == 4) {
					qs->setQuestVar(2); // 2
					updateQuestStatus(env);
					return true;
				}
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t id = item.getItemTemplate()->getTemplateId();
		int32_t itemObjId = item.getObjectId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr || qs->getStatus() != QuestStatus::START || id != 182215594) {
			return HandlerResult::UNKNOWN;
		}

		int32_t var = qs->getQuestVarById(0);
		if (var != 3)
			return HandlerResult::UNKNOWN;

		PacketSendUtility::broadcastPacket(*player, SM_ITEM_USAGE_ANIMATION(player->getObjectId(), itemObjId, id, 3000, 0, 0), true);
		ThreadPoolManager::getInstance().schedule({this, &env}, [this, player = runtime::Ref<Player>(player), itemObjId, id, &env, qs = runtime::Ref<QuestState>(qs)] {
			PacketSendUtility::broadcastPacket(*player, SM_ITEM_USAGE_ANIMATION(player->getObjectId(), itemObjId, id, 0, 1, 0), true);
			playQuestMovie(env, 553);
			removeQuestItem(env, 182215594, 1);
			qs->setQuestVar(4);
			qs->setStatus(QuestStatus::REWARD);
			updateQuestStatus(env);
		}, 3000);

		return HandlerResult::SUCCESS;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {20031});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {20031});
	}
};
AION_QUEST_HANDLER(_20033DranaSolution, 20033);

} // namespace aion::gameserver::handlers::quest::gelkmaros
