#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.h"
#include "aion/gameserver/services/instance/InstanceService.h"
#include "aion/gameserver/services/teleport/TeleportService.h"
#include "aion/gameserver/world/WorldMapInstance.h"
#include "aion/gameserver/world/WorldMapTypeInfo.h"

namespace aion::gameserver::handlers::quest::gelkmaros {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/gelkmaros/_20032AllAboutAbnormalAether.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Majka
 */
class _20032AllAboutAbnormalAether final : public AbstractQuestHandler {
public:
	_20032AllAboutAbnormalAether() : AbstractQuestHandler(20032) {}

	void register_() override {
		// Angrad ID: 799247
		// Eddas ID: 799250
		// Taloc's Guardian ID: 799325
		// Taloc's Mirage ID: 799503
		std::array<int32_t, 3> npcs{799247, 799250, 799325};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerOnEnterWorld(questId);
		qe.registerOnDie(questId);
		qe.registerOnLogOut(questId);
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
		qe.registerQuestNpc(215488)->addOnKillEvent(questId); // Celestius
		qe.registerQuestItem(182215592, questId); // quest_20032a
		qe.registerQuestItem(182215593, questId); // quest_20032b
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;
		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 799247) { // Angrad
				if (var == 0) {
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1011);
						case SETPRO1:
							return defaultCloseDialog(env, var, var + 1); // 1
					}
				}
			} else if (targetId == 799250) { // Eddas
				if (var == 1) {
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1352);
						case SETPRO2:
							return defaultCloseDialog(env, var, var + 1); // 2
					}
				}
			} else if (targetId == 799325) { // Taloc's Guardian
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 2) {
							return sendQuestDialog(env, 1693);
						}
						break;
					case SETPRO3:
						if (giveQuestItem(env, 182215592, 1) && giveQuestItem(env, 182215593, 1)) {
							changeQuestStep(env, 2, 3); // 3
							runtime::Ptr<WorldMapInstance> newInstance = InstanceService::getNextAvailableInstance(::aion::gameserver::world::getId(WorldMapType::TALOCS_HOLLOW), *player);
							TeleportService::teleportTo(*player, *newInstance, 202.26694f, 226.0532f, 1098.236f, static_cast<int8_t>(30), TeleportAnimation::FADE_OUT_BEAM);
							return closeDialogWindow(env);
						} else {
							PacketSendUtility::sendPacket(*player, SM_SYSTEM_MESSAGE::STR_MSG_FULL_INVENTORY());
							return sendQuestSelectionDialog(env);
						}
				}
			}
			/*
			 * To check on retail if there is a dedicate portal to exit.
			 * else if (targetId == 799503) { // Taloc's Mirage
			 * switch (dialogActionId) {
			 * case USE_OBJECT:
			 * if (var == 7) {
			 * return sendQuestDialog(env, 3057);
			 * }
			 * break;
			 * case SETPRO7: {
			 * qs.setQuestVar(8); // Reward
			 * qs.setStatus(QuestStatus.REWARD);
			 * updateQuestStatus(env);
			 * TeleportService.teleportTo(env.getPlayer(), 220070000, 1025, 2782, 388, (byte) 60, TeleportAnimation.BEAM_ANIMATION);
			 * return closeDialogWindow(env);
			 * }
			 * }
			 * }
			 */
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799247) { // Angrad
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t targetId = env.getTargetId();
			int32_t var = qs->getQuestVarById(0);

			switch (targetId) {
				case 215488: // Celestius
					if (var == 6) {
						playQuestMovie(env, 437);
						return defaultOnKillEvent(env, 215488, var, var + 1); // 7
					}
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (player->getWorldId() == 300190000) {
				int32_t itemId = item.getItemId();
				int32_t var = qs->getQuestVarById(0);
				int32_t var1 = qs->getQuestVarById(1);
				if (itemId == 182215593) { // quest_20032b
					changeQuestStep(env, 4, 5); // 7
					return HandlerResult::SUCCESS; // //TODO: Should return FAILED (not removed, but skill still should be used)
				} else if (itemId == 182215592) { // quest_20032a
					if (var == 5) {
						if (var1 >= 0 && var1 < 19) {
							changeQuestStep(env, var1, var1 + 1, false, 1); // 3: 19
							return HandlerResult::SUCCESS;
						} else if (var1 == 19) {
							qs->setQuestVar(6);
							updateQuestStatus(env);
							return HandlerResult::SUCCESS;
						}
					}
				}
			}
		}
		return HandlerResult::UNKNOWN;
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (player->getWorldId() == 300190000) {
				qs->setQuestVar(4);
				updateQuestStatus(env);
				return true;
			} else {
				removeQuestItem(env, 182215592, 1);
				removeQuestItem(env, 182215593, 1);

				int32_t var = qs->getQuestVarById(0);
				if (var >= 3 && var < 7) {
					restoreStep(env);
					return true;
				} else if (var == 7) { // Final boss killed
					removeQuestItem(env, 182215618, 1);
					removeQuestItem(env, 182215619, 1);
					qs->setQuestVar(8); // Reward
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return true;
				}
			}
		}
		return false;
	}

	bool onDieEvent(QuestEnv& env) override {
		return restoreStep(env);
	}

	bool onLogOutEvent(QuestEnv& env) override {
		return restoreStep(env);
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {20031});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {20031});
	}

private:
	bool restoreStep(QuestEnv& env) {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (var >= 3 && var <= 7) {
				removeQuestItem(env, 182215618, 1);
				removeQuestItem(env, 182215619, 1);
				qs->setQuestVar(2);
				updateQuestStatus(env);
				return true;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_20032AllAboutAbnormalAether, 20032);

} // namespace aion::gameserver::handlers::quest::gelkmaros
