#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::gelkmaros {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/gelkmaros/_21068TheGameIsAfoot.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _21068TheGameIsAfoot final : public AbstractQuestHandler {
public:
	_21068TheGameIsAfoot() : AbstractQuestHandler(21068) {}

	void register_() override {
		qe.registerQuestNpc(799405)->addOnQuestStart(questId);
		qe.registerQuestNpc(799405)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799406)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799405) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 799406) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0)
						return sendQuestDialog(env, 1352);
				} else if (dialogActionId == SETPRO1) {
					return defaultCloseDialog(env, 0, 1);
				}
			} else if (targetId == 799405) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 1)
						return sendQuestDialog(env, 1693);
				} else if (dialogActionId == SETPRO2) {
					return defaultCloseDialog(env, 1, 2, true, false);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799406) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_21068TheGameIsAfoot, 21068);

} // namespace aion::gameserver::handlers::quest::gelkmaros
