#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::gelkmaros {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/gelkmaros/_21036DeliveryofAetherSample.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author VladimirZ
 */
class _21036DeliveryofAetherSample final : public AbstractQuestHandler {
public:
	_21036DeliveryofAetherSample() : AbstractQuestHandler(21036) {}

	void register_() override {
		std::array<int32_t, 4> npcs{799258, 799238, 798713, 799239};
		for (int32_t npc : npcs)
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799258)->addOnQuestStart(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		if (sendQuestNoneDialog(env, 799258, 182207832, 1))
			return true;

		runtime::Ptr<QuestState> qs = env.getPlayer()->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		if (qs->getStatus() == QuestStatus::START) {
			if (env.getTargetId() == 799238) {
				switch (env.getDialogActionId()) {
					case QUEST_SELECT:
						if (var == 0)
							return sendQuestDialog(env, 1352);
						return false;
					case SETPRO1:
						return defaultCloseDialog(env, 0, 1);
				}
			} else if (env.getTargetId() == 798713) {
				switch (env.getDialogActionId()) {
					case QUEST_SELECT:
						if (var == 1)
							return sendQuestDialog(env, 1693);
						return false;
					case SETPRO2:
						return defaultCloseDialog(env, 1, 2, true, false);
				}
			}
		}
		return sendQuestRewardDialog(env, 799239, 2375);
	}
};
AION_QUEST_HANDLER(_21036DeliveryofAetherSample, 21036);

} // namespace aion::gameserver::handlers::quest::gelkmaros
