#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::gelkmaros {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/gelkmaros/_21217NewResearchPlan.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _21217NewResearchPlan final : public AbstractQuestHandler {
public:
	_21217NewResearchPlan() : AbstractQuestHandler(21217) {}

	void register_() override {
		qe.registerQuestNpc(799316)->addOnQuestStart(questId);
		qe.registerQuestNpc(799239)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798713)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799226)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799316) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env, 182207890, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 799239) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0)
						return sendQuestDialog(env, 1352);
				} else if (dialogActionId == SETPRO1) {
					return defaultCloseDialog(env, 0, 1);
				}
			} else if (targetId == 798713) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 1)
						return sendQuestDialog(env, 1693);
				} else if (dialogActionId == SETPRO2) {
					qs->setQuestVar(2);
					return defaultCloseDialog(env, 2, 2, true, false);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799226) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_21217NewResearchPlan, 21217);

} // namespace aion::gameserver::handlers::quest::gelkmaros
