#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::gelkmaros {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/gelkmaros/_21460AShulacksStory.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author vlog
 */
class _21460AShulacksStory final : public AbstractQuestHandler {
public:
	_21460AShulacksStory() : AbstractQuestHandler(21460) {}

	void register_() override {
		qe.registerQuestNpc(799258)->addOnQuestStart(questId);
		qe.registerQuestNpc(799258)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799502)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799276)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799258) { // Denskel
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 799502: // Dorkin
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 1352);
							}
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1, 182209520, 1, 0, 0); // 1
					}
					break;
				case 799276: // Chenkiki
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1) {
								return sendQuestDialog(env, 2375);
							}
							return false;
						case SELECT_QUEST_REWARD:
							if (removeQuestItem(env, 182209520, 1))
								changeQuestStep(env, 1, 1, true); // reward
							return sendQuestDialog(env, 5);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799276) { // Chenkiki
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_21460AShulacksStory, 21460);

} // namespace aion::gameserver::handlers::quest::gelkmaros
