// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.tribe - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::model::templates::tribe {

class Tribe;

} // namespace aion::gameserver::model::templates::tribe
