#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"
#include "aion/gameserver/world/WorldPosition.h"

namespace aion::gameserver::handlers::quest::enshar {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/enshar/_20504TiamatsShadow.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @Author Majka
 * @Description:
 * 							Talk with Xeikun.
 *               Investigate the Beritra troops (5) in The Beritra Defense Line.
 *               Talk with Xeikun.
 *               Investigate Vengeful Aetheric Guard Dominators (5) in the Wretched Plot.
 *               Take down Cursed Gilgamesh. (1)
 *               Talk with Gilgamesh.
 *               Talk with Jalturan somewhere near Cet Siege Territory.
 *               Report to Xeikun.
 *               Order: Xeikun is looking for you. Go and see him.
 */
class _20504TiamatsShadow final : public AbstractQuestHandler {
public:
	_20504TiamatsShadow() : AbstractQuestHandler(20504) {}

	void register_() override {
		// Xeikun 804730
		// Jalturan 804731
		// Gilgamesh 804742
		std::array<int32_t, 3> npcs{804730, 804731, 804742};
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}

		std::array<int32_t, 7> mobs{219943, 219944, 219945, 219946, 219947, 219948, 219949};
		for (int32_t mob : mobs) {
			qe.registerQuestNpc(mob)->addOnKillEvent(questId);
		}
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerOnInvisibleTimerEnd(questId);
		qe.registerOnLogOut(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		switch (targetId) {
			case 804730: // Xeikun
				if (qs->getStatus() == QuestStatus::START) {
					if (var == 0) { // Step 0: Talk with Xeikun.
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 1011);

						if (dialogActionId == SETPRO1)
							return defaultCloseDialog(env, var, var + 1);
					}

					if (var == 2) { // Step 2: Talk with Xeikun.
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 1693);

						if (dialogActionId == SETPRO3)
							return defaultCloseDialog(env, var, var + 1);
					}
				}

				if (qs->getStatus() == QuestStatus::REWARD) {
					if (dialogActionId == USE_OBJECT) {
						return sendQuestDialog(env, 10002);
					}

					return sendQuestEndDialog(env);
				}
				break;
			case 804742: // Gilgamesh
				if (qs->getStatus() == QuestStatus::START) {
					if (var == 5) { // Step 5: Talk with Gilgamesh.
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 2716);

						if (dialogActionId == SETPRO6)
							return defaultCloseDialog(env, var, var + 1);
					}
				}
				break;
			case 804731: // Jalturan
				if (qs->getStatus() == QuestStatus::START) {
					if (var == 6) { // Step 6: Talk with Jalturan somewhere near Cet Siege Territory.
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 3057);

						if (dialogActionId == SET_SUCCEED) {
							qs->setStatus(QuestStatus::REWARD);
							qs->setQuestVar(var + 1);
							updateQuestStatus(env);
							return closeDialogWindow(env);
						}
					}
				}
				break;
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		switch (targetId) {
			case 219943:
			case 219944:
			case 219945:
				if (var == 1) { // Step 1: Investigate the Beritra troops (5) in The Beritra Defense Line.
					int32_t varKill = qs->getQuestVarById(1); // Kill counter
					qs->setQuestVarById(1, varKill + 1); // 1-5 with varNum 1
					if (varKill >= 4) {
						qs->setQuestVar(var + 1);
					}
					updateQuestStatus(env);
					return true;
				}
				break;
			case 219946:
			case 219947:
			case 219948:
				if (var == 3) { // Step 3: Investigate Vengeful Aetheric Guard Dominators (5) in the Wretched Plot.
					int32_t varKill = qs->getQuestVarById(1); // Kill counter
					qs->setQuestVarById(1, varKill + 1); // 1-5 with varNum 1
					if (varKill >= 4) {
						qs->setQuestVar(var + 1);
					}
					updateQuestStatus(env);
					return true;
				}
				break;
			case 219949:
				if (var == 4) { // Step 4: Take down Cursed Gilgamesh. (1)
					qs->setQuestVar(var + 1);
					updateQuestStatus(env);
					spawnForFiveMinutes(804742, *env.getVisibleObject()->getPosition());
					QuestService::invisibleTimerStart(env, 300);
					return true;
				}
				break;
		}
		return false;
	}

	bool onLogOutEvent(QuestEnv& env) override {
		return RestoreQuestStep(env, 5, 4);
	}

	bool onInvisibleTimerEndEvent(QuestEnv& env) override {
		return RestoreQuestStep(env, 5, 4);
	}

private:
	bool RestoreQuestStep(QuestEnv& env, int32_t step, int32_t oldStep) {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		if (var == step) {
			qs->setQuestVar(oldStep);
			updateQuestStatus(env);
		}
		return true;
	}

public:
	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {20500});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {20500});
	}
};
AION_QUEST_HANDLER(_20504TiamatsShadow, 20504);

} // namespace aion::gameserver::handlers::quest::enshar
