#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::enshar {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/enshar/_25070TruthOfTheCrystal.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @Author Majka
 */
class _25070TruthOfTheCrystal final : public AbstractQuestHandler {
public:
	_25070TruthOfTheCrystal() : AbstractQuestHandler(25070) {}

	void register_() override {
		// Brandun 804919
		qe.registerQuestNpc(804919)->addOnQuestStart(questId);
		std::array<int32_t, 2> npcs{804919, 731552};
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 804919) { // Brandun
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);

			switch (targetId) {
				case 731552: // Cold crystal
					if (var == 0) {
						if (dialogActionId == QUEST_SELECT) {
							return sendQuestDialog(env, 1011);
						}

						if (dialogActionId == SET_SUCCEED) {
							giveQuestItem(env, 182215723, 1);
							qs->setQuestVar(var + 1);
							return defaultCloseDialog(env, var + 1, var + 1, true, false);
						}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			switch (targetId) {
				case 804919: // Brandun
					if (dialogActionId == USE_OBJECT)
						return sendQuestDialog(env, 10002);

					removeQuestItem(env, 182215723, 1);
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_25070TruthOfTheCrystal, 25070);

} // namespace aion::gameserver::handlers::quest::enshar
