#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"
#include "aion/gameserver/world/WorldMapInstance.h"

namespace aion::gameserver::handlers::quest::enshar {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/enshar/_25050TreasureInTheDeepSea.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Majka
 */
class _25050TreasureInTheDeepSea final : public AbstractQuestHandler {
public:
	_25050TreasureInTheDeepSea() : AbstractQuestHandler(25050) {}

	void register_() override {
		// Recluse's grave 731553
		// Soglo 804915
		// Zagmus 805160
		qe.registerQuestNpc(804915)->addOnQuestStart(questId);
		std::array<int32_t, 3> npcs{731553, 804915, 805160};
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
		qe.registerOnInvisibleTimerEnd(questId);
		qe.registerOnLogOut(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 804915) { // Soglo
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);

			switch (targetId) {
				case 804915: // Soglo
					if (var == 0) {
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 1011);

						if (dialogActionId == CHECK_USER_HAS_QUEST_ITEM)
							return checkQuestItems(env, var, var + 1, false, 10000, 10001);
					}
					if (var == 1) {
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 1352);

						if (dialogActionId == SETPRO2)
							return defaultCloseDialog(env, var, var + 1, 182215719, 1);
					}
					break;
				case 731553: // Recluse's grave
					if (var == 2) {
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 1693);

						if (dialogActionId == SETPRO3) {
							// Spawn of Zagmus
							spawnForFiveMinutes(805160, *env.getVisibleObject()->getWorldMapInstance(), 2046.8f, 1588.8f, 348.4f, static_cast<int8_t>(90));
							QuestService::invisibleTimerStart(env, 300);
							return defaultCloseDialog(env, var, var + 1);
						}
					}
					break;
				case 805160: // Zagmus
					if (var == 3) {
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 2034);

						if (dialogActionId == SET_SUCCEED) {
							removeQuestItem(env, 182215719, 1);
							qs->setQuestVar(var + 1);
							return defaultCloseDialog(env, var + 1, var + 1, true, false);
						}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			switch (targetId) {
				case 804915: // Soglo
					if (dialogActionId == USE_OBJECT)
						return sendQuestDialog(env, 10002);

					return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onLogOutEvent(QuestEnv& env) override {
		return RestoreQuestStep(env);
	}

	bool onInvisibleTimerEndEvent(QuestEnv& env) override {
		return RestoreQuestStep(env);
	}

private:
	bool RestoreQuestStep(QuestEnv& env) {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		if (var == 3) {
			qs->setQuestVar(var - 1);
			updateQuestStatus(env);
		}
		return true;
	}
};
AION_QUEST_HANDLER(_25050TreasureInTheDeepSea, 25050);

} // namespace aion::gameserver::handlers::quest::enshar
