#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::enshar {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/enshar/_25062OminousAdvice.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @Author Majka
 */
class _25062OminousAdvice final : public AbstractQuestHandler {
public:
	_25062OminousAdvice() : AbstractQuestHandler(25062) {}

	void register_() override {
		// Runlil 804917
		// Sorg 804918
		qe.registerQuestNpc(804917)->addOnQuestStart(questId);
		std::array<int32_t, 2> npcs{804917, 804918};
		for (int32_t npc : npcs) {
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 804917) { // Runlil
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);

			switch (targetId) {
				case 804917: // Runlil
					if (var == 0) {
						if (dialogActionId == QUEST_SELECT)
							return sendQuestDialog(env, 1011);

						if (dialogActionId == CHECK_USER_HAS_QUEST_ITEM) {
							if (QuestService::collectItemCheck(env, true)) {
								qs->setStatus(QuestStatus::REWARD);
								qs->setQuestVar(var + 1);
								updateQuestStatus(env);
								return sendQuestDialog(env, 10000);
							} else {
								return sendQuestDialog(env, 10001);
							}
						}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			switch (targetId) {
				case 804918: // Sorg
					if (dialogActionId == USE_OBJECT)
						return sendQuestDialog(env, 10002);

					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_25062OminousAdvice, 25062);

} // namespace aion::gameserver::handlers::quest::enshar
