// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.skillengine.condition - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::skillengine::condition {

class AbnormalStateCondition;
class BackCondition;
class ChainCondition;
class ChargeArmorCondition;
class ChargeCondition;
class ChargeWeaponCondition;
class CombatCheckCondition;
class Condition;
class Conditions;
class DpCondition;
class FormCondition;
class FrontCondition;
class HpCondition;
class ItemChargeCondition;
class LeftHandCondition;
class MpCondition;
class NoFlyingCondition;
class OnFlyCondition;
class PlayerMovedCondition;
class PolishChargeCondition;
class RaceCondition;
class RideRobotCondition;
class SelfFlyingCondition;
class SkillChargeCondition;
enum class TargetAttribute : std::uint8_t;
class TargetCondition;
class TargetFlyingCondition;
class WeaponCondition;

} // namespace aion::gameserver::skillengine::condition
