#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/controllers/NpcController.h"
#include "aion/gameserver/controllers/VisibleObjectController.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/item/ItemTemplate.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::verteron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/verteron/_1197KrallBook.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author MrPoke, Nephis, Rolandas
 */
class _1197KrallBook final : public AbstractQuestHandler {
public:
	_1197KrallBook() : AbstractQuestHandler(1197) {}

	void register_() override {
		qe.registerQuestNpc(700004)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203129)->addOnTalkEvent(questId);
		qe.registerQuestItem(182200558, questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		runtime::Ptr<Npc> npc = runtime::as<Npc>(env.getVisibleObject());
		if (!(npc != nullptr)) {
			if (env.getDialogActionId() == QUEST_ACCEPT_1) {
				QuestService::startQuest(env);
				PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(0, 0));
				return true;
			}
		} else if (npc->getNpcId() == 700004) {
			if (qs == nullptr || qs->isStartable()) {
				if (player->getInventory().getItemCountByItemId(182200558) == 0 && giveQuestItem(env, 182200558, 1)) {
					npc->getController().deleteAndScheduleRespawn();
				}
			}
			return true;
		} else if (npc->getNpcId() == 203129) {
			if (qs != nullptr) {
				if (env.getDialogActionId() == QUEST_SELECT && qs->getStatus() == QuestStatus::START) {
					return sendQuestDialog(env, 2375);
				} else if (env.getDialogActionId() == SELECT_QUEST_REWARD && qs->getStatus() != QuestStatus::COMPLETE) {
					removeQuestItem(env, 182200558, 1);
					qs->setQuestVar(1);
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return sendQuestEndDialog(env);
				} else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		int32_t id = item.getItemTemplate()->getTemplateId();

		if (id != 182200558)
			return HandlerResult::UNKNOWN;
		sendQuestDialog(env, 4);
		return HandlerResult::SUCCESS;
	}
};
AION_QUEST_HANDLER(_1197KrallBook, 1197);

} // namespace aion::gameserver::handlers::quest::verteron
