#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"
#include "aion/gameserver/services/item/ItemService.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::verteron {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/verteron/_14014TurningTheIde.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Ritsu, Majka
 */
class _14014TurningTheIde final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 2> mobs{210178, 216892};

public:
	_14014TurningTheIde() : AbstractQuestHandler(14014) {}

	void register_() override {
		std::array<int32_t, 4> questNpcs{203146, 203147, 802045, 203098};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestItem(182215314, questId);
		for (int32_t questNpc : questNpcs)
			qe.registerQuestNpc(questNpc)->addOnTalkEvent(questId);
		for (int32_t mob : mobs)
			qe.registerQuestNpc(mob)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 203146:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							return false;
						case SETPRO1:
							ItemService::addItem(*player, 182215314, 1);
							return defaultCloseDialog(env, 0, 1); // 1
					}
					break;
				case 203147:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 2)
								return sendQuestDialog(env, 1693);
							return false;
						case SETPRO3:
							return defaultCloseDialog(env, 2, 3); // 3
					}
					break;
				case 802045:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 3)
								return sendQuestDialog(env, 2034);
							return false;
						case CHECK_USER_HAS_QUEST_ITEM:
							if (var == 3)
								return checkQuestItems(env, 3, 5, false, 2375, 2120);
					}
					break;
				case 203098:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 8)
								return sendQuestDialog(env, 3057);
							return false;
						case SELECT_QUEST_REWARD:
							return defaultCloseDialog(env, 8, 8, true, false);
					}
					break;
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203098)
				return sendQuestEndDialog(env);
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		return defaultOnKillEvent(env, mobs, 5, 7) || defaultOnKillEvent(env, mobs, 7, true);
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (qs->getQuestVarById(0) == 1 && player->isInsideZone(ZoneName::get("TURSIN_OUTPOST_210030000"))) {
				return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 1, 2, false, 18));
			}
		}
		return HandlerResult::FAILED;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {14010});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {14010});
	}
};
AION_QUEST_HANDLER(_14014TurningTheIde, 14014);

} // namespace aion::gameserver::handlers::quest::verteron
