#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::charlirunerks_daemons {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/charlirunerks_daemons/_48002CharlirunerksDaemonsWantYou.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author vlog
 */
class _48002CharlirunerksDaemonsWantYou final : public AbstractQuestHandler {
public:
	_48002CharlirunerksDaemonsWantYou() : AbstractQuestHandler(48002) {}

	void register_() override {
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(799886)->addOnTalkEvent(questId);
	}

	void onLevelChangedEvent(Player& player) override {
		runtime::Ptr<QuestState> qs = player.getQuestStateList()->getQuestState(questId);
		if (player.getLevel() >= 50 && (qs == nullptr || qs->isStartable()))
			QuestService::startQuest(*QuestEnv::create(nullptr, player, questId));
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (targetId == 799886) { // Tikalanerk
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 10002);
				} else if (dialogActionId == SELECT_QUEST_REWARD) {
					changeQuestStep(env, 0, 0, true);
					return sendQuestDialog(env, 5);
				}
			}
		} else if (qs != nullptr && qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799886) { // Tikalanerk
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_48002CharlirunerksDaemonsWantYou, 48002);

} // namespace aion::gameserver::handlers::quest::charlirunerks_daemons
