#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::levinshor {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/levinshor/_23708SoundtheAlarm.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Pad
 */
class _23708SoundtheAlarm final : public AbstractQuestHandler {
private:
	static constexpr int32_t npcId = 802344; // Kestum
	static constexpr int32_t itemId = 182215535;

public:
	_23708SoundtheAlarm() : AbstractQuestHandler(23708) {}

	void register_() override {
		qe.registerQuestNpc(npcId)->addOnQuestStart(questId);
		qe.registerQuestNpc(npcId)->addOnTalkEvent(questId);
		qe.registerQuestItem(itemId, questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == npcId) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env, itemId, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == npcId) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 1) {
							return sendQuestDialog(env, 2375);
						}
						return false;
					case SELECT_QUEST_REWARD:
						return defaultCloseDialog(env, 1, 1, true, true);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == npcId) {
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (player->isInsideZone(ZoneName::get("LDF4_ADVANCE_ITEMUSEAREA_Q23708_600100000"))) {
				return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 0, 1, false));
			}
		}
		return HandlerResult::FAILED;
	}
};
AION_QUEST_HANDLER(_23708SoundtheAlarm, 23708);

} // namespace aion::gameserver::handlers::quest::levinshor
