// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.spawns.vortexspawns - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::model::templates::spawns::vortexspawns {

struct VortexSpawn;
class VortexSpawnTemplate;

// Nested types (declared inside their outer class, include its header):
//   VortexSpawn::VortexStateTemplate

} // namespace aion::gameserver::model::templates::spawns::vortexspawns
