// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.actions - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::actions {

class PlayerActions;
enum class PlayerMode : std::uint8_t;

} // namespace aion::gameserver::model::actions
