// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.team - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::team {

template <class M, class TM> class GeneralTeam;
class PlayerTeamMember;
class TeamEvent;
template <class M> class TeamMember;
enum class TeamType : std::uint8_t;
template <class TM> class TemporaryPlayerTeam;

} // namespace aion::gameserver::model::team
