// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.spawns - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::templates::spawns {

struct HouseSpawn;
class HouseSpawns;
class Spawn;
class SpawnGroup;
class SpawnMap;
class SpawnSearchResult;
class SpawnSpotTemplate;
class SpawnTemplate;
enum class SpawnType : std::uint8_t;
class TemporarySpawn;

} // namespace aion::gameserver::model::templates::spawns
