#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::pandaemonium {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/pandaemonium/_29048SeriphimTeachings.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _29048SeriphimTeachings final : public AbstractQuestHandler {
public:
	_29048SeriphimTeachings() : AbstractQuestHandler(29048) {}

	void register_() override {
		qe.registerQuestNpc(798304)->addOnQuestStart(questId);
		qe.registerQuestNpc(798304)->addOnTalkEvent(questId);
		qe.registerQuestItem(182212217, questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798304) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env, 182212217, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798304) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				removeQuestItem(env, 182212217, 1);
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (qs->getQuestVarById(0) == 0) {
				qs->setQuestVar(1);
				changeQuestStep(env, 1, 1, true);
				return HandlerResult::SUCCESS;
			}
		}
		return HandlerResult::FAILED;
	}
};
AION_QUEST_HANDLER(_29048SeriphimTeachings, 29048);

} // namespace aion::gameserver::handlers::quest::pandaemonium
