#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::pandaemonium {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/pandaemonium/_2937UnexpectedReward.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Gigi, vlog
 */
class _2937UnexpectedReward final : public AbstractQuestHandler {
public:
	_2937UnexpectedReward() : AbstractQuestHandler(2937) {}

	void register_() override {
		qe.registerQuestNpc(204092)->addOnQuestStart(questId);
		qe.registerQuestNpc(204092)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798059)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204092) { // Talon
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 798059) { // Nekorunuerk
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0) {
							return sendQuestDialog(env, 2375);
						}
						return false;
					case SELECT_QUEST_REWARD:
						qs->setQuestVar(1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 5);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798059) { // Nekorunuerk
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2937UnexpectedReward, 2937);

} // namespace aion::gameserver::handlers::quest::pandaemonium
