#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::pandaemonium {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/pandaemonium/_2963OnBehalfOfAFriend.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _2963OnBehalfOfAFriend final : public AbstractQuestHandler {
public:
	_2963OnBehalfOfAFriend() : AbstractQuestHandler(2963) {}

	void register_() override {
		qe.registerQuestNpc(204253)->addOnQuestStart(questId);
		qe.registerQuestNpc(204253)->addOnTalkEvent(questId);
		qe.registerQuestNpc(278137)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204253) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 278137) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0) {
						return sendQuestDialog(env, 1352);
					}
				} else if (dialogActionId == SETPRO1) {
					qs->setQuestVar(2);
					return defaultCloseDialog(env, 2, 2, true, false);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204253) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2963OnBehalfOfAFriend, 2963);

} // namespace aion::gameserver::handlers::quest::pandaemonium
