#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::pandaemonium {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/pandaemonium/_4906TalesOfHeroes.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _4906TalesOfHeroes final : public AbstractQuestHandler {
public:
	_4906TalesOfHeroes() : AbstractQuestHandler(4906) {}

	void register_() override {
		qe.registerQuestNpc(204211)->addOnQuestStart(questId);
		qe.registerQuestNpc(204211)->addOnTalkEvent(questId);
		qe.registerQuestNpc(205188)->addOnTalkEvent(questId);
		qe.registerQuestNpc(278003)->addOnTalkEvent(questId);
		qe.registerQuestNpc(204057)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204211) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env, 182207075, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 205188) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0) {
						return sendQuestDialog(env, 1352);
					}
				} else if (dialogActionId == SETPRO1) {
					removeQuestItem(env, 182207075, 1);
					giveQuestItem(env, 182207076, 1);
					return defaultCloseDialog(env, 0, 1);
				}
			}
			if (targetId == 278003) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 1) {
						return sendQuestDialog(env, 1693);
					}
				} else if (dialogActionId == SETPRO2) {
					removeQuestItem(env, 182207076, 1);
					giveQuestItem(env, 182207077, 1);
					return defaultCloseDialog(env, 1, 2);
				}
			}
			if (targetId == 204057) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 2) {
						return sendQuestDialog(env, 2034);
					}
				} else if (dialogActionId == SETPRO3) {
					removeQuestItem(env, 182207077, 1);
					giveQuestItem(env, 182207078, 1);
					qs->setQuestVar(3);
					return defaultCloseDialog(env, 3, 3, true, false);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204211) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				removeQuestItem(env, 182207078, 1);
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_4906TalesOfHeroes, 4906);

} // namespace aion::gameserver::handlers::quest::pandaemonium
