#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::pandaemonium {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/pandaemonium/_4970TheFashionistas.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _4970TheFashionistas final : public AbstractQuestHandler {
public:
	_4970TheFashionistas() : AbstractQuestHandler(4970) {}

	void register_() override {
		qe.registerQuestNpc(799315)->addOnQuestStart(questId);
		qe.registerQuestNpc(798392)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798393)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799315) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env, 182206120, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 798392) {
				if (dialogActionId == QUEST_SELECT) {
					if (qs->getQuestVarById(0) == 0) {
						return sendQuestDialog(env, 1352);
					}
				} else if (dialogActionId == SETPRO1) {
					qs->setQuestVar(1);
					return defaultCloseDialog(env, 1, 1, true, false);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798393) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				removeQuestItem(env, 182206120, 1);
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_4970TheFashionistas, 4970);

} // namespace aion::gameserver::handlers::quest::pandaemonium
