#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/controllers/VisibleObjectController.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"
#include "aion/gameserver/questEngine/model/QuestVars.h"
#include "aion/gameserver/services/instance/InstanceService.h"
#include "aion/gameserver/services/teleport/TeleportService.h"
#include "aion/gameserver/world/WorldMapInstance.h"
#include "aion/gameserver/world/WorldMapTypeInfo.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::bare_truth {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/bare_truth/_14031AHyperVention.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur
 */
class _14031AHyperVention final : public AbstractQuestHandler {
public:
	_14031AHyperVention() : AbstractQuestHandler(14031) {}

	void register_() override {
		std::array<int32_t, 5> npc_ids{203700, 801216, 790001, 203183, 203989};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerOnEnterWorld(questId);
		qe.registerQuestItem(182215388, questId);
		qe.registerQuestItem(182215389, questId);
		qe.registerQuestItem(182215390, questId);
		qe.registerQuestNpc(233878)->addOnKillEvent(questId);
		for (int32_t npc_id : npc_ids)
			qe.registerQuestNpc(npc_id)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();
		if (qs == nullptr)
			return false;
		if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 203700: // Fasimedes
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1011);
						case SETPRO1:
							qs->setQuestVar(1);
							updateQuestStatus(env);
							return closeDialogWindow(env);
					}
					break;
				case 801216: // Losthes
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1352);
						case SETPRO2:
							qs->setQuestVar(2);
							updateQuestStatus(env);
							return closeDialogWindow(env);
					}
					break;
				case 790001: // Pernos
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1693);
						case SETPRO3:
							if (!giveQuestItem(env, 182215388, 1))
								return true;
							qs->setQuestVar(3);
							updateQuestStatus(env);
							return closeDialogWindow(env);
					}
					break;
				case 203183: // Khidia
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 2375);
						case SETPRO5:
							if (!giveQuestItem(env, 182215389, 1))
								return true;
							qs->setQuestVar(5);
							updateQuestStatus(env);
							return closeDialogWindow(env);
					}
					break;
				case 203989: // Tumblusen
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 6) {
								return sendQuestDialog(env, 3057);
							}
							if (var == 8) {
								return sendQuestDialog(env, 3739);
							}
							return false;
						case SETPRO7:
							if (!giveQuestItem(env, 182215390, 1))
								return true;
							qs->setQuestVar(7);
							updateQuestStatus(env);
							return closeDialogWindow(env);
						case SETPRO9: {
							qs->setQuestVar(9);
							updateQuestStatus(env);
							runtime::Ptr<WorldMapInstance> newInstance = InstanceService::getNextAvailableInstance(::aion::gameserver::world::getId(WorldMapType::NIDALBER), *player);
							TeleportService::teleportTo(*player, *newInstance, 274, 167, 204);
							return closeDialogWindow(env);
						}
					}
					break;
				case 730888: // Large Teleporter
					switch (dialogActionId) {
						case QUEST_SELECT:
							env.getVisibleObject()->getController().delete_();
							qs->setQuestVar(11);
							updateQuestStatus(env);
							playQuestMovie(env, 888);
							spawn(730898, *player, 257, 257, static_cast<float>(226.35), static_cast<int8_t>(95)); // Broken Teleporter Device
					}
					break;
				case 730898: // Broken Large Teleporter
					switch (dialogActionId) {
						case QUEST_SELECT:
							env.getVisibleObject()->getController().delete_();
							qs->setStatus(QuestStatus::REWARD);
							updateQuestStatus(env);
							TeleportService::teleportTo(*player, 110010000, 1876.29f, 1511.0f, 812.675f, static_cast<int8_t>(60), TeleportAnimation::FADE_OUT_BEAM);
					}
					break;
			}
		}
		if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203700) // Fasimedes
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 4083);
					case SELECT_QUEST_REWARD:
						return sendQuestDialog(env, 5);
					default:
						{
							return sendQuestEndDialog(env);
						}
				}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t var = qs->getQuestVarById(0);
		if (qs->getStatus() == QuestStatus::START) {
			if (player->isInsideItemUseZone(ZoneName::get("LF1_ITEMUSEAREA_Q14031"))) {
				if (var == 3) {
					playQuestMovie(env, 21);
					return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 3, 4, false)); // 3-4
				}
			}
			if (player->isInsideItemUseZone(ZoneName::get("LF1A_ITEMUSEAREA_Q14031"))) {
				if (var == 5) {
					return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 5, 6, false)); // 5-6
				}
			}
			if (player->isInsideItemUseZone(ZoneName::get("LF2_ITEMUSEAREA_Q14031"))) {
				if (var == 7) {
					return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 7, 8, false)); // 7-8
				}
			}
		}
		return HandlerResult::SUCCESS;
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVars()->getQuestVars();
			if (var == 9 && player->getWorldId() == 320040000) {
				// Shattered Large Teleporter
				spawn(730888, *player, 257, 257, static_cast<float>(226.35), static_cast<int8_t>(95));
				// Captain Tarbana
				spawn(233878, *player, static_cast<float>(262.9), static_cast<float>(224.5), static_cast<float>(211.348), static_cast<int8_t>(95));
				// 5x Baranath Sentinel
				spawn(233886, *player, static_cast<float>(217.015), static_cast<float>(221.694), static_cast<float>(207.49455), static_cast<int8_t>(97));
				spawn(233886, *player, static_cast<float>(239.732), static_cast<float>(211.250), static_cast<float>(209.19), static_cast<int8_t>(97));
				spawn(233886, *player, static_cast<float>(257.065), static_cast<float>(204.49), static_cast<float>(209.094), static_cast<int8_t>(97));
				spawn(233886, *player, static_cast<float>(274.899), static_cast<float>(199.398), static_cast<float>(208.83487), static_cast<int8_t>(97));
				spawn(233886, *player, static_cast<float>(282.878), static_cast<float>(223.742), static_cast<float>(208.252), static_cast<int8_t>(97));
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (env.getTargetId() == 233878)
				env.getVisibleObject()->getController().delete_();
			return defaultOnKillEvent(env, 233878, 9, 10);
		}
		return false;
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {14030});
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {14030});
	}
};
AION_QUEST_HANDLER(_14031AHyperVention, 14031);

} // namespace aion::gameserver::handlers::quest::bare_truth
