// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.configs.schedule - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::configs::schedule {

class RiftSchedule;
class SiegeSchedules;
class WorldRaidSchedules;

// Nested types (declared inside their outer class, include its header):
//   RiftSchedule::Rift
//   SiegeSchedules::AgentFight
//   SiegeSchedules::Fortress
//   SiegeSchedules::SiegeSchedule
//   WorldRaidSchedules::WorldRaidSchedule

} // namespace aion::gameserver::configs::schedule
