# Chunk manifest support (docs/design/handlers-and-porting-plan.md §2.2): the functions that chunks.cmake calls, the configure-time ownership
# checks, one static library per chunk target, aion_gs_core, the chunk unit tests and <build>/game-server/chunks.json.
#
# Manifest syntax (cpp/game-server/chunks.cmake; tools/porting/chunks.py implements the same rules without CMake):
#
#   aion_gs_chunks_settings(EXTENSIONS <ext>... ROOTS <dir>... JAVA_ROOTS <glob>...)
#       EXTENSIONS   file extensions under the ROOTS that must have exactly one owner (other files, e.g. generated JSON, are not checked)
#       ROOTS        C++ source roots below cpp/game-server (src, handlers, generated)
#       JAVA_ROOTS   globs of the Java files (relative to the Java game-server directory) that must be claimed exactly once
#
#   aion_gs_chunk(<name> (TARGET <library> | LEASE) PHASE <n> [ROOT <root>...]
#       GLOBS <glob>... [EXCLUDE <glob>...]           C++ files of the part, relative to each ROOT (default ROOT: src)
#       [JAVA <glob>... [JAVA_EXCLUDE <glob>...]]     Java files the part ports, relative to the Java game-server directory
#       [DEPENDS <target>...]                         leaf part: links only these (plus the build options); its tests link only its library.
#                                                     Either all parts of a target have DEPENDS or none.
#       [PCH <header>...]                             precompiled headers (include paths, e.g. the handler category preludes)
#       [TESTS <dir>] [TEST_INCLUDES <dir>...]        unit test directory below game-server/tests (default: the target name without aion_gs_;
#                                                     <that>/<chunk name> when several chunks share the target), extra include directories of
#                                                     the test executable (below game-server/tests)
#       [TEST_SUPPORT <dir>...]                       further test directories the chunk owns that are not compiled into the part's test
#                                                     executable (shared support headers, a harness that CMakeLists.txt builds itself)
#       [OTHER_FILES <glob>...]                       other files the chunk owns (or, in a LEASE, may change) below cpp/game-server outside the
#                                                     ROOTS and tests/, e.g. CMake scripts in cmake/ (relative to cpp/game-server). Only
#                                                     chunks.py owner and check-ownership use them; the configure step validates the globs and
#                                                     writes them to chunks.json, and the manifest review keeps the owners of such files disjoint
#       [MAIN <file>]                                 a file of the part (relative to its ROOT) compiled into aion_game_server, not the library
#       [COMPILE_WHEN_EXISTS <file>]                  the part's .cpp files are compiled only once <ROOT>/<file> exists (header-only until then)
#       [XMLGEN_SHELLS])                              restricts the matches to xmlgen behaviour class shells: src X.h/X.cpp whose
#                                                     generated/<same path>/X.xml.inc exists
#   A chunk is identified by <name> and may have several parts (calls) with different targets; several chunks may share a target. A LEASE part
#   owns nothing: it lets chunk <name> change files (GLOBS, OTHER_FILES) or test directories (TEST_SUPPORT) that other parts own (checked by chunks.py
#   check-ownership only) and creates no target. A keyword may appear only once per call.
#
# Glob language: `**/` any number of directories (also none), a trailing `/**` everything below, `*` any characters except `/`, `?` one character
# except `/`, `[A-K]` a character class, `{a,b}` alternatives (not nested). Other characters are literal; allowed are letters, digits and `_-./`.
#
# Checks (aion_gs_check_chunks; aion_gs_finalize_chunks runs it, cmake/CheckChunks.cmake runs it in script mode), all problems in one
# FATAL_ERROR: every file with one of the EXTENSIONS below a ROOT matches exactly one non-lease part (unowned files, files with several owners);
# no file below the ROOTS or tests/ has another C++ source extension (hpp, cc, inl, ..., compared case-insensitively) or an EXTENSION in
# another case (Foo.H); every C++ file below tests/ lies in exactly one chunk's test directory (TESTS or TEST_SUPPORT; the test directories of
# different chunks or targets must not overlap, a manifest error); every Java file of JAVA_ROOTS is claimed by exactly one part (with
# -DAION_GS_JAVA_CLAIMS=WARNING only a warning, unless there are C++ problems as well). The lists are globbed with CONFIGURE_DEPENDS, so adding
# or removing a file re-runs the check. Documented non-source files: every other extension (e.g. the JSON, TOML and Markdown outputs in
# generated/, the Python oracle in tests/) is not checked.
#
# Targets: one STATIC library per TARGET with the files of all its parts (headers are listed for the IDE, .cpp compiled; a library without a
# compiled file gets a placeholder translation unit). Include roots src/ and generated/ come from aion_gs_build_options; handler libraries
# (ROOT handlers) add handlers/ and use unity builds (AION_HANDLER_UNITY, aion_gs_handler_unity_groups) with their PCH. Non-leaf libraries link
# aion_gs_core_deps (every leaf library, commons and the build options); they do not link each other, because MSVC resolves symbols across all
# static libraries of a link. aion_gs_core (INTERFACE) links every core library (roots src and generated); aion_gs_handlers links every handler
# library.
#
# Unit tests: one executable <target>_tests from the test directories of the target's parts that exist. A leaf target's tests link only the
# library; other core targets' tests link aion_gs_core plus the empty registries; a handler target's tests also link their handler library (and
# with it the handlers/ include root).

include_guard(GLOBAL)

if(NOT CMAKE_SCRIPT_MODE_FILE)
	option(AION_HANDLER_UNITY "Unity builds (batches of 16 files) for the handler libraries" ON)
	set(AION_GS_JAVA_CLAIMS "FATAL" CACHE STRING "Java files claimed by no or several chunks: FATAL or WARNING")
	set_property(CACHE AION_GS_JAVA_CLAIMS PROPERTY STRINGS FATAL WARNING)
endif()

# Converts a manifest glob to a regular expression without anchors (the same replacement sequence as glob_to_regex in tools/porting/chunks.py).
function(aion_gs_glob_to_regex out glob)
	if(NOT glob MATCHES "^[][A-Za-z0-9_./*?{},-]+$")
		message(FATAL_ERROR "chunks.cmake: glob '${glob}': only letters, digits and _-./*?[]{}, are allowed")
	endif()
	string(REGEX REPLACE "{[^{}]*}" "" outside "${glob}")
	if(outside MATCHES "[{},]")
		message(FATAL_ERROR "chunks.cmake: glob '${glob}': unbalanced or nested braces, or a comma outside braces")
	endif()
	string(REGEX REPLACE "[^[]" "" opening "${glob}")
	string(REGEX REPLACE "[^]]" "" closing "${glob}")
	string(LENGTH "${opening}" opening)
	string(LENGTH "${closing}" closing)
	if(NOT opening EQUAL closing)
		message(FATAL_ERROR "chunks.cmake: glob '${glob}': unbalanced character class")
	endif()
	string(REPLACE "." "\\." r "${glob}")
	string(REPLACE "**/" "@D@" r "${r}")
	string(REPLACE "/**" "@E@" r "${r}")
	string(REPLACE "**" "@F@" r "${r}")
	string(REPLACE "*" "[^/]*" r "${r}")
	string(REPLACE "?" "[^/]" r "${r}")
	string(REPLACE "{" "(" r "${r}")
	string(REPLACE "}" ")" r "${r}")
	string(REPLACE "," "|" r "${r}")
	string(REPLACE "@D@" "(.*/)?" r "${r}")
	string(REPLACE "@E@" "/.*" r "${r}")
	string(REPLACE "@F@" ".*" r "${r}")
	set(${out} "${r}" PARENT_SCOPE)
endfunction()

# ^(prefix|...)/(glob|...)$ for a list of globs; empty if there are none. prefixes may be empty (Java globs).
function(aion_gs_globs_to_regex out prefixes)
	set(bodies)
	foreach(glob IN LISTS ARGN)
		aion_gs_glob_to_regex(r "${glob}")
		list(APPEND bodies "${r}")
	endforeach()
	if(NOT bodies)
		set(${out} "" PARENT_SCOPE)
		return()
	endif()
	list(JOIN bodies "|" body)
	if(prefixes)
		list(JOIN prefixes "|" prefix)
		set(${out} "^(${prefix})/(${body})$" PARENT_SCOPE)
	else()
		set(${out} "^(${body})$" PARENT_SCOPE)
	endif()
endfunction()

function(aion_gs_chunks_settings)
	cmake_parse_arguments(ARG "" "" "EXTENSIONS;ROOTS;JAVA_ROOTS" ${ARGN})
	if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_EXTENSIONS OR NOT ARG_ROOTS OR NOT ARG_JAVA_ROOTS)
		message(FATAL_ERROR "aion_gs_chunks_settings: EXTENSIONS, ROOTS and JAVA_ROOTS are required (unknown arguments: ${ARG_UNPARSED_ARGUMENTS})")
	endif()
	foreach(ext IN LISTS ARG_EXTENSIONS)
		if(NOT ext MATCHES "^[a-z0-9]+$")
			message(FATAL_ERROR "aion_gs_chunks_settings: extension '${ext}': lower-case letters and digits only")
		endif()
	endforeach()
	set_property(GLOBAL PROPERTY AION_GS_CHUNK_EXTENSIONS ${ARG_EXTENSIONS})
	set_property(GLOBAL PROPERTY AION_GS_CHUNK_ROOTS ${ARG_ROOTS})
	set_property(GLOBAL PROPERTY AION_GS_CHUNK_JAVA_ROOTS ${ARG_JAVA_ROOTS})
endfunction()

function(aion_gs_chunk name)
	set(options LEASE XMLGEN_SHELLS)
	set(single TARGET PHASE TESTS MAIN COMPILE_WHEN_EXISTS)
	set(multi ROOT GLOBS EXCLUDE JAVA JAVA_EXCLUDE DEPENDS PCH TEST_INCLUDES TEST_SUPPORT OTHER_FILES)
	set(where "chunks.cmake: aion_gs_chunk(${name})")
	set(seen)
	foreach(arg IN LISTS ARGN)
		if(arg IN_LIST options OR arg IN_LIST single OR arg IN_LIST multi)
			if(arg IN_LIST seen)
				message(FATAL_ERROR "${where}: ${arg} given twice")
			endif()
			list(APPEND seen "${arg}")
		endif()
	endforeach()
	cmake_parse_arguments(ARG "${options}" "${single}" "${multi}" ${ARGN})
	if(ARG_UNPARSED_ARGUMENTS)
		message(FATAL_ERROR "${where}: unexpected arguments ${ARG_UNPARSED_ARGUMENTS}")
	endif()
	if(NOT name MATCHES "^[A-Za-z0-9][A-Za-z0-9_-]*$")
		message(FATAL_ERROR "${where}: invalid chunk name")
	endif()
	if(ARG_LEASE)
		if(ARG_TARGET OR ARG_JAVA OR ARG_JAVA_EXCLUDE OR ARG_DEPENDS OR ARG_PCH OR ARG_MAIN OR ARG_TESTS OR ARG_TEST_INCLUDES OR ARG_COMPILE_WHEN_EXISTS)
			message(FATAL_ERROR "${where}: a LEASE has only PHASE, ROOT, GLOBS, EXCLUDE, TEST_SUPPORT, OTHER_FILES and XMLGEN_SHELLS")
		endif()
	elseif(NOT ARG_TARGET)
		message(FATAL_ERROR "${where}: TARGET is required (or LEASE)")
	endif()
	if(NOT ARG_PHASE)
		message(FATAL_ERROR "${where}: PHASE is required")
	endif()
	if(NOT ARG_GLOBS AND NOT ARG_MAIN AND NOT (ARG_LEASE AND (ARG_TEST_SUPPORT OR ARG_OTHER_FILES)))
		message(FATAL_ERROR "${where}: GLOBS is required")
	endif()
	foreach(dir IN LISTS ARG_TESTS ARG_TEST_INCLUDES ARG_TEST_SUPPORT)
		if(NOT dir MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.-]*(/[A-Za-z0-9_][A-Za-z0-9_.-]*)*$")
			message(FATAL_ERROR "${where}: test directory '${dir}': a relative path below game-server/tests (letters, digits and _-./)")
		endif()
	endforeach()
	if(NOT ARG_ROOT)
		set(ARG_ROOT src)
	endif()
	get_property(roots GLOBAL PROPERTY AION_GS_CHUNK_ROOTS)
	foreach(root IN LISTS ARG_ROOT)
		if(NOT root IN_LIST roots)
			message(FATAL_ERROR "${where}: unknown ROOT ${root} (aion_gs_chunks_settings must come first)")
		endif()
	endforeach()
	foreach(glob IN LISTS ARG_OTHER_FILES)
		aion_gs_glob_to_regex(ignored "${glob}")
		string(REGEX REPLACE "/.*$" "" first "${glob}")
		if(first IN_LIST roots OR first STREQUAL "tests" OR glob MATCHES "(^|/)\\.\\.?(/|$)" OR glob MATCHES "(^/|//|/$)")
			message(FATAL_ERROR "${where}: OTHER_FILES glob '${glob}': a path below cpp/game-server outside the ROOTS and tests/")
		endif()
	endforeach()
	if(ARG_XMLGEN_SHELLS AND NOT ARG_ROOT STREQUAL "src")
		message(FATAL_ERROR "${where}: XMLGEN_SHELLS needs ROOT src")
	endif()
	list(LENGTH ARG_ROOT root_count)
	if(ARG_MAIN AND NOT root_count EQUAL 1)
		message(FATAL_ERROR "${where}: MAIN needs exactly one ROOT")
	endif()

	get_property(index GLOBAL PROPERTY AION_GS_CHUNK_PART_COUNT)
	if(NOT index)
		set(index 0)
	endif()
	math(EXPR next "${index} + 1")
	set_property(GLOBAL PROPERTY AION_GS_CHUNK_PART_COUNT ${next})
	set_property(GLOBAL PROPERTY AION_GS_CHUNK_${index}_NAME "${name}")
	foreach(key IN LISTS options single multi)
		set_property(GLOBAL PROPERTY AION_GS_CHUNK_${index}_${key} "${ARG_${key}}")
	endforeach()
endfunction()

# JSON string list ["a","b"] (the values contain no quotes or backslashes: globs and paths)
function(aion_gs_json_list out)
	set(items)
	foreach(value IN LISTS ARGN)
		list(APPEND items "\"${value}\"")
	endforeach()
	list(JOIN items "," joined)
	set(${out} "[${joined}]" PARENT_SCOPE)
endfunction()

# Lists at most 200 lines of a problem list for a configure message.
function(aion_gs_format_problems out)
	set(lines ${ARGN})
	list(LENGTH lines count)
	if(count GREATER 200)
		list(SUBLIST lines 0 200 lines)
		list(APPEND lines "... and more (${count} in total)")
	endif()
	list(JOIN lines "\n  " text)
	set(${out} "  ${text}" PARENT_SCOPE)
endfunction()

# Owner description of a file for problem messages ("P4-05 (aion_gs_base), P4-10 (aion_gs_world)"); leases are not owners.
function(aion_gs_describe_owners out file kind)
	get_property(count GLOBAL PROPERTY AION_GS_CHUNK_PART_COUNT)
	math(EXPR last "${count} - 1")
	set(owners)
	foreach(i RANGE ${last})
		get_property(files GLOBAL PROPERTY AION_GS_CHUNK_${i}_${kind})
		get_property(lease GLOBAL PROPERTY AION_GS_CHUNK_${i}_LEASE)
		if(file IN_LIST files AND NOT lease)
			get_property(name GLOBAL PROPERTY AION_GS_CHUNK_${i}_NAME)
			get_property(target GLOBAL PROPERTY AION_GS_CHUNK_${i}_TARGET)
			list(APPEND owners "${name} (${target})")
		endif()
	endforeach()
	list(JOIN owners ", " text)
	set(${out} "${text}" PARENT_SCOPE)
endfunction()

# Matches the files of every chunk part, runs the ownership checks and writes the chunks.json that tools read (also usable in script mode:
# tools/porting/tests run it with cmake -P to compare chunks.py with this implementation).
#   aion_gs_check_chunks(SOURCE_DIR <cpp/game-server> JAVA_DIR <game-server> JSON <file>)
# The unit test directories are below <SOURCE_DIR>/tests. Stores, for part i, the global properties AION_GS_CHUNK_<i>_FILES,
# AION_GS_CHUNK_<i>_JAVA_FILES and AION_GS_CHUNK_<i>_TESTS_DIR (the resolved test directory; empty for a lease).
function(aion_gs_check_chunks)
	cmake_parse_arguments(ARG "" "SOURCE_DIR;JAVA_DIR;JSON" "" ${ARGN})
	get_property(extensions GLOBAL PROPERTY AION_GS_CHUNK_EXTENSIONS)
	get_property(roots GLOBAL PROPERTY AION_GS_CHUNK_ROOTS)
	get_property(java_roots GLOBAL PROPERTY AION_GS_CHUNK_JAVA_ROOTS)
	get_property(count GLOBAL PROPERTY AION_GS_CHUNK_PART_COUNT)
	if(NOT count)
		message(FATAL_ERROR "aion_gs_check_chunks: no aion_gs_chunk() calls")
	endif()
	math(EXPR last "${count} - 1")

	# -- manifest rules across parts: leaf targets, test directories ----------------------------------------------------------------------------
	set(targets)
	foreach(i RANGE ${last})
		foreach(key IN ITEMS NAME TARGET DEPENDS)
			get_property(p_${key} GLOBAL PROPERTY AION_GS_CHUNK_${i}_${key})
		endforeach()
		if(p_TARGET)
			if(NOT p_TARGET IN_LIST targets)
				list(APPEND targets "${p_TARGET}")
				set(chunks_${p_TARGET})
				set(parts_${p_TARGET} 0)
				set(leaves_${p_TARGET} 0)
			endif()
			list(APPEND chunks_${p_TARGET} "${p_NAME}")
			math(EXPR parts_${p_TARGET} "${parts_${p_TARGET}} + 1")
			if(p_DEPENDS)
				math(EXPR leaves_${p_TARGET} "${leaves_${p_TARGET}} + 1")
			endif()
		endif()
	endforeach()
	foreach(target IN LISTS targets)
		if(leaves_${target} GREATER 0 AND NOT leaves_${target} EQUAL parts_${target})
			message(FATAL_ERROR "chunks.cmake: target ${target}: either all parts have DEPENDS (leaf) or none")
		endif()
		list(REMOVE_DUPLICATES chunks_${target})
	endforeach()

	# test directories owned by the non-lease parts: TESTS (default: the target without aion_gs_, plus /<chunk> for a target of several chunks)
	# and TEST_SUPPORT. Equal entries (the same chunk, target and kind) count once; any other two must not be equal or nested.
	set(test_keys)
	set(test_dirs)
	set(test_owners)
	foreach(i RANGE ${last})
		foreach(key IN ITEMS NAME TARGET LEASE TESTS TEST_SUPPORT)
			get_property(p_${key} GLOBAL PROPERTY AION_GS_CHUNK_${i}_${key})
		endforeach()
		set(tests_dir "")
		if(NOT p_LEASE)
			if(p_TESTS)
				set(tests_dir "${p_TESTS}")
			else()
				string(REGEX REPLACE "^aion_gs_" "" tests_dir "${p_TARGET}")
				list(LENGTH chunks_${p_TARGET} target_chunks)
				if(target_chunks GREATER 1)
					string(APPEND tests_dir "/${p_NAME}")
				endif()
			endif()
			set(keys "${tests_dir}|${p_NAME}|${p_TARGET}|TESTS")
			foreach(dir IN LISTS p_TEST_SUPPORT)
				list(APPEND keys "${dir}|${p_NAME}||TEST_SUPPORT")
			endforeach()
			foreach(key IN LISTS keys)
				if(NOT key IN_LIST test_keys)
					string(REGEX REPLACE "\\|.*$" "" dir "${key}")
					list(APPEND test_keys "${key}")
					list(APPEND test_dirs "${dir}")
					list(APPEND test_owners "${p_NAME} (${p_TARGET})")
				endif()
			endforeach()
		endif()
		set_property(GLOBAL PROPERTY AION_GS_CHUNK_${i}_TESTS_DIR "${tests_dir}")
	endforeach()
	list(LENGTH test_dirs test_dir_count)
	math(EXPR test_dir_last "${test_dir_count} - 2")
	set(overlaps)
	if(test_dir_count GREATER 1)
		foreach(a RANGE ${test_dir_last})
			math(EXPR b_first "${a} + 1")
			math(EXPR b_last "${test_dir_count} - 1")
			list(GET test_dirs ${a} dir_a)
			foreach(b RANGE ${b_first} ${b_last})
				list(GET test_dirs ${b} dir_b)
				string(FIND "${dir_a}/" "${dir_b}/" b_in_a)
				string(FIND "${dir_b}/" "${dir_a}/" a_in_b)
				if(b_in_a EQUAL 0 OR a_in_b EQUAL 0)
					list(GET test_owners ${a} owner_a)
					list(GET test_owners ${b} owner_b)
					list(APPEND overlaps "test directory tests/${dir_a} of ${owner_a} overlaps tests/${dir_b} of ${owner_b}")
				endif()
			endforeach()
		endforeach()
	endif()
	if(overlaps)
		list(JOIN overlaps "\n  " text)
		message(FATAL_ERROR "chunks.cmake: the test directories of different chunks or targets must not overlap:\n  ${text}")
	endif()

	# -- C++ files per root and below tests/ ----------------------------------------------------------------------------------------------------
	# Everything is globbed and filtered with case-sensitive expressions, so the result does not depend on the file system's case sensitivity.
	set(source_like ${extensions} c cc cxx cpp h hh hpp hxx inc inl ipp ixx tcc tpp)
	list(REMOVE_DUPLICATES source_like)
	set(any_case)
	foreach(ext IN LISTS source_like)
		set(pattern "")
		string(LENGTH "${ext}" length)
		math(EXPR char_last "${length} - 1")
		foreach(pos RANGE ${char_last})
			string(SUBSTRING "${ext}" ${pos} 1 char)
			string(TOUPPER "${char}" upper_char)
			if(char STREQUAL upper_char)
				string(APPEND pattern "${char}")
			else()
				string(APPEND pattern "[${upper_char}${char}]")
			endif()
		endforeach()
		list(APPEND any_case "${pattern}")
	endforeach()
	list(JOIN any_case "|" any_case)
	list(JOIN extensions "|" exact)
	set(extension_list ${extensions})
	list(TRANSFORM extension_list PREPEND ".")
	list(JOIN extension_list " " extension_list)
	set(all_files)
	set(test_files)
	set(extension_problems)
	foreach(top IN LISTS roots ITEMS tests)
		set(top_files)
		if(IS_DIRECTORY "${ARG_SOURCE_DIR}/${top}")
			if(CMAKE_SCRIPT_MODE_FILE)
				file(GLOB_RECURSE top_files LIST_DIRECTORIES false RELATIVE "${ARG_SOURCE_DIR}" "${ARG_SOURCE_DIR}/${top}/*")
			else()
				file(GLOB_RECURSE top_files CONFIGURE_DEPENDS LIST_DIRECTORIES false RELATIVE "${ARG_SOURCE_DIR}" "${ARG_SOURCE_DIR}/${top}/*")
			endif()
		endif()
		list(FILTER top_files INCLUDE REGEX "\\.(${any_case})$")
		set(wrong ${top_files})
		list(FILTER top_files INCLUDE REGEX "\\.(${exact})$")
		list(FILTER wrong EXCLUDE REGEX "\\.(${exact})$")
		foreach(file IN LISTS wrong)
			list(APPEND extension_problems "unexpected C++ file extension: ${file} (allowed: ${extension_list})")
		endforeach()
		list(SORT top_files)
		if(top STREQUAL "tests")
			set(test_files ${top_files})
		else()
			set(files_${top} ${top_files})
			list(APPEND all_files ${top_files})
		endif()
	endforeach()
	list(SORT extension_problems)

	# every C++ file below tests/ is in exactly one owned test directory (the directories do not overlap)
	set(test_owned)
	foreach(dir IN LISTS test_dirs)
		string(REPLACE "." "\\." dir_regex "${dir}")
		set(inside ${test_files})
		list(FILTER inside INCLUDE REGEX "^tests/${dir_regex}/")
		list(APPEND test_owned ${inside})
	endforeach()
	set(test_problems)
	set(unowned_tests ${test_files})
	if(test_owned)
		list(REMOVE_ITEM unowned_tests ${test_owned})
	endif()
	foreach(file IN LISTS unowned_tests)
		list(APPEND test_problems "no chunk owns test file ${file}")
	endforeach()

	# -- Java files -----------------------------------------------------------------------------------------------------------------------------
	set(java_files)
	aion_gs_globs_to_regex(java_root_regex "" ${java_roots})
	set(java_tops)
	foreach(glob IN LISTS java_roots)
		string(REGEX REPLACE "/.*" "" top "${glob}")
		list(APPEND java_tops "${top}")
	endforeach()
	list(REMOVE_DUPLICATES java_tops)
	foreach(top IN LISTS java_tops)
		if(IS_DIRECTORY "${ARG_JAVA_DIR}/${top}")
			file(GLOB_RECURSE top_files LIST_DIRECTORIES false RELATIVE "${ARG_JAVA_DIR}" "${ARG_JAVA_DIR}/${top}/*.java")
			list(APPEND java_files ${top_files})
		endif()
	endforeach()
	list(FILTER java_files INCLUDE REGEX "${java_root_regex}")
	list(SORT java_files)

	# -- matching -------------------------------------------------------------------------------------------------------------------------------
	set(claimed)
	set(java_claimed)
	foreach(i RANGE ${last})
		foreach(key IN ITEMS NAME LEASE XMLGEN_SHELLS ROOT GLOBS EXCLUDE JAVA JAVA_EXCLUDE MAIN)
			get_property(p_${key} GLOBAL PROPERTY AION_GS_CHUNK_${i}_${key})
		endforeach()
		set(candidates)
		foreach(root IN LISTS p_ROOT)
			list(APPEND candidates ${files_${root}})
		endforeach()
		set(matched)
		if(p_GLOBS AND candidates)
			aion_gs_globs_to_regex(include_regex "${p_ROOT}" ${p_GLOBS})
			set(matched ${candidates})
			list(FILTER matched INCLUDE REGEX "${include_regex}")
			if(p_EXCLUDE AND matched)
				aion_gs_globs_to_regex(exclude_regex "${p_ROOT}" ${p_EXCLUDE})
				list(FILTER matched EXCLUDE REGEX "${exclude_regex}")
			endif()
		endif()
		if(p_MAIN AND "${p_ROOT}/${p_MAIN}" IN_LIST candidates AND NOT "${p_ROOT}/${p_MAIN}" IN_LIST matched)
			list(APPEND matched "${p_ROOT}/${p_MAIN}")
		endif()
		if(p_XMLGEN_SHELLS)
			set(shells)
			foreach(file IN LISTS matched)
				string(REGEX REPLACE "^src/(.*)\\.[^./]+$" "generated/\\1.xml.inc" counterpart "${file}")
				if(counterpart IN_LIST files_generated)
					list(APPEND shells "${file}")
				endif()
			endforeach()
			set(matched ${shells})
		endif()
		set_property(GLOBAL PROPERTY AION_GS_CHUNK_${i}_FILES ${matched})
		if(NOT p_LEASE)
			list(APPEND claimed ${matched})
		endif()

		set(java_matched)
		if(p_JAVA AND java_files)
			aion_gs_globs_to_regex(java_regex "" ${p_JAVA})
			set(java_matched ${java_files})
			list(FILTER java_matched INCLUDE REGEX "${java_regex}")
			if(p_JAVA_EXCLUDE AND java_matched)
				aion_gs_globs_to_regex(java_exclude_regex "" ${p_JAVA_EXCLUDE})
				list(FILTER java_matched EXCLUDE REGEX "${java_exclude_regex}")
			endif()
		endif()
		set_property(GLOBAL PROPERTY AION_GS_CHUNK_${i}_JAVA_FILES ${java_matched})
		list(APPEND java_claimed ${java_matched})
	endforeach()

	# -- exactly one owner / claim --------------------------------------------------------------------------------------------------------------
	foreach(kind IN ITEMS FILES JAVA_FILES)
		if(kind STREQUAL "FILES")
			set(universe ${all_files})
			set(taken ${claimed})
			set(problems ${extension_problems})
		else()
			set(universe ${java_files})
			set(taken ${java_claimed})
			set(problems)
		endif()
		set(unique ${taken})
		list(REMOVE_DUPLICATES unique)
		set(unowned ${universe})
		if(unique)
			list(REMOVE_ITEM unowned ${unique})
		endif()
		foreach(file IN LISTS unowned)
			if(kind STREQUAL "FILES")
				list(APPEND problems "no chunk owns ${file}")
			else()
				list(APPEND problems "no chunk claims Java file ${file}")
			endif()
		endforeach()
		list(LENGTH taken taken_count)
		list(LENGTH unique unique_count)
		if(NOT taken_count EQUAL unique_count)
			list(SORT taken)
			set(previous "")
			set(duplicates)
			foreach(file IN LISTS taken)
				if(file STREQUAL previous)
					list(APPEND duplicates "${file}")
				endif()
				set(previous "${file}")
			endforeach()
			list(REMOVE_DUPLICATES duplicates)
			foreach(file IN LISTS duplicates)
				aion_gs_describe_owners(owners "${file}" ${kind})
				if(kind STREQUAL "FILES")
					list(APPEND problems "several chunks own ${file}: ${owners}")
				else()
					list(APPEND problems "several chunks claim Java file ${file}: ${owners}")
				endif()
			endforeach()
		endif()
		if(kind STREQUAL "FILES")
			set(cpp_problems ${problems} ${test_problems})
		else()
			set(java_problems ${problems})
		endif()
	endforeach()
	# one message with every problem, so a broken manifest is fixed in one round
	set(hint "Fix cpp/game-server/chunks.cmake (python tools/porting/chunks.py owner <path> shows the matching parts).")
	set(java_text "")
	if(java_problems)
		aion_gs_format_problems(java_text ${java_problems})
		set(java_text "Every Java file must be claimed by exactly one chunk:\n${java_text}\n")
	endif()
	if(cpp_problems)
		aion_gs_format_problems(text ${cpp_problems})
		message(FATAL_ERROR "Chunk ownership check failed: every C++ file below ${roots} must match exactly one chunk, every C++ file below tests/ "
			"must lie in one chunk's test directory.\n${text}\n${java_text}${hint}")
	elseif(java_problems AND "${AION_GS_JAVA_CLAIMS}" STREQUAL "WARNING")
		message(WARNING "Chunk Java claims: ${java_text}${hint}")
	elseif(java_problems)
		message(FATAL_ERROR "Chunk Java claims check failed: ${java_text}${hint}")
	endif()
	list(LENGTH all_files file_count)
	list(LENGTH java_files java_count)
	list(LENGTH test_files test_file_count)

	# -- chunks.json ----------------------------------------------------------------------------------------------------------------------------
	set(json "{\n\"format\": \"aion-chunks\",\n\"version\": 1,\n\"sourceDir\": \"${ARG_SOURCE_DIR}\",\n\"javaDir\": \"${ARG_JAVA_DIR}\",\n")
	aion_gs_json_list(j_roots ${roots})
	string(APPEND json "\"roots\": ${j_roots},\n\"fileCount\": ${file_count},\n\"javaFileCount\": ${java_count},\n\"testFileCount\": ${test_file_count},\n"
		"\"parts\": [\n")
	foreach(i RANGE ${last})
		foreach(key IN ITEMS NAME TARGET PHASE LEASE XMLGEN_SHELLS ROOT GLOBS EXCLUDE JAVA JAVA_EXCLUDE DEPENDS PCH TESTS_DIR TEST_SUPPORT MAIN
				COMPILE_WHEN_EXISTS FILES JAVA_FILES OTHER_FILES)
			get_property(p_${key} GLOBAL PROPERTY AION_GS_CHUNK_${i}_${key})
		endforeach()
		foreach(key IN ITEMS ROOT GLOBS EXCLUDE JAVA JAVA_EXCLUDE DEPENDS PCH TEST_SUPPORT FILES JAVA_FILES OTHER_FILES)
			aion_gs_json_list(j_${key} ${p_${key}})
		endforeach()
		set(lease false)
		if(p_LEASE)
			set(lease true)
		endif()
		set(shells false)
		if(p_XMLGEN_SHELLS)
			set(shells true)
		endif()
		string(APPEND json "{\"name\": \"${p_NAME}\", \"target\": \"${p_TARGET}\", \"phase\": \"${p_PHASE}\", \"lease\": ${lease}, "
			"\"xmlgenShells\": ${shells}, \"roots\": ${j_ROOT}, \"globs\": ${j_GLOBS}, \"exclude\": ${j_EXCLUDE}, \"java\": ${j_JAVA}, "
			"\"javaExclude\": ${j_JAVA_EXCLUDE}, \"depends\": ${j_DEPENDS}, \"pch\": ${j_PCH}, \"tests\": \"${p_TESTS_DIR}\", "
			"\"testSupport\": ${j_TEST_SUPPORT}, \"otherFiles\": ${j_OTHER_FILES}, \"main\": \"${p_MAIN}\", \"compileWhenExists\": \"${p_COMPILE_WHEN_EXISTS}\",\n \"files\": ${j_FILES},\n "
			"\"javaFiles\": ${j_JAVA_FILES}}")
		if(i LESS last)
			string(APPEND json ",")
		endif()
		string(APPEND json "\n")
	endforeach()
	string(APPEND json "]\n}\n")
	file(CONFIGURE OUTPUT "${ARG_JSON}" CONTENT "${json}" @ONLY)

	message(STATUS "Game server chunks: ${count} parts, ${file_count} C++ files, ${test_file_count} test files and ${java_count} Java files owned exactly once")
endfunction()

# Unity groups of a handler library's .cpp files, stable when files are added (handlers-and-porting-plan.md §1.11: batches are grouped by
# directory, so an edit or a new file rebuilds only its own batch). Every C++ file ports one Java file at the mirrored path
# (handlers/aion/gameserver/handlers/<dir>/X.cpp <- data/handlers/<dir>/X.java), and the Java directories are fixed: a file's group is its
# directory plus (index of the last Java file name <= its own name in the sorted Java names of that directory) / BATCH. So groups fill up to
# BATCH files in Java order, and adding a file never moves another one. A directory without Java files is one group.
#   aion_gs_handler_unity_groups(<out> [BATCH <n>] JAVA <path below the Java game-server dir>... SOURCES <handlers/... .cpp path>...)
# Sets <out> to a list of "<source>|<group>" (group: a C identifier); sources outside handlers/aion/gameserver/handlers/ are left out.
function(aion_gs_handler_unity_groups out)
	cmake_parse_arguments(ARG "" "BATCH" "JAVA;SOURCES" ${ARGN})
	if(NOT ARG_BATCH)
		set(ARG_BATCH 16)
	endif()
	set(dirs)
	foreach(java IN LISTS ARG_JAVA)
		if(java MATCHES "^data/handlers/(.*/)?([^/]+)\\.java$")
			list(APPEND "stems_${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
			list(APPEND dirs "${CMAKE_MATCH_1}")
		endif()
	endforeach()
	list(REMOVE_DUPLICATES dirs)
	foreach(dir IN LISTS dirs)
		list(SORT "stems_${dir}")
	endforeach()
	set(result)
	foreach(source IN LISTS ARG_SOURCES)
		if(NOT source MATCHES "^handlers/aion/gameserver/handlers/(.*/)?([^/]+)\\.cpp$")
			continue()
		endif()
		set(dir "${CMAKE_MATCH_1}")
		set(stem "${CMAKE_MATCH_2}")
		set(position 0)
		foreach(java_stem IN LISTS "stems_${dir}")
			if(java_stem STRGREATER stem)
				break()
			endif()
			math(EXPR position "${position} + 1")
		endforeach()
		if(position GREATER 0)
			math(EXPR position "${position} - 1")
		endif()
		math(EXPR batch "${position} / ${ARG_BATCH}")
		string(REGEX REPLACE "/$" "" name "${dir}")
		string(MAKE_C_IDENTIFIER "handlers/${name}_${batch}" group)
		list(APPEND result "${source}|${group}")
	endforeach()
	set(${out} ${result} PARENT_SCOPE)
endfunction()

# Runs aion_gs_check_chunks and creates the chunk libraries, aion_gs_core_deps, aion_gs_core, aion_gs_handlers and the chunk unit tests.
#   aion_gs_finalize_chunks(SOURCE_DIR <cpp/game-server> JAVA_DIR <game-server> JSON <file> [REGISTRY_EMPTY <target>])
# The unit test directories are below <SOURCE_DIR>/tests. Sets AION_GS_CHUNK_TARGETS, AION_GS_CORE_TARGETS, AION_GS_HANDLER_TARGETS,
# AION_GS_LEAF_TARGETS and AION_GS_MAIN_SOURCES in the caller's scope.
function(aion_gs_finalize_chunks)
	cmake_parse_arguments(ARG "" "SOURCE_DIR;JAVA_DIR;JSON;REGISTRY_EMPTY" "" ${ARGN})
	if(ARG_UNPARSED_ARGUMENTS)
		message(FATAL_ERROR "aion_gs_finalize_chunks: unknown arguments ${ARG_UNPARSED_ARGUMENTS}")
	endif()
	aion_gs_check_chunks(SOURCE_DIR "${ARG_SOURCE_DIR}" JAVA_DIR "${ARG_JAVA_DIR}" JSON "${ARG_JSON}")
	get_property(count GLOBAL PROPERTY AION_GS_CHUNK_PART_COUNT)
	math(EXPR last "${count} - 1")
	set(tests_root "${ARG_SOURCE_DIR}/tests")

	# -- targets --------------------------------------------------------------------------------------------------------------------------------
	set(targets)
	foreach(i RANGE ${last})
		get_property(target GLOBAL PROPERTY AION_GS_CHUNK_${i}_TARGET)
		if(target)
			list(APPEND targets "${target}")
			set_property(GLOBAL APPEND PROPERTY AION_GS_CHUNK_TARGET_${target}_PARTS ${i})
		endif()
	endforeach()
	list(REMOVE_DUPLICATES targets)

	set(core_targets)
	set(handler_targets)
	set(leaf_targets)
	set(main_sources)
	foreach(target IN LISTS targets)
		get_property(parts GLOBAL PROPERTY AION_GS_CHUNK_TARGET_${target}_PARTS)
		set(sources)
		set(deferred)
		set(depends)
		set(pch)
		set(target_roots)
		set(target_java)
		set(tests_dirs)
		set(test_includes)
		set(leaf 0)
		foreach(i IN LISTS parts)
			foreach(key IN ITEMS FILES JAVA_FILES ROOT DEPENDS PCH TESTS_DIR TEST_INCLUDES MAIN COMPILE_WHEN_EXISTS)
				get_property(p_${key} GLOBAL PROPERTY AION_GS_CHUNK_${i}_${key})
			endforeach()
			set(main_file "")
			if(p_MAIN)
				set(main_file "${p_ROOT}/${p_MAIN}")
				if(main_file IN_LIST p_FILES)
					list(APPEND main_sources "${ARG_SOURCE_DIR}/${main_file}")
				endif()
			endif()
			foreach(file IN LISTS p_FILES)
				if(NOT file STREQUAL main_file)
					list(APPEND sources "${file}")
					if(p_COMPILE_WHEN_EXISTS AND NOT EXISTS "${ARG_SOURCE_DIR}/${p_ROOT}/${p_COMPILE_WHEN_EXISTS}" AND file MATCHES "\\.cpp$")
						list(APPEND deferred "${file}")
					endif()
				endif()
			endforeach()
			list(APPEND target_java ${p_JAVA_FILES})
			list(APPEND depends ${p_DEPENDS})
			list(APPEND pch ${p_PCH})
			list(APPEND target_roots ${p_ROOT})
			list(APPEND test_includes ${p_TEST_INCLUDES})
			if(IS_DIRECTORY "${tests_root}/${p_TESTS_DIR}")
				list(APPEND tests_dirs "${tests_root}/${p_TESTS_DIR}")
			endif()
			if(p_DEPENDS)
				set(leaf 1) # aion_gs_check_chunks checked that all parts of the target have DEPENDS
			endif()
		endforeach()
		list(REMOVE_DUPLICATES target_roots)
		list(REMOVE_DUPLICATES depends)
		list(REMOVE_DUPLICATES pch)
		list(REMOVE_DUPLICATES tests_dirs)
		list(REMOVE_DUPLICATES test_includes)
		set(handler_target OFF)
		if("handlers" IN_LIST target_roots)
			set(handler_target ON)
		endif()

		set(compiled ${sources})
		list(FILTER compiled INCLUDE REGEX "\\.cpp$")
		if(deferred)
			list(REMOVE_ITEM compiled ${deferred})
			list(TRANSFORM deferred PREPEND "${ARG_SOURCE_DIR}/")
			set_source_files_properties(${deferred} PROPERTIES HEADER_FILE_ONLY ON)
		endif()
		if(handler_target AND AION_HANDLER_UNITY AND compiled)
			aion_gs_handler_unity_groups(groups JAVA ${target_java} SOURCES ${compiled})
			foreach(entry IN LISTS groups)
				string(REGEX MATCH "^(.*)\\|([^|]*)$" entry "${entry}")
				set_source_files_properties("${ARG_SOURCE_DIR}/${CMAKE_MATCH_1}" PROPERTIES UNITY_GROUP "${CMAKE_MATCH_2}")
			endforeach()
		endif()
		list(TRANSFORM sources PREPEND "${ARG_SOURCE_DIR}/")
		if(sources)
			source_group(TREE "${ARG_SOURCE_DIR}" FILES ${sources})
		endif()
		if(NOT compiled)
			set(placeholder "${CMAKE_CURRENT_BINARY_DIR}/chunk_placeholders/${target}_placeholder.cpp")
			file(CONFIGURE OUTPUT "${placeholder}" CONTENT "// placeholder for ${target}, which has no compiled sources yet\n")
			list(APPEND sources "${placeholder}")
		endif()
		add_library(${target} STATIC ${sources})
		# no C++ modules in the port; equal file names in different directories would otherwise make MSBuild's module scan warn (MSB8074)
		set_target_properties(${target} PROPERTIES CXX_SCAN_FOR_MODULES OFF)
		if(pch)
			list(TRANSFORM pch REPLACE "^(.+)$" "<\\1>") # include paths (searched in the include directories), not paths relative to this directory
			target_precompile_headers(${target} PRIVATE ${pch})
		endif()
		if(leaf)
			target_link_libraries(${target} PUBLIC ${depends} aion_gs_build_options aion::compiler_options)
			list(APPEND leaf_targets ${target})
		else()
			target_link_libraries(${target} PUBLIC aion_gs_core_deps)
		endif()
		if(handler_target)
			target_include_directories(${target} PUBLIC "${ARG_SOURCE_DIR}/handlers")
			if(AION_HANDLER_UNITY)
				# groups from aion_gs_handler_unity_groups (at most 16 files, stable when files are added); files without a group compile alone
				set_target_properties(${target} PROPERTIES UNITY_BUILD ON UNITY_BUILD_MODE GROUP)
			endif()
			list(APPEND handler_targets ${target})
		else()
			list(APPEND core_targets ${target})
		endif()

		if(tests_dirs)
			if(leaf)
				set(test_depends ${target} aion_gs_build_options)
			elseif(handler_target)
				set(test_depends aion_gs_core ${target} ${ARG_REGISTRY_EMPTY})
			else()
				set(test_depends aion_gs_core ${ARG_REGISTRY_EMPTY})
			endif()
			list(POP_FRONT tests_dirs first_tests_dir)
			aion_add_tests(${target}_tests "${first_tests_dir}" EXTRA_DIRS ${tests_dirs} DEPENDS ${test_depends})
			if(TARGET ${target}_tests)
				foreach(dir IN LISTS test_includes)
					target_include_directories(${target}_tests PRIVATE "${tests_root}/${dir}")
				endforeach()
			endif()
		endif()
	endforeach()

	add_library(aion_gs_core_deps INTERFACE)
	target_link_libraries(aion_gs_core_deps INTERFACE ${leaf_targets} aion::commons aion_gs_build_options aion::compiler_options)
	add_library(aion_gs_core INTERFACE)
	target_link_libraries(aion_gs_core INTERFACE ${core_targets} aion_gs_core_deps)
	add_library(aion_gs_handlers INTERFACE)
	target_link_libraries(aion_gs_handlers INTERFACE ${handler_targets})

	list(LENGTH targets target_count)
	message(STATUS "Game server chunk libraries: ${target_count}")
	set(AION_GS_CHUNK_TARGETS ${targets} PARENT_SCOPE)
	set(AION_GS_CORE_TARGETS ${core_targets} PARENT_SCOPE)
	set(AION_GS_HANDLER_TARGETS ${handler_targets} PARENT_SCOPE)
	set(AION_GS_LEAF_TARGETS ${leaf_targets} PARENT_SCOPE)
	set(AION_GS_MAIN_SOURCES ${main_sources} PARENT_SCOPE)
endfunction()

# aion_gs_header_check(<target> HEADERS <include path>... [INCLUDE_DIRECTORIES <dir>...] LINK <target>...)
# One generated translation unit per header, containing only `#include "<header>"`, compiled with /W4 /WX: proves that each header is
# self-contained (handlers-and-porting-plan.md §2.5, §3.1 item 7). Headers are include paths relative to the include roots.
function(aion_gs_header_check target)
	cmake_parse_arguments(ARG "" "" "HEADERS;INCLUDE_DIRECTORIES;LINK" ${ARGN})
	set(dir "${CMAKE_CURRENT_BINARY_DIR}/${target}")
	set(sources)
	foreach(header IN LISTS ARG_HEADERS)
		string(REGEX REPLACE "[/.]" "_" stem "${header}")
		set(tu "${dir}/${stem}.cpp")
		if(NOT EXISTS "${tu}") # the content depends only on the file name
			file(WRITE "${tu}" "// generated by aion_gs_header_check: ${header} must compile on its own\n#include \"${header}\"\n")
		endif()
		list(APPEND sources "${tu}")
	endforeach()
	add_library(${target} OBJECT ${sources})
	set_target_properties(${target} PROPERTIES CXX_SCAN_FOR_MODULES OFF)
	target_include_directories(${target} PRIVATE ${ARG_INCLUDE_DIRECTORIES})
	target_link_libraries(${target} PRIVATE ${ARG_LINK})
	if(MSVC)
		target_compile_options(${target} PRIVATE /WX)
	else()
		target_compile_options(${target} PRIVATE -Werror)
	endif()
endfunction()
