#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::tiamat_stronghold {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/tiamat_stronghold/_30758SuramaTheBitter.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * 1. Step: Talk to Surama.
 * 2. Step: Rescue 5 Captured Drakan Scientists.
 * 3. Step: Kill Brigade General Laksyaka
 * 4. Step: Talk to Murugan The Loyal.
 *
 * Second step is currently handled by {@link ai.instance.tiamatStrongHold.CapturedDrakanScientistAI}.
 *
 * @author Estrayl
 */
class _30758SuramaTheBitter final : public AbstractQuestHandler {
private:
	static constexpr int32_t START_NPC_ID = 800369; // Surama
	static constexpr int32_t END_NPC_ID = 800438; // Murugan the Loyal
	static constexpr int32_t TARGET_TO_KILL = 219356; // Brigade General Laksyaka

public:
	_30758SuramaTheBitter() : AbstractQuestHandler(30758) {}

	void register_() override {
		qe.registerQuestNpc(TARGET_TO_KILL)->addOnKillEvent(questId);
		qe.registerQuestNpc(START_NPC_ID)->addOnQuestStart(questId);
		qe.registerQuestNpc(END_NPC_ID)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<QuestState> qs = env.getPlayer()->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == START_NPC_ID) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == END_NPC_ID) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 10002);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		if (env.getTargetId() == TARGET_TO_KILL && qs->getQuestVarById(0) == 5) {
			qs->setStatus(QuestStatus::REWARD);
			updateQuestStatus(env);
			return true;
		}
		return false;
	}
};
AION_QUEST_HANDLER(_30758SuramaTheBitter, 30758);

} // namespace aion::gameserver::handlers::quest::tiamat_stronghold
