#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::miragent_holy_templar {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/miragent_holy_templar/_19064TemplarOfConstruction.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _19064TemplarOfConstruction final : public AbstractQuestHandler {
public:
	_19064TemplarOfConstruction() : AbstractQuestHandler(19064) {}

	void register_() override {
		std::array<int32_t, 3> npcs{203701, 798450, 203752};
		qe.registerQuestNpc(203701)->addOnQuestStart(questId);
		for (int32_t npc : npcs)
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203701) {
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 798450:
					switch (dialogActionId) {
						case QUEST_SELECT:
							return sendQuestDialog(env, 1352);
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
					}
					break;
				case 203752:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1 && player->getInventory().getItemCountByItemId(182213237) >= 1 && player->getInventory().getItemCountByItemId(186000081) >= 1) {
								return sendQuestDialog(env, 2375);
							}
							return false;
						case CHECK_USER_HAS_QUEST_ITEM_SIMPLE:
							if (player->getInventory().getItemCountByItemId(182213237) >= 1 && player->getInventory().getItemCountByItemId(186000081) >= 1) {
								removeQuestItem(env, 182213237, 1);
								removeQuestItem(env, 186000081, 1);
								return defaultCloseDialog(env, 1, 1, true, false);
							}
					}
					break;
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203701) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 5);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_19064TemplarOfConstruction, 19064);

} // namespace aion::gameserver::handlers::quest::miragent_holy_templar
