#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::miragent_holy_templar {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/miragent_holy_templar/_3936DecorationsOfSanctum.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Nanou, Gigi
 */
class _3936DecorationsOfSanctum final : public AbstractQuestHandler {
public:
	_3936DecorationsOfSanctum() : AbstractQuestHandler(3936) {}

	void register_() override {
		qe.registerQuestNpc(203710)->addOnQuestStart(questId); // Dairos
		qe.registerQuestNpc(203710)->addOnTalkEvent(questId); // Dairos
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		// Start to Dairos
		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203710) {
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				// 1 - Report the result to Dairos.
				case 203710:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							else if (var == 1)
								return sendQuestDialog(env, 1352);
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
						case CHECK_USER_HAS_QUEST_ITEM: {
							int64_t itemCount1 = player->getInventory().getItemCountByItemId(182206091);
							int64_t itemCount2 = player->getInventory().getItemCountByItemId(182206092);
							int64_t itemCount3 = player->getInventory().getItemCountByItemId(182206093);
							int64_t itemCount4 = player->getInventory().getItemCountByItemId(182206094);
							if (itemCount1 >= 10 && itemCount2 >= 10 && itemCount3 >= 10 && itemCount4 >= 10) {
								removeQuestItem(env, 182206091, 10);
								removeQuestItem(env, 182206092, 10);
								removeQuestItem(env, 182206093, 10);
								removeQuestItem(env, 182206094, 10);
								changeQuestStep(env, 1, 1, true);
								return sendQuestDialog(env, 5);
							} else
								return sendQuestDialog(env, 10001);
						}
					}
					break;
				// No match
				default:
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203710)
				return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_3936DecorationsOfSanctum, 3936);

} // namespace aion::gameserver::handlers::quest::miragent_holy_templar
