#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::aturam_sky_fortress {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/aturam_sky_fortress/_28300FloatingDoom.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author zhkchi, Pad
 */
class _28300FloatingDoom final : public AbstractQuestHandler {
public:
	_28300FloatingDoom() : AbstractQuestHandler(28300) {}

	void register_() override {
		qe.registerQuestNpc(804719)->addOnQuestStart(questId);
		qe.registerQuestNpc(804719)->addOnTalkEvent(questId);
		qe.registerQuestNpc(804821)->addOnTalkEvent(questId);
		qe.registerQuestNpc(799530)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 804719) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 4762);
					default:
						return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 0) {
			if (targetId == 804821) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case SELECT1_1_1:
						return sendQuestDialog(env, 1013);
					case SETPRO1:
						qs->setQuestVarById(0, 1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return closeDialogWindow(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799530) {
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 10002);
					case SELECT_QUEST_REWARD:
						return sendQuestDialog(env, 5);
					default:
						return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_28300FloatingDoom, 28300);

} // namespace aion::gameserver::handlers::quest::aturam_sky_fortress
