#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::aturam_sky_fortress {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/aturam_sky_fortress/_28301PowerOn.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author zhkchi, Pad
 */
class _28301PowerOn final : public AbstractQuestHandler {
private:
	static constexpr int32_t sphereId = 702656;

public:
	_28301PowerOn() : AbstractQuestHandler(28301) {}

	void register_() override {
		qe.registerQuestNpc(799530)->addOnQuestStart(questId);
		qe.registerQuestNpc(799530)->addOnTalkEvent(questId);
		qe.registerQuestNpc(730374)->addOnTalkEvent(questId);
		qe.registerQuestNpc(sphereId)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 799530) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else if (dialogActionId == QUEST_ACCEPT_1) {
					playQuestMovie(env, 468);
					return sendQuestStartDialog(env);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 730374 && qs->getQuestVarById(0) == 7) {
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 1352);
					case SETPRO2:
						giveQuestItem(env, 182212110, 1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return closeDialogWindow(env);
					default:
						return sendQuestEndDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 799530) {
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 10002);
					case SELECT_QUEST_REWARD:
						return sendQuestDialog(env, 5);
					default:
						return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();

		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var0 = qs->getQuestVarById(0);
			if (var0 <= 6 && targetId == sphereId) {
				qs->setQuestVarById(0, var0 + 1);
				updateQuestStatus(env);
				return true;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_28301PowerOn, 28301);

} // namespace aion::gameserver::handlers::quest::aturam_sky_fortress
