#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/teleport/TeleportService.h"

namespace aion::gameserver::handlers::quest::reshanta {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/reshanta/_14044ShardsOfMemory.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Majka
 */
class _14044ShardsOfMemory final : public AbstractQuestHandler {
public:
	_14044ShardsOfMemory() : AbstractQuestHandler(14044) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(279029)->addOnTalkEvent(questId);
		qe.registerQuestNpc(278501)->addOnTalkEvent(questId);
		qe.registerQuestNpc(790001)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700355)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 278501:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							return false;
						case SETPRO1:
							if (var == 0) {
								changeQuestStep(env, 0, 1);
								TeleportService::teleportTo(*player, 210010000, 244.09f, 1638.28f, 100.38f, static_cast<int8_t>(52), TeleportAnimation::FADE_OUT_BEAM);
								return true;
							}
					}
					break;
				case 279029:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 2)
								return sendQuestDialog(env, 1693);
							return false;
						case SETPRO3:
							if (var == 2) {
								qs->setQuestVarById(0, var + 1);
								updateQuestStatus(env);
								playQuestMovie(env, 271);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 0));
								return true;
							}
					}
					break;
				case 700355:
					if (var == 3) {
						if (checkItemExistence(env, 188020000, 1, true))
							return useQuestObject(env, 3, 3, true, false);
						PacketSendUtility::sendMonologue(*player, 1111203); // I need an Artifact Activation Stone!
					}
					break;
				case 790001:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 1)
								return sendQuestDialog(env, 1352);
							return false;
						case SETPRO2:
							if (var == 1) {
								changeQuestStep(env, 1, 2);
								TeleportService::teleportTo(*player, 400010000, 2929.65f, 964.836f, 1538.17f, static_cast<int8_t>(43), TeleportAnimation::FADE_OUT_BEAM);
								return true;
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 279029) {
				if (env.getDialogActionId() == USE_OBJECT)
					return sendQuestDialog(env, 10002);
				else if (env.getDialogActionId() == SELECT_QUEST_REWARD)
					return sendQuestDialog(env, 5);
				else
					return sendQuestEndDialog(env);
			}
			return false;
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {14040});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {14040});
	}
};
AION_QUEST_HANDLER(_14044ShardsOfMemory, 14044);

} // namespace aion::gameserver::handlers::quest::reshanta
