#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::reshanta {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/reshanta/_1705Defeat6thRankAsmodianSoldiers.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Hilgert, vlog
 */
class _1705Defeat6thRankAsmodianSoldiers final : public AbstractQuestHandler {
public:
	_1705Defeat6thRankAsmodianSoldiers() : AbstractQuestHandler(1705) {}

	void register_() override {
		qe.registerQuestNpc(278503)->addOnQuestStart(questId);
		qe.registerQuestNpc(278503)->addOnTalkEvent(questId);
		qe.registerOnKillRanked(AbyssRankEnum::GRADE6_SOLDIER, questId);
	}

	bool onKillRankedEvent(QuestEnv& env) override {
		return defaultOnKillRankedEvent(env, 0, 10, true); // reward
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (env.getTargetId() == 278503) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			} else if (qs->getStatus() == QuestStatus::REWARD) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1705Defeat6thRankAsmodianSoldiers, 1705);

} // namespace aion::gameserver::handlers::quest::reshanta
