#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::reshanta {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/reshanta/_1725CenturionsForgetfulness.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Hilgert
 */
class _1725CenturionsForgetfulness final : public AbstractQuestHandler {
public:
	_1725CenturionsForgetfulness() : AbstractQuestHandler(1725) {}

	void register_() override {
		qe.registerQuestNpc(278520)->addOnQuestStart(questId);
		qe.registerQuestNpc(278520)->addOnTalkEvent(questId);
		qe.registerQuestNpc(278514)->addOnTalkEvent(questId);
		qe.registerQuestNpc(278590)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 278520) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else if (env.getDialogActionId() == QUEST_ACCEPT_1) {
					if (QuestService::startQuest(env)) {
						if (giveQuestItem(env, 182202153, 1))
							return sendQuestDialog(env, 1003);
						else
							return true;
					}
				} else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 278514) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else if (env.getDialogActionId() == SETPRO1) {
					qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
					updateQuestStatus(env);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				}
			} else if (targetId == 278590) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 2375);
				else if (env.getDialogActionId() == SELECT_QUEST_REWARD) {
					removeQuestItem(env, 182202153, 1);
					qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return sendQuestEndDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD && targetId == 278590) {
			return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1725CenturionsForgetfulness, 1725);

} // namespace aion::gameserver::handlers::quest::reshanta
