#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::reshanta {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/reshanta/_2719ChallengeElyosOfficers.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * Fight and defeat Elyos Officers.(10) Report back to Votan (278001).
 *
 * @author vlog
 */
class _2719ChallengeElyosOfficers final : public AbstractQuestHandler {
private:
	static constexpr int32_t _questId = 2719;

public:
	_2719ChallengeElyosOfficers() : AbstractQuestHandler(_questId) {}

	void register_() override {
		qe.registerQuestNpc(278001)->addOnTalkEvent(_questId);
		qe.registerQuestNpc(278001)->addOnQuestStart(_questId);
		qe.registerOnKillRanked(AbyssRankEnum::STAR1_OFFICER, _questId);
	}

	bool onKillRankedEvent(QuestEnv& env) override {
		return defaultOnKillRankedEvent(env, 0, 10, true); // reward
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(_questId);

		if (env.getTargetId() == 278001) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			} else if (qs->getStatus() == QuestStatus::REWARD) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2719ChallengeElyosOfficers, 2719);

} // namespace aion::gameserver::handlers::quest::reshanta
