#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::reshanta {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/reshanta/_2758CarryTheFlame.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _2758CarryTheFlame final : public AbstractQuestHandler {
public:
	_2758CarryTheFlame() : AbstractQuestHandler(2758) {}

	void register_() override {
		qe.registerQuestNpc(279000)->addOnQuestStart(questId);
		qe.registerQuestNpc(790016)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 279000) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 279000) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				}
				if (env.getDialogActionId() == SETPRO1) {
					giveQuestItem(env, 182205645, 1);
					QuestService::questTimerStart(env, 900);
					return defaultCloseDialog(env, 0, 1);
				}
			} else if (targetId == 790016) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 1352);
				} else if (env.getDialogActionId() == SET_SUCCEED) {
					QuestService::questTimerEnd(env);
					removeQuestItem(env, 182205645, 1);
					qs->setStatus(QuestStatus::REWARD);
					qs->setQuestVar(1);
					updateQuestStatus(env);
					return sendQuestDialog(env, 5);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 790016) {
				if (env.getDialogActionId() == USE_OBJECT) {
					return sendQuestDialog(env, 5);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onQuestTimerEndEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (var > 1) {
				removeQuestItem(env, 182205645, 1);
				changeQuestStep(env, var, 0);
				return true;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2758CarryTheFlame, 2758);

} // namespace aion::gameserver::handlers::quest::reshanta
