// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.services.event - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::services::event {

class Event;
class EventBuffHandler;
class EventService;

// Nested types (declared inside their outer class, include its header):
//   EventService::SingletonHolder

} // namespace aion::gameserver::services::event
