// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.questEngine.handlers.models.xmlQuest.conditions - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::questEngine::handlers::models::xmlQuest::conditions {

class DialogIdCondition;
class NpcIdCondition;
class PcInventoryCondition;
class QuestCondition;
class QuestConditions;
class QuestStatusCondition;
class QuestVarCondition;

} // namespace aion::gameserver::questEngine::handlers::models::xmlQuest::conditions
