#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::morheim {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/morheim/_2345OrashunerkSpecialOrder.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _2345OrashunerkSpecialOrder final : public AbstractQuestHandler {
public:
	_2345OrashunerkSpecialOrder() : AbstractQuestHandler(2345) {}

	void register_() override {
		qe.registerQuestNpc(798084)->addOnQuestStart(questId);
		qe.registerQuestNpc(798084)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700238)->addOnTalkEvent(questId);
		qe.registerQuestNpc(204304)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798084) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 798084) {
				if (dialogActionId == QUEST_SELECT) {
					if (var == 0)
						return sendQuestDialog(env, 1011);
					else if (var == 1)
						return sendQuestDialog(env, 1352);
				} else if (dialogActionId == CHECK_USER_HAS_QUEST_ITEM) {
					return checkQuestItems(env, 0, 1, false, 10000, 10001);
				} else if (dialogActionId == SETPRO10) {
					giveQuestItem(env, 182204137, 1);
					changeQuestStep(env, 1, 10);
					qs->setRewardGroup(0);
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return closeDialogWindow(env);
				} else if (dialogActionId == SETPRO20) {
					giveQuestItem(env, 182204138, 1);
					changeQuestStep(env, 1, 20);
					qs->setRewardGroup(1);
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return closeDialogWindow(env);
				}
			} else if (targetId == 700238 && player->getInventory().getItemCountByItemId(182204136) < 3) {
				return true; // looting
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204304) {
				if (dialogActionId == USE_OBJECT) {
					if (qs->getQuestVarById(0) == 10) {
						removeQuestItem(env, 182204137, 1);
						return sendQuestDialog(env, 1693);
					} else if (qs->getQuestVarById(0) == 20) {
						removeQuestItem(env, 182204138, 1);
						return sendQuestDialog(env, 2034);
					}
				}
				return sendQuestEndDialog(env);
			}
		}

		return false;
	}
};
AION_QUEST_HANDLER(_2345OrashunerkSpecialOrder, 2345);

} // namespace aion::gameserver::handlers::quest::morheim
