#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::morheim {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/morheim/_2392BeautifulFeather.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _2392BeautifulFeather final : public AbstractQuestHandler {
public:
	_2392BeautifulFeather() : AbstractQuestHandler(2392) {}

	void register_() override {
		qe.registerQuestNpc(798085)->addOnQuestStart(questId);
		qe.registerQuestNpc(798085)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798085) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 798085) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else if (dialogActionId == SETPRO1) {
					if (player->getInventory().getItemCountByItemId(182204159) != 0) {
						removeQuestItem(env, 182204159, 1);
						changeQuestStep(env, 0, 1);
						qs->setRewardGroup(0);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 5);
					} else
						return sendQuestDialog(env, 1097);
				} else if (dialogActionId == SETPRO2) {
					if (player->getInventory().getItemCountByItemId(182204160) != 0) {
						removeQuestItem(env, 182204160, 1);
						changeQuestStep(env, 0, 2);
						qs->setRewardGroup(1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 6);
					} else
						return sendQuestDialog(env, 1097);
				} else if (dialogActionId == SETPRO3) {
					if (player->getInventory().getItemCountByItemId(182204161) != 0) {
						removeQuestItem(env, 182204161, 1);
						changeQuestStep(env, 0, 3);
						qs->setRewardGroup(2);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestDialog(env, 7);
					} else
						return sendQuestDialog(env, 1097);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798085)
				return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2392BeautifulFeather, 2392);

} // namespace aion::gameserver::handlers::quest::morheim
