#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::morheim {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/morheim/_2409Propaganda.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _2409Propaganda final : public AbstractQuestHandler {
public:
	_2409Propaganda() : AbstractQuestHandler(2409) {}

	void register_() override {
		qe.registerQuestItem(182204169, questId);
		qe.registerQuestNpc(204301)->addOnTalkEvent(questId);
		qe.registerQuestNpc(204208)->addOnTalkEvent(questId);
		qe.registerCanAct(questId, 700243);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();
		int32_t targetId = env.getTargetId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 0) {
				if (dialogActionId == QUEST_ACCEPT_1) {
					QuestService::startQuest(env);
					return closeDialogWindow(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 204301) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1352);
				} else if (dialogActionId == SETPRO1) {
					return defaultCloseDialog(env, 0, 1, false, false);
				}
			} else if (targetId == 204208) {
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 2375);
				} else if (dialogActionId == SELECT_QUEST_REWARD) {
					return defaultCloseDialog(env, 1, 1, true, true);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204208) {
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 2375);
				}
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->isStartable()) {
			return ::aion::gameserver::questEngine::handlers::fromBoolean(sendQuestDialog(env, 4));
		}
		return HandlerResult::FAILED;
	}
};
AION_QUEST_HANDLER(_2409Propaganda, 2409);

} // namespace aion::gameserver::handlers::quest::morheim
