#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::morheim {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/morheim/_24023ABlazingRescue.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Ritsu
 */
class _24023ABlazingRescue final : public AbstractQuestHandler {
public:
	_24023ABlazingRescue() : AbstractQuestHandler(24023) {}

	void register_() override {
		std::array<int32_t, 3> npc_ids{204317, 204372, 204408};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerOnEnterWorld(questId);
		for (int32_t npc_id : npc_ids)
			qe.registerQuestNpc(npc_id)->addOnTalkEvent(questId);
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {24020});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {24020});
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (player->getWorldId() == 320050000 && qs->getQuestVarById(0) == 2) {
				qs->setQuestVar(3);
				updateQuestStatus(env);
			}
		}
		return false;
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 204317:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							return false;
						case SETPRO1:
							if (var == 0) {
								return defaultCloseDialog(env, 0, 1); // 1
							}
					}
					break;
				case 204408:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1)
								return sendQuestDialog(env, 1352);
							else if (var == 3)
								return sendQuestDialog(env, 2034);
							return false;
						case SELECT2_1_1:
							playQuestMovie(env, 78);
							break;
						case SETPRO2:
							if (var == 1) {
								if (!giveQuestItem(env, 182215369, 1))
									return true;
								qs->setQuestVarById(0, 2);
								updateQuestStatus(env);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
								return true;
							}
							return false;
						case CHECK_USER_HAS_QUEST_ITEM:
							if (var == 3) {
								if (QuestService::collectItemCheck(env, true)) {
									removeQuestItem(env, 182215369, 1);
									qs->setStatus(QuestStatus::REWARD);
									updateQuestStatus(env);
									return sendQuestDialog(env, 10000);
								} else
									return sendQuestDialog(env, 10001);
							}
					}
					break;
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204372) {
				if (dialogActionId == USE_OBJECT)
					return sendQuestDialog(env, 10002);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_24023ABlazingRescue, 24023);

} // namespace aion::gameserver::handlers::quest::morheim
