#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/teleport/TeleportService.h"

namespace aion::gameserver::handlers::quest::morheim {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/morheim/_2423ThereAndBackAgain.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Cheatkiller
 */
class _2423ThereAndBackAgain final : public AbstractQuestHandler {
public:
	_2423ThereAndBackAgain() : AbstractQuestHandler(2423) {}

	void register_() override {
		qe.registerQuestNpc(204326)->addOnQuestStart(questId);
		qe.registerQuestNpc(204375)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204326) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 4762);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 204375:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							{
								if (qs->getQuestVarById(0) == 0)
									return sendQuestDialog(env, 1011);
								else if (qs->getQuestVarById(0) == 1)
									return sendQuestDialog(env, 1352);
								else if (qs->getQuestVarById(0) == 2)
									return sendQuestDialog(env, 1693);
								return false;
							}
						case CHECK_USER_HAS_QUEST_ITEM:
							{
								return checkQuestItems(env, 1, 2, false, 10000, 10001);
							}
						case SETPRO3:
							{
								TeleportService::teleportTo(*player, 210020000, 1, 370.13f, 2682.59f, 171, static_cast<int8_t>(30), TeleportAnimation::FADE_OUT_BEAM);
								qs->setQuestVar(3);
								return defaultCloseDialog(env, 3, 3, true, false);
							}
						case SELECT3_2:
							{
								return sendQuestDialog(env, 1779);
							}
						case SETPRO1:
							{
								TeleportService::teleportTo(*player, 210020000, 1, 370.13f, 2682.59f, 171, static_cast<int8_t>(30), TeleportAnimation::FADE_OUT_BEAM);
								return defaultCloseDialog(env, 0, 1);
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204375) {
				if (env.getDialogActionId() == USE_OBJECT) {
					return sendQuestDialog(env, 10002);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2423ThereAndBackAgain, 2423);

} // namespace aion::gameserver::handlers::quest::morheim
