#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"

namespace aion::gameserver::handlers::quest::morheim {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/morheim/_2480ElimOfElysea.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author MrPoke, Nephis
 */
class _2480ElimOfElysea final : public AbstractQuestHandler {
public:
	_2480ElimOfElysea() : AbstractQuestHandler(2480) {}

	void register_() override {
		qe.registerQuestNpc(730038)->addOnQuestStart(questId);
		qe.registerQuestNpc(730038)->addOnTalkEvent(questId);
		qe.registerQuestNpc(730021)->addOnTalkEvent(questId);
		qe.registerQuestNpc(730019)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (targetId == 730038) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			} else if (qs->getStatus() == QuestStatus::START) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 2375);
				else if (env.getDialogActionId() == SELECT_QUEST_REWARD) {
					qs->setQuestVar(3);
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return sendQuestEndDialog(env);
				} else
					return sendQuestEndDialog(env);
			} else if (qs->getStatus() == QuestStatus::REWARD) {
				return sendQuestEndDialog(env);
			}
		} else if (targetId == 730021) {
			if (qs != nullptr && qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 0) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else if (env.getDialogActionId() == SETPRO1) {
					qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
					updateQuestStatus(env);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				} else
					return sendQuestStartDialog(env);
			}
		} else if (targetId == 730019) {
			if (qs != nullptr && qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 1) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else if (env.getDialogActionId() == SETPRO1) {
					qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
					updateQuestStatus(env);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				} else
					return sendQuestStartDialog(env);
			}
		}

		return false;
	}
};
AION_QUEST_HANDLER(_2480ElimOfElysea, 2480);

} // namespace aion::gameserver::handlers::quest::morheim
