#pragma once

#include <cstdint>
#include <string_view>

#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/services/PunishmentService_PunishmentType.h"
#include "aion/gameserver/services/fwd.h"

namespace aion::gameserver::services {

/**
 * @author lord_rex, Cura, nrg
 */
class PunishmentService {
public:
	using PunishmentType = ::aion::gameserver::services::PunishmentService_PunishmentType; // generated by xmlgen
public:
	/** This method will handle unbanning a character */
	static void unbanChar(int32_t playerId);
	/** This method will handle banning a character */
	static void banChar(int32_t playerId, int32_t dayCount, std::string_view reason);
	/** Calculates the timestamp when a given number of days is over */
	static int64_t calculateDuration(int32_t dayCount);
	/** This method will handle moving or removing a player from prison */
	static void setIsInPrison(model::gameobjects::player::Player& player, bool state, int64_t delayInMinutes, std::string_view reason);
	/** This method will update the prison status */
	static void updatePrisonStatus(model::gameobjects::player::Player& player);
private:
	/** This method will schedule a prison task */
	static void schedulePrisonTask(model::gameobjects::player::Player& player, int64_t prisonTimer);
public:
	/** This method will handle can or cant gathering */
	static void setIsNotGatherable(model::gameobjects::player::Player& player, int32_t captchaCount, bool state, int64_t delay);
};

} // namespace aion::gameserver::services
