#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/collections/ConcurrentHashMap.h"
#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/runtime/lifetime/RefCounted.h"
#include "aion/gameserver/runtime/sched/Future.h"
#include "aion/gameserver/model/gameobjects/fwd.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/services/RecallService_CancelReason.h"
#include "aion/gameserver/services/fwd.h"

namespace aion::gameserver::services {

/**
 * Handles pending summon requests (Summon Group Member, example skillId: 3777).<br>
 * The request is not re-validated when the summoned player accepts it. Instead, every state change that would invalidate it cancels the request, see
 * {@link #cancel(Player, CancelReason)}.
 */
class RecallService : public runtime::Immortal {
public:
	using CancelReason = ::aion::gameserver::services::RecallService_CancelReason; // generated by xmlgen
private:
	class Request;
	class Request : public runtime::RefCounted {
		AION_MAKE_REF_FRIEND
	public:
		const int32_t casterObjectId{};
		const int32_t worldId{};
		const int32_t instanceId{};
		const float x{};
		const float y{};
		const float z{};
		const int8_t heading{};
		runtime::Field<runtime::FutureRef> timeout{};
	protected:
		Request(int32_t casterObjectId, int32_t worldId, int32_t instanceId, float x, float y, float z, int8_t heading);
	public:
		static runtime::Ref<RecallService::Request> create(int32_t casterObjectId, int32_t worldId, int32_t instanceId, float x, float y, float z,
			int8_t heading);
	protected:
		~Request() override;
	};
	static constexpr int32_t CONFIRMATION_SECONDS = 30;
	runtime::ConcurrentHashMap<int32_t, runtime::Ref<RecallService::Request>> requests{AION_LOCK_CLASS(RecallService::requests#stripe)};
public:
	static RecallService& getInstance(); // Java singleton
private:
	RecallService();
public:
	bool hasPendingRequest(model::gameobjects::player::Player& summoned);
	/** Asks the summoned player whether he wants to be teleported to the position the caster is standing on. */
	void requestSummon(model::gameobjects::player::Player& caster, model::gameobjects::player::Player& summoned, int32_t skillId);
	/** Teleports the player to the caster of his pending request, without validating it again. */
	void accept(model::gameobjects::player::Player& summoned);
	/**
	 * Drops the pending request of the given player, if there is one, and notifies both sides as the reason dictates.
	 */
	void cancel(model::gameobjects::player::Player& summoned, RecallService::CancelReason reason);
private:
	runtime::Ptr<RecallService::Request> remove(model::gameobjects::player::Player& summoned);
public:
	/** Checks everything a summon skill needs before it may be cast and tells the caster why it failed. */
	static bool validateCast(model::gameobjects::player::Player& caster, model::gameobjects::VisibleObject& target);
	static bool canBeSummoned(model::gameobjects::Creature& caster, model::gameobjects::Creature& summoned);
	static bool canRecallAt(model::gameobjects::player::Player& caster);
};

} // namespace aion::gameserver::services
