#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::iron_wall_warfront {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/iron_wall_warfront/_16960FacetheCommander.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Mr.Madison
 */
class _16960FacetheCommander final : public AbstractQuestHandler {
public:
	_16960FacetheCommander() : AbstractQuestHandler(16960) {}

	void register_() override {
		qe.registerQuestNpc(801281)->addOnQuestStart(questId);
		qe.registerQuestNpc(801281)->addOnTalkEvent(questId);
		qe.registerQuestNpc(802055)->addOnTalkEvent(questId);
		qe.registerQuestNpc(233544)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 801281) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					case QUEST_ACCEPT_SIMPLE:
						return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 802055) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1352);
					case SELECT2_1:
						return sendQuestDialog(env, 1353);
					case SETPRO1:
						return defaultCloseDialog(env, 0, 1);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 801281) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 2375);
				} else {
					return sendQuestEndDialog(env);
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		return defaultOnKillEvent(env, 233544, 0, true);
	}
};
AION_QUEST_HANDLER(_16960FacetheCommander, 16960);

} // namespace aion::gameserver::handlers::quest::iron_wall_warfront
