#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/item/ItemTemplate.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::esoterrace {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/esoterrace/_18405MemoriesInTheCornerOfHisMind.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Vincas
 */
class _18405MemoriesInTheCornerOfHisMind final : public AbstractQuestHandler {
private:
	static constexpr int32_t npcDaidra = 799553;
	static constexpr int32_t npcTillen = 799552;

public:
	_18405MemoriesInTheCornerOfHisMind() : AbstractQuestHandler(18405) {}

	void register_() override {
		qe.registerQuestNpc(npcDaidra)->addOnTalkEvent(questId);
		qe.registerQuestNpc(npcTillen)->addOnTalkEvent(questId);
		qe.registerQuestItem(182215002, questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();

		if (env.getTargetId() == 0 && env.getDialogActionId() == QUEST_ACCEPT_1) {
			QuestService::startQuest(env);
			PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(0, 0));
			return true;
		}

		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		if (qs->getStatus() == QuestStatus::START) {
			switch (env.getTargetId()) {
				case npcDaidra:
					if (qs->getQuestVarById(0) == 0) {
						if (env.getDialogActionId() == QUEST_SELECT)
							return sendQuestDialog(env, 1352);
						else if (env.getDialogActionId() == SETPRO1)
							return defaultCloseDialog(env, 0, 1, 182215024, 1, 182215002, 1);
					}
					return false;
				case npcTillen:
					if (qs->getQuestVarById(0) == 1) {
						if (env.getDialogActionId() == QUEST_SELECT)
							return sendQuestDialog(env, 2375);
						else if (env.getDialogActionId() == SELECT_QUEST_REWARD)
							removeQuestItem(env, 182215024, 1);
						return defaultCloseDialog(env, 1, 2, true, true);
					}
			}
		}
		return sendQuestRewardDialog(env, npcTillen, 0);
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		int32_t id = item.getItemTemplate()->getTemplateId();

		if (id != 182215002)
			return HandlerResult::FAILED;
		sendQuestDialog(env, 4);
		return HandlerResult::SUCCESS;
	}
};
AION_QUEST_HANDLER(_18405MemoriesInTheCornerOfHisMind, 18405);

} // namespace aion::gameserver::handlers::quest::esoterrace
