// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.geoEngine.math - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::geoEngine::math {

struct FastMath;
class Matrix3f;
class Matrix4f;
class Ray;
class Vector2f;
class Vector3f;

} // namespace aion::gameserver::geoEngine::math
