#pragma once

#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/model/gameobjects/fwd.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/model/items/storage/fwd.h"
#include "aion/gameserver/services/item/ItemPacketService_ItemAddType.h"
#include "aion/gameserver/services/item/ItemPacketService_ItemDeleteType.h"
#include "aion/gameserver/services/item/ItemPacketService_ItemUpdateType.h"
#include "aion/gameserver/services/item/fwd.h"

namespace aion::gameserver::services::item {

/**
 * (Java TODO)<br>
 * 0x01 0000 0001 increase count by merge<br>
 * 0x06 0000 0110 decrease count after split, equip<br>
 * 0x16 0001 0110 decrease count by use item<br>
 * 0x19 0001 1001 increase count by looting<br>
 * 0x1A 0001 1010 increase kinah by loot<br>
 * 0x1D 0001 1101 decrease kinah<br>
 * 0x32 0011 0010 increase kinah by quest<br>
 * <p>
 * C++: a static-only class (hub-headers.md §11.1). The nested enums are generated (ItemPacketService_ItemUpdateType.h, ...) and aliased.
 *
 * @author ATracer
 */
class ItemPacketService {
public:
	using ItemUpdateType = ::aion::gameserver::services::item::ItemPacketService_ItemUpdateType; // generated by xmlgen
	using ItemAddType = ::aion::gameserver::services::item::ItemPacketService_ItemAddType; // generated by xmlgen
	using ItemDeleteType = ::aion::gameserver::services::item::ItemPacketService_ItemDeleteType; // generated by xmlgen
	static void updateItemAfterInfoChange(model::gameobjects::player::Player& player, model::gameobjects::Item& item);
	static void updateItemAfterInfoChange(model::gameobjects::player::Player& player, model::gameobjects::Item& item, ItemPacketService::ItemUpdateType updateType);
	static void updateItemAfterEquip(model::gameobjects::player::Player& player, model::gameobjects::Item& item);
	static void sendItemPacket(model::gameobjects::player::Player& player, model::items::storage::StorageType storageType, model::gameobjects::Item& item, ItemPacketService::ItemUpdateType updateType);
	/** Item will be deleted from UI slot */
	static void sendItemDeletePacket(model::gameobjects::player::Player& player, model::items::storage::StorageType storageType, model::gameobjects::Item& item, ItemPacketService::ItemDeleteType deleteType);
	/** Item will be updated in UI slot (stacked items) */
	static void sendItemUpdatePacket(model::gameobjects::player::Player& player, model::items::storage::StorageType storageType, model::gameobjects::Item& item, ItemPacketService::ItemUpdateType updateType);
	static void sendStorageUpdatePacket(model::gameobjects::player::Player& player, model::items::storage::StorageType storageType, model::gameobjects::Item& item);
	/** New item will be displayed in storage */
	static void sendStorageUpdatePacket(model::gameobjects::player::Player& player, model::items::storage::StorageType storageType, model::gameobjects::Item& item, ItemPacketService::ItemAddType addType);
	static void sendItemUnlockPacket(model::gameobjects::player::Player& player, model::gameobjects::Item& item);
};

} // namespace aion::gameserver::services::item
