// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.gameobjects.state - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

#include <cstdint>

namespace aion::gameserver::model::gameobjects::state {

enum class CreatureSeeState : std::uint8_t;
enum class CreatureState : std::uint8_t;
enum class CreatureVisualState : std::uint8_t;
enum class FlyState : std::uint8_t;

} // namespace aion::gameserver::model::gameobjects::state
