#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::ascension {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/ascension/_2903DispatchtoAltgard.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Mr. Poke
 */
class _2903DispatchtoAltgard final : public AbstractQuestHandler {
public:
	_2903DispatchtoAltgard() : AbstractQuestHandler(2903) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerQuestNpc(204191)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203559)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 204191:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1352);
							break;
						case SETPRO1:
							if (var == 0) {
								qs->setQuestVarById(0, var + 1);
								updateQuestStatus(env);
								return closeDialogWindow(env);
							}
					}
					return false;
				case 203559:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							if (var == 1) {
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								return sendQuestDialog(env, 2375);
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203559) {
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env);
	}
};
AION_QUEST_HANDLER(_2903DispatchtoAltgard, 2903);

} // namespace aion::gameserver::handlers::quest::ascension
