// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.utils.audit - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::utils::audit {

class AuditLogger;
class AutoBan;
class GMService;

// Nested types (declared inside their outer class, include its header):
//   GMService::SingletonHolder

} // namespace aion::gameserver::utils::audit
