// Contract test of aion_gs_runtime_fields (headers stage): Field/Final/Array/Atomic* API shapes, including the design's Effect sample
// (runtime-architecture.md §14.2c).

#include <gtest/gtest.h>

#include <memory>
#include <optional>
#include <string>

#include "aion/gameserver/runtime/base/Exceptions.h"
#include "aion/gameserver/runtime/fields/Array.h"
#include "aion/gameserver/runtime/fields/Atomic.h"
#include "aion/gameserver/runtime/fields/Field.h"
#include "aion/gameserver/runtime/fields/Final.h"
#include "aion/gameserver/runtime/lifetime/Reclaimer.h"
#include "aion/gameserver/runtime/lifetime/TaskScope.h"

using namespace aion::gameserver::runtime;

namespace {

class Task final : public RefCounted {
	AION_MAKE_REF_FRIEND

public:
	static Ref<Task> create() { return makeRef<Task>(); }
	bool cancelled = false;

protected:
	Task() = default;
	~Task() override = default;
};

enum class AIState { IDLE, FOLLOWING };

class Connection {};

/** Member layout as generated by fieldmap.py for a K4 class */
class Effect final : public RefCounted {
	AION_MAKE_REF_FRIEND

public:
	static Ref<Effect> create() { return makeRef<Effect>(); }

	Field<int32_t> duration;
	Field<float> x;
	Field<AIState> state{AIState::IDLE};
	Field<std::optional<int64_t>> lastAttack;
	Field<std::string> name;
	Field<Ref<Task>> endTask;
	Field<Ref<Array<Ref<Task>>>> periodicTasks;
	Field<std::shared_ptr<Connection>> connection;
	Final<const Effect*> template_;
	AtomicBoolean wasSpawned{AION_LOCK_CLASS(Effect::wasSpawned)};
	AtomicInteger counter;
	AtomicLong startMillis;
	AtomicReference<Ref<Task>> task;
	AtomicLongArray stageStartMillis{6};

	/** design §14.2c Effect::setPeriodicTask */
	void setPeriodicTask(Ref<Task> periodicTask, int32_t position) {
		if (!periodicTasks)
			periodicTasks = Array<Ref<Task>>::make(4);
		else if ((*periodicTasks)[position - 1] && periodicTask) {
			periodicTask->cancelled = true;
			throw IllegalStateException("already has a periodic task at position " + std::to_string(position));
		}
		(*periodicTasks)[position - 1] = std::move(periodicTask);
	}

	void stopTasks() {
		if (endTask) {
			endTask->cancelled = true;
			endTask = nullptr;
		}
		if (periodicTasks) {
			for (Ptr<Task> periodicTask : *periodicTasks)
				if (periodicTask)
					periodicTask->cancelled = true;
			periodicTasks = nullptr;
		}
	}

protected:
	Effect() = default;
	~Effect() override = default;
};

} // namespace

TEST(FieldsContractTest, ScalarFields) {
	Ref<Effect> effect = Effect::create();
	effect->duration = 5;
	effect->duration += 3;
	int32_t old = effect->duration++;
	EXPECT_EQ(old, 8);
	EXPECT_EQ(effect->duration.get(), 9);
	effect->state = AIState::FOLLOWING;
	EXPECT_EQ(effect->state.get(), AIState::FOLLOWING);
	effect->lastAttack = std::optional<int64_t>(42);
	EXPECT_EQ(effect->lastAttack.get().value(), 42);
	effect->template_.set(effect.get());
	EXPECT_EQ(effect->template_.get(), effect.get());
}

TEST(FieldsContractTest, ReferenceAndStringFieldsNeedATaskScope) {
	TaskScope scope(AION_TASK_INFO(TaskKind::TEST));
	Ref<Effect> effect = Effect::create();
	Ref<Task> task = Task::create();
	effect->endTask = task;
	EXPECT_TRUE(effect->endTask == Ptr<Task>(task));
	EXPECT_TRUE(TaskScope::isPublished()) << "a Field<Ref> load publishes the epoch (read barrier)";
	EXPECT_EQ(task->refCount(), 2u);
	Ref<Task> previous = effect->endTask.exchange(nullptr);
	EXPECT_EQ(previous, task);
	EXPECT_TRUE(effect->endTask.compareAndSet(nullptr, task));
	EXPECT_FALSE(effect->endTask.compareAndSet(nullptr, task));

	effect->name = "Poison";
	std::string copy = effect->name;
	EXPECT_EQ(copy, "Poison");

	effect->connection = std::make_shared<Connection>();
	EXPECT_TRUE(static_cast<bool>(effect->connection));
}

TEST(FieldsContractTest, ArraysAndTheEffectSample) {
	TaskScope scope(AION_TASK_INFO(TaskKind::TEST));
	Ref<Effect> effect = Effect::create();
	Ref<Task> first = Task::create();
	effect->setPeriodicTask(first, 1);
	effect->setPeriodicTask(Task::create(), 2);
	EXPECT_THROW(effect->setPeriodicTask(Task::create(), 1), IllegalStateException);
	EXPECT_EQ((*effect->periodicTasks).length(), 4);
	EXPECT_THROW((void)(*effect->periodicTasks)[4], ArrayIndexOutOfBoundsException);
	effect->stopTasks();
	EXPECT_TRUE(first->cancelled);
	EXPECT_FALSE(static_cast<bool>(effect->periodicTasks));
	Ref<Array<int32_t>> values = Array<int32_t>::of({1, 2, 3});
	EXPECT_EQ(values->get(2), 3);
}

TEST(FieldsContractTest, AtomicShims) {
	TaskScope scope(AION_TASK_INFO(TaskKind::TEST));
	Ref<Effect> effect = Effect::create();
	EXPECT_TRUE(effect->wasSpawned.compareAndSet(false, true));
	EXPECT_FALSE(effect->wasSpawned.compareAndSet(false, true));
	EXPECT_EQ(effect->counter.incrementAndGet(), 1);
	EXPECT_EQ(effect->startMillis.addAndGet(10), 10);
	EXPECT_EQ(effect->stageStartMillis.incrementAndGet(5), 1);
	Ref<Task> task = Task::create();
	EXPECT_TRUE(effect->task.compareAndSet(nullptr, task));
	EXPECT_EQ(effect->task.get(), task);
	SYNCHRONIZED(effect->wasSpawned) {
		EXPECT_TRUE(effect->wasSpawned.monitor().isHeldByCurrentThread());
	}
	EXPECT_EQ(&monitorOf(effect->wasSpawned).lockClass, &LockClass::named("Effect::wasSpawned"));
}
