#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/model/gameobjects/fwd.h"
#include "aion/gameserver/network/aion/AionServerPacket.h"
#include "aion/gameserver/network/aion/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/SM_ATTACK_STATUS_LOG.h"
#include "aion/gameserver/network/aion/serverpackets/SM_ATTACK_STATUS_TYPE.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"

namespace aion::gameserver::network::aion::serverpackets {

/**
 * @author alexa026, ATracer, kecimis
 */
class SM_ATTACK_STATUS : public AionServerPacket {
public:
	using TYPE = ::aion::gameserver::network::aion::serverpackets::SM_ATTACK_STATUS_TYPE; // generated by xmlgen
	using LOG = ::aion::gameserver::network::aion::serverpackets::SM_ATTACK_STATUS_LOG; // generated by xmlgen

private:
	static constexpr int32_t CRITICAL_DISPLAY_CODE = 12;
	runtime::Ref<model::gameobjects::Creature> creature{};
	SM_ATTACK_STATUS::TYPE type{};
	int32_t skillId{};
	int32_t value{};
	int32_t logId{};
	bool criticalHit{};

public:
	SM_ATTACK_STATUS(model::gameobjects::Creature& creature, SM_ATTACK_STATUS::TYPE type, int32_t skillId, int32_t value, SM_ATTACK_STATUS::LOG log,
		bool criticalHit);
	SM_ATTACK_STATUS(model::gameobjects::Creature& creature, SM_ATTACK_STATUS::TYPE type, int32_t skillId, int32_t value, SM_ATTACK_STATUS::LOG log);
	SM_ATTACK_STATUS(model::gameobjects::Creature& creature, SM_ATTACK_STATUS::TYPE type, int32_t skillId, int32_t value);
	SM_ATTACK_STATUS(model::gameobjects::Creature& creature, int32_t value);
	~SM_ATTACK_STATUS() override;

protected:
	void writeImpl(AionConnection* con) override;
};

} // namespace aion::gameserver::network::aion::serverpackets
