#pragma once

#include <cstdint>

#include "aion/gameserver/network/aion/AionServerPacket.h"
#include "aion/gameserver/network/aion/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/SM_ENTER_WORLD_CHECK_Msg.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"

namespace aion::gameserver::network::aion::serverpackets {

/**
 * This packet sends message boxes to the client, to indicate the connection status of the current character.
 *
 * @author -Nemesiss-
 */
class SM_ENTER_WORLD_CHECK : public AionServerPacket {
public:
	using Msg = ::aion::gameserver::network::aion::serverpackets::SM_ENTER_WORLD_CHECK_Msg; // generated by xmlgen

private:
	int8_t msg{};

public:
	explicit SM_ENTER_WORLD_CHECK(SM_ENTER_WORLD_CHECK::Msg msg);
	SM_ENTER_WORLD_CHECK();

protected:
	void writeImpl(AionConnection* con) override;
};

} // namespace aion::gameserver::network::aion::serverpackets
