#pragma once

#include <cstdint>

#include "aion/gameserver/network/aion/AionServerPacket.h"
#include "aion/gameserver/network/aion/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/SM_LOOT_STATUS_Status.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"

namespace aion::gameserver::network::aion::serverpackets {

/**
 * @author alexa026
 */
class SM_LOOT_STATUS : public AionServerPacket {
public:
	using Status = ::aion::gameserver::network::aion::serverpackets::SM_LOOT_STATUS_Status; // generated by xmlgen
private:
	int32_t targetObjectId{};
	SM_LOOT_STATUS::Status status{};
	int32_t lootEffectId{};
public:
	SM_LOOT_STATUS(int32_t targetObjectId, SM_LOOT_STATUS::Status status);
protected:
	void writeImpl(AionConnection* con) override;
private:
	static int32_t getLootEffect(int32_t targetObjectId);
};

} // namespace aion::gameserver::network::aion::serverpackets
