#pragma once

#include <cstdint>
#include <string>
#include <string_view>

#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/network/aion/AionServerPacket.h"
#include "aion/gameserver/network/aion/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/SM_MEGAPHONE_FactionLabel.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"

namespace aion::gameserver::network::aion::serverpackets {

/**
 * Messages from this packet are displayed in a separate chat window which is only visible if the client is started with the -megaphone argument.
 *
 * @author Artur, Neon
 */
class SM_MEGAPHONE : public AionServerPacket {
public:
	using FactionLabel = ::aion::gameserver::network::aion::serverpackets::SM_MEGAPHONE_FactionLabel; // generated by xmlgen
private:
	SM_MEGAPHONE::FactionLabel senderFaction{};
	std::string senderName{};
	std::string message{};
	int32_t itemId{};
public:
	SM_MEGAPHONE(model::gameobjects::player::Player& sender, std::string_view message, int32_t itemId);
	SM_MEGAPHONE(SM_MEGAPHONE::FactionLabel senderFaction, std::string_view senderName, std::string_view message, int32_t itemId);
protected:
	void writeImpl(AionConnection* con) override;
};

} // namespace aion::gameserver::network::aion::serverpackets
