#pragma once

#include <cstdint>

#include "aion/gameserver/runtime/lifetime/Ref.h"
#include "aion/gameserver/network/aion/AionServerPacket.h"
#include "aion/gameserver/network/aion/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/SM_QUEST_ACTION_ActionType.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"
#include "aion/gameserver/questEngine/model/fwd.h"

namespace aion::gameserver::network::aion::serverpackets {

/**
 * @author VladimirZ
 */
class SM_QUEST_ACTION : public AionServerPacket {
public:
	using ActionType = ::aion::gameserver::network::aion::serverpackets::SM_QUEST_ACTION_ActionType; // generated by xmlgen
private:
	SM_QUEST_ACTION::ActionType actionType{};
	int32_t questId{};
	int32_t status{};
	int32_t step{};
	int32_t flags{};
	int32_t timer{};
	int32_t sharerId{};
	bool shareInAlliance{};
public:
	/** Use this constructor to notify the client about a new/abandoned quest or quest state updates. */
	SM_QUEST_ACTION(SM_QUEST_ACTION::ActionType actionType, questEngine::model::QuestState& qs);
	explicit SM_QUEST_ACTION(int32_t questId);
	/** Display Timer */
	SM_QUEST_ACTION(int32_t questId, int32_t timer);
	/** Shows a question window that asks to share the quest with the packet receiver. */
	SM_QUEST_ACTION(int32_t questId, int32_t sharerId, bool shareInAlliance);
protected:
	void writeImpl(AionConnection* con) override;
};

} // namespace aion::gameserver::network::aion::serverpackets
