// Generated by cpp/tools/gen/sysmsg.py - do not edit. Regenerate with: python cpp/tools/gen/sysmsg.py
// Source: game-server/src/com/aionemu/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.java (factories 2576 to 3090 of 4117)
#include "aion/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.h"

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace aion::gameserver::network::aion::serverpackets {

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BLOCK_PC_ROOM_COMPLAIN2() {
	return SM_SYSTEM_MESSAGE(1400066, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_STIGMA_ALREADY_EQUIP_STONE() {
	return SM_SYSTEM_MESSAGE(1400067, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REMAIN_CHANGE_CHANNEL_COOLTIME(std::string_view durationtime0, std::string_view durationtime1) {
	return SM_SYSTEM_MESSAGE(1400068, std::vector<std::string>{std::string(durationtime0), std::string(durationtime1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_UPGRADE_LEVEL(int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400069, std::vector<std::string>{toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_DEGRADE_LEVEL(int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400070, std::vector<std::string>{toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_INFO_1_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400071, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_INFO_2_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400072, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_INFO_3_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400073, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_INFO_4_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400074, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WEAPON_BOOST_MODE_BURN_OUT() {
	return SM_SYSTEM_MESSAGE(1400075, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_INFO_NORMAL() {
	return SM_SYSTEM_MESSAGE(1400076, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MAIL_ITEM_DEL_DENIED() {
	return SM_SYSTEM_MESSAGE(1400077, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_OPEN_STORE_DURING_CRAFTING() {
	return SM_SYSTEM_MESSAGE(1400078, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ASF_COMBAT() {
	return SM_SYSTEM_MESSAGE(1400079, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ASF_MOVE_TYPE_WALK() {
	return SM_SYSTEM_MESSAGE(1400080, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ASF_CASTING_SKILL() {
	return SM_SYSTEM_MESSAGE(1400081, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ASF_GLIDE() {
	return SM_SYSTEM_MESSAGE(1400082, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_DEGRADE_NORMAL_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400083, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_NOT_SKIN_CHANGED_ITEM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400084, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANNOT_ACCUSE() {
	return SM_SYSTEM_MESSAGE(1400085, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANNOT_ACCUSE_CITY() {
	return SM_SYSTEM_MESSAGE(1400086, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SUMMON_CANT_ORDER_BY_INVALID_STANCE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400087, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SOCIALACTION_ALREADY_HAS_SKILL() {
	return SM_SYSTEM_MESSAGE(1400088, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CHANGE_ITEM_SKIN_CANNOT_INVALID_ITEM() {
	return SM_SYSTEM_MESSAGE(1400089, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_CANT_SUBMIT_BY_NO_COUNT() {
	return SM_SYSTEM_MESSAGE(1400090, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_COUNT_INFO(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400091, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_CANT_BE_INVITED() {
	return SM_SYSTEM_MESSAGE(1400092, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_CANT_INVITE_OTHER() {
	return SM_SYSTEM_MESSAGE(1400093, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_CANT_JOIN_PARTY() {
	return SM_SYSTEM_MESSAGE(1400094, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_CANT_JOIN_FORCE() {
	return SM_SYSTEM_MESSAGE(1400095, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GIVE_ITEM_OPTION_CANT_FOR_TOO_HIGH_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400096, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_Recall_CANNOT_ACCEPT_EFFECT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400097, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_Recall_DONOT_ACCEPT_EFFECT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400098, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_Recall_Reject_EFFECT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400099, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_Recall_Rejected_EFFECT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400100, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_Recall_CANCEL_EFFECT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400101, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_Recall_DUPLICATE_EFFECT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400102, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_OTHER_IS_BANISHED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400103, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_GIFT_SUCCESS() {
	return SM_SYSTEM_MESSAGE(1400104, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_ERROR() {
	return SM_SYSTEM_MESSAGE(1400105, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_NO_USER_TO_GIFT() {
	return SM_SYSTEM_MESSAGE(1400106, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_INVALID_GOODS() {
	return SM_SYSTEM_MESSAGE(1400107, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_NOT_ENOUGH_POINT() {
	return SM_SYSTEM_MESSAGE(1400108, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_INVALID_RACE() {
	return SM_SYSTEM_MESSAGE(1400109, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_INVALID_GENDER() {
	return SM_SYSTEM_MESSAGE(1400110, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_INVALID_CLASS() {
	return SM_SYSTEM_MESSAGE(1400111, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_DUPLICATED_TITLE() {
	return SM_SYSTEM_MESSAGE(1400112, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_DUPLICATED_SOCIAL() {
	return SM_SYSTEM_MESSAGE(1400113, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_DUPLICATED_CUBE() {
	return SM_SYSTEM_MESSAGE(1400114, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BINDSTONE_CANNOT_FOR_INVALID_RIGHT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400115, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_CANNOT_GIVE_TO_ME() {
	return SM_SYSTEM_MESSAGE(1400116, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_MAIL_CANT_FOR_YOU_EXCLUDED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400117, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PING_RESULT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400118, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EXCHANGE_CANNOT_UNREGISTER_ITEM() {
	return SM_SYSTEM_MESSAGE(1400119, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EXCHANGE_CANNOT_DECREASE_MONEY() {
	return SM_SYSTEM_MESSAGE(1400120, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_ERROR_WORLD_LOCAL_CODE_FAIL() {
	return SM_SYSTEM_MESSAGE(1400121, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_GET_PVP_EXP_TARGET_LIMIT() {
	return SM_SYSTEM_MESSAGE(1400122, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_GET_PVP_EXP_TIMEBASE_LIMIT() {
	return SM_SYSTEM_MESSAGE(1400123, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_BUDDYLIST_CANNOT_BLOCK_ME() {
	return SM_SYSTEM_MESSAGE(1400124, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_ITEM_DICE_CUSTOM_ME(int32_t num0, int32_t num1) {
	return SM_SYSTEM_MESSAGE(1400125, std::vector<std::string>{toJavaString(num0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DICE_CUSTOM_ME(int32_t num0, int32_t num1) {
	return SM_SYSTEM_MESSAGE(1400126, std::vector<std::string>{toJavaString(num0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DICE_CUSTOM_OTHER(std::string_view value0, int32_t num1, int32_t num2) {
	return SM_SYSTEM_MESSAGE(1400127, std::vector<std::string>{std::string(value0), toJavaString(num1), toJavaString(num2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FORCE_CANT_INVITE_WHEN_HE_IS_IN_INSTANCE() {
	return SM_SYSTEM_MESSAGE(1400128, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_TARGET_IS_NOT_VALID() {
	return SM_SYSTEM_MESSAGE(1400129, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PREVIEW_INVALID_GENDER() {
	return SM_SYSTEM_MESSAGE(1400130, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_VENDOR_ACCOUNT_IS_NOT_EMPTY() {
	return SM_SYSTEM_MESSAGE(1400131, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_USE_DIRECT_PORTAL_BY_SLAYER() {
	return SM_SYSTEM_MESSAGE(1400132, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_NOTIFY_LOGIN_GUILD(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400133, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PERSONAL_SHOP_SELL_ITEM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400134, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PERSONAL_SHOP_SELL_ITEM_MULTI(int64_t num1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400135, std::vector<std::string>{std::string(value0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAN_CHAT_NOW() {
	return SM_SYSTEM_MESSAGE(1400136, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_UPGRADE_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400137, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_DEGRADE_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400138, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_DEGRADE_TO_NOMAL_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400139, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_DEATH_TO_B(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400140, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_LIGHT_DEATH_TO_B(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400141, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_DARK_DEATH_TO_B(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400142, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_UP_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400143, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_DOWN_LEVEL(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400144, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SLAYER_DOWN_TO_NOMAL_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400145, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_OTHER_combine_START(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400146, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_OTHER_combine_SUCCESS(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400147, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_OTHER_combine_FAIL(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400148, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_USE_DIRECT_PORTAL_BY_SLAYER_GRADE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400149, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_ERROR_ONLY_MASTER_CAN_CHANGE_NAME() {
	return SM_SYSTEM_MESSAGE(1400150, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_CHAR_NAME_ERROR_WRONG_INPUT() {
	return SM_SYSTEM_MESSAGE(1400151, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_ERROR_WRONG_INPUT() {
	return SM_SYSTEM_MESSAGE(1400152, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_CHAR_NAME_ERROR_SAME_YOUR_NAME() {
	return SM_SYSTEM_MESSAGE(1400153, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_ERROR_SAME_YOUR_NAME() {
	return SM_SYSTEM_MESSAGE(1400154, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_CHAR_NAME_ALREADY_EXIST() {
	return SM_SYSTEM_MESSAGE(1400155, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_ALREADY_EXIST() {
	return SM_SYSTEM_MESSAGE(1400156, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_CHAR_NAME_SUCCESS(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400157, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_SUCCESS(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400158, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_NAME_ERROR_DEFAULT(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400159, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_CANT_FOR_HAVING_HOUSE() {
	return SM_SYSTEM_MESSAGE(1400160, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BOT_CANNOT_USE_NPC_UTILITY() {
	return SM_SYSTEM_MESSAGE(1400161, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BOT_CANNOT_USE_PC_TRADE() {
	return SM_SYSTEM_MESSAGE(1400162, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_BANISHED_FROM_PARTY() {
	return SM_SYSTEM_MESSAGE(1400163, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ACCUSE_BANISHED_FROM_FORCE() {
	return SM_SYSTEM_MESSAGE(1400164, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BOT_CANNOT_RECEIVE_VITAL_BONUS() {
	return SM_SYSTEM_MESSAGE(1400165, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANNOT_USE_PC_TRADE_TO_BOT() {
	return SM_SYSTEM_MESSAGE(1400166, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_NOGLIDE_AREA() {
	return SM_SYSTEM_MESSAGE(1400167, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_NOGLIDE_AREA_STOP() {
	return SM_SYSTEM_MESSAGE(1400168, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_BINDSTONE_WARNING_REMAIN_TIME(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400169, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EDIT_GUILD_NAME_CANT_FOR_DISPERSING_GUILD() {
	return SM_SYSTEM_MESSAGE(1400170, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANNOT_ACCUSE_IN_THIS_ZONE() {
	return SM_SYSTEM_MESSAGE(1400171, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INGAMESHOP_DUPLICATED_WAREHOUSE() {
	return SM_SYSTEM_MESSAGE(1400172, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHAT_CHANNEL_HOST() {
	return SM_SYSTEM_MESSAGE(1400173, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHAT_CHANNEL_CHAR_NAME_CHANGED1() {
	return SM_SYSTEM_MESSAGE(1400174, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHAT_CHANNEL_CHAR_NAME_CHANGED2() {
	return SM_SYSTEM_MESSAGE(1400175, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHAT_CHANNEL_PARTY() {
	return SM_SYSTEM_MESSAGE(1400176, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_USE_DUPLICATED_ITEM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400177, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_COOL_TIME_REMAIN(std::string_view worldname1, std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400178, std::vector<std::string>{std::string(worldname1), std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_ENTER_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400179, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_TOO_MANY_MEMBERS(int32_t num0, int32_t mapId) {
	return SM_SYSTEM_MESSAGE(1400180, std::vector<std::string>{toJavaString(num0), toJavaString(mapId)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_ALREADY_REGISTERED(int32_t worldId) {
	return SM_SYSTEM_MESSAGE(1400181, std::vector<std::string>{toJavaString(worldId)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_NOT_LEADER() {
	return SM_SYSTEM_MESSAGE(1400182, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REGISTER_CANCELED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400183, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_ENTER_GIVEUP(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400184, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_ENTER_STATE() {
	return SM_SYSTEM_MESSAGE(1400185, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_ENTER_NOTICE() {
	return SM_SYSTEM_MESSAGE(1400186, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_INSTANCE_ENTER_MEMBER(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400187, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CHANGE_CHANNEL5(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400188, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PARTY_MATCH_JUST_SENT_APPLY(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400189, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PARTY_MATCH_JUST_INVITE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400190, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FORCE_MATCH_JUST_SENT_APPLY(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400191, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FORCE_MATCH_JUST_INVITE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400192, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_OTHER_USER_USE_RESURRECTDEBUFF_SKILL_ALREADY() {
	return SM_SYSTEM_MESSAGE(1400193, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REGISTER_SUCCESS() {
	return SM_SYSTEM_MESSAGE(1400194, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REMAIN_TIME(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400195, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_START_IDLF1() {
	return SM_SYSTEM_MESSAGE(1400196, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_BOSS_ATTACKED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400198, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_ROOM_DESTROYED(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400199, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PARTY_MATCH_NOT_EXIST() {
	return SM_SYSTEM_MESSAGE(1400200, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANNOT_ENTER_INSTANCE_MAX_COUNT(int32_t num0, std::string_view worldname1) {
	return SM_SYSTEM_MESSAGE(1400201, std::vector<std::string>{toJavaString(num0), std::string(worldname1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REMAIN_TIME_60(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400202, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REMAIN_TIME_30(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400203, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REMAIN_TIME_10(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400204, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_REMAIN_TIME_5(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400205, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CMD_LINK_EXPIRED() {
	return SM_SYSTEM_MESSAGE(1400206, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FORCE_MATCH_CANT_USE_PARTY_MATCH(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400207, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PREVIEW_INVALID_RACE() {
	return SM_SYSTEM_MESSAGE(1400208, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PREVIEW_INVALID_COSMETIC() {
	return SM_SYSTEM_MESSAGE(1400209, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PREVIEW_NO_EXIST_COSMETIC_DATA() {
	return SM_SYSTEM_MESSAGE(1400210, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_ENHANCED1_STIGMA_SLOT_IS_NOT_OPENED() {
	return SM_SYSTEM_MESSAGE(1400211, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_CANT_OPERATE_PARTY_COMMAND() {
	return SM_SYSTEM_MESSAGE(1400212, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_STIGMA_TO_EQUIP_STONE_LEARN_PRESKILL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400213, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_STIGMA_CANT_UNEQUIP_STONE_FOR_AFTERSKILL(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400214, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PARTY_MATCH_ALREADY_SENT_APPLY(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400215, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FORCE_MATCH_ALREADY_SENT_APPLY(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400216, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PARTY_MATCH_DECLINED() {
	return SM_SYSTEM_MESSAGE(1400217, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FORCE_MATCH_DECLINED() {
	return SM_SYSTEM_MESSAGE(1400218, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_CANT_ENTER_WITHOUT_ITEM() {
	return SM_SYSTEM_MESSAGE(1400219, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REMAIN_TIME(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400220, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REMAIN_TIME_60(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400221, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REMAIN_TIME_30(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400222, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REMAIN_TIME_10(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400223, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REMAIN_TIME_5(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400224, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_CHANNELCHAT_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400225, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LEFTWALL_CREATED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400226, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_RIGHTWALL_CREATED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400227, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LEFTTELEPORTER_CREATED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400228, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_RIGHTTELEPORTER_CREATED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400229, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LEFTDOOR_DESTROYED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400230, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_RIGHTDOOR_DESTROYED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400231, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ITEM_LEFT(int32_t num1, std::string_view value0s) {
	return SM_SYSTEM_MESSAGE(1400232, std::vector<std::string>{toJavaString(num1), std::string(value0s)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_PREPARE_TIME() {
	return SM_SYSTEM_MESSAGE(1400233, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BOSSTELEPORTER_CREATED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400234, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_CANT_ENTER_FOR_TIMEOVER(int32_t worldId) {
	return SM_SYSTEM_MESSAGE(1400235, std::vector<std::string>{toJavaString(worldId)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_SCORE_ALARM(int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400236, std::vector<std::string>{toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GET_SCORE(std::string_view value0, int32_t num1) {
	return SM_SYSTEM_MESSAGE(1400237, std::vector<std::string>{std::string(value0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_OPEN_STORE_IN_THIS_ZONE() {
	return SM_SYSTEM_MESSAGE(1400238, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHAT_CHANNEL_JOIN_ZONE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400239, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHAT_CHANNEL_JOIN_TRADE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400240, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_PARTY_MATCH_ALREADY_SENT_DECLINE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400241, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FORCE_MATCH_ALREADY_SENT_DECLINE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400242, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_START_IDABRE() {
	return SM_SYSTEM_MESSAGE(1400243, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_TREASUREBOX_DESPAWN_ALL() {
	return SM_SYSTEM_MESSAGE(1400244, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_TREASUREBOX_DESPAWN_ONE() {
	return SM_SYSTEM_MESSAGE(1400245, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_OPEN_DOOR(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400246, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_REGISTER_BINDSTONE_FULL() {
	return SM_SYSTEM_MESSAGE(1400247, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_OPEN_DOOR_01() {
	return SM_SYSTEM_MESSAGE(1400248, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_OPEN_DOOR_02() {
	return SM_SYSTEM_MESSAGE(1400249, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_OPEN_DOOR_03() {
	return SM_SYSTEM_MESSAGE(1400250, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_OPEN_DOOR_04() {
	return SM_SYSTEM_MESSAGE(1400251, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_OPEN_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400252, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_PORTAL_TIME() {
	return SM_SYSTEM_MESSAGE(1400253, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_BATTLE_TIME(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400254, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_BATTLE_END(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400255, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_GET_AP_LEVELBASE_LIMIT() {
	return SM_SYSTEM_MESSAGE(1400256, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_S_RANK_BATTLE_TIME() {
	return SM_SYSTEM_MESSAGE(1400257, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_S_RANK_BATTLE_END() {
	return SM_SYSTEM_MESSAGE(1400258, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_A_RANK_BATTLE_TIME() {
	return SM_SYSTEM_MESSAGE(1400259, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_A_RANK_BATTLE_END() {
	return SM_SYSTEM_MESSAGE(1400260, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_USER_KICKED_BY_TIMEOUT(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400261, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_TIMER_START() {
	return SM_SYSTEM_MESSAGE(1400262, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_IDSHULACKSHIP_TIMER_END() {
	return SM_SYSTEM_MESSAGE(1400263, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ALARM_COLD_GAME_IDAB1_DREADGION(std::string_view durationtime0) {
	return SM_SYSTEM_MESSAGE(1400264, std::vector<std::string>{std::string(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_NUCLEARTELEPORTER_CREATED_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400265, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_ALLIANCE_TOO_LOW_LEVEL_TO_INVITE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400266, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANNOT_USE_ITEM_TOO_HIGH_LEVEL(int32_t value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400267, std::vector<std::string>{toJavaString(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_RESTRICTED(int32_t durationtime0) {
	return SM_SYSTEM_MESSAGE(1400268, std::vector<std::string>{toJavaString(durationtime0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_RECOVERED() {
	return SM_SYSTEM_MESSAGE(1400269, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_UNRESTRICT() {
	return SM_SYSTEM_MESSAGE(1400270, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_UNRESTRICT_FAILED_RETRY(int32_t value0) {
	return SM_SYSTEM_MESSAGE(1400271, std::vector<std::string>{toJavaString(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_UNRESTRICT_FAILED() {
	return SM_SYSTEM_MESSAGE(1400272, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_REMAIN_RESTRICT_TIME(int32_t duration) {
	return SM_SYSTEM_MESSAGE(1400273, std::vector<std::string>{toJavaString(duration)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CAPTCHA_NOT_RESTRICTED() {
	return SM_SYSTEM_MESSAGE(1400274, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_PORTAL_OPEN_IDLF3_Castle_Indratoo() {
	return SM_SYSTEM_MESSAGE(1400275, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_PORTAL_OPEN_IDDF3_Dragon() {
	return SM_SYSTEM_MESSAGE(1400276, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GET_SCORE_FOR_ENEMY(int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400277, std::vector<std::string>{toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANT_FLY_NOW_DUE_TO_NOFLY_FROM_PET() {
	return SM_SYSTEM_MESSAGE(1400278, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_DECOMPOSE_EQUIP_ITEM_CAN_NOT_BE_DECOMPOSED() {
	return SM_SYSTEM_MESSAGE(1400279, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_REMAIN_PLAYTIME_CENTER_DISPLAY(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400280, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_BUY_SELL_NOT_ENOUGH_AIONJEWELS_TO_BUY_ITEM() {
	return SM_SYSTEM_MESSAGE(1400281, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANT_CHANGE_OPPOSITE_ITEM_SKIN(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400282, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CHANGE_ITEM_SKIN_NOT_SKIN_EXTRACTABLE_ITEM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400283, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GATHER_CANT_EXTEND_MASTER() {
	return SM_SYSTEM_MESSAGE(1400284, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CRAFT_CANT_EXTEND_HIGH_MASTER() {
	return SM_SYSTEM_MESSAGE(1400285, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CRAFT_CANT_EXTEND_GRAND_MASTER() {
	return SM_SYSTEM_MESSAGE(1400286, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMBINE_USAGE_OVER(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400287, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUND_ERROR_MAIN_REQUIRE_HIGHER_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400288, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUND_ERROR_NOT_AVAILABLE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400289, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_CHANGE_SKIN_OPPOSITE_REQUIREMENT(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400290, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SKIN_CHANGE_TIME_EXPIRED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400291, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_PVP_ON() {
	return SM_SYSTEM_MESSAGE(1400292, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_PVP_OFF(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400293, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_BOSS_ATTACKED() {
	return SM_SYSTEM_MESSAGE(1400294, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_BOSS_KILLED(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400295, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DRAGON_BOSS_KILLED() {
	return SM_SYSTEM_MESSAGE(1400296, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_GUILD_WIN_CASTLE(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400297, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_WIN_CASTLE(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400298, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_GUILD_CASTLE_TAKEN(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400299, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_CASTLE_TAKEN(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400300, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GUILD_EVENT_WIN_FIELDARTIFACT(std::string_view value1, std::string_view value0, std::string_view value2) {
	return SM_SYSTEM_MESSAGE(1400301, std::vector<std::string>{std::string(value1), std::string(value0), std::string(value2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GUILD_EVENT_LOSE_FIELDARTIFACT(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400302, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DOOR_ATTACKED() {
	return SM_SYSTEM_MESSAGE(1400303, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DOOR_ATSTAKE() {
	return SM_SYSTEM_MESSAGE(1400304, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DOOR_BROKEN(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400305, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DRAGON_DOOR_BROKEN() {
	return SM_SYSTEM_MESSAGE(1400306, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_REPAIR_ATTACKED() {
	return SM_SYSTEM_MESSAGE(1400307, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_REPAIR_BROKEN(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400308, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DRAGON_REPAIR_BROKEN() {
	return SM_SYSTEM_MESSAGE(1400309, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_CARRIER_SPAWN() {
	return SM_SYSTEM_MESSAGE(1400310, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_CARRIER_DROP_DRAGON() {
	return SM_SYSTEM_MESSAGE(1400311, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_CARRIER_DESPAWN() {
	return SM_SYSTEM_MESSAGE(1400312, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDARTIFACT_CASTING(std::string_view value1, std::string_view value0, std::string_view value2) {
	return SM_SYSTEM_MESSAGE(1400313, std::vector<std::string>{std::string(value1), std::string(value0), std::string(value2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDARTIFACT_CORE_CASTING(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400314, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDARTIFACT_CANCELED(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400315, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDARTIFACT_FIRE(std::string_view value1, std::string_view value0, std::string_view value2) {
	return SM_SYSTEM_MESSAGE(1400316, std::vector<std::string>{std::string(value1), std::string(value0), std::string(value2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_LIGHTBOSS_SPAWN() {
	return SM_SYSTEM_MESSAGE(1400317, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DARKBOSS_SPAWN() {
	return SM_SYSTEM_MESSAGE(1400318, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_LIGHTBOSS_DESPAWN() {
	return SM_SYSTEM_MESSAGE(1400319, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DARKBOSS_DESPAWN() {
	return SM_SYSTEM_MESSAGE(1400320, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_LIGHTBOSS_ATTACKED() {
	return SM_SYSTEM_MESSAGE(1400321, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DARKBOSS_ATTACKED() {
	return SM_SYSTEM_MESSAGE(1400322, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DARKBOSS_KILLED(std::string_view playerName, std::string_view faction) {
	return SM_SYSTEM_MESSAGE(1400323, std::vector<std::string>{std::string(faction), std::string(playerName)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_LIGHTBOSS_KILLED(std::string_view playerName, std::string_view faction) {
	return SM_SYSTEM_MESSAGE(1400324, std::vector<std::string>{std::string(faction), std::string(playerName)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_BARRIER_ATTACKED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400325, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_BARRIER_ATSTAKE(std::string_view value0value) {
	return SM_SYSTEM_MESSAGE(1400326, std::vector<std::string>{std::string(value0value)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_BARRIER_BROKEN(std::string_view value1, std::string_view value0, std::string_view subzone2) {
	return SM_SYSTEM_MESSAGE(1400327, std::vector<std::string>{std::string(value1), std::string(value0), std::string(subzone2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_LIGHTUNDERPASS_SPAWN() {
	return SM_SYSTEM_MESSAGE(1400328, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DARKUNDERPASS_SPAWN() {
	return SM_SYSTEM_MESSAGE(1400329, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_LIGHTUNDERPASS_DESPAWN() {
	return SM_SYSTEM_MESSAGE(1400330, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DARKUNDERPASS_DESPAWN() {
	return SM_SYSTEM_MESSAGE(1400331, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GATHERING_REQUIRE_ITEM() {
	return SM_SYSTEM_MESSAGE(1400332, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_USE_CASH_TYPE_ITEM1(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400333, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_USE_CASH_TYPE_ITEM2(std::string_view value1, std::string_view value0s) {
	return SM_SYSTEM_MESSAGE(1400334, std::vector<std::string>{std::string(value1), std::string(value0s)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUNDED_ITEM_DECOMPOUND_SUCCESS(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400335, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUND_SUCCESS(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400336, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUND_ERROR_NOT_ENOUGH_MONEY(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400337, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WRONG_TARGET_CLASS(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400338, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WRONG_TARGET_RACE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400339, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANT_MAIL_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400340, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANT_WHO_LEVEL(int32_t value0) {
	return SM_SYSTEM_MESSAGE(1400341, std::vector<std::string>{toJavaString(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GET_EXP_VITAL_BONUS(std::string_view value0, int64_t num1, int64_t num2) {
	return SM_SYSTEM_MESSAGE(1400342, std::vector<std::string>{std::string(value0), toJavaString(num1), toJavaString(num2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GET_EXP_MAKEUP_BONUS(std::string_view value0, int64_t num1, int64_t num2) {
	return SM_SYSTEM_MESSAGE(1400343, std::vector<std::string>{std::string(value0), toJavaString(num1), toJavaString(num2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GET_EXP_VITAL_MAKEUP_BONUS(std::string_view value0, int64_t num1, int64_t num2, int64_t num3) {
	return SM_SYSTEM_MESSAGE(1400344, std::vector<std::string>{std::string(value0), toJavaString(num1), toJavaString(num2), toJavaString(num3)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_COMBAT_MY_EXP_GAIN_VITAL_BONUS(std::string_view value0, int32_t num1) {
	return SM_SYSTEM_MESSAGE(1400345, std::vector<std::string>{std::string(value0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_COMBAT_MY_EXP_GAIN_MAKEUP_BONUS(std::string_view value0, int32_t num1) {
	return SM_SYSTEM_MESSAGE(1400346, std::vector<std::string>{std::string(value0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_COMBAT_MY_EXP_GAIN_VITAL_MAKEUP_BONUS(std::string_view value0, int32_t num1, int32_t num2) {
	return SM_SYSTEM_MESSAGE(1400347, std::vector<std::string>{std::string(value0), toJavaString(num1), toJavaString(num2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GET_EXP2_VITAL_BONUS(int64_t num0, int64_t num1) {
	return SM_SYSTEM_MESSAGE(1400348, std::vector<std::string>{toJavaString(num0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GET_EXP2_MAKEUP_BONUS(int64_t num0, int64_t num1) {
	return SM_SYSTEM_MESSAGE(1400349, std::vector<std::string>{toJavaString(num0), toJavaString(num1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_GET_EXP2_VITAL_MAKEUP_BONUS(int64_t num0, int64_t num1, int64_t num2) {
	return SM_SYSTEM_MESSAGE(1400350, std::vector<std::string>{toJavaString(num0), toJavaString(num1), toJavaString(num2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMITED_SALE_CANT_SELECT_OVER_ITEMS() {
	return SM_SYSTEM_MESSAGE(1400351, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMITED_SALE_CANT_SELECT_NO_ITEMS() {
	return SM_SYSTEM_MESSAGE(1400352, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMITED_BUYING_CANT_SELECT_NO_ITEMS() {
	return SM_SYSTEM_MESSAGE(1400353, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMITED_BUYING_CANT_SELECT_OVER_ITEMS() {
	return SM_SYSTEM_MESSAGE(1400354, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WAREHOUSE_CANT_LEGION_DEPOSIT() {
	return SM_SYSTEM_MESSAGE(1400355, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WAREHOUSE_CANT_ACCOUNT_DEPOSIT() {
	return SM_SYSTEM_MESSAGE(1400356, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_DUNGEON_WITH_DIFFICULTY_OPENED(std::string_view worldname1, std::string_view value2, int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400357, std::vector<std::string>{std::string(worldname1), std::string(value2), toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_DUNGEON_OPENED(std::string_view worldname1, int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400358, std::vector<std::string>{std::string(worldname1), toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_DUNGEON_WITH_DIFFICULTY_OPENED_INFO(std::string_view worldname1, std::string_view value2, int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400359, std::vector<std::string>{std::string(worldname1), std::string(value2), toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_DUNGEON_OPENED_INFO(std::string_view worldname1, int32_t num0) {
	return SM_SYSTEM_MESSAGE(1400360, std::vector<std::string>{std::string(worldname1), toJavaString(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_INSTANCE_DUNGEON_CANT_ENTER_NOT_OPENED() {
	return SM_SYSTEM_MESSAGE(1400361, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REQUIRE_IN_INVENTORY() {
	return SM_SYSTEM_MESSAGE(1400362, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DECOMPRESS_INVENTORY_IS_FULL() {
	return SM_SYSTEM_MESSAGE(1400363, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUND_ERROR_DIFFERENT_TYPE() {
	return SM_SYSTEM_MESSAGE(1400364, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_COMPOUND_ERROR_NOT_COMPARABLE_ITEM() {
	return SM_SYSTEM_MESSAGE(1400365, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDTP_FANATIC_Die_Keynamed() {
	return SM_SYSTEM_MESSAGE(1400366, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDTP_FANATIC_DieAll_Keynamed() {
	return SM_SYSTEM_MESSAGE(1400367, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REJECT_WHISPER_FROM_LOW_LEVEL(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400368, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_REJECT_MAIL_FROM_LOW_LEVEL(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400369, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SKIN_CHANGE_TIME_EXPIRED_IN_WAREHOUSE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400370, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANT_CHANGE_SAME_ITEM_SKIN(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400371, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNCHANGE_ITEM_SKIN_SUCCEED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400372, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_DECOMPOUND_ERROR_NOT_AVAILABLE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400373, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_TEST_DESC01(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400374, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_SEND_OVER_MAILS() {
	return SM_SYSTEM_MESSAGE(1400375, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CANT_GATHERING_B_ITEM_CHECK(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400376, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_CANT_SHOUT_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400377, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CHAR_HIDE_AUTO_ON() {
	return SM_SYSTEM_MESSAGE(1400378, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WindPathIN() {
	return SM_SYSTEM_MESSAGE(1400379, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_BombDrakan_TargetMSG() {
	return SM_SYSTEM_MESSAGE(1400380, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_Spectre_Buff() {
	return SM_SYSTEM_MESSAGE(1400381, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_TombDrakan() {
	return SM_SYSTEM_MESSAGE(1400382, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest2_01() {
	return SM_SYSTEM_MESSAGE(1400383, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDAbRe_Core_Oops_Reward_Is_Gone() {
	return SM_SYSTEM_MESSAGE(1400384, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WindPathNoOUT() {
	return SM_SYSTEM_MESSAGE(1400385, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_Summoner_Reflect() {
	return SM_SYSTEM_MESSAGE(1400386, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_Summoner_DeadlyCasting() {
	return SM_SYSTEM_MESSAGE(1400387, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ElementalFire_Buff() {
	return SM_SYSTEM_MESSAGE(1400388, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_TEST_DESC02(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400389, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_TEST_DESC03() {
	return SM_SYSTEM_MESSAGE(1400390, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_TEST_DESC04(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400391, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_OFFER_PARTY_POSTED() {
	return SM_SYSTEM_MESSAGE(1400392, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_SEEK_PARTY_POSTED() {
	return SM_SYSTEM_MESSAGE(1400393, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_POST_DELETED_TOO_OLD() {
	return SM_SYSTEM_MESSAGE(1400394, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_POST_DELETED_ENTERED_PARTY() {
	return SM_SYSTEM_MESSAGE(1400395, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_POST_DELETED_PARTY_FULL() {
	return SM_SYSTEM_MESSAGE(1400396, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_POST_DELETED_PARTY_BROKE() {
	return SM_SYSTEM_MESSAGE(1400397, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_USE_VENDOR(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400398, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_OPEN_PERSONAL_SHOP(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400399, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_TRADE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400400, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_SEND_ITEM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400401, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_USE_WAREHOUSE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400402, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_USE_GUILD_WAREHOUSE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400403, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FREE_EXPERIENCE_CHARACTER_CANT_USE_ACCOUNT_WAREHOUSE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400404, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_BOSS_SPAWN_IDAB1_DREADGION() {
	return SM_SYSTEM_MESSAGE(1400405, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DELETE_CASH_ITEM_BY_TIMEOUT_IN_WAREHOUSE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400406, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_SEARCH_FOUND() {
	return SM_SYSTEM_MESSAGE(1400407, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_10() {
	return SM_SYSTEM_MESSAGE(1400408, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_20() {
	return SM_SYSTEM_MESSAGE(1400409, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_30() {
	return SM_SYSTEM_MESSAGE(1400410, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_40() {
	return SM_SYSTEM_MESSAGE(1400411, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_50() {
	return SM_SYSTEM_MESSAGE(1400412, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_60() {
	return SM_SYSTEM_MESSAGE(1400413, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_70() {
	return SM_SYSTEM_MESSAGE(1400414, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_80() {
	return SM_SYSTEM_MESSAGE(1400415, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_90() {
	return SM_SYSTEM_MESSAGE(1400416, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_91() {
	return SM_SYSTEM_MESSAGE(1400417, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_92() {
	return SM_SYSTEM_MESSAGE(1400418, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_93() {
	return SM_SYSTEM_MESSAGE(1400419, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_94() {
	return SM_SYSTEM_MESSAGE(1400420, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_95() {
	return SM_SYSTEM_MESSAGE(1400421, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_96() {
	return SM_SYSTEM_MESSAGE(1400422, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_97() {
	return SM_SYSTEM_MESSAGE(1400423, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_98() {
	return SM_SYSTEM_MESSAGE(1400424, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_99() {
	return SM_SYSTEM_MESSAGE(1400425, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_COUNT_100() {
	return SM_SYSTEM_MESSAGE(1400426, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_DEATHBLOW_FAIL() {
	return SM_SYSTEM_MESSAGE(1400427, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_BUFF_FIRST_OBJECT_ON() {
	return SM_SYSTEM_MESSAGE(1400428, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_BUFF_SECOND_OBJECT_ON() {
	return SM_SYSTEM_MESSAGE(1400429, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_BUFF_CAN_USE_OBJECT() {
	return SM_SYSTEM_MESSAGE(1400430, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_GODELITE_BUFF_CANT_USE_OBJECT_NOT_ENOUGH_MEMBER() {
	return SM_SYSTEM_MESSAGE(1400431, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_INFORM_INVITE_REJECT_STATE() {
	return SM_SYSTEM_MESSAGE(1400434, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ENCHANT_ITEM_SUCCEEDED_15(std::string_view playerName, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400435, std::vector<std::string>{std::string(playerName), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_GATHERING_DESC01(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400436, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FACTION_JOIN_ERROR_RACE() {
	return SM_SYSTEM_MESSAGE(1400437, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FACTION_JOIN_ERROR_MIN_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400438, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_M_EPIC_SHOP_DESC01(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400439, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_M_EPIC_SHOP_DESC02(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400440, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LIMIT_SALE_EPIC_SHOP_MATERIAL_DESC01(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400441, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDTP_FANATIC_DrakanNamed_SpawnMSG() {
	return SM_SYSTEM_MESSAGE(1400442, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Normal_Stalker_DrainHealth() {
	return SM_SYSTEM_MESSAGE(1400443, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Normal_Stalker_Sanctuary() {
	return SM_SYSTEM_MESSAGE(1400444, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Normal_Slime_Isolation() {
	return SM_SYSTEM_MESSAGE(1400445, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_BoneDrake_Sanctuary() {
	return SM_SYSTEM_MESSAGE(1400446, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_PARTY_MATCH_SEEK_POST_DELETED_ENTERED_PARTY() {
	return SM_SYSTEM_MESSAGE(1400447, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_USE_ITEM_MULTI(std::string_view value1, std::string_view value0s) {
	return SM_SYSTEM_MESSAGE(1400448, std::vector<std::string>{std::string(value1), std::string(value0s)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FATIGUE_INFO_0_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400449, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FATIGUE_INFO_1_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400450, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FATIGUE_INFO_2_LEVEL() {
	return SM_SYSTEM_MESSAGE(1400451, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNCOMPRESS_COMPRESSED_ITEM_SUCCEEDED(std::string_view num0) {
	return SM_SYSTEM_MESSAGE(1400452, std::vector<std::string>{std::string(num0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNCOMPRESS_COMPRESSED_ITEM_CANCELED(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400453, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_Artifact_Light() {
	return SM_SYSTEM_MESSAGE(1400454, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_Artifact_Dark() {
	return SM_SYSTEM_MESSAGE(1400455, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_Artifact_LightBoom() {
	return SM_SYSTEM_MESSAGE(1400456, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_Artifact_DarkBoom() {
	return SM_SYSTEM_MESSAGE(1400457, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MERCENARY_FOLLOWING_CANCELED_BY_TOO_DISTANCE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400458, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_2phase() {
	return SM_SYSTEM_MESSAGE(1400459, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_3phase() {
	return SM_SYSTEM_MESSAGE(1400460, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_4phase() {
	return SM_SYSTEM_MESSAGE(1400461, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_5phase() {
	return SM_SYSTEM_MESSAGE(1400462, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_Boss_ArchPriest_6phase() {
	return SM_SYSTEM_MESSAGE(1400463, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_FATIGUE_UPGRADE_LEVEL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400464, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdSpecter_Spawn() {
	return SM_SYSTEM_MESSAGE(1400465, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdLich_weakness1() {
	return SM_SYSTEM_MESSAGE(1400466, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdLich_weakness2() {
	return SM_SYSTEM_MESSAGE(1400467, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdLich_weakness3() {
	return SM_SYSTEM_MESSAGE(1400468, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdLich_Leave() {
	return SM_SYSTEM_MESSAGE(1400469, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdSpecter_Start() {
	return SM_SYSTEM_MESSAGE(1400470, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_NmdShulack_Rufukin() {
	return SM_SYSTEM_MESSAGE(1400471, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_SHIELD_ATTACKED() {
	return SM_SYSTEM_MESSAGE(1400472, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_SHIELD_BROKEN(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400473, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIELDABYSS_DRAGON_SHIELD_BROKEN() {
	return SM_SYSTEM_MESSAGE(1400474, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDELIM_COCOON_INFO() {
	return SM_SYSTEM_MESSAGE(1400475, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDELIM_EGG_BREAK() {
	return SM_SYSTEM_MESSAGE(1400476, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDELIM_WIND_INFO() {
	return SM_SYSTEM_MESSAGE(1400477, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_RESTRICTED_STATE_CANT_GET_ITEM() {
	return SM_SYSTEM_MESSAGE(1400478, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_RESTRICTED_STATE_CANT_THROW_DICE() {
	return SM_SYSTEM_MESSAGE(1400479, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_IDCatacombs_BigOrb_Spawn() {
	return SM_SYSTEM_MESSAGE(1400480, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_CASH_ITEM_TIME_LEFT(std::string_view value0, int32_t minutes) {
	return SM_SYSTEM_MESSAGE(1400481, std::vector<std::string>{std::string(value0), toJavaString(minutes) + "min"});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_SKIN_CHANGE_TIME_LEFT(std::string_view value1, std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400482, std::vector<std::string>{std::string(value1), std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FACTION_CAN_NOT_RECEIVE_QUEST_TWICE_A_DAY() {
	return SM_SYSTEM_MESSAGE(1400483, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MERCENARY_CANT_ORDER_BY_TOO_DISTANCE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400484, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_JUMP_TRIGGER_ON_INFO() {
	return SM_SYSTEM_MESSAGE(1400485, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WINDBOX_TRIGGER_ON_INFO() {
	return SM_SYSTEM_MESSAGE(1400486, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_120M() {
	return SM_SYSTEM_MESSAGE(1400487, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_90M() {
	return SM_SYSTEM_MESSAGE(1400488, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_60M() {
	return SM_SYSTEM_MESSAGE(1400489, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_30M() {
	return SM_SYSTEM_MESSAGE(1400490, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_15M() {
	return SM_SYSTEM_MESSAGE(1400491, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_10M() {
	return SM_SYSTEM_MESSAGE(1400492, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_5M() {
	return SM_SYSTEM_MESSAGE(1400493, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_3M() {
	return SM_SYSTEM_MESSAGE(1400494, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_2M() {
	return SM_SYSTEM_MESSAGE(1400495, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_1M() {
	return SM_SYSTEM_MESSAGE(1400496, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_30S() {
	return SM_SYSTEM_MESSAGE(1400497, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_15S() {
	return SM_SYSTEM_MESSAGE(1400498, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_10S() {
	return SM_SYSTEM_MESSAGE(1400499, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_5S() {
	return SM_SYSTEM_MESSAGE(1400500, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_4S() {
	return SM_SYSTEM_MESSAGE(1400501, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_3S() {
	return SM_SYSTEM_MESSAGE(1400502, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_2S() {
	return SM_SYSTEM_MESSAGE(1400503, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_1S() {
	return SM_SYSTEM_MESSAGE(1400504, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_OUT_TIMER_0S() {
	return SM_SYSTEM_MESSAGE(1400505, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_120M() {
	return SM_SYSTEM_MESSAGE(1400506, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_90M() {
	return SM_SYSTEM_MESSAGE(1400507, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_60M() {
	return SM_SYSTEM_MESSAGE(1400508, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_30M() {
	return SM_SYSTEM_MESSAGE(1400509, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_15M() {
	return SM_SYSTEM_MESSAGE(1400510, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_10M() {
	return SM_SYSTEM_MESSAGE(1400511, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_5M() {
	return SM_SYSTEM_MESSAGE(1400512, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_3M() {
	return SM_SYSTEM_MESSAGE(1400513, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_2M() {
	return SM_SYSTEM_MESSAGE(1400514, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_1M() {
	return SM_SYSTEM_MESSAGE(1400515, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_30S() {
	return SM_SYSTEM_MESSAGE(1400516, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_15S() {
	return SM_SYSTEM_MESSAGE(1400517, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_10S() {
	return SM_SYSTEM_MESSAGE(1400518, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_5S() {
	return SM_SYSTEM_MESSAGE(1400519, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_4S() {
	return SM_SYSTEM_MESSAGE(1400520, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_3S() {
	return SM_SYSTEM_MESSAGE(1400521, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_2S() {
	return SM_SYSTEM_MESSAGE(1400522, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_1S() {
	return SM_SYSTEM_MESSAGE(1400523, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_OUT_TIMER_0S() {
	return SM_SYSTEM_MESSAGE(1400524, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_LAY_EGG() {
	return SM_SYSTEM_MESSAGE(1400525, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_LAY_EGG() {
	return SM_SYSTEM_MESSAGE(1400526, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_START_1() {
	return SM_SYSTEM_MESSAGE(1400527, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_START_1() {
	return SM_SYSTEM_MESSAGE(1400528, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_GODELITE_START_1() {
	return SM_SYSTEM_MESSAGE(1400529, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_GODELITE_START_2() {
	return SM_SYSTEM_MESSAGE(1400530, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_GODELITE_START_3() {
	return SM_SYSTEM_MESSAGE(1400531, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_GODELITE_START_4() {
	return SM_SYSTEM_MESSAGE(1400532, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_GODELITE_START_1() {
	return SM_SYSTEM_MESSAGE(1400533, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_GODELITE_START_2() {
	return SM_SYSTEM_MESSAGE(1400534, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_GODELITE_START_3() {
	return SM_SYSTEM_MESSAGE(1400535, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_GODELITE_START_4() {
	return SM_SYSTEM_MESSAGE(1400536, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_START_2() {
	return SM_SYSTEM_MESSAGE(1400537, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_START_3() {
	return SM_SYSTEM_MESSAGE(1400538, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_LF4_DRAMATA_START_4() {
	return SM_SYSTEM_MESSAGE(1400539, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_START_2() {
	return SM_SYSTEM_MESSAGE(1400540, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_START_3() {
	return SM_SYSTEM_MESSAGE(1400541, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_DF4_DRAMATA_START_4() {
	return SM_SYSTEM_MESSAGE(1400542, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_BUDDYLIST_BUDDYS_LIST_FULL(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400543, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ENTER_ONLY_FORCE_DON() {
	return SM_SYSTEM_MESSAGE(1400544, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_LEVEL_LIMIT_QUEST_NOT_FINISHED1() {
	return SM_SYSTEM_MESSAGE(1400545, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIND_POS_SUBZONE_FOUND_DEV(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400546, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIND_POS_TOO_FAR_FROM_SUBZONE_DEV(std::string_view value0, std::string_view value2, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400547, std::vector<std::string>{std::string(value0), std::string(value2), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIND_POS_NPC_FOUND_DEV(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400548, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIND_POS_TOO_FAR_FROM_NPC_DEV(std::string_view value0, std::string_view value2, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400549, std::vector<std::string>{std::string(value0), std::string(value2), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIND_POS_NPC_FOUND_IN_OTHER_WORLD_DEV(std::string_view value0, std::string_view value2, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400550, std::vector<std::string>{std::string(value0), std::string(value2), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_FIND_POS_CANT_USE_UNTIL_DELAYTIME() {
	return SM_SYSTEM_MESSAGE(1400551, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_ALARM_REMAIN_ONE_MINUTE(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400552, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_END_OF_EXCHANGE_TIME(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400553, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_WRONG_EXCHANGE_TARGET(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400554, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_EXCHANGE_TIME_OVER(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400555, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_COMPLETE_EXCHANGE(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400556, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_MSG_NOT_ENOUGH_TRADE_MONEY(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400557, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_INVITE_HIM(std::string_view value0, int32_t allianceSize) {
	return SM_SYSTEM_MESSAGE(1400558, std::vector<std::string>{std::string(value0), toJavaString(allianceSize)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_INVITE_HIS_LEADER(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400559, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ENTER_ME(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400560, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ENTER_HIM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400561, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_REJECT_ME(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400562, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_REJECT_HIM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400563, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ALREADY_OTHER_UNION(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400564, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_CANT_ADD_NEW_MEMBER() {
	return SM_SYSTEM_MESSAGE(1400565, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ONLY_LEADER_CAN_INVITE() {
	return SM_SYSTEM_MESSAGE(1400566, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_CANT_INVITE_WHEN_HE_IS_ASKED_QUESTION(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400567, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_CANT_INVITE_SELF() {
	return SM_SYSTEM_MESSAGE(1400568, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_OFFLINE_MEMBER() {
	return SM_SYSTEM_MESSAGE(1400569, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_CANT_INVITE_WHEN_DEAD() {
	return SM_SYSTEM_MESSAGE(1400570, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_LEAVE_ME() {
	return SM_SYSTEM_MESSAGE(1400571, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_LEAVE_HIM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400572, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ONLY_LEADER_CAN_LEAVE() {
	return SM_SYSTEM_MESSAGE(1400573, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_BAN_HIM(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400574, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_BAN_HIS_LEADER(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400575, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_BAN_ME(std::string_view value0) {
	return SM_SYSTEM_MESSAGE(1400576, std::vector<std::string>{std::string(value0)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ONLY_LEADER_CAN_BAN() {
	return SM_SYSTEM_MESSAGE(1400577, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_CANT_BAN_SELF() {
	return SM_SYSTEM_MESSAGE(1400578, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_DISPERSED() {
	return SM_SYSTEM_MESSAGE(1400579, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_CHANGE_LEADER(std::string_view value0, std::string_view value1) {
	return SM_SYSTEM_MESSAGE(1400580, std::vector<std::string>{std::string(value0), std::string(value1)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_HE_IS_NEW_LEADER(std::string_view value0, std::string_view value1, std::string_view value2) {
	return SM_SYSTEM_MESSAGE(1400581, std::vector<std::string>{std::string(value0), std::string(value1), std::string(value2)});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_YOU_BECOME_NEW_LEADER() {
	return SM_SYSTEM_MESSAGE(1400582, std::vector<std::string>{});
}

SM_SYSTEM_MESSAGE SM_SYSTEM_MESSAGE::STR_UNION_ONLY_LEADER_CAN_CHANGE_LEADER() {
	return SM_SYSTEM_MESSAGE(1400583, std::vector<std::string>{});
}

} // namespace aion::gameserver::network::aion::serverpackets
