#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/questEngine/handlers/HandlerResultInfo.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_1345BearerOfBadNews.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Ritsu
 */
class _1345BearerOfBadNews final : public AbstractQuestHandler {
public:
	_1345BearerOfBadNews() : AbstractQuestHandler(1345) {}

	void register_() override {
		qe.registerQuestNpc(204006)->addOnQuestStart(questId); // Demokritos
		qe.registerQuestNpc(204006)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203765)->addOnTalkEvent(questId); // Kreon
		qe.registerQuestItem(182201320, questId); // Tarnished Ring
	}

	HandlerResult onItemUseEvent(QuestEnv& env, Item& item) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
			if (player->isInsideItemUseZone(ZoneName::get("LC1_ITEMUSEAREA_Q1345")))
				return ::aion::gameserver::questEngine::handlers::fromBoolean(useQuestItem(env, item, 1, 2, true, 0, 0, 0));
		}
		return HandlerResult::SUCCESS; // ??
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		int32_t dialogActionId = env.getDialogActionId();
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 204006) { // Demokritos
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 203765) { // Kreon
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0)
							return sendQuestDialog(env, 1352);
						return false;
					case SETPRO1:
						if (var == 0) {
							removeQuestItem(env, 186000015, 1);
							giveQuestItem(env, 182201320, 1);
							return defaultCloseDialog(env, 0, 1);
						}
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 204006)
				return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1345BearerOfBadNews, 1345);

} // namespace aion::gameserver::handlers::quest::eltnen
