#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"
#include "aion/gameserver/world/WorldMapTypeInfo.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_14020OrdersFromEltnen.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Majka
 */
class _14020OrdersFromEltnen final : public AbstractQuestHandler {
public:
	_14020OrdersFromEltnen() : AbstractQuestHandler(14020) {}

	void register_() override {
		qe.registerQuestNpc(203901)->addOnTalkEvent(questId);
		qe.registerOnEnterWorld(questId);
		qe.registerOnLevelChanged(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t targetId = env.getTargetId();
		if (targetId != 203901)
			return false;
		if (qs->getStatus() == QuestStatus::START) {
			if (env.getDialogActionId() == QUEST_SELECT) {
				qs->setStatus(QuestStatus::REWARD);
				updateQuestStatus(env);
				return sendQuestDialog(env, 1011);
			} else
				return sendQuestStartDialog(env);
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			return sendQuestEndDialog(env);
		}
		return false;
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		if (player->getWorldId() == ::aion::gameserver::world::getId(WorldMapType::ELTNEN) && !player->getQuestStateList()->hasQuest(questId))
			return QuestService::startQuest(env);
		return false;
	}

	void onLevelChangedEvent(Player& player) override {
		onEnterWorldEvent(*QuestEnv::create(nullptr, player, questId));
	}
};
AION_QUEST_HANDLER(_14020OrdersFromEltnen, 14020);

} // namespace aion::gameserver::handlers::quest::eltnen
