#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"
#include "aion/gameserver/services/teleport/TeleportService.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_14025CookingUpDisasters.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Majka, Sykra
 */
class _14025CookingUpDisasters final : public AbstractQuestHandler {
private:
	static constexpr std::array<int32_t, 3> mobs{211017, 217090, 232133};

public:
	_14025CookingUpDisasters() : AbstractQuestHandler(14025) {}

	void register_() override {
		std::array<int32_t, 3> npcs{203989, 203901, 204020};
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerOnDie(questId);
		for (int32_t npc : npcs)
			qe.registerQuestNpc(npc)->addOnTalkEvent(questId);
		for (int32_t mob : mobs)
			qe.registerQuestNpc(mob)->addOnKillEvent(questId);
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {14020});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {14020});
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->getStatus() != QuestStatus::START)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		switch (targetId) {
			case 211017:
			case 232133: {
				int32_t killVar1 = qs->getQuestVarById(1);
				if (var == 5 && killVar1 < 4) {
					qs->setQuestVarById(1, killVar1 + 1);
					updateQuestStatus(env);
					return true;
				}
				break;
			}
			case 217090: {
				int32_t killVar2 = qs->getQuestVarById(2);
				if (var == 5 && killVar2 < 1) {
					qs->setQuestVarById(2, killVar2 + 1);
					updateQuestStatus(env);
					return true;
				}
			}
		}
		return false;
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203901) // Telemachus
				if (dialogActionId == USE_OBJECT) {
					return sendQuestDialog(env, 3057);
				}
			return sendQuestEndDialog(env);
		} else if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 203989) { // Tumblusen
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0)
							return sendQuestDialog(env, 1011);
						else if (var == 1)
							return sendQuestDialog(env, 1352);
						else if (var == 4)
							return sendQuestDialog(env, 2034);
						else if (var == 5)
							return sendQuestDialog(env, 2716);
						break;
					case SELECT1_1_1:
						if (var == 0)
							playQuestMovie(env, 183);
						break;
					case SETPRO1:
						if (var == 0)
							return defaultCloseDialog(env, var, var + 1); // 1
						else
							return sendQuestDialog(env, 1352);
					case CHECK_USER_HAS_QUEST_ITEM:
						if (var == 1) {
							if (QuestService::collectItemCheck(env, true)) {
								changeQuestStep(env, var, var + 1, false); // 2
								return sendQuestDialog(env, 1438);
							} else
								return sendQuestDialog(env, 1353);
						}
						return false;
					case SETPRO2:
						if (var == 2)
							return defaultCloseDialog(env, var, var + 1); // 3
						return false;
					case SETPRO4:
						if (var == 4)
							return defaultCloseDialog(env, var, var + 1); // 5
						break;
					case SETPRO6:
						if (var == 5) {
							changeQuestStep(env, 5, 6, true);
							return closeDialogWindow(env);
						}
				}
			} else if (targetId == 204020) { // Mabangtah
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 3)
							return sendQuestDialog(env, 1693);
						if (var == 6)
							return sendQuestDialog(env, 2034);
						else if (var == 10)
							return sendQuestDialog(env, 3057);
						break;
					case SETPRO3:
						if (var == 3) {
							TeleportService::teleportTo(*player, 210020000, 1761.0742f, 907.1806f, 427.8147f, static_cast<int8_t>(47), TeleportAnimation::FADE_OUT_BEAM);
							qs->setQuestVar(4);
							updateQuestStatus(env);
							return true;
						}
						break;
					case SETPRO7:
						return defaultCloseDialog(env, 10, 10, true, false); // reward
				}
			}
		}
		return false;
	}

	bool onDieEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);

		if (qs->getStatus() == QuestStatus::START) {
			if (var >= 7 && var <= 10) {
				qs->setQuestVarById(0, 6); // 6
				updateQuestStatus(env);
				return true;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_14025CookingUpDisasters, 14025);

} // namespace aion::gameserver::handlers::quest::eltnen
