#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_1414OperationWindmill.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Xitanium
 */
class _1414OperationWindmill final : public AbstractQuestHandler {
public:
	_1414OperationWindmill() : AbstractQuestHandler(1414) {}

	void register_() override {
		qe.registerQuestNpc(203989)->addOnQuestStart(questId); // Tumblusen
		qe.registerQuestNpc(203989)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700175)->addOnTalkEvent(questId); // Old Gear
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203989) { // Tumblusen
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else if (env.getDialogActionId() == QUEST_ACCEPT_1) {
					if (giveQuestItem(env, 182201349, 1))
						return sendQuestStartDialog(env);
					else
						return true;
				} else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			return sendQuestEndDialog(env);
		} else if (qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 0) {
			switch (targetId) {
				case 700175: // Old Gear
					if (qs->getQuestVarById(0) == 0 && env.getDialogActionId() == USE_OBJECT) {
						qs->setQuestVar(1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						removeQuestItem(env, 182201349, 1);
						return true;
					}
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1414OperationWindmill, 1414);

} // namespace aion::gameserver::handlers::quest::eltnen
