#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_1452DoubtfulCharacters.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author MrPoke, Xitanium
 */
class _1452DoubtfulCharacters final : public AbstractQuestHandler {
public:
	_1452DoubtfulCharacters() : AbstractQuestHandler(1452) {}

	void register_() override {
		qe.registerQuestNpc(203934)->addOnQuestStart(questId);
		qe.registerQuestNpc(203934)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203834)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203704)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (targetId == 203934) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			}
		} else if (targetId == 203834) {
			if (qs != nullptr && qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 0) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else if (env.getDialogActionId() == SETPRO1) {
					qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
					updateQuestStatus(env);
					PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
					return true;
				} else
					return sendQuestStartDialog(env);
			}
		} else if (targetId == 203704) {
			if (qs != nullptr) {
				if (env.getDialogActionId() == QUEST_SELECT && qs->getStatus() == QuestStatus::START)
					return sendQuestDialog(env, 2375);
				else if (env.getDialogActionId() == SELECT_QUEST_REWARD && qs->getStatus() != QuestStatus::COMPLETE) {
					qs->setQuestVar(2);
					qs->setStatus(QuestStatus::REWARD);
					updateQuestStatus(env);
					return sendQuestEndDialog(env);
				} else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1452DoubtfulCharacters, 1452);

} // namespace aion::gameserver::handlers::quest::eltnen
