#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestItems.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_1483HarumonerksRequest.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author MrPoke, Xitanium
 */
class _1483HarumonerksRequest final : public AbstractQuestHandler {
public:
	_1483HarumonerksRequest() : AbstractQuestHandler(1483) {}

	void register_() override {
		qe.registerQuestNpc(798126)->addOnQuestStart(questId);
		qe.registerQuestNpc(798126)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203940)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203944)->addOnTalkEvent(questId);
		qe.registerQuestNpc(798127)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (targetId == 798126) {
			if (qs == nullptr || qs->isStartable()) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else
					return sendQuestStartDialog(env);
			}
		} else if (targetId == 203940) {
			if (qs != nullptr && qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 0) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1352);
				else if (env.getDialogActionId() == SETPRO1) {
					changeQuestStep(env, 0, 1);
					giveQuestItem(env, workItems->get(0)->getItemId(), workItems->get(0)->getCount());
					return closeDialogWindow(env);
				}
			}
		} else if (targetId == 203944) {
			if (qs != nullptr && qs->getStatus() == QuestStatus::START && qs->getQuestVarById(0) == 1) {
				if (env.getDialogActionId() == QUEST_SELECT)
					return sendQuestDialog(env, 1693);
				else if (env.getDialogActionId() == SETPRO2) {
					changeQuestStep(env, 1, 2);
					giveQuestItem(env, workItems->get(workItems->size() - 1)->getItemId(), workItems->get(workItems->size() - 1)->getCount());
					return closeDialogWindow(env);
				}
			}
		} else if (targetId == 798127) {
			if (qs != nullptr) {
				if (env.getDialogActionId() == QUEST_SELECT && qs->getStatus() == QuestStatus::START)
					return sendQuestDialog(env, 2375);
				else if (env.getDialogActionId() == SELECT_QUEST_REWARD && qs->getStatus() != QuestStatus::COMPLETE)
					changeQuestStep(env, 2, 3, true);
				return sendQuestEndDialog(env);
			}
		}
		return AbstractQuestHandler::onDialogEvent(env);
	}
};
AION_QUEST_HANDLER(_1483HarumonerksRequest, 1483);

} // namespace aion::gameserver::handlers::quest::eltnen
