#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/teleport/TeleportService.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_1482ATeleportationAdventure.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Balthazar
 */
class _1482ATeleportationAdventure final : public AbstractQuestHandler {
public:
	_1482ATeleportationAdventure() : AbstractQuestHandler(1482) {}

	void register_() override {
		qe.registerQuestNpc(203919)->addOnQuestStart(questId);
		qe.registerQuestNpc(203919)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203337)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203919) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 4762);
				} else
					return sendQuestStartDialog(env);
			}
		}
		if (qs == nullptr)
			return false;

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 203337:
					switch (env.getDialogActionId()) {
						case QUEST_SELECT:
							{
								switch (qs->getQuestVarById(0)) {
									case 0:
										{
											return sendQuestDialog(env, 1011);
										}
									case 1:
										{
											return sendQuestDialog(env, 1352);
										}
									case 2:
										{
											return sendQuestDialog(env, 1693);
										}
									case 3:
										{
											return sendQuestDialog(env, 10002);
										}
								}
								return false;
							}
						case SETPRO1:
							{
								qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
								updateQuestStatus(env);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
								return true;
							}
						case SETPRO3:
							{
								qs->setQuestVar(3);
								qs->setStatus(QuestStatus::REWARD);
								updateQuestStatus(env);
								TeleportService::teleportTo(*player, 220020000, 1, 638, 2337, 425, static_cast<int8_t>(20));
								return true;
							}
						case CHECK_USER_HAS_QUEST_ITEM:
							{
								int64_t itemCount1 = player->getInventory().getItemCountByItemId(182201399);
								if (itemCount1 >= 3) {
									removeQuestItem(env, 182201399, itemCount1);
									changeQuestStep(env, 1, 2);
									return sendQuestDialog(env, 10000);
								} else
									return sendQuestDialog(env, 10001);
							}
						default:
							return sendQuestStartDialog(env);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203337) {
				if (env.getDialogActionId() == SELECT_QUEST_REWARD)
					return sendQuestDialog(env, 5);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1482ATeleportationAdventure, 1482);

} // namespace aion::gameserver::handlers::quest::eltnen
