#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::eltnen {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/eltnen/_3326TheShugoMenace.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Balthazar
 */
class _3326TheShugoMenace final : public AbstractQuestHandler {
public:
	_3326TheShugoMenace() : AbstractQuestHandler(3326) {}

	void register_() override {
		qe.registerQuestNpc(798053)->addOnQuestStart(questId);
		qe.registerQuestNpc(798053)->addOnTalkEvent(questId);
		qe.registerQuestNpc(210897)->addOnKillEvent(questId);
		qe.registerQuestNpc(210939)->addOnKillEvent(questId);
		qe.registerQuestNpc(210873)->addOnKillEvent(questId);
		qe.registerQuestNpc(210919)->addOnKillEvent(questId);
		qe.registerQuestNpc(211754)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 798053) {
				if (env.getDialogActionId() == QUEST_SELECT) {
					return sendQuestDialog(env, 4);
				} else
					return sendQuestStartDialog(env);
			}
		}

		if (qs == nullptr)
			return false;

		if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 798053) {
				switch (env.getDialogActionId()) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 10002);
					case SELECT_QUEST_REWARD:
						if (qs->getQuestVarById(0) != 20) {
							return false;
						}
						qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestEndDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 798053) {
				if (env.getDialogActionId() == SELECT_QUEST_REWARD)
					return sendQuestDialog(env, 5);
				else
					return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->getStatus() != QuestStatus::START)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();

		if (targetId == 210897 || targetId == 210939 || targetId == 210873 || targetId == 210919 || targetId == 211754) {
			if (var >= 0 && var < 20) {
				qs->setQuestVarById(0, var + 1);
				updateQuestStatus(env);
				return true;
			}
		}
		return false;
	}
};
AION_QUEST_HANDLER(_3326TheShugoMenace, 3326);

} // namespace aion::gameserver::handlers::quest::eltnen
