#pragma once

// Prelude of the admin chat command handlers (data/handlers/admincommands; the three command packages form one library, aion_gs_handlers_commands).
// A prelude holds the core names of its category as using-declarations in the category namespace, e.g. `using gameserver::ai::NpcAI;`
// (handlers-and-porting-plan.md §1.2). It is identical for every file of the category, so unity batches may include it any number of times.
// Handler files include it first; it also provides the registration markers and AION_UNPORTED. The handler file rules apply
// (aion_gs_regscan): declarations only inside the namespace of this directory, no namespace-scope `static`, no other namespaces.
// Each command package has its own prelude: a using-declaration here and a command class of the same name in this package (Pet, Event,
// SysMail, WorldRaid) are a compile error in every build, instead of lookup that depends on the unity batch. Such a name is not re-exported;
// the commands spell the core type qualified (test_handler_preludes checks the names against the Java classes of the package).
// Using-declarations (S0b): every core type that the Java files of the category import, when a forward header declares it, its simple
// name comes from one package only and no Java type of the category has that name (nested types are spelled Outer::Inner or
// Outer_Inner). The prelude includes the full headers of the category's handler base classes, the generated headers of the
// re-exported enums, the full hub headers the category's handlers use most (Player, Npc, PacketSendUtility, ...; spine freeze) and the forward
// headers of the rest.

#include "aion/gameserver/runtime/base/Unported.h"
#include "aion/gameserver/ai/AIState.h"
#include "aion/gameserver/ai/event/AIEventType.h"
#include "aion/gameserver/ai/event/fwd.h"
#include "aion/gameserver/ai/fwd.h"
#include "aion/gameserver/cache/fwd.h"
#include "aion/gameserver/configs/administration/fwd.h"
#include "aion/gameserver/configs/fwd.h"
#include "aion/gameserver/configs/main/fwd.h"
#include "aion/gameserver/controllers/movement/fwd.h"
#include "aion/gameserver/custom/instance/CustomInstanceRankEnum.h"
#include "aion/gameserver/custom/instance/fwd.h"
#include "aion/gameserver/dao/fwd.h"
#include "aion/gameserver/dataholders/fwd.h"
#include "aion/gameserver/geoEngine/collision/CollisionIntention.h"
#include "aion/gameserver/geoEngine/collision/fwd.h"
#include "aion/gameserver/handlers/HandlerRegistry.h"
#include "aion/gameserver/model/ChatType.h"
#include "aion/gameserver/model/PlayerClass.h"
#include "aion/gameserver/model/Race.h"
#include "aion/gameserver/model/SkillElement.h"
#include "aion/gameserver/model/animations/ObjectDeleteAnimation.h"
#include "aion/gameserver/model/animations/TeleportAnimation.h"
#include "aion/gameserver/model/animations/fwd.h"
#include "aion/gameserver/model/assemblednpc/fwd.h"
#include "aion/gameserver/model/autogroup/AutoGroupType.h"
#include "aion/gameserver/model/autogroup/fwd.h"
#include "aion/gameserver/model/base/BaseOccupier.h"
#include "aion/gameserver/model/base/fwd.h"
#include "aion/gameserver/model/craft/Profession.h"
#include "aion/gameserver/model/craft/fwd.h"
#include "aion/gameserver/model/drop/fwd.h"
#include "aion/gameserver/model/enchants/fwd.h"
#include "aion/gameserver/model/event/fwd.h"
#include "aion/gameserver/model/fwd.h"
#include "aion/gameserver/model/gameobjects/LetterType.h"
#include "aion/gameserver/model/gameobjects/fwd.h"
#include "aion/gameserver/model/gameobjects/player/CustomPlayerState.h"
#include "aion/gameserver/model/gameobjects/player/Player.h"
#include "aion/gameserver/model/gameobjects/player/fwd.h"
#include "aion/gameserver/model/gameobjects/player/npcFaction/ENpcFactionQuestState.h"
#include "aion/gameserver/model/gameobjects/player/npcFaction/fwd.h"
#include "aion/gameserver/model/gameobjects/siege/fwd.h"
#include "aion/gameserver/model/gameobjects/state/CreatureSeeState.h"
#include "aion/gameserver/model/gameobjects/state/CreatureState.h"
#include "aion/gameserver/model/gameobjects/state/CreatureVisualState.h"
#include "aion/gameserver/model/gameobjects/state/fwd.h"
#include "aion/gameserver/model/house/fwd.h"
#include "aion/gameserver/model/items/fwd.h"
#include "aion/gameserver/model/items/storage/fwd.h"
#include "aion/gameserver/model/siege/SiegeRace.h"
#include "aion/gameserver/model/siege/SiegeType.h"
#include "aion/gameserver/model/siege/fwd.h"
#include "aion/gameserver/model/skill/fwd.h"
#include "aion/gameserver/model/stats/calc/functions/fwd.h"
#include "aion/gameserver/model/stats/calc/fwd.h"
#include "aion/gameserver/model/stats/container/StatEnum.h"
#include "aion/gameserver/model/stats/container/fwd.h"
#include "aion/gameserver/model/stats/listeners/fwd.h"
#include "aion/gameserver/model/team/alliance/fwd.h"
#include "aion/gameserver/model/team/fwd.h"
#include "aion/gameserver/model/team/group/fwd.h"
#include "aion/gameserver/model/team/legion/fwd.h"
#include "aion/gameserver/model/templates/assemblednpc/fwd.h"
#include "aion/gameserver/model/templates/event/fwd.h"
#include "aion/gameserver/model/templates/fwd.h"
#include "aion/gameserver/model/templates/globaldrops/fwd.h"
#include "aion/gameserver/model/templates/housing/HouseType.h"
#include "aion/gameserver/model/templates/housing/fwd.h"
#include "aion/gameserver/model/templates/item/actions/fwd.h"
#include "aion/gameserver/model/templates/item/enums/ItemGroup.h"
#include "aion/gameserver/model/templates/item/enums/fwd.h"
#include "aion/gameserver/model/templates/item/fwd.h"
#include "aion/gameserver/model/templates/itemset/fwd.h"
#include "aion/gameserver/model/templates/npc/fwd.h"
#include "aion/gameserver/model/templates/npcskill/fwd.h"
#include "aion/gameserver/model/templates/pet/fwd.h"
#include "aion/gameserver/model/templates/quest/fwd.h"
#include "aion/gameserver/model/templates/rewards/fwd.h"
#include "aion/gameserver/model/templates/spawns/fwd.h"
#include "aion/gameserver/model/templates/stats/fwd.h"
#include "aion/gameserver/model/templates/walker/fwd.h"
#include "aion/gameserver/model/templates/world/fwd.h"
#include "aion/gameserver/model/templates/worldraid/fwd.h"
#include "aion/gameserver/model/templates/zone/ZoneClassName.h"
#include "aion/gameserver/model/templates/zone/ZoneType.h"
#include "aion/gameserver/model/templates/zone/fwd.h"
#include "aion/gameserver/model/vortex/fwd.h"
#include "aion/gameserver/network/aion/clientpackets/fwd.h"
#include "aion/gameserver/network/aion/fwd.h"
#include "aion/gameserver/network/aion/serverpackets/fwd.h"
#include "aion/gameserver/network/fwd.h"
#include "aion/gameserver/network/loginserver/fwd.h"
#include "aion/gameserver/questEngine/fwd.h"
#include "aion/gameserver/questEngine/handlers/models/fwd.h"
#include "aion/gameserver/questEngine/model/QuestStatus.h"
#include "aion/gameserver/questEngine/model/fwd.h"
#include "aion/gameserver/restrictions/fwd.h"
#include "aion/gameserver/services/abyss/fwd.h"
#include "aion/gameserver/services/ban/fwd.h"
#include "aion/gameserver/services/craft/fwd.h"
#include "aion/gameserver/services/drop/fwd.h"
#include "aion/gameserver/services/event/fwd.h"
#include "aion/gameserver/services/fwd.h"
#include "aion/gameserver/services/instance/fwd.h"
#include "aion/gameserver/services/item/fwd.h"
#include "aion/gameserver/services/mail/fwd.h"
#include "aion/gameserver/services/panesterra/fwd.h"
#include "aion/gameserver/services/player/fwd.h"
#include "aion/gameserver/services/siege/fwd.h"
#include "aion/gameserver/services/teleport/fwd.h"
#include "aion/gameserver/services/toypet/fwd.h"
#include "aion/gameserver/skillengine/effect/AbnormalState.h"
#include "aion/gameserver/skillengine/effect/fwd.h"
#include "aion/gameserver/skillengine/fwd.h"
#include "aion/gameserver/skillengine/model/DispelSlotType.h"
#include "aion/gameserver/skillengine/model/fwd.h"
#include "aion/gameserver/spawnengine/SpawnHandlerType.h"
#include "aion/gameserver/spawnengine/fwd.h"
#include "aion/gameserver/utils/PacketSendUtility.h"
#include "aion/gameserver/utils/chathandlers/AdminCommand.h"
#include "aion/gameserver/utils/chathandlers/fwd.h"
#include "aion/gameserver/utils/collections/fwd.h"
#include "aion/gameserver/utils/fwd.h"
#include "aion/gameserver/utils/idfactory/fwd.h"
#include "aion/gameserver/utils/stats/CalculationType.h"
#include "aion/gameserver/utils/stats/fwd.h"
#include "aion/gameserver/utils/time/fwd.h"
#include "aion/gameserver/utils/time/gametime/fwd.h"
#include "aion/gameserver/utils/xml/fwd.h"
#include "aion/gameserver/world/World.h"
#include "aion/gameserver/world/WorldDropType.h"
#include "aion/gameserver/world/WorldMapType.h"
#include "aion/gameserver/world/fwd.h"
#include "aion/gameserver/world/geo/fwd.h"
#include "aion/gameserver/world/zone/fwd.h"

namespace aion::gameserver::handlers::admincommands {

using ::aion::gameserver::ai::AIEngine;
using ::aion::gameserver::ai::AIState;
using ::aion::gameserver::ai::event::AIEventLog;
using ::aion::gameserver::ai::event::AIEventType;
using ::aion::gameserver::cache::HTMLCache;
using ::aion::gameserver::configs::Config;
using ::aion::gameserver::configs::administration::AdminConfig;
using ::aion::gameserver::configs::main::AIConfig;
using ::aion::gameserver::configs::main::EventsConfig;
using ::aion::gameserver::configs::main::GSConfig;
using ::aion::gameserver::configs::main::GeoDataConfig;
using ::aion::gameserver::configs::main::NameConfig;
using ::aion::gameserver::configs::main::ShutdownConfig;
using ::aion::gameserver::controllers::movement::MovementMask;
using ::aion::gameserver::custom::instance::CustomInstanceRankEnum;
using ::aion::gameserver::custom::instance::CustomInstanceService;
using ::aion::gameserver::dao::BookmarkDAO;
using ::aion::gameserver::dao::HeadhuntingDAO;
using ::aion::gameserver::dao::OldNamesDAO;
using ::aion::gameserver::dao::PlayerDAO;
using ::aion::gameserver::dao::PlayerPasskeyDAO;
using ::aion::gameserver::dataholders::DataManager;
using ::aion::gameserver::dataholders::WalkerData;
using ::aion::gameserver::geoEngine::collision::CollisionIntention;
using ::aion::gameserver::geoEngine::collision::CollisionResult;
using ::aion::gameserver::geoEngine::collision::CollisionResults;
using ::aion::gameserver::model::Announcement;
using ::aion::gameserver::model::ChatType;
using ::aion::gameserver::model::PlayerClass;
using ::aion::gameserver::model::Race;
using ::aion::gameserver::model::SkillElement;
using ::aion::gameserver::model::animations::ObjectDeleteAnimation;
using ::aion::gameserver::model::animations::TeleportAnimation;
using ::aion::gameserver::model::assemblednpc::AssembledNpc;
using ::aion::gameserver::model::assemblednpc::AssembledNpcPart;
using ::aion::gameserver::model::autogroup::AutoGroupType;
using ::aion::gameserver::model::base::Base;
using ::aion::gameserver::model::base::BaseLocation;
using ::aion::gameserver::model::base::BaseOccupier;
using ::aion::gameserver::model::craft::Profession;
using ::aion::gameserver::model::drop::Drop;
using ::aion::gameserver::model::drop::DropGroup;
using ::aion::gameserver::model::drop::DropModifiers;
using ::aion::gameserver::model::drop::NpcDrop;
using ::aion::gameserver::model::enchants::EnchantEffect;
using ::aion::gameserver::model::event::Headhunter;
using ::aion::gameserver::model::gameobjects::Creature;
using ::aion::gameserver::model::gameobjects::Gatherable;
using ::aion::gameserver::model::gameobjects::HouseObject;
using ::aion::gameserver::model::gameobjects::Item;
using ::aion::gameserver::model::gameobjects::LetterType;
using ::aion::gameserver::model::gameobjects::Npc;
using ::aion::gameserver::model::gameobjects::VisibleObject;
using ::aion::gameserver::model::gameobjects::player::CustomPlayerState;
using ::aion::gameserver::model::gameobjects::player::Player;
using ::aion::gameserver::model::gameobjects::player::PlayerCommonData;
using ::aion::gameserver::model::gameobjects::player::npcFaction::ENpcFactionQuestState;
using ::aion::gameserver::model::gameobjects::player::npcFaction::NpcFaction;
using ::aion::gameserver::model::gameobjects::siege::SiegeNpc;
using ::aion::gameserver::model::gameobjects::state::CreatureSeeState;
using ::aion::gameserver::model::gameobjects::state::CreatureState;
using ::aion::gameserver::model::gameobjects::state::CreatureVisualState;
using ::aion::gameserver::model::house::House;
using ::aion::gameserver::model::items::ItemCooldown;
using ::aion::gameserver::model::items::ItemId;
using ::aion::gameserver::model::items::ManaStone;
using ::aion::gameserver::model::items::storage::Storage;
using ::aion::gameserver::model::siege::FortressLocation;
using ::aion::gameserver::model::siege::SiegeLocation;
using ::aion::gameserver::model::siege::SiegeRace;
using ::aion::gameserver::model::siege::SiegeType;
using ::aion::gameserver::model::skill::PlayerSkillEntry;
using ::aion::gameserver::model::skill::PlayerSkillList;
using ::aion::gameserver::model::stats::calc::Stat2;
using ::aion::gameserver::model::stats::calc::StatOwner;
using ::aion::gameserver::model::stats::calc::functions::IStatFunction;
using ::aion::gameserver::model::stats::container::PlayerGameStats;
using ::aion::gameserver::model::stats::container::StatEnum;
using ::aion::gameserver::model::stats::listeners::ItemEquipmentListener;
using ::aion::gameserver::model::team::TemporaryPlayerTeam;
using ::aion::gameserver::model::team::alliance::PlayerAllianceService;
using ::aion::gameserver::model::team::group::PlayerGroupService;
using ::aion::gameserver::model::team::legion::Legion;
using ::aion::gameserver::model::team::legion::LegionMember;
using ::aion::gameserver::model::templates::L10n;
using ::aion::gameserver::model::templates::QuestTemplate;
using ::aion::gameserver::model::templates::TitleTemplate;
using ::aion::gameserver::model::templates::assemblednpc::AssembledNpcTemplate;
using ::aion::gameserver::model::templates::event::EventTemplate;
using ::aion::gameserver::model::templates::globaldrops::GlobalDropItem;
using ::aion::gameserver::model::templates::globaldrops::GlobalRule;
using ::aion::gameserver::model::templates::housing::HouseType;
using ::aion::gameserver::model::templates::housing::PlaceableHouseObject;
using ::aion::gameserver::model::templates::item::ItemTemplate;
using ::aion::gameserver::model::templates::item::actions::AbstractItemAction;
using ::aion::gameserver::model::templates::item::actions::ItemActions;
using ::aion::gameserver::model::templates::item::actions::MegaphoneAction;
using ::aion::gameserver::model::templates::item::actions::SummonHouseObjectAction;
using ::aion::gameserver::model::templates::item::actions::TamperingAction;
using ::aion::gameserver::model::templates::item::enums::ItemGroup;
using ::aion::gameserver::model::templates::itemset::ItemPart;
using ::aion::gameserver::model::templates::itemset::ItemSetTemplate;
using ::aion::gameserver::model::templates::npc::NpcTemplate;
using ::aion::gameserver::model::templates::npcskill::NpcSkillTemplate;
using ::aion::gameserver::model::templates::npcskill::NpcSkillTemplates;
using ::aion::gameserver::model::templates::pet::PetFunction;
using ::aion::gameserver::model::templates::pet::PetTemplate;
using ::aion::gameserver::model::templates::quest::FinishedQuestCond;
using ::aion::gameserver::model::templates::quest::XMLStartCondition;
using ::aion::gameserver::model::templates::rewards::RewardItem;
using ::aion::gameserver::model::templates::spawns::SpawnGroup;
using ::aion::gameserver::model::templates::spawns::SpawnTemplate;
using ::aion::gameserver::model::templates::stats::ModifiersTemplate;
using ::aion::gameserver::model::templates::walker::RouteStep;
using ::aion::gameserver::model::templates::walker::WalkerTemplate;
using ::aion::gameserver::model::templates::world::WeatherEntry;
using ::aion::gameserver::model::templates::worldraid::WorldRaidLocation;
using ::aion::gameserver::model::templates::zone::ZoneClassName;
using ::aion::gameserver::model::templates::zone::ZoneType;
using ::aion::gameserver::model::vortex::VortexLocation;
using ::aion::gameserver::network::BannedMacManager;
using ::aion::gameserver::network::aion::AionConnection;
using ::aion::gameserver::network::aion::clientpackets::CM_APPEARANCE;
using ::aion::gameserver::network::aion::serverpackets::SM_ABNORMAL_STATE;
using ::aion::gameserver::network::aion::serverpackets::SM_CUSTOM_PACKET;
using ::aion::gameserver::network::aion::serverpackets::SM_DELETE;
using ::aion::gameserver::network::aion::serverpackets::SM_DIALOG_WINDOW;
using ::aion::gameserver::network::aion::serverpackets::SM_GAME_TIME;
using ::aion::gameserver::network::aion::serverpackets::SM_GATHERABLE_INFO;
using ::aion::gameserver::network::aion::serverpackets::SM_ITEM_COOLDOWN;
using ::aion::gameserver::network::aion::serverpackets::SM_MEGAPHONE;
using ::aion::gameserver::network::aion::serverpackets::SM_MESSAGE;
using ::aion::gameserver::network::aion::serverpackets::SM_NPC_ASSEMBLER;
using ::aion::gameserver::network::aion::serverpackets::SM_NPC_INFO;
using ::aion::gameserver::network::aion::serverpackets::SM_PLAYER_STATE;
using ::aion::gameserver::network::aion::serverpackets::SM_PLAY_MOVIE;
using ::aion::gameserver::network::aion::serverpackets::SM_POSITION;
using ::aion::gameserver::network::aion::serverpackets::SM_QUEST_ACTION;
using ::aion::gameserver::network::aion::serverpackets::SM_QUEST_COMPLETED_LIST;
using ::aion::gameserver::network::aion::serverpackets::SM_RESURRECT;
using ::aion::gameserver::network::aion::serverpackets::SM_SKILL_COOLDOWN;
using ::aion::gameserver::network::aion::serverpackets::SM_STATS_INFO;
using ::aion::gameserver::network::aion::serverpackets::SM_STATUPDATE_EXP;
using ::aion::gameserver::network::aion::serverpackets::SM_SYSTEM_MESSAGE;
using ::aion::gameserver::network::aion::serverpackets::SM_UPDATE_PLAYER_APPEARANCE;
using ::aion::gameserver::network::loginserver::LoginServer;
using ::aion::gameserver::questEngine::QuestEngine;
using ::aion::gameserver::questEngine::handlers::models::XMLQuest;
using ::aion::gameserver::questEngine::model::QuestEnv;
using ::aion::gameserver::questEngine::model::QuestState;
using ::aion::gameserver::questEngine::model::QuestStatus;
using ::aion::gameserver::restrictions::PlayerRestrictions;
using ::aion::gameserver::services::AdminService;
using ::aion::gameserver::services::AnnouncementService;
using ::aion::gameserver::services::BaseService;
using ::aion::gameserver::services::ClassChangeService;
using ::aion::gameserver::services::CommandsAccessService;
using ::aion::gameserver::services::CubeExpandService;
using ::aion::gameserver::services::EnchantService;
using ::aion::gameserver::services::GameTimeService;
using ::aion::gameserver::services::HTMLService;
using ::aion::gameserver::services::HousingBidService;
using ::aion::gameserver::services::HousingService;
using ::aion::gameserver::services::LegionService;
using ::aion::gameserver::services::NameRestrictionService;
using ::aion::gameserver::services::PunishmentService;
using ::aion::gameserver::services::PvpService;
using ::aion::gameserver::services::QuestService;
using ::aion::gameserver::services::RiftService;
using ::aion::gameserver::services::SiegeService;
using ::aion::gameserver::services::SkillLearnService;
using ::aion::gameserver::services::TownService;
using ::aion::gameserver::services::VortexService;
using ::aion::gameserver::services::WeatherService;
using ::aion::gameserver::services::WorldRaidService;
using ::aion::gameserver::services::abyss::AbyssPointsService;
using ::aion::gameserver::services::abyss::AbyssRankUpdateService;
using ::aion::gameserver::services::abyss::GloryPointsService;
using ::aion::gameserver::services::ban::ChatBanService;
using ::aion::gameserver::services::ban::HDDBanService;
using ::aion::gameserver::services::craft::RelinquishCraftStatus;
using ::aion::gameserver::services::drop::DropRegistrationService;
using ::aion::gameserver::services::event::EventService;
using ::aion::gameserver::services::instance::InstanceService;
using ::aion::gameserver::services::instance::PeriodicInstanceManager;
using ::aion::gameserver::services::item::ItemPacketService;
using ::aion::gameserver::services::item::ItemService;
using ::aion::gameserver::services::item::ItemSocketService;
using ::aion::gameserver::services::mail::MailFormatter;
using ::aion::gameserver::services::mail::SystemMailService;
using ::aion::gameserver::services::panesterra::PanesterraService;
using ::aion::gameserver::services::player::PlayerReviveService;
using ::aion::gameserver::services::player::PlayerService;
using ::aion::gameserver::services::player::SecurityTokenService;
using ::aion::gameserver::services::siege::BalaurAssaultService;
using ::aion::gameserver::services::teleport::TeleportService;
using ::aion::gameserver::services::toypet::PetAdoptionService;
using ::aion::gameserver::skillengine::SkillEngine;
using ::aion::gameserver::skillengine::effect::AbnormalState;
using ::aion::gameserver::skillengine::model::DispelSlotType;
using ::aion::gameserver::skillengine::model::Effect;
using ::aion::gameserver::skillengine::model::Skill;
using ::aion::gameserver::skillengine::model::SkillTemplate;
using ::aion::gameserver::spawnengine::ClusteredNpc;
using ::aion::gameserver::spawnengine::SpawnEngine;
using ::aion::gameserver::spawnengine::SpawnHandlerType;
using ::aion::gameserver::utils::ChatUtil;
using ::aion::gameserver::utils::PacketSendUtility;
using ::aion::gameserver::utils::PositionUtil;
using ::aion::gameserver::utils::ThreadPoolManager;
using ::aion::gameserver::utils::Util;
using ::aion::gameserver::utils::chathandlers::AdminCommand;
using ::aion::gameserver::utils::chathandlers::ChatProcessor;
using ::aion::gameserver::utils::collections::Predicates;
using ::aion::gameserver::utils::idfactory::IDFactory;
using ::aion::gameserver::utils::stats::CalculationType;
using ::aion::gameserver::utils::stats::StatFunctions;
using ::aion::gameserver::utils::time::ServerTime;
using ::aion::gameserver::utils::time::gametime::GameTime;
using ::aion::gameserver::utils::xml::JAXBUtil;
using ::aion::gameserver::utils::xml::XmlUtil;
using ::aion::gameserver::world::World;
using ::aion::gameserver::world::WorldDropType;
using ::aion::gameserver::world::WorldMapInstance;
using ::aion::gameserver::world::WorldMapType;
using ::aion::gameserver::world::WorldPosition;
using ::aion::gameserver::world::geo::GeoService;
using ::aion::gameserver::world::zone::ZoneInstance;
using ::aion::gameserver::world::zone::ZoneName;

} // namespace aion::gameserver::handlers::admincommands
