#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/items/storage/Storage.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/world/WorldMapInstance.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_2223AMythicalMonster.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Mr. Poke, Gigi, vlog
 */
class _2223AMythicalMonster final : public AbstractQuestHandler {
public:
	_2223AMythicalMonster() : AbstractQuestHandler(2223) {}

	void register_() override {
		qe.registerQuestNpc(203616)->addOnQuestStart(questId);
		qe.registerQuestNpc(203616)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700134)->addOnTalkEvent(questId);
		qe.registerQuestNpc(211621)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = env.getTargetId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203616) { // Gefion
				if (dialogActionId == QUEST_SELECT) {
					return sendQuestDialog(env, 1011);
				} else {
					return sendQuestStartDialog(env);
				}
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			switch (targetId) {
				case 203620: // Lamir
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 1352);
							} else if (var == 1) {
								if (player->getInventory().getItemCountByItemId(182203217) == 1) {
									return sendQuestDialog(env, 1694);
								} else {
									giveQuestItem(env, 182203217, 1);
									return sendQuestDialog(env, 1779);
								}
							}
							return false;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1, 182203217, 1, 0, 0); // 1
						case FINISH_DIALOG:
							return sendQuestSelectionDialog(env);
					}
					break;
				case 700134: // Old Incense Burner
					if (env.getDialogActionId() == USE_OBJECT) {
						if (player->getInventory().getItemCountByItemId(182203217) == 1) {
							return useQuestObject(env, 1, 1, false, 0, 0, 0, 182203217, 1, 67, true); // movie + die
						}
					}
					break;
				case 203616: // Gefion
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0) {
								return sendQuestDialog(env, 2716);
							}
							return false;
						case FINISH_DIALOG:
							return sendQuestSelectionDialog(env);
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203616) { // Gefion
				switch (dialogActionId) {
					case USE_OBJECT:
						return sendQuestDialog(env, 2375);
					case SELECT_QUEST_REWARD:
						return sendQuestDialog(env, 5);
					default:
						{
							return sendQuestEndDialog(env);
						}
				}
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		return defaultOnKillEvent(env, 211621, 1, true); // reward
	}

	void onMovieEndEvent(QuestEnv& env, int32_t movieId) override {
		if (movieId == 67)
			spawnForFiveMinutes(211621, *env.getPlayer()->getWorldMapInstance(), static_cast<float>(1547.1047), static_cast<float>(894.2969), static_cast<float>(248.019), static_cast<int8_t>(85));
	}
};
AION_QUEST_HANDLER(_2223AMythicalMonster, 2223);

} // namespace aion::gameserver::handlers::quest::altgard
