#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_2266ATrustworthyMessenger.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Ritsu
 */
class _2266ATrustworthyMessenger final : public AbstractQuestHandler {
public:
	_2266ATrustworthyMessenger() : AbstractQuestHandler(2266) {}

	void register_() override {
		qe.registerQuestNpc(203558)->addOnQuestStart(questId);
		qe.registerQuestNpc(203558)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203655)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203654)->addOnTalkEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();

		if (qs == nullptr || qs->isStartable()) {
			if (targetId == 203558) {
				if (dialogActionId == QUEST_SELECT)
					return sendQuestDialog(env, 1011);
				else if (dialogActionId == QUEST_ACCEPT_1) {
					if (!giveQuestItem(env, 182203244, 1))
						return true;
					return sendQuestStartDialog(env);
				} else
					return sendQuestStartDialog(env);
			}
		} else if (qs->getStatus() == QuestStatus::START) {
			int32_t var = qs->getQuestVarById(0);
			if (targetId == 203655) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0)
							return sendQuestDialog(env, 1352);
						return false;
					case SETPRO1:
						if (var == 0) {
							qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
							updateQuestStatus(env);
							PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
							return true;
						}
				}
			}
			if (targetId == 203654) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 1) {
							qs->setQuestVar(3);
							qs->setStatus(QuestStatus::REWARD);
							updateQuestStatus(env);
							return sendQuestDialog(env, 2375);
						}
						return false;
					case SELECT_QUEST_REWARD:
						if (var == 3) {
							removeQuestItem(env, 182203244, 1);
							return sendQuestEndDialog(env);
						}
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			return sendQuestEndDialog(env);
		}
		return false;
	}
};
AION_QUEST_HANDLER(_2266ATrustworthyMessenger, 2266);

} // namespace aion::gameserver::handlers::quest::altgard
