#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/world/zone/ZoneName.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_24012AnOminousCrop.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Ritsu, Majka
 */
class _24012AnOminousCrop final : public AbstractQuestHandler {
public:
	_24012AnOminousCrop() : AbstractQuestHandler(24012) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(203605)->addOnTalkEvent(questId);
		qe.registerQuestNpc(700096)->addOnTalkEvent(questId);
		qe.registerOnEnterZone(ZoneName::get("MUMU_FARMLAND_220030000"), questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 203605: // Loriniah
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							else if (var == 5)
								return sendQuestDialog(env, 2716);
							return false;
						case SELECT1_1_1:
							playQuestMovie(env, 61);
							return sendQuestDialog(env, 1013);
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
						case CHECK_USER_HAS_QUEST_ITEM:
							return checkQuestItems(env, 5, 6, true, 5, 10001); // reward
					}
					break;
				case 700096: // MuMu Cart
					switch (dialogActionId) {
						case USE_OBJECT:
							if (var >= 2 && var < 5) {
								return useQuestObject(env, var, var + 1, false, true); // 4,5
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203605) // Loriniah
				return sendQuestEndDialog(env);
		}
		return false;
	}

	bool onEnterZoneEvent(QuestEnv& env, const ZoneName* zoneName) override {
		if (zoneName == ZoneName::get("MUMU_FARMLAND_220030000")) {
			runtime::Ptr<Player> player = env.getPlayer();
			if (player == nullptr)
				return false;
			runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
			if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
				int32_t var = qs->getQuestVarById(0);
				if (var == 1) {
					changeQuestStep(env, 1, 2); // 2
					return true;
				}
			}
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {24010});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {24010});
	}
};
AION_QUEST_HANDLER(_24012AnOminousCrop, 24012);

} // namespace aion::gameserver::handlers::quest::altgard
