#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include <array>

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_24011FunnyFloatingFungus.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Majka
 */
class _24011FunnyFloatingFungus final : public AbstractQuestHandler {
public:
	_24011FunnyFloatingFungus() : AbstractQuestHandler(24011) {}

	void register_() override {
		std::array<int32_t, 3> talkNpcs{203558, 203572, 203558};
		qe.registerQuestNpc(700092)->addOnKillEvent(questId);
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		for (int32_t id : talkNpcs)
			qe.registerQuestNpc(id)->addOnTalkEvent(questId);
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		if (qs->getStatus() != QuestStatus::START)
			return false;
		if (targetId == 700092) {
			if (var > 0 && var < 6) {
				qs->setQuestVarById(0, qs->getQuestVarById(0) + 1);
				updateQuestStatus(env);
				return true;
			} else if (var == 6) {
				changeQuestStep(env, 6, 6, true); // reward
				return true;
			}
		}
		return false;
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			if (targetId == 203558) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0)
							return sendQuestDialog(env, 1011);
						return false;
					case SETPRO1:
						return defaultCloseDialog(env, 0, 1); // 1
				}
			} else if (targetId == 203572) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 1)
							return sendQuestDialog(env, 1352);
						return false;
					case SELECT2_1:
						if (var == 1) {
							playQuestMovie(env, 60);
							return sendQuestDialog(env, 1353);
						}
						return false;
					case SETPRO2:
						return defaultCloseDialog(env, 1, 2); // 2
				}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203558) {
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {24010});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {24010});
	}
};
AION_QUEST_HANDLER(_24011FunnyFloatingFungus, 24011);

} // namespace aion::gameserver::handlers::quest::altgard
