#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/network/aion/serverpackets/SM_DIALOG_WINDOW.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_24014StompOutThePlot.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Ritsu, Majka
 */
class _24014StompOutThePlot final : public AbstractQuestHandler {
public:
	_24014StompOutThePlot() : AbstractQuestHandler(24014) {}

	void register_() override {
		qe.registerOnQuestCompleted(questId);
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(203665)->addOnTalkEvent(questId);
		qe.registerQuestNpc(203668)->addOnTalkEvent(questId);
		qe.registerQuestNpc(210562)->addOnKillEvent(questId);
		qe.registerQuestNpc(216914)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();

		if (qs->getStatus() == QuestStatus::START) {
			switch (targetId) {
				case 203665:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 0)
								return sendQuestDialog(env, 1011);
							break;
						case SETPRO1:
							return defaultCloseDialog(env, 0, 1); // 1
					}
					break;
				case 203668:
					switch (dialogActionId) {
						case QUEST_SELECT:
							if (var == 1)
								return sendQuestDialog(env, 1352);
							else if (var == 5)
								return sendQuestDialog(env, 2716);
							break;
						case SETPRO2:
						case SETPRO3:
							if (var == 1 || var == 5) {
								qs->setQuestVarById(0, var + 1);
								updateQuestStatus(env);
								PacketSendUtility::sendPacket(*player, SM_DIALOG_WINDOW(env.getVisibleObject()->getObjectId(), 10));
								return true;
							}
							return false;
						case CHECK_USER_HAS_QUEST_ITEM:
							if (var == 5) {
								if (QuestService::collectItemCheck(env, true)) {
									qs->setStatus(QuestStatus::REWARD);
									updateQuestStatus(env);
									return sendQuestDialog(env, 5);
								} else
									return sendQuestDialog(env, 10001);
							}
					}
			}
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			if (targetId == 203668)
				return sendQuestEndDialog(env);
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->getStatus() != QuestStatus::START)
			return false;

		int32_t var = qs->getQuestVarById(0);
		int32_t targetId = env.getTargetId();

		if ((targetId == 210562 || targetId == 216914) && var >= 2 && var < 5) {
			qs->setQuestVarById(0, var + 1);
			updateQuestStatus(env);
			return true;
		}
		return false;
	}

	void onQuestCompletedEvent(QuestEnv& env) override {
		defaultOnQuestCompletedEvent(env, {24010});
	}

	void onLevelChangedEvent(Player& player) override {
		defaultOnLevelChangedEvent(player, {24010});
	}
};
AION_QUEST_HANDLER(_24014StompOutThePlot, 24014);

} // namespace aion::gameserver::handlers::quest::altgard
