#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"
#include "aion/gameserver/world/WorldMapTypeInfo.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_24010SuthransOrders.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author Artur, Majka
 */
class _24010SuthransOrders final : public AbstractQuestHandler {
public:
	_24010SuthransOrders() : AbstractQuestHandler(24010) {}

	void register_() override {
		qe.registerQuestNpc(203557)->addOnTalkEvent(questId);
		qe.registerOnEnterWorld(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr)
			return false;

		int32_t targetId = env.getTargetId();
		int32_t dialogActionId = env.getDialogActionId();
		if (targetId != 203557)
			return false;
		if (qs->getStatus() == QuestStatus::START) {
			if (dialogActionId == QUEST_SELECT) {
				qs->setStatus(QuestStatus::REWARD);
				updateQuestStatus(env);
				return sendQuestDialog(env, 1011);
			} else
				return sendQuestStartDialog(env);
		} else if (qs->getStatus() == QuestStatus::REWARD) {
			return sendQuestEndDialog(env);
		}
		return false;
	}

	bool onEnterWorldEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		if (player->getWorldId() == ::aion::gameserver::world::getId(WorldMapType::ALTGARD) && !player->getQuestStateList()->hasQuest(questId))
			return QuestService::startQuest(env);
		return false;
	}
};
AION_QUEST_HANDLER(_24010SuthransOrders, 24010);

} // namespace aion::gameserver::handlers::quest::altgard
