#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"

namespace aion::gameserver::handlers::quest::altgard {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/altgard/_24112NoLaissezFaireForLepharists.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @Author Majka
 */
class _24112NoLaissezFaireForLepharists final : public AbstractQuestHandler {
private:
	static constexpr int32_t questStartNpcId = 203631; // Nokir
	static constexpr int32_t questEndNpcId = 832821; // Brodir
	static constexpr int32_t questKillNpcId = 210510; // Comrade Sumarhon

public:
	_24112NoLaissezFaireForLepharists() : AbstractQuestHandler(24112) {}

	void register_() override {
		qe.registerQuestNpc(questStartNpcId)->addOnQuestStart(questId);
		qe.registerQuestNpc(questStartNpcId)->addOnTalkEvent(questId);
		qe.registerQuestNpc(questEndNpcId)->addOnTalkEvent(questId);
		qe.registerQuestNpc(questKillNpcId)->addOnKillEvent(questId);
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr) {
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		}

		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		int32_t dialogActionId = env.getDialogActionId();

		if (targetId == questStartNpcId) { // Nokir
			if (qs == nullptr || qs->isStartable()) {
				switch (dialogActionId) {
					case QUEST_SELECT:
						return sendQuestDialog(env, 1011);
					default:
						return sendQuestStartDialog(env);
				}
			}
		}

		if (targetId == questEndNpcId) { // Brodir
			if (qs != nullptr && qs->getStatus() == QuestStatus::START) {
				int32_t var = qs->getQuestVarById(0);

				switch (dialogActionId) {
					case QUEST_SELECT:
						if (var == 0) { // @ToDo: find a way to reach this part. It works with var = -1 but doesn't activate following step
							return sendQuestDialog(env, 1352);
						} else if (var == 1) {
							return sendQuestDialog(env, 2375);
						}
						return false;
					case SETPRO1:
						qs->setQuestVarById(0, 1);
						return sendQuestSelectionDialog(env);
					case SELECT_QUEST_REWARD:
						qs->setStatus(QuestStatus::REWARD);
						updateQuestStatus(env);
						return sendQuestEndDialog(env);
				}
			}

			if (qs != nullptr && qs->getStatus() == QuestStatus::REWARD) {
				return sendQuestEndDialog(env);
			}
		}
		return false;
	}

	bool onKillEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->getStatus() != QuestStatus::START) {
			return false;
		}

		int32_t targetId = env.getTargetId();
		int32_t var = qs->getQuestVarById(0);

		if (var == 0 && targetId == questKillNpcId) {
			qs->setQuestVarById(0, 1);
			updateQuestStatus(env);
			return true;
		}
		return false;
	}
};
AION_QUEST_HANDLER(_24112NoLaissezFaireForLepharists, 24112);

} // namespace aion::gameserver::handlers::quest::altgard
