#include "aion/gameserver/handlers/quest/QuestPrelude.h"

#include "aion/gameserver/model/PlayerClassInfo.h"
#include "aion/gameserver/model/gameobjects/player/QuestStateList.h"
#include "aion/gameserver/model/templates/quest/QuestNpc.h"
#include "aion/gameserver/services/QuestService.h"

namespace aion::gameserver::handlers::quest::poeta {

// Generated by cpp/tools/gen/questgen from game-server/data/handlers/quest/poeta/_1205ANewSkill.java.
// Compiled into its Q chunk's handler library (game-server/chunks.cmake). Do not edit: change the generator and regenerate.

/**
 * @author MrPoke
 */
class _1205ANewSkill final : public AbstractQuestHandler {
public:
	_1205ANewSkill() : AbstractQuestHandler(1205) {}

	void register_() override {
		qe.registerOnLevelChanged(questId);
		qe.registerQuestNpc(203087)->addOnTalkEvent(questId); // Warrior
		qe.registerQuestNpc(203088)->addOnTalkEvent(questId); // Scout
		qe.registerQuestNpc(203089)->addOnTalkEvent(questId); // Mage
		qe.registerQuestNpc(203090)->addOnTalkEvent(questId); // Priest
		qe.registerQuestNpc(801210)->addOnTalkEvent(questId); // Engineer
		qe.registerQuestNpc(801211)->addOnTalkEvent(questId); // Artist
	}

	void onLevelChangedEvent(Player& player) override {
		if (player.getQuestStateList()->hasQuest(questId))
			return;
		runtime::Ref<QuestEnv> env = QuestEnv::create(nullptr, player, questId);
		if (QuestService::startQuest(*env)) {
			runtime::Ptr<QuestState> qs = player.getQuestStateList()->getQuestState(questId);
			qs->setStatus(QuestStatus::REWARD);
			switch (::aion::gameserver::model::getStartingClass(player.getPlayerClass())) {
				case PlayerClass::WARRIOR:
					qs->setQuestVar(1);
					qs->setRewardGroup(0);
					break;
				case PlayerClass::SCOUT:
					qs->setQuestVar(2);
					qs->setRewardGroup(1);
					break;
				case PlayerClass::MAGE:
					qs->setQuestVar(3);
					qs->setRewardGroup(2);
					break;
				case PlayerClass::PRIEST:
					qs->setQuestVar(4);
					qs->setRewardGroup(3);
					break;
				case PlayerClass::ENGINEER:
					qs->setQuestVar(5);
					qs->setRewardGroup(4);
					break;
				case PlayerClass::ARTIST:
					qs->setQuestVar(6);
					qs->setRewardGroup(5);
					break;
			}
			updateQuestStatus(*env);
		}
	}

	bool onDialogEvent(QuestEnv& env) override {
		runtime::Ptr<Player> player = env.getPlayer();
		runtime::Ptr<QuestState> qs = player->getQuestStateList()->getQuestState(questId);
		if (qs == nullptr || qs->getStatus() != QuestStatus::REWARD)
			return false;

		int32_t targetId = 0;
		if (runtime::as<Npc>(env.getVisibleObject()) != nullptr)
			targetId = (runtime::cast<Npc>(env.getVisibleObject()))->getNpcId();
		PlayerClass playerClass = ::aion::gameserver::model::getStartingClass(player->getPlayerClass());
		switch (targetId) {
			case 203087:
				if (playerClass == PlayerClass::WARRIOR) {
					if (env.getDialogActionId() == USE_OBJECT)
						return sendQuestDialog(env, 1011);
					else
						return sendQuestEndDialog(env);
				}
				return false;
			case 203088:
				if (playerClass == PlayerClass::SCOUT) {
					if (env.getDialogActionId() == USE_OBJECT)
						return sendQuestDialog(env, 1352);
					else
						return sendQuestEndDialog(env);
				}
				return false;
			case 203089:
				if (playerClass == PlayerClass::MAGE) {
					if (env.getDialogActionId() == USE_OBJECT)
						return sendQuestDialog(env, 1693);
					else
						return sendQuestEndDialog(env);
				}
				return false;
			case 203090:
				if (playerClass == PlayerClass::PRIEST) {
					if (env.getDialogActionId() == USE_OBJECT)
						return sendQuestDialog(env, 2034);
					else
						return sendQuestEndDialog(env);
				}
				return false;
			case 801210:
				if (playerClass == PlayerClass::ENGINEER) {
					if (env.getDialogActionId() == USE_OBJECT)
						return sendQuestDialog(env, 2375);
					else
						return sendQuestEndDialog(env);
				}
				return false;
			case 801211:
				if (playerClass == PlayerClass::ARTIST) {
					if (env.getDialogActionId() == USE_OBJECT)
						return sendQuestDialog(env, 2716);
					else
						return sendQuestEndDialog(env);
				}
				return false;
		}
		return false;
	}
};
AION_QUEST_HANDLER(_1205ANewSkill, 1205);

} // namespace aion::gameserver::handlers::quest::poeta
