// GENERATED by cpp/tools/gen/skeleton.py --fwd from the Java package com.aionemu.gameserver.model.templates.ai - do not edit.
// Regenerate after adding a Java class or regenerating xmlgen: python cpp/tools/gen/skeleton.py --fwd --out cpp/game-server/src
#pragma once

namespace aion::gameserver::model::templates::ai {

struct AITemplate;
struct BombTemplate;
struct Bombs;
struct Percentage;
class SummonGroup;
struct Summons;

} // namespace aion::gameserver::model::templates::ai
